### ISSUE TITLE
Changing rows per page doesn't re-calculate page number when using paginationServer

### ISSUE THREAD

**Issue by Lknechtli** [jbetancur/react-data-table-component#101]
## Describe the bug
Changing the number of rows per page does not re-calculate the page number to ensure that there are rows to display. This is the default behaviour specified in the changelog for 1.5.1, but it results in the component showing no data if the current page fetches no data with the new number of rows per page.

## To Reproduce
* Open this example: https://jbetancur.github.io/react-data-table-component/?selectedKind=Advanced&selectedStory=Server-Side%20Pagination&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
* Go to the second page using the pagination controls
* Change the rows per page to something > 10 (15 works)
* Observe that it sees no data for that page and shows the no data component. The only way to move to a valid page is to reload the component because the pagination controls are hidden.

## Expected behaviour
The component should calculate a new page based off the current page and the old / new perPage values. It should not attempt to show a page where the provided count is < the number of rows per page * page number. I think ideally it would try to show a page which is as close to the original page as possible, maybe something like
 `Math.floor((oldPerPage * page) / newPerPage) - 1` for pages starting at 0

## Code Sandbox
https://jbetancur.github.io/react-data-table-component/?selectedKind=Advanced&selectedStory=Server-Side%20Pagination&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

## Screenshots
N/A

## Versions (please complete the following information)
 - React ^16.8.6
 - Styled Components ^4.2.0
 - OS: Linux
 - Browser: Firefox developer edition v68.0b9
 - Version: 1.5.3

## Additional context
N/A

**Comment by jbetancur** [comment]
Thanks for the sanbox. Yea that is definitely a bug. I'll look into it

**Comment by jbetancur** [comment]
Just a note that this only happens when using server side pagination

**Comment by Lknechtli** [comment]
It looks like the page number isn't consistent for client-side pagination either. The only difference is that there's still data in the array, so the noDataComponent isn't rendered:
Reproduction:
* Open the react-md example in storybook
* Set "rows per page" to 20 using the dropdown
* Set it back to 10 and observe that the page reads "11-20" and there are no rows in the table.
* At this point you have to click the previous/first page pagination icons in order to fix the state.

**Comment by jbetancur** [comment]
Thank you. Yea I confirmed the same. I’m working on a fix for the page calculation
