### ISSUE TITLE
[FEATURE]: Display pagination clones at the top of the table

### ISSUE THREAD

**Issue by Daiki-ka** [jbetancur/react-data-table-component#1010]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe
Hi.
Is there any way to display a duplicate of an existing pagination at the top of a table?
For convenience when the number of rows to be displayed increases, we would like to display pagination at the top of the table as well.
I have tried cloning elements, etc., but have not been able to implement it successfully.

If there is such an option, it would be very helpful.

I apologize if there are any mistakes in English.
Thank you very much for your time.

## Describe the solution you'd like
How about providing it as General Properties of the DataTable Component.

**Comment by anderson-dasilva-osf** [comment]
I vote for this

**Comment by douglasc0leman** [comment]
This seems to be a highly requested feature. Any update on it? It's been talked about since 2020 and I don't see any implementation.
