### ISSUE TITLE
Warning: title is a string based column selector which has been deprecated as of v7 and will be removed in v8[DESCRIPTION]

### ISSUE THREAD

**Issue by FatimeyiZahra** [jbetancur/react-data-table-component#1016]
-------------------------------------------------------------------------------------------------------------------------------------------
I GOT THOOSE 2 ERROR FROM TableCol.tsx:123. HOPE UR TEAM LL FIX IT

Warning: title is a string based column selector which has been deprecated as of v7 and will be removed in v8. Instead, use a selector function e.g. row => row[field]...

TableCol.tsx:123 Warning: director is a string based column selector which has been deprecated as of v7 and will be removed in v8. Instead, use a selector function e.g. row => row[field]...  

AND I DONT WANNA IMPORT BOOTSTRAP.MIN.CSS CUZ IM USING ANT ANT DESIGN AND METERIAL UI. BOOTSTRAP.MIN.CSS CHANGED MY DESIGN. IS THERE ANY WAY FOR EXAMPLE IF I WANNA USE DATATABLE I SHOULD IMPORT ONLY CSS FILE FOR DATATABLE

**Comment by jbetancur** [comment]
selectors need to be functions not strings in V7. that's it and it is in the docs

selector: 'whatever'
should now be
selector: row => row.whatever

**Comment by mcamendoza1** [comment]
@FatimeyiZahra 

this might work for you. 
From:
```
const columns = [
	{
		name: 'Title',
		selector: 'title',
	},
	{
		name: 'Year',
		selector: 'year',
	},
];
```

To this:
```
const columns = [
	{
		name: 'Title',
		selector: row => row.title,
	},
	{
		name: 'Year',
		selector: row => row.year,
	},
];
```
