### ISSUE TITLE
multiple-column-sort

### ISSUE THREAD

**Issue by adibenporat** [jbetancur/react-data-table-component#1018]
Hi everyone,
I would like for your help.
I would like to know if there is an option to make multi-columns-sorting
I know that there is a way with jQuery and holding shift but it didn't worked

Hope that you could help me
Thanks!

**Comment by Imiut-ZT** [comment]
+1

**Comment by zakasalaheddine** [comment]
facing the same issue, is there any help that can be shared
Thanks!

**Comment by khushahal** [comment]
I am also figuring, how can we achieve multiple column sort in react data table .
