### ISSUE TITLE
How to display a no data available component upon failed search

### ISSUE THREAD

**Issue by smammadov1994** [jbetancur/react-data-table-component#1019]
Hello,
I would like to know how to display a no data component upon a failed search. Is there an API for this? Also, what does the Data structure have to be (null,undefined,empty array)? Thank you

**Comment by smammadov1994** [comment]
Anybody on this? I feel like it's such a simple thing but I don't see any documentation on this feature.

**Comment by Afsana1313** [comment]
@smammadov1994 , did you find any solution?

**Comment by juninhodeluca** [comment]
If you are using the built-in filtering (example here: [](https://react-data-table-component.netlify.app/?path=/story/examples-filtering--filtering)) you can use the prop noDataComponent (search it at [](https://react-data-table-component.netlify.app/?path=/docs/api-props--page)). It accept a string or a custom component. Server side filtering are a bit more complex, but even in this case, if the filtered data is empty, trigger the noDataComponent.

Sorry my bad english. Working in progress.
