### ISSUE TITLE
How to add table column dynamically from json value

### ISSUE THREAD

**Issue by cool-raju** [jbetancur/react-data-table-component#1021]
Datatable column is successfully working by using static value like this
const columns = [
  {
    id: 1,
    name: "Title",
    selector: (row) => row.title,
    sortable: true,
    reorder: true
  },
  {
    id: 2,
    name: "Director",
    selector: (row) => row.director,
    sortable: true,
    reorder: true
  },
  {
    id: 3,
    name: "Runtime (m)",
    selector: (row) => row.runtime,
    sortable: true,
    right: true,
    reorder: true
  }
];

But I want to fetch this from rest API json
Is there any way out??

**Comment by cool-raju** [comment]
i have solved this thing by selector = selector name
but it shows an error.. to use row => row['fileds]
how to use it in json
any help??

**Comment by kusaljr** [comment]
Any way this can be achieved?

**Comment by cool-raju** [comment]
yes i have found a solution

**Comment by kusaljr** [comment]
> yes i have found a solution

can you share please?
