### ISSUE TITLE
The grow column API doesn't work while button API tag is attached. 

### ISSUE THREAD

**Issue by chrisdel101** [jbetancur/react-data-table-component#1023]
## Expected behavior

The `grow` column API should work under all circumstances. It seems it doesn't work while the same column has the `button` API added. Once the `button` is removed, `grow` works as expected.

## Code Sandbox, Screenshots, or Relevant Code

Code demo: https://codesandbox.io/s/react-data-table-forked-zj3zbb?file=/src/index.js

**Comment by jbetancur** [comment]
I tried switching setting the button: false and I did not notice a difference. What exactly are you trying to achieve in terms of layout??

**Comment by chrisdel101** [comment]
Simply an FYI. 

- The `button` was there in the code base and I went to use `grow` and it didn't work. 
- It took some debugging to figure out it only worked when I removed button
- button was doing nothing towards the final goal, but it being there disrupted `grow` which seemed like a bug

Once I get this running locally I'll see if U can PR this, if U want?

**Comment by jbetancur** [comment]
sounds good. Did you also try using cell instead of format? format was meant to change the data while retaining the sort selector
