### ISSUE TITLE
Change the "X item selected" text 

### ISSUE THREAD

**Issue by Silidrone** [jbetancur/react-data-table-component#1028]
Is there a prop to change the text when cases are selected? Currently it says "3 items selected" if 3 items are selected, but I want it to say something like "3 records selected" or whatever I want? Is there a prop or any way to change it somehow?

**Comment by jbetancur** [comment]
Yes in the documentation 😉 

https://react-data-table-component.netlify.app/?path=/docs/api-props--page

scroll to Header Context Menu when using Selectable Rows
