### ISSUE TITLE
Can we Update columns dynamically?

### ISSUE THREAD

**Issue by rakeshmanjunatha** [jbetancur/react-data-table-component#103]
Hi, I'm trying to update the table **columns** dynamically along with **data** using **state** but its not taking new value from the **state** rather than its showing old columns.

Don't know its because of table issue or my code.

Thanks

**Comment by jbetancur** [comment]
It’s likely not your code. This was an early design decision as I wanted to minimize the columns re-rendering every time the parent component updated. 

Can you give me an idea of your use case or why you need column re-rendering?

**Comment by rakeshmanjunatha** [comment]
Sure, i'm trying to re-render the table on change of dropdown. Based on selected value from dropdown i'm calling API and trying to load the table with new data/response. 
Even i'm following all the basic steps like assigning values **columns** and **data** using **state**.

**Comment by jbetancur** [comment]
so your trigger a drop down in a row and you want that to change the values in the columns? 

Can you paste your code or setup a quick https://codesandbox.io/embed/react-data-table-sandbox-ienim ?

**Comment by rakeshmanjunatha** [comment]
No, dropdown is outside of the table

**Comment by rakeshmanjunatha** [comment]
import React from "react";
import ReactDOM from "react-dom";
import DataTable from "react-data-table-component";

import "./styles.css";

let data = [
  { id: 1, title: "Conan the Barbarian", year: 1982 },
  { id: 2, title: "Men in Black", year: 1999 }
];

const columns = [
  {
    name: "Title",
    selector: "title",
    sortable: true
  },
  {
    name: "Year",
    selector: "year",
    sortable: true,
    right: true
  }
];

class App extends React.Component {
  constructor(props){
    super(props);
    this.state = {
      tbl_columns: columns,
      tbl_data: data
    }
    this.OnChangeRequest = this.OnChangeRequest.bind(this)
  }
  OnChangeRequest(option){
    //Calling an API
    // depend up on option.value the data and columns are different
    let result_from_API = [{  name: "Rama", year: 1982 },
      {  name: "Krishna", year: 1999 }]
    
    let new_columns = [
      {
        name: "Name",
        selector: "name",
        sortable: true
      },
      {
        name: "Year",
        selector: "year",
        sortable: true,
        right: true
      }

      
    ]
    this.setState({
      tbl_columns: new_columns,
      tbl_data: result_from_API
    })


  }
  render(){
    return (
      <>
        <select name="" id="" onChange={this.OnChangeRequest}>
          <option value="0">select</option>
          <option value="1">Request-1</option>
          <option value="2">Request-1</option>
        </select>
      <div className="App">
        <DataTable title="People" columns={this.state.tbl_columns} data={this.state.data} />
      </div>
      </>
    )
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

**Comment by jbetancur** [comment]
Why not just map your responses so they are consistent and then update the state? Or are your column keys always going to be ever changing ?

```
result_from_API .map(({ name, year } )=> ({ title: name, year));
```

**Comment by jbetancur** [comment]
I suspect you want to completely change the table columns.

This won't be a quick change as I would need to verify if there is any performance impact, but I can see the value. As I mentioned earlier I could add a prop that allows the column to re-render so you can "opt in"  to column re-renders, but I will not be able to look into doing that until sometime next week.

**Comment by rakeshmanjunatha** [comment]
> I suspect you want to completely change the table columns depending on some drop down data source :)
> 
> This won't be a quick change as I would need to verify if there is any performance impact, but I can see the value. As I mentioned earlier I could add a prop that allows the column to re-render so you can "opt in" to column re-renders, but I will not be able to look into doing that until sometime next week.

yes, i want to change table columns completely depending up on dropdown value.

**Comment by Lknechtli** [comment]
I agree that it would be nice to have some way to force the component to re-render using the values passed to props which are currently only read during initialization. 
For consistency, it would probably make sense to do it in the same way that the clearSelectedRows toggle prop works.
I would argue that performance is less of a concern for this because we're basically saying "reset all state and render from scratch" when we use it.

**Comment by rakeshmanjunatha** [comment]
Not at all ... I guess it won't  affect any performance..why because  we
have seen this feature and implemented  using jQuery Ajax Data tables...

**Comment by rakeshmanjunatha** [comment]
When we have this re-rendering feature in jQuery Data tables ... What is the problem with ReactJs?

**Comment by Lknechtli** [comment]
Started exploring what it could look like on my fork: https://github.com/Lknechtli/react-data-table-component/tree/103-reread-defaults
I've got it resetting columns to the prop right now, working on resetting other state to the originating props.

**Comment by Lknechtli** [comment]
For context, my use-case is a component that can display one of two data-sets, each with different columns and data. Switching between them in the parent component is possible, but I don't see a straightforward way to render a different table for each dataset outside adding a property that forces re-reading the props defining table initialization defaults.

**Comment by Lknechtli** [comment]
After some further investigation, I think it's probably a lot easier just to do something like this when you want to re-initialize the table with different columns etc:

```javascript
import SomePlaceholderComponent = "someComponent.js"
function UpdatingTable({changingProp, data, columns}) {
  const [localChangingProp, setLocalChangingProp] = useState(changingProp);
  // Update the local state and render the table again
  useEffect(() => {
    if (changingProp !== localChangingProp) {
      setLocalChangingProp(changingProp);
    }
  }, [changingProp, localChangingProp, setLocalChangingProp])
  return changingProp === localChangingProp ? 
    (<DataTable data={data} columns={columns} ></DataTable>) :
    (<SomePlaceholderComponent />)
}
```

**Comment by rakeshmanjunatha** [comment]
Thanks for the code, i will try to implement this.

**Comment by rakeshmanjunatha** [comment]
> ```js
> function UpdatingTable({changingProp, data, columns}) {
>   const [localChangingProp, setLocalChangingProp] = useState(changingProp);
>   // Update the local state and render the table again
>   useEffect(() => {
>     if (changingProp !== localChangingProp) {
>       setLocalChangingProp(changingProp);
>     }
>   }, [changingProp])
>   return changingProp === localChangingProp ? 
>     (<DataTable data={data} columns={columns} ></DataTable>) :
>     (<SomePlaceholderComponent />) // or just a React.Fragment
> }
> ```

Thanks lot @Lknechtli its working, now i'm able to load the data with different columns. You saved my time, but its taking few seconds to load the data.

**Comment by jbetancur** [comment]
@rakeshmanjunatha I have some good news. Please check out The Release notes for version 3.0.0. I've made some internal changes that allow RDT to re-render when the columns property changes. Note that 3.0.0 requires React 16.8.0+.

Also please look at https://github.com/jbetancur/react-data-table-component#optimizing-for-performance-and-caveats for best practices on mitigating performance issues

**Comment by impactcolor** [comment]
I'm having a challenge in reloading the data.
In `this.state.data` I make a change to one of the columns.  I add a new column that wasn't there initially.  I then `this.setState({ data: newUpdatedData })` but RDT doesn't reload.  According to this it seems like it should work.  I'm using 6.2.  You mention "allow RDT to re-render when the columns property changes."  Is there something else that has to be done or should the table rerender just based upon a state change to the data?
