### ISSUE TITLE
No font loading up 

### ISSUE THREAD

**Issue by EzhnoFR** [jbetancur/react-data-table-component#1032]
## Describe the bug
After installing both components (styled-components and react-data-table-component) , the tables work great but no font seems to load, instead I have basic sherif font. (see screenshot) 

## To Reproduce
Installed "npm install react-data-table-component", then "npm install styled-components" 

## Expected behavior
The font should be the same family as on documentation page, or should have a default family. 

## Code Sandbox

https://snack.expo.dev/@37creaorganization/font-issue
![image](https://user-images.githubusercontent.com/75476898/161397604-6e96260d-8d37-4045-a173-c8493bb63082.png)

## Versions 
 - React (RDT requires 16.8.0+) : 17.0.1
 - Styled Components : YES -Is probably the issue-
 - OS: [e.g. iOS] WEB
 - Browser [e.g. chrome, safari, firefox] Chrome
 - Using EXPO
 - 
## Additional context

I suppose something is not loading up. It exactly looks like when you're missing a font in css.

**Comment by nvkex** [comment]
You have to specify the font manually.
Take a look at this sandbox https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
Check the `style.css` file.

**Comment by jbetancur** [comment]
closing this as @nvkex has answered this.
