### ISSUE TITLE
When I hover table cell popup shows but Z-index doesnt work

### ISSUE THREAD

**Issue by emreertoprak** [jbetancur/react-data-table-component#1033]
##Problem

When I hover table cell popup shows but Z-index doesnt work.

I gave 99999 z index to cell it shows  on dev tools but as you can see below popup doesnt go up over row.

## Expected behavior
I want the popup to indexed at top 

![1](https://user-images.githubusercontent.com/47323323/162001895-b2d6df58-680e-43f0-82fe-7f1a1c8a9ede.png)
![2](https://user-images.githubusercontent.com/47323323/162001924-6ca7be59-872f-4657-8f6a-b642e5ba3975.png)

these are my codes

```
 <DataTableBox
      noHeader={true}
      fixedHeader={true}
      striped={true}
      pagination={true}
      paginationPerPage={50}
      paginationRowsPerPageOptions={[10, 15, 20, 25, 30, 50]}
      paginationServer={true}
      responsive={true}
      sortServer={true}
      noDataComponent={
        <Box sx={{ height: 512 }}>
          <NoRecordFound />
        </Box>
      }
      customStyles={{
        tableWrapper: {
          style: {},
        },
        table: {
          style: {
            maxHeight: "calc(100vh - 80px - 70px)",
            overflowY: "inherit",
            minHeight: "400px",
            zIndex: 1,
          },
        },
        headRow: {
          style: {
            minHeight: 32,
            ...rowBorderBottom,
          },
        },
        headCells: {
          style: {
            fontWeight: "bold",
            paddingRight: 0,
          },
        },
        cells: {
          style: {
            minHeight: 32,
            paddingRight: 0,
            ...cellsStyle,
          },
        },
        rows: {
          style: {
            zIndex: 99999,
            minHeight: 132,
            borderBottomStyle: "solid",
            borderBottomColor: "rgba(0,0,0,.12)",
            borderBottomWidth: 1,
            ...rowStyle,
            ...rowBorderBottom,
            ":not(:last-of-type)": { ...rowBorderBottom },
          },
        },
        pagination: {
          style: {
            borderTop: "none",
          },
        },
      }}
      progressComponent={
        <LoadingPlaceholder
          isLoading={true}
          style={{ height: 512 }}
          message={progressComponentMessage}
        />
      }
      {...otherProps}
    />
  );
`};`
```

**Comment by NayeerBM** [comment]
Hi. I'm having the same issue. Where I had to place a dropdown inside the table and it gets hidden due to the height of the table. Did you manage to solve the issue?

**Comment by safakyavsan** [comment]
It is not about z-index you need to give position fixed to your popup element.

**Comment by Fir-3** [comment]
i had the same issue. no answers yet.
https://github.com/jbetancur/react-data-table-component/issues/926#issuecomment-952797703

**Comment by to-fuu** [comment]
> It is not about z-index you need to give position fixed to your popup element.

If the table is scrollable, fixed position will cause the drop-down to go down
![image](https://user-images.githubusercontent.com/59798736/169707314-41357518-0c2e-4569-a877-1c997f31eae1.png)
