### ISSUE TITLE
The browser freezes when there is many rows 

### ISSUE THREAD

**Issue by sarahrara18** [jbetancur/react-data-table-component#1034]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [ ] You installed `styled-components`
- [ ] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
Hello, i have Browser freezing issue when i call for all the rows that i need (more than 1000 row), is there a property that works like virtualised list ? or just anything that can fix my problem ? 

## Expected behavior
i expect my browser to stop freezing and work properly 

this is the problem that i am getting 

![image](https://user-images.githubusercontent.com/40120636/162251389-440bbe09-9009-445d-b4f9-a82adca460df.png)

## Versions
 - React 17.0.2
 - OS: [windows 10
 - Browser: chrome 100.0.4896.60

**Comment by jbetancur** [comment]
Use pagination - virtualized rows are not in scope for this library at this time unless someone has the time to propose an implementation.

**Comment by sarahrara18** [comment]
> Use pagination - virtualized rows are not in scope for this library at this time unless someone has the time to propose an implementation.

I see , thank you for answering
