### ISSUE TITLE
Cutting a new release

### ISSUE THREAD

**Issue by gsimko** [jbetancur/react-data-table-component#1038]
@jbetancur, is there a way for us external contributors to help you cut new releases and upload them to npm? Ideally you would just need to approve those releases but I don't know if github/npm supports such a setup.

**Comment by gsimko** [comment]
Maybe you could some automation like https://github.com/marketplace/actions/automated-releases-for-npm-packages or https://sergiodxa.com/articles/github-actions-npm-publish?

**Comment by jbetancur** [comment]
@gsimko I usually release when making a feature or patch such as this right after PR(s) are merged. I think in this case I ran out of time as I am quite busy these days. So, yea if I had the time I would have a system where PR's/commits were a certain format and we could automate the release notes and cut a new version say if the PR had a # Release notes.  Any effort or PR's on this would be welcome.

On a related note I just cut 7.5.0 which has your onMouseX changes.
