### ISSUE TITLE
String does not appear in column 

### ISSUE THREAD

**Issue by slimandslam** [jbetancur/react-data-table-component#1040]
The code is simple. 
What I want to do is have the string '---' appear if fileName is empty and display
fileName if fileName contains any content. 

What happens is that fileName does appear if fileName is a non-empty string,
but if fileName is empty, nothing appears (instead of '---')

Data Table version 7.5
React 17.02

```
const columns = [
 {
      name: "Filename",
      selector: "fileName",
      format: (d) => (d.fileName === '' ? ' --- ' : d.fileName),
      width: "160px",
      cell: Cell("fileName"),
    }
]
```

**Comment by jbetancur** [comment]
Cell supersedes format. You'll want to use one or the other.

**Comment by slimandslam** [comment]
I can't seem to get it to accept both a conditional and tooltips. 
I tried something like this:

`format:  (d) => (d.fileName === '' ? ' --- ' : <span style={{whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}} title={d.filename}>{d.filename}</span>),`

**Comment by jbetancur** [comment]
Try the cell property. Format is meant for simpler use cases.

**Comment by slimandslam** [comment]
I ended up using format:

`format: (d) => (d.fileName === '' ? ' --- ' : <span style={{whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}} title={d.fileName}>{d.fileName}</span>),`
