### ISSUE TITLE
useDidUpdateEffect / useFirstUpdate logic appears to be incorrect

### ISSUE THREAD

**Issue by anmcn** [jbetancur/react-data-table-component#1046]
The logic in src/DataTable/DataTable.tsx appears to be incorrect. Currently, it has:
```
const useFirstUpdate: Hook = (fn, inputs) => {
	const firstUpdate = React.useRef(true);

	React.useEffect(() => {
		if (firstUpdate.current) {
			firstUpdate.current = false;
			return;
		}

		fn();
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, inputs);
};
```
To my understanding, this will run `fn()` on every call, EXCEPT the first - I doubt this is the intention, given the name.

**Comment by jbetancur** [comment]
The intention is to ignore the call on the first render and only run the func if the prop dependancies have been updated. In other words, the hook version of the classic React componentDidUpdate lifecycle method which is what was needed for these edge cases.

It's essentially useEffect that does not run a func on first mount.

**Comment by anmcn** [comment]
Fair enough - thanks for the insight.
