### ISSUE TITLE
Excel button

### ISSUE THREAD

**Issue by BayoKwendo** [jbetancur/react-data-table-component#1055]
## No export feature for excel.
- Is there any solution for  exporting data in Excel?

**Comment by juninhodeluca** [comment]
There's not a built-in Excel button, but you can follow the same logic of 
[https://react-data-table-component.netlify.app/?path=/story/examples-export-csv--export-csv](https://react-data-table-component.netlify.app/?path=/story/examples-export-csv--export-csv
)which uses the benefits of the actions component
