### ISSUE TITLE
Ability to shift-click selectable rows to select multiple rows at once

### ISSUE THREAD

**Issue by MikeWillis** [jbetancur/react-data-table-component#1057]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

no

## Describe the solution you'd like

Would it be possible to add shift-click capability to the selectable rows checkbox? With the idea being:

1. user normal-clicks a checkbox to select a row
2. user shift-clicks another checkbox, presumably many rows above or below the first clicked checkbox
3. all rows between first click and last click get selected

I'm going to look into a PR myself but I'm not good with TS so it could be troublesome.

Alternatively, maybe just a callback when a checkbox is clicked, so this can be implemented manually outside of the DT?

**Comment by brunohq** [comment]
+1
