### ISSUE TITLE
[FEATURE]: headerWrap

### ISSUE THREAD

**Issue by bmm-brobbins** [jbetancur/react-data-table-component#1058]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

I have some long column names.  Currently being truncated with ellipses.  Would like the option to have the header cells wrap instead.

## Describe the solution you'd like

Ideally a setting, similar to 'subHeaderWrap' or 'wrap'.

_In the meantime, could anyone please post a style override to accomplish this? (Or column name component if necessary)_

## Describe alternatives you've considered

Unsuccessfully tried a few style overrides and custom column name components. 

Thank you.

**Comment by joey80** [comment]
> In the meantime, could anyone please post a style override to accomplish this? (Or column name component if necessary)

Yes I would love an override example as well or the ability to wrap the column names directly
