### ISSUE TITLE
onClick image

### ISSUE THREAD

**Issue by Angelk90** [jbetancur/react-data-table-component#106]
## Describe the bug

I'm using your module, in a column of the table I generate a qrcode, I have to make sure that when you click on the image of the qr code a function is called.

## To Reproduce
Click image qr code

## Expected behavior
The function is called.

## Code Sandbox

https://codesandbox.io/s/react-data-table-sandbox-j5ed9

**Comment by Angelk90** [comment]
@jbetancur : Perhaps it seems to have solved by putting: `ignoreRowClick: true`

**Comment by jbetancur** [comment]
Yup that's it! Please close if this is resolved for you.
