### ISSUE TITLE
[FEATURE]:Totals of some columns in the footer of the table

### ISSUE THREAD

**Issue by mariomac71** [jbetancur/react-data-table-component#1061]
Hi, is there already the possibility of having the total per page and the grand total of the values of a single column of the table? Otherwise it would be a nice implementation idea.

![tabl example](https://user-images.githubusercontent.com/15072623/170951540-3d8bc00b-c1d4-48fd-9d77-45ded7937209.png)

**Comment by MichelZiade** [comment]
Hi can you please share how you did your rows in white and grey please

**Comment by mariomac71** [comment]
Hi, you must set the striped attribute to true	
<DataTable
			theme={theme.theme === ThemeColor.dark ? 'dark' : 'default'}
			dense
			**striped**
			pagination
			data={movements}
			columns={columns}
		/>

**Comment by nevermind89x** [comment]
Is this now possible or was this just closed?
