### ISSUE TITLE
[FEATURE]: [Expandable Rows when you click on the whole row]

### ISSUE THREAD

**Issue by MichelZiade** [jbetancur/react-data-table-component#1062]
Hello , 

Is it possible to expand a row just by clicking on the row not on the left arrow to expand.

Thank you

**Comment by juninhodeluca** [comment]
Hi,
Did you already tried the expandOnRowClicked prop?
If not, search it at [https://react-data-table-component.netlify.app/?path=/docs/api-props--page](https://react-data-table-component.netlify.app/?path=/docs/api-props--page)
