### ISSUE TITLE
[FEATURE]: [Button in the rows]

### ISSUE THREAD

**Issue by MichelZiade** [jbetancur/react-data-table-component#1066]
Hello,

Is it possible to add a button at the end of each row ?
If yes, how ?

Thank you

**Comment by Clinton594** [comment]
Create an extra component for the button like this:
`import Edit from "../Icons/Edit";

export default function ComponentEdit(row, event) {
  return (
    <span className="edit" title={`Edit ${row.title}`}>
      <Edit />
    </span>
  );
}
`


Then import it and add a "cell" key to your columns array like this:


`
import Cell from ".../";
const column=[
    {
      name: "Date Created",
      selector: (row) => row.date,
    },
    {
      name: "Actions",
      cell: Cell,
    }
];
`

**Comment by MichelZiade** [comment]
Thank you very much for your help !
