### ISSUE TITLE
[FEATURE]: [Dispatch once when I expand row]

### ISSUE THREAD

**Issue by Sk8erboi99** [jbetancur/react-data-table-component#1074]
Hello ,
I am trying to use dispatch when I expand a row I want it to be called once when the row is expanded .
Thank you

**Comment by juninhodeluca** [comment]
Please, check this link
[https://react-data-table-component.netlify.app/?path=/docs/api-props--page](https://react-data-table-component.netlify.app/?path=/docs/api-props--page)
Section Row Expander, look for onRowExpandToggled

**Comment by MichelZiade** [comment]
Thank you very much !!! I was searching for that one, I was using expandableRowsComponent and it was always calling the dispatch. THANKS

**Comment by MichelZiade** [comment]
Like is there a way to add an onClick on any elements on the row so the row can be expanded ?
