### ISSUE TITLE
SortIcon: Please make it always visible

### ISSUE THREAD

**Issue by sv1979** [jbetancur/react-data-table-component#1075]
I am trying to achieve cerain appearance and I need SortIcon in the table header always be visible (not only on hover).
I can not find anything about its behaviour in headCells styling section.
I made some changes for its placement but now it disappearing when I am hovering the table head cell. My customs style for head cell looks like this now:

    headCells: {
      style: {
        color: '#fff',
        fontSize: '18px',
        textTransform: 'uppercase',
        backgroundColor: '#222',
        'svg' : {
          marginLeft: '5px',
          opacity: '1 !important',
          display: 'block'
        }
      }
    },

**Comment by codigoisaac** [comment]
@sv1979 where you able to solve this and make the sort icon always visible? I would like to achieve this too...

**Comment by nstylo** [comment]
Why was this closed? It would be great to always see the sorting direction. Especially when reloading and pass on an initial sorting, the arrow is not showing, although the table is sorted on that column.
