### ISSUE TITLE
Default LANG

### ISSUE THREAD

**Issue by jcdesignweb** [jbetancur/react-data-table-component#1089]
How can I change the Language? Is it possible this?
In case does not possible.. How can I change the default String values? E.g: "There are no records to display"
( I already read the docs but I could not finded anything )

**Comment by juninhodeluca** [comment]
Not sure if is possible to do for full library, but you can ever do it by component.
Check here https://react-data-table-component.netlify.app/?path=/docs/api-props--page
and look for noDataComponent. It could be string or a react-component

**Comment by jcdesignweb** [comment]
Hi @juninhodeluca thanks for your answer but What about the other values?

**Comment by juninhodeluca** [comment]
Hi. Nice to know I'm helping. Basically, all pieces of DataTable React Component are made by smaller components.
If you wanna change something inside the paginator component, just implement the text substitution on paginationComponentOptions (this works only with the built-in paginator), changing the text values by your i18n implemementation of that keys. I can, also create your own implementation using paginationComponent.
