### ISSUE TITLE
Responsive no work

### ISSUE THREAD

**Issue by Angelk90** [jbetancur/react-data-table-component#109]
## Describe the bug
I tried to put the responsive property in the table but it seems to be malfunctioning.

## To Reproduce
I open the page in question is the resize.

## Expected behavior
That the table was resized.

**Comment by jbetancur** [comment]
`responsive` prop only allows you to scroll horizontally when the view is smaller than the table.

Ideally, and when I have time I would like to work on a feature that collapses the table to X rows depending on screen width, however,  there are some challenges to that (sorting, paging, fixed headers) that need to be hashed out

**Comment by jbetancur** [comment]
closing this as Works as Designed.

When I get around to it I will open a separate feature around making rdt work on smaller devices.
