### ISSUE TITLE
Can not make horizontal scroll bar always visible

### ISSUE THREAD

**Issue by andy-yu-y** [jbetancur/react-data-table-component#1096]
There is no way to make  horizontal scroll bar always visible. User can only scroll down to the bottom of the table to do the scroll left and right action.
below is the code for your reference:
<div style={{ maxWidth: '100%' }}>
          <DataTable
            title={title}
            theme={window.THEME.palette.type}
            progressPending={pending}
            progressComponent={<LinearIndeterminate />}
            columns={getColumns()}
            data={tableData.list}
            keyField={keyField}

if add responsive={false} to the code, the horizontal scroll bar will impact the whole page not only data table and the background color is mess up.
![horizontal](https://user-images.githubusercontent.com/77145416/184088562-1891bf93-65dc-4c43-bac8-b777fae61f80.JPG)
![responsive](https://user-images.githubusercontent.com/77145416/184089612-d3b955f5-bc39-45de-8689-e25966645f06.png)
Any suggestion about it?

**Comment by advsuite** [comment]
I've the same issue on laptop

**Comment by andy-yu-y** [comment]
Can someone take a look at this issue? It is a pretty normal function should be considered.
Thanks.

**Comment by andy-yu-y** [comment]
issue still there.
