### ISSUE TITLE
Columns can be reordered when reorder is disabled

### ISSUE THREAD

**Issue by TxJson** [jbetancur/react-data-table-component#1109]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
If you have `reorder` disabled on your table columns, you can still make them reorder. This can be seen on the documentation as well when using the various stories (see GIF in Screenshots section). Sometimes this enables reorder for the whole table as well, although was unable to recreate that again for the example GIFs.

## To Reproduce
1. Disable reorder (assuming it is enabled)
2. Go to your table and drag from just about the start of a column.
3. You've now reordered the table.

## Expected behavior
I expect it to not be possible to reorder the table when `reorder` is disabled. 

## Code Sandbox, Screenshots, or Relevant Code
GIF with my Table
![still-possible-to-reorder](https://user-images.githubusercontent.com/16917393/188128267-0177bc28-0f39-4100-a265-1172d0bd30f3.gif)

GIF with table in Story
![still-possible-to-reorder-2](https://user-images.githubusercontent.com/16917393/188128688-d69173c9-403b-48d8-899f-f610bbbaa0d1.gif)

## Versions (please complete the following information)
 - React: 17.0.1
 - Styled Components
 - OS: Ubuntu Linux
 - Browser: Chrome Version 103.0.5060.114 (Official Build) (64-bit)

## Additional context
N/A

**Comment by mcinarpro** [comment]
Hello, I have the same issue.
Reorder is disabled in my datatable and I can drag and drop cells. 
@TxJson @jbetancur Do you have a solution for this problem?
