### ISSUE TITLE
pageIndex should not be set to 1 when user want to use own sort function

### ISSUE THREAD

**Issue by andy-yu-y** [jbetancur/react-data-table-component#1111]
Use below paras to try to override sort fuction, handleSort is the method which i would like to use.
sortServer
onSort={handleSort}

But before handleSort is called, the key para pageIndex is auto changed to 1 which is not expected.
Is there anyway can avoid this behaviors?
I would like to have full control of sort function inside handleSort method.

**Comment by ahmed-kareem9** [comment]
@andy-yu-y  have you find any solution for this?
