### ISSUE TITLE
Ouput current row index in ExpandComponent

### ISSUE THREAD

**Issue by LouisMuriuki** [jbetancur/react-data-table-component#1117]
Hello, I apologize for asking what might seem to be a novice question but am stuck somewhere and I need your help,Please
I want to output something when a row is expanded, when the first row is expanded it should should show "this is row one" and the second "this is row two" like that but i cant figure out how to do it. I have followed the doc and did a couple of trials but to not avail
This is how i have setup my table

       <DataTable
        title="Movie List"
        columns={columns}
        data={completedProducts}
        expandableRows
        expandableRowsComponent={ExpandedComponent}
        pagination
        />

        const ExpandedComponent =({ data }) => {
       // i would like to show the index of the current expanded row here 
        });
        };
how do you recommend me to do it.?

**Comment by LouisMuriuki** [comment]
got a workaround

**Comment by wojciech-piekarczyk-fg** [comment]
> got a workaround

Hi, do you remember what the workaround was? Have run into the same issue. Thanks
