### ISSUE TITLE
Custom expander button and disable expandable feature for specific rows

### ISSUE THREAD

**Issue by Wiland** [jbetancur/react-data-table-component#112]
Hi,

I'm looking for adding a custom element instead of the default expander button, is there any way to do that with the current props of the component?

And also, I want to disable the expandable feature for some specific rows due to data validations, but I don't know if this is possible.

I hope you can help me clarify these questions.

Thanks!

**Comment by jbetancur** [comment]
Yes, see the readme section for theming. 
https://github.com/jbetancur/react-data-table-component#theming

I've actually been meaning to move this to a property in the future, but for now use theming.

You can juse edit: `collapsedButton` and `collapsedButton`. make sure you properly encode your svg or icon. e.g.

```
  expander: {
    fontColor: 'rgba(0,0,0,.87)',
    backgroundColor: 'transparent',
    collapsedButton: 'data:image/svg+xml,%3Csvg%20fill%3D%22%23757575%22%20height%3D%2224%22%20viewBox%3D%220%200%2024%2024%22%20width%3D%2224%22%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%3E%0A%20%20%20%20%3Cpath%20d%3D%22M8.59%2016.34l4.58-4.59-4.58-4.59L10%205.75l6%206-6%206z%22/%3E%0A%20%20%20%20%3Cpath%20d%3D%22M0-.25h24v24H0z%22%20fill%3D%22none%22/%3E%0A%3C/svg%3E',
    expandedButton: 'data:image/svg+xml,%3Csvg%20fill%3D%22%23757575%22%20height%3D%2224%22%20viewBox%3D%220%200%2024%2024%22%20width%3D%2224%22%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%3E%0A%20%20%20%20%3Cpath%20d%3D%22M7.41%207.84L12%2012.42l4.59-4.58L18%209.25l-6%206-6-6z%22/%3E%0A%20%20%20%20%3Cpath%20d%3D%22M0-.75h24v24H0z%22%20fill%3D%22none%22/%3E%0A%3C/svg%3E',
  },
```

**Comment by jbetancur** [comment]
As for disabling the expander for specific rows, this is not currently possible. I imagine this feature could just be a prop that you can set on your data that the table will look for and disable the expander.

`expanderDisabledProp="disabled"`

Then you just manage that prop however you map your data set.

I don't have time to add this right now, but I'm open to PR requests ;)
