### ISSUE TITLE
[FEATURE]: [Column resizing]

### ISSUE THREAD

**Issue by Simon-Druchinin** [jbetancur/react-data-table-component#1131]
## Column resizing feature.

Dear @jbetancur. I would be grateful if you would implement a column resizing to this already flawless datatable.

**Comment by hari-bhandari** [comment]
has this been completed? how do we use it? thanks

**Comment by KikoAraujo** [comment]
How can we use the column resizing @jbetancur?

**Comment by MeterKishor** [comment]
@jbetancur ?
