### ISSUE TITLE
Intercept the change in status of the column sorting for table pagination server-side

### ISSUE THREAD

**Issue by Angelk90** [jbetancur/react-data-table-component#114]
**Is your feature request related to a problem? Please describe.**

I'm using the server-side paging table, the problem that when I try to sort data by column the data is not sorted, because the data is server-side paged.

**Describe the solution you'd like**

Add a method that intercepts which column you are trying to sort at the time the action takes place and what sort of sort "asc or desc".

**Comment by jbetancur** [comment]
I believe this is what `onSort` does. However, there is a bug I am working to fix where the state is stale

https://github.com/jbetancur/react-data-table-component/issues/113

**Comment by jbetancur** [comment]
It seems I did not document this in the README. I will update that as well.

**Comment by Angelk90** [comment]
@jbetancur  : where can I find an example where onSort is used?

**Comment by jbetancur** [comment]
see https://github.com/jbetancur/react-data-table-component/issues/114
There will be a 1.6.0 with fixed sorting in an hour or so

**Comment by Angelk90** [comment]
@jbetancur : At the moment I have installed version 1.5.3, but on npm I find version 1.5.5, let me know when you update the version on npm.

**Comment by jbetancur** [comment]
1.6.0 is now available! please see the release notes.

**Comment by Angelk90** [comment]
@jbetancur : Ok, it seems to work but it doesn't tell me the sortDirection.

return
```
{
id: "EDFMbgAbz"
name: "Id"
selector: "id"
sortable: true
}
```

**Comment by jbetancur** [comment]
It’s the second parameter in the call back. That is just the column

**Comment by Angelk90** [comment]
@jbetancur  : ok, but why not put it as assigned to the inside of the first parameter?

**Comment by jbetancur** [comment]
Because the first parameter is just the column object you configured when you set up your columns, not the internal state of what is being sorted. 

This pattern gives you access to your the all the selected column should props should you need them.

```
handleOnSort({ selector, name, sortable, .... }, sortDirection ) {
   console.log(selector, sortDirection)
}
```

or

```
handleOnSort(selectedColumn, sortDirection ) {
   console.log(selectedColumn.selector, sortDirection)
}
```

**Comment by bsides** [comment]
What if my sorting happens only server side? Right now, if I sort server side it first tries to sort front side (re-render the component) then after the data is brought back from the server it's rendered again. Could you help me with that? Maybe I should `sortable: false` and add an `onclick` event in each column header? 

Also, since it's returning the column configured by me and in some columns I need to transform the data (example: a column that returns boolean, I transform the result into something readable like 'active' or 'inactive') I can't reach that value because it is a return from the function and the param isn't in that context.

Example:

```javascript
const columns = useMemo(
  () => [
    // ...
    {
      name: 'Status',
      cell: ({status}) => (status ? 'Active' : 'Inactive')
    }
])
// ... 
function handleSort(column, sortDirection) {
  console.log(column.cell())
}
```

`TypeError: Cannot read property 'status' of undefined`

**Comment by jbetancur** [comment]
Good question. RDT probably needs a feature to disable the client-side sorting  i.e. `sortServer`.

If you could open a new issue for this I'll take a look at adding `sortServer`

A workaround for you can hijack the `sortFunction` property that is used to override the default sort behavior, then handle `onSort` and use `progressPending` if you wish to show the data is updating.
```
sortFunction={row => row} // this is sort of a noop that just returns the row back unsorted
progressPending={isSorting} //
onSort={handleSort}  
```

**Comment by jbetancur** [comment]
Regarding your second question, you can try `format` instead of `cell`:

```
  () => [
    // ...
    {
      name: 'Status',
      format: ({status}) => (status ? 'Active' : 'Inactive')
    }
])
```
`cell` is used when you want to pass in a compeont and `format` when you just want to transform the row

**Comment by bsides** [comment]
> If you could open a new issue for this I'll take a look at adding `sortServer`

Sure thing. I believe it's as easy as just checking this variable to skip some others.

> A workaround you can hijack the `sortFunction` property that is used to override the default sort behavior, then handle `onSort` and use `progressPending` if you wish to show the data is updating.

That's exactly what I did, thanks!

> Regarding your second question, you can try `format` instead of `cell`:
I tried but then an error I never saw is thrown `Error: selector must be a . delimted string eg (my.property)` 😭 

![image](https://user-images.githubusercontent.com/87631/62979477-4b0b0d80-bdfa-11e9-87ca-c6843417f410.png)

It may not be associated with the component though, so I'm investigating

**Comment by bsides** [comment]
> It may not be associated with the component though, so I'm investigating

Well it is and isn't. I didn't know if I pass `format` it needs a `selector`. Maybe I should open a PR with that info on the docs 😄

**Comment by jbetancur** [comment]
You still need the selector if you are sorting
