### ISSUE TITLE
I cant build react website with react-data-table-component

### ISSUE THREAD

**Issue by linthujan** [jbetancur/react-data-table-component#1169]
> set NODE_OPTIONS=--openssl-legacy-provider &&  react-scripts build

Creating an optimized production build...
Failed to compile.

./node_modules/react-data-table-component/dist/index.cjs.js
TypeError: buildUndefinedNode is not a function

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/react-data-table-component/dist/index.cjs.js:1:552

Read more here: http://bit.ly/2tRViJ9

**Comment by Git-Codder** [comment]
@linthujan Could you please provide additional information about the error? 
I am currently using the same library for a project. If you could share some code or any details that might help me reproduce the error, it would be greatly appreciated.

**Comment by linthujan** [comment]
> @linthujan Could you please provide additional information about the error? I am currently using the same library for a project. If you could share some code or any details that might help me reproduce the error, it would be greatly appreciated.

it showed like above but it worked perfectly
before i used react scripts 1.x 
so that showed above warning but everything is fine on production live 
you can use this without hesitate
