### ISSUE TITLE
Sorting is case sensitive

### ISSUE THREAD

**Issue by jnbrn** [jbetancur/react-data-table-component#117]
Is there a way for sorting to case insensitive or prevent default sorting mech when onSort is present.

![image](https://user-images.githubusercontent.com/46614865/59898640-48a4bc80-9424-11e9-86db-b9ab78f384a1.png)

**Comment by jbetancur** [comment]
There is currently no way to case insensitive sort. It would probably be easy to just replace the `defaultSortField` param with a function instead and add a new `sortCaseInsensitive` bool prop so. I'll look into this as a potential feature but it probably won't happen until sometime next week.

```
   this.sortedRows = memoize((rows, defaultSortField, direction) => orderBy(rows, defaultSortField, direction));
```

**Comment by jbetancur** [comment]
I'm going to introduce a new prop `sortFunction`. It will essentially allow you to override the default sort behavior. This way, rather than adding opinionated props you can just control your own sort behavior as needed.

Here is an example:

```
const customSort = (rows, field, direction) => {
  const handleField = row => {
    if (row[field]) {
      return row[field].toLowerCase();
    }

    return row[field];
  };

  return orderBy(rows, handleField, direction);
};
....
<DataTable ...... sortFunction={customSort}>
```

The `sortFunction` would achieve your lowercase sorting or whatever other custom behavior you want. It's a bit more code than just adding `sortCaseInsensitive` but it keeps the spirit of this data table being flexible

**Comment by jbetancur** [comment]
also, something else to consider is that you can just map your own data set before it is loaded and add a new field that is lowercased. Then, just use that new field in your column selector.

**Comment by jbetancur** [comment]
https://jbetancur.github.io/react-data-table-component/?path=/story/basic--sortable-custom

**Comment by austingayler** [comment]
why not include this as a property of the columns array? 
```
const customSortFn = (a,b) => a.namelocaleCompare(b.name);
const columns = [name: "foo", selector: "foo", customSort=customSortFn];
const data = [{foo: "AAA"}, {foo: "AAA"}];
```

Then you can easily attach custom sorting on a per-column basis, which makes the most sense IMO.

**Comment by gokaco** [comment]
For case insensitive sorting you can pass ` sortTypes` in table props like this:
```
useTable({
    sortTypes: {
        alphanumeric: (row1, row2, columnName) => {
               return row1.values[columnName].toUpperCase() >
                   row2.values[columnName].toUpperCase()
                   ? 1
                   : -1;
         }
    }
})
```
