### ISSUE TITLE
[FEATURE]: Server-side pagination

### ISSUE THREAD

**Issue by talhameer** [jbetancur/react-data-table-component#1171]
## Feature Checklist

- [ ] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [ ] Read the README to ensure the feature is not already present
- [ ] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [ ] Considered the value versus complexity for all users of the library as well as library maintenance
- [ ] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe
In my app where I'm using the react data table component, I've a very large amount of data, so I've implemented pagination on the server side to make the API response optimized... But unfortunately, the library doesn't support the server-side pagination yet...

**Comment by ZenHarbinger** [comment]
I got around this by tracking: onChangeRowsPerPage, onChangePage, onSort
Then I can send a request to the server to get data based on the desired sorting with an offset and limit based on what page I am on and the pageSize.  Any data returned from the server should also have a total length count to set paginationTotalRows.

**Comment by talhameer** [comment]
Thanks @ZenHarbinger. I fixed this issue the way you mentioned. Actually, I was missing `totalRowCount` back then.
