### ISSUE TITLE
Tables on the Netlify documentation website appear as plaintext now

### ISSUE THREAD

**Issue by PleatherStarfish** [jbetancur/react-data-table-component#1202]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
Tables on the Netlify documentation website appear as plaintext now.

## To Reproduce
Go to the website at https://react-data-table-component.netlify.app/?path=/docs/api-props--docs or https://react-data-table-component.netlify.app/?path=/docs/api-columns--docs and notice the lack of tables.

## Expected behavior
Documentation on the Netlify website previously displayed things like the "Column Definitions API" as a table of properties.

## Code Sandbox, Screenshots, or Relevant Code
<img width="1916" alt="Screenshot 2024-01-13 at 1 53 49 PM" src="https://github.com/jbetancur/react-data-table-component/assets/10040486/1c829649-0dc7-45db-867a-793446855ac0">

## Versions (please complete the following information)
n/a

## Additional context
n/a

**Comment by ADTC** [comment]
Came here to report the same. What's going on?
