### ISSUE TITLE
When using materialize-css and activating pagination a scrollbar appears

### ISSUE THREAD

**Issue by ferrettinico** [jbetancur/react-data-table-component#121]
Looks like this: https://ibb.co/zhPtGzP

And you can scroll for 1px

Without pagination activated works flawlessly.

This is the latest version of this library/react/materialize-css

Thanks!

**Comment by ferrettinico** [comment]
If I remove the property overflow-x from the chrome dev tools it looks like this:
![data](https://user-images.githubusercontent.com/9100708/60276344-cc9def00-98d1-11e9-9e40-0a5f95ebdaf6.jpg)

a blue block appears and it looks better

**Comment by ferrettinico** [comment]
Fixed by adding the following CSS, to override materialize nav styles

```css
nav.rdt_TableFooter {
  line-height: unset;
  box-shadow: unset;
}
```

**Comment by jbetancur** [comment]
The overflow-x is used to control the hidden context actions. 

Perhaps something with materialize-css is causing this. It would be good to see which css props are being computed on the footer and from where.
