### ISSUE TITLE
Second icons on rows per page element

### ISSUE THREAD

**Issue by alfi-dim** [jbetancur/react-data-table-component#1221]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [ ] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
There's a second icons on my rows per page element

## To Reproduce
Create component as docs recommended

## Expected behavior
Only ONE icon on that element

## Code Sandbox, Screenshots, or Relevant Code
my first table
```
<DataTable
    title="Data Rekap Lembur"
    columns={columns}
    data={recapData}
    customStyles={customStyles}
    noDataComponent="Tidak ada data"
    fixedHeader
    fixedHeaderScrollHeight="300px"
    progressPending={loadingFetchRecap}
    pagination
    paginationServer
    paginationTotalRows={paginationTotalRows}
    onChangeRowsPerPage={onChangeRowsPerPage}
    onChangePage={onChangePage}
  />
```
![image](https://github.com/jbetancur/react-data-table-component/assets/74103308/2bb28c22-48ab-475f-8dfb-53b5329d8a4a)

my second table
```
<DataTable
    title="Data Analisa Lembur"
    columns={columns}
    data={dataAnalytics}
    customStyles={customStyles}
    noDataComponent="Tidak ada data"
    fixedHeader
    fixedHeaderScrollHeight="300px"
    progressPending={loadingAnalytics}
    pagination
    paginationServer
    paginationTotalRows={totalDataAnalytics}
    onChangeRowsPerPage={handlerPerRowChange}
    onChangePage={handlePageChange}
  />
```
![image](https://github.com/jbetancur/react-data-table-component/assets/74103308/28cd1a92-8dcf-4fd2-85ee-72ac73ecc937)

## Versions (please complete the following information)
 - NextJS 14.1.4
 - Styled Components 6.1.8
 - OS: Windows 11
 - Browser MS.Edge

**Comment by allan-vera** [comment]
i see this too

**Comment by alfi-dim** [comment]
> i see this too ![Screenshot 2024-04-01 at 1 09 39 PM](https://private-user-images.githubusercontent.com/153534041/318512670-2f7ae9cc-54dd-4db8-b13d-a7aad709c509.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjEwMjEsIm5iZiI6MTcxMjAyMDcyMSwicGF0aCI6Ii8xNTM1MzQwNDEvMzE4NTEyNjcwLTJmN2FlOWNjLTU0ZGQtNGRiOC1iMTNkLWE3YWFkNzA5YzUwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQwMTE4NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDYxYjkzOTAzMDE0MTY0MjgwMTAxODY2ZDUyMWM0YjI0ZjZkMWY4MTQxMmJhYTQ4ZTgzOWU3ZDU4ZTc5ZmFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fKCMvWG9qlW4uJRxVeIVOkMS_jfBDIll3a5Hk-ga_zk)
> 
> I solved it with this in a css file
> 
> ```
> .rdt_Pagination select {
>   background: transparent;
> }
> ```

Thanks! it solved my problem
