### ISSUE TITLE
expandableRowsComponent is not return row data

### ISSUE THREAD

**Issue by rakeshmanjunatha** [jbetancur/react-data-table-component#131]
i have followed the same steps mentioned in below link:

https://github.com/jbetancur/react-data-table-component/issues/31#issuecomment-421182392

But i'm getting undefined response.

**Comment by jbetancur** [comment]
Please use the issue template and include a code sandbox when logging issues and include a codesandbox of your issue. https://codesandbox.io/embed/react-data-table-sandbox-ienim 


Briefly looking at your code in comment https://github.com/jbetancur/react-data-table-component/issues/31#issuecomment-421182392 your `ExpandableComponent`  code is incomplete. You are missing your HTML tags and a leading paren:

e.g.
`const ExpanableComponent = ({ data }) => (<div>{data.title}</div>);`

**Comment by rakeshmanjunatha** [comment]
> Please use the issue template and include a code sandbox when logging issues. https://codesandbox.io/embed/react-data-table-sandbox-l6hpl
> 
> Briefly looking at your code in comment [#31 (comment)](https://github.com/jbetancur/react-data-table-component/issues/31#issuecomment-421182392) your `ExpandableComponent` code is incomplete. You are missing your HTML tags and a leading paren:
> 
> i.e.
> `const ExpanableComponent = ({ data }) => {data.title});`
> shoud be
> `const ExpanableComponent = ({ data }) => (<div>{data.title}</div>);`

Yes, actually that code copied from your statement only, but i noticed one thing  in code sandbox,

It wont work if we change the name of the variable "data" into some other name.
For reference,
![image](https://user-images.githubusercontent.com/34750717/60784276-ecec6a00-a16b-11e9-8ce7-40e1cf789907.png)

**Comment by jbetancur** [comment]
changing the name will not work because that is object destructuring. the destructed property is `data`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

**Comment by rakeshmanjunatha** [comment]
Thanks for the info
