### ISSUE TITLE
Do we have an option to wrap column name?

### ISSUE THREAD

**Issue by rakeshmanjunatha** [jbetancur/react-data-table-component#132]
Even i tried with "width" option but its not working.

**Comment by jbetancur** [comment]
Currently, no

**Comment by jbetancur** [comment]
Actually, try using one of the className hooks `rdt_TableCol` You can set whatever css you need to make it wrap

**Comment by rakeshmanjunatha** [comment]
okay thanks.

**Comment by rakeshmanjunatha** [comment]
Hi

**rdt_TableCol**  is not working especially for wrapping. Because of this below class,

In this below class you have specified **min-width: 100px;** width and **white-space: nowrap;** 
even i'm not able to override this class.

.bILqDE {
    position: relative;
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-align-items: center;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    box-sizing: border-box;
    line-height: normal;
    padding-left: calc(48px / 6);
    padding-right: calc(48px / 6);
    padding-top: calc(48px / 12);
    padding-bottom: calc(48px / 12);
    -webkit-flex: 1 0 0;
    -ms-flex: 1 0 0;
    flex: 1 0 0;
    max-width: 100%;
    min-width: 100px;
    font-size: 12px;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    font-weight: 500;
    white-space: nowrap; 
    color: rgba(0,0,0,.54);
    min-height: 48px;
}

**Comment by jbetancur** [comment]
Try !imporant or && to increase the specificity

**Comment by rakeshmanjunatha** [comment]
Even I tried with ! important, it's not working.

**Comment by rakeshmanjunatha** [comment]
Can you please allow us to override the class .*blLqDE *so that it will be
help full for us to wrap the column name easily.

**Comment by jbetancur** [comment]
@rakeshmanjunatha I recently made some changes to the css for Table Col in release `2.0.1` .  Among many internal changes, I also removed the css line that was restricting word wrap. `TableCol` text should now wrap when you shrink the table down or when the names are long.

**Comment by rakeshmanjunatha** [comment]
Thanks
