### ISSUE TITLE
Have some layout problem with Samsung Browser

### ISSUE THREAD

**Issue by sangumee** [jbetancur/react-data-table-component#133]
## Report

I have some issue with mobile layout.

I tested various environment and tested results are like this.

Google Chrome (Desktop) : Works Well
Google Chrome (Android Latest) : Works Well
Google Chrome Developer Tool (Mobile & Responsive Test) : Pass

Samsung Internet (Android Latest) : Have Some Problem
<img src="https://i.imgur.com/RKn2d2k.jpg" width="50%">

And also I got some report from Safari Browser user but I cannot test it because I don't have any apple machines. And It seems that layout are broke same with samsung browser.

I did not use any UI framework so It seems that some CSS are not compatible with Safari Browser and Samsung Browser. Is there any solution with this?

## Code Sandbox & Github Pages
[Github Pages Link](https://sangumee.github.io/Crypto-Table)

[Code SandBox Link](https://codesandbox.io/s/github/sangumee/Crypto-Table/tree/master/)

**Comment by jbetancur** [comment]
Thanks for logging this. Unfortunately, I don't have a Samsung device to test but I will see if I can find anything. It's possible I saw this issue on an older version of Edge.

btw, it looks like you are using an older codesandbox link.  can you try switching the react-data-table-component version to the latest 1.7.2 just to be sure?

**Comment by jbetancur** [comment]
Actually, I think this may be an issue with `fixedHeader` can you remove that and see if it renders correctly?  to be honest `fixedHeader` is kinda buggy in its current form.

**Comment by jbetancur** [comment]
the issue is more specifically with `max-height` or setting any fixed height, which is necessary for making the fixed header work.  I may hide this feature until it's more ready for prime time.

**Comment by jbetancur** [comment]
Seems that adding a min-height: to TableRows fixes the issue. If you want to work around this for now just use use the css className `rdt_TableRow` and add a `min-height`

**Comment by jbetancur** [comment]
I'll have a 1.7.3 with a fix that I will publish shortly.

**Comment by sangumee** [comment]
Thanks! Solved.
