### ISSUE TITLE
Responsive Hide Columns

### ISSUE THREAD

**Issue by jbetancur** [jbetancur/react-data-table-component#136]
Implement a feature that hides columns for a certain screen width.

* Define breakpoints (that can be overridden)sm, md, lg, custom
* new column prop that hides the column/cells in a media query

**Comment by marlosirapuan** [comment]
Hi, i'm having a problem with this property

![image](https://user-images.githubusercontent.com/802722/87883820-6609d880-c9e0-11ea-809e-a97b519ec0c1.png)

```ts
const columns = useMemo(() => {
    return [
      {
        name: 'Nome',
        selector: 'name',
        sortable: true,
        grow: 2
      },
      {
        name: 'Email',
        selector: 'email',
        sortable: true
      },
      {
        name: 'Ativo',
        selector: 'active',
        sortable: true,
        // eslint-disable-next-line react/display-name
        cell: (row: DataUser) => <BagdeActive active={row.active} />
      },
      {
        name: 'Cadastro',
        selector: 'created_at',
        sortable: true,
        // @ts-ignore
        cell: (row: DateUser) => {
          return format(parseISO(row.created_at), 'dd/MM/yy HH:mm')
        },
        hide: 'sm'
      }
    ]
  }, [])
```

![image](https://user-images.githubusercontent.com/802722/87883743-cea48580-c9df-11ea-839c-0d01a40792ae.png)

If I put `hide: 300` or any number works without error (but not hide).
