### ISSUE TITLE
Support TypeScript

### ISSUE THREAD

**Issue by vladimirvorobiev** [jbetancur/react-data-table-component#137]
**Is your feature request related to a problem? Please describe.**
any plans to support Typescript?

**Comment by jbetancur** [comment]
Yes! It will probably be a version 2 also with prop some clean up and slight architectural changes. Probably not anytime soon though as my schedule is hectic.

**Comment by jbetancur** [comment]
Thoughts on flow va typescript? I’m leaning towards typescript

**Comment by DocCaliban** [comment]
+1 Typescript.

**Comment by janhartmann** [comment]
See: https://github.com/jbetancur/react-data-table-component/pulls

**Comment by jbetancur** [comment]
Typescript definitions will be in a 4.0 release later today. I'll go ahead and close this out. As for moving the codebase to typescript, I'll open separate features for that.

**Comment by veddermatic** [comment]
First: Thank you so much for adding types!  

Second: stupid question: I've installed 4.0 but typescript doesn't acknowledge that types exist.

**Comment by janhartmann** [comment]
I guess they need to be in the files section on psckage.json then.

**Comment by jbetancur** [comment]
I think it index.d.ts needs to live next to the index file in dist. @janhartmann perhaps we Just need to change files package.json to place the file in dist?

**Comment by DocCaliban** [comment]
I typically put it under 'src/types'
then make sure the declaration in package.json is
"types": "./src/types/index.d.ts"
