### ISSUE TITLE
Specify the width of a column

### ISSUE THREAD

**Issue by MarcDAFrame** [jbetancur/react-data-table-component#138]
is there any way to specify the width of a column? I have a column which should take up about 50% of the width and another that would only require 10%. 

its a bit of a waste to have them be all the same size.

otherwise, really like this component.

**Comment by jbetancur** [comment]
Yep, there is column.width, column.minWidth and since it’s a flex based table you use column.grow if you want to column to grow or take up more space more than the rest (every column has a default grow of 1)

https://github.com/jbetancur/react-data-table-component/blob/master/README.md#columns
