### ISSUE TITLE
A working Demo could make things very clear

### ISSUE THREAD

**Issue by faizhameed** [jbetancur/react-data-table-component#157]
A good demo showing the wokring table would be nice. At least a good motivation for users to implement it
Thank you

**Comment by jbetancur** [comment]
There is a storybook link in the Readme.

https://jbetancur.github.io/react-data-table-component

**Comment by jbetancur** [comment]
Otherwise, was there something specific you are asking for?

**Comment by jbetancur** [comment]
I "think" what you are looking for is `onRowClicked`. If you take a look at the README, `onRowClicked` is a callback you can use to access the row and event (if needed).
