### ISSUE TITLE
Empty space in the header that is not used

### ISSUE THREAD

**Issue by Angelk90** [jbetancur/react-data-table-component#161]
## Describe the bug
I removed the title from the DataTable because I didn't need it, but I realized that if no element is found the space in the header remains the same and this gives me several problems because it takes up space unnecessarily.

## Expected behavior
If there is nothing in the header then that space should not be put.

## Code Sandbox
https://codesandbox.io/s/react-data-table-sandbox-nu4gm

## Screenshots
![Screenshot_20190725_111kk126](https://user-images.githubusercontent.com/20476002/61862016-6eaef800-aecd-11e9-9572-4ddf4c10a516.png)

**Comment by jbetancur** [comment]
use the `noHeader` prop to hide the header.  The reason for this also is that header can take actions and is also used for the `selectableRows` context menu.

**Comment by jbetancur** [comment]
Closing as I assume this is resolved. Let me know otherwise
