### ISSUE TITLE
Striped Columns

### ISSUE THREAD

**Issue by jbetancur** [jbetancur/react-data-table-component#174]
Similar to the striped row feature, it might be cool if you could apply a different color to a column within the columns config:

```js
const columns = [
  ...
  striped: '#FAFAFA'
];
```

**Comment by puuble** [comment]
I want to excel theme. looks like excel bordered or space. How to change it. I tried customTheme but i didnt. :(

**Comment by jbetancur** [comment]
I really can't help you without some details 😉  Did you read the section on theming in the README?

In any case, this sounds like a separate question unrelated to this issue.

**Comment by puuble** [comment]
yes, i read. but i can't add a border to cells.

**Comment by jbetancur** [comment]
Ok adding a border to cells is an interesting feature, but this won't be possible with theme-ing. 
Likely it would be a new property `borderedCells` perhaps? 

Please open a new ticket for it and I will try to get some time to work on it :)

**Comment by jbetancur** [comment]
Changed my mind about this feature - closing unless there is demand
