### ISSUE TITLE
bordered cells/can add border to cells.

### ISSUE THREAD

**Issue by puuble** [jbetancur/react-data-table-component#183]
Maybe we can add border to cells. And can we do like this [datatable](https://www.ag-grid.com/example.php#/)   with your library

**Comment by jbetancur** [comment]
I don't see borders on the cells in that example. Do you mean something simple like this?

![Screen Shot 2019-07-31 at 5 07 01 PM](https://user-images.githubusercontent.com/1385932/62248332-d4135500-b3b5-11e9-8bcb-7ce12449b29e.png)
