### ISSUE TITLE
Select all rows changes allSelected to "true" but doesn't actually select them

### ISSUE THREAD

**Issue by sotirelisc** [jbetancur/react-data-table-component#186]
## Describe the bug
Selecting all rows sets allSelected to true, but selectedRows array remains empty and rows are not actually selected. The select all checkbox is correctly checked.

I didn't do any configuration and it didn't work before Redux either.

## To Reproduce
1. Go to table
2. Click on select all checkbox
3. See result (you can also check the console for the updates)

## Screenshots
<img width="259" alt="Screenshot 2019-08-02 at 15 49 47" src="https://user-images.githubusercontent.com/7081352/62371308-2fbc1a80-b53d-11e9-9456-9d38c4c25b0f.png">

<img width="592" alt="Screenshot 2019-08-02 at 15 50 38" src="https://user-images.githubusercontent.com/7081352/62371336-4b272580-b53d-11e9-92cf-67e0f85bc4f1.png">

**Comment by jbetancur** [comment]
What version of rdt? This is fixed in the latest  Version 3.0.4

**Comment by jbetancur** [comment]
It looks like you are using an older version. Btw, onTableUpdated has been deprecated. Please use onRowSelected instead.

**Comment by sotirelisc** [comment]
I'm using onRowSelected but, yes, it was due to version 3.0.1. I installed in only a few days ago, so I thought it was the latest one. Thanks!
