### ISSUE TITLE
[Demos] Add example for creating link in cell

### ISSUE THREAD

**Issue by rtbishop** [jbetancur/react-data-table-component#191]
Related to issue #120 

**Suggestion**:
Minor suggestion, but it might be helpful to others to add a demo example (or add this in one of the existing demo examples) for creating a link within a cell (probably a frequent use case for people). I was stumped for a bit until I found the above issue instructing to use ignoreRowClick. Also under API and Usage perhaps add a note for this-

prevents the onRowClicked event from being passed on a specific TableCell column. This is really useful for a menu or button where you do not want the onRowClicked triggered. _For hyperlinking text this should be set to true_.

**Code Snippet**:
This would be for the Custom Cell - Movie List example.
```
const columns = [
  {
    name: 'Title',
    selector: 'title',
    sortable: true,
  },
  {
    name: 'Director',
    selector: 'director',
    sortable: true,
  },
  {
    name: 'Genres',
    selector: 'genres',

    cell: row => row.genres.map((genre, i) => <div key={i}>{genre}</div>),
  },
  {
    name: 'Year',
    selector: 'year',
    sortable: true,
  },
  {
    name: 'Poster',
    selector: 'posterUrl',
    cell: row => <img height="42px" width="80px" alt={row.name} src={row.posterUrl} />,
  },
  {
    name: 'IMBd',
    ignoreRowClick: true,
    cell: row => {
      return (
        <a href="#">IMBd link</a>
      );
    }
  }
];
```

**Comment by jbetancur** [comment]
@rtbishop I amended the Custom Cells storybook example to reflect links as well as other custom fields. This is a stopgap and probably needs some fancier examples or other real-world use cases in the future

**Comment by jbetancur** [comment]
#204
