### ISSUE TITLE
Infinite pagination

### ISSUE THREAD

**Issue by gsrosa** [jbetancur/react-data-table-component#193]
When the datatable is using the paginate and it has the data updated, in specific case the component generate a specific pagination
For example:

perPage: 3
data.length: 4
currentPage: 2

![image](https://user-images.githubusercontent.com/34446944/62732758-8329df00-b9fb-11e9-9655-386dbaa20ae3.png)

-- event in table (by button) that update data to lenght = 3
this event is a request, it delete de item and update the data in table
result:

![image](https://user-images.githubusercontent.com/34446944/62732783-95a41880-b9fb-11e9-9a69-ea0f1c05df33.png)

![image](https://user-images.githubusercontent.com/34446944/62732795-9e94ea00-b9fb-11e9-9693-1ff7d35e165e.png)

**Comment by jbetancur** [comment]
Hmmm. I think I've seen this bug before. If you can provide me a code sandbox that would be helpful:

https://github.com/jbetancur/react-data-table-component/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by jbetancur** [comment]
What version of RDT are you using? 

I created a quick sandbox based on the info you provided, but you'll need to fill in the blanks for me to help further as I cannot duplicate otherwise:

https://codesandbox.io/embed/react-data-table-sandbox-data-6932d

**Comment by gsrosa** [comment]
https://codesandbox.io/s/react-data-table-sandbox-data-hs29m

**Comment by jbetancur** [comment]
Ahh you meant when the data is deleted. Yea, def a bug. I’ll see about getting a fix in soon.

**Comment by jbetancur** [comment]
This is now fixed in 3.0.9

**Comment by ThandeSperatti** [comment]
I used this version and the problem persists

**Comment by jbetancur** [comment]
Make sure you are actually updated to 3.0.9.

This is a fork of the original sandbox with the issue resolved:

https://codesandbox.io/s/react-data-table-sandbox-data-qo8cq

If you still have issues please include a code sandbox and more detail.

**Comment by miguelteixeiraNeev** [comment]
Is it possible to achieve the same behaviour on server pagination?
