### ISSUE TITLE
Column selector property doesn't accept arrays

### ISSUE THREAD

**Issue by DocCaliban** [jbetancur/react-data-table-component#205]
## Describe the bug
You can not use array data in the column selector property

## To Reproduce
1. Pass some Data and Selector to the component like the below sample
2. Render the component

## Expected behavior
Data shold render, but in  fact it does not

## Code Sandbox
https://codesandbox.io/s/react-data-table-sandbox-yqgb6

## Versions (please complete the following information)
React: 16.8.6
Styled Components: 4.3.2
OS: Windows 10
Browser Chrome, FF
react-data-table-component: 2.1.0

**Comment by jbetancur** [comment]
Not necessarily a bug just a missing feature 😉. 

Please update to v3.0.7 for array selector syntax.

### What about bracket notation?
Just in case someone asks - bracket notation is not supported at this time - unless there is some demand.

I may add bracket notation in the future or just "may" lodash get and be done with it, but, I'd prefer to move away from a lodash dependency while keeping the underlying selector code lightweight
