### ISSUE TITLE
Add an option to sort server side (sortServer)

### ISSUE THREAD

**Issue by bsides** [jbetancur/react-data-table-component#207]
**Is your feature request related to a problem? Please describe.**
Right now if I try to change the sort function (or onSort) to refresh the data from the backend, it will first sort on frontend then re-render with the updated data from the backend. 

**Describe the solution you'd like**
The ideal here is to only render after the data's changed - just disabling frontend sorting. Configurable by `sortServer: boolean` or something alike.

**Describe alternatives you've considered**
None.

**Additional context**
Refer to issue #114

**Comment by jbetancur** [comment]
sortServer added which disables internal sorting behavior. use onSort to get the sort state
