### ISSUE TITLE
`react-material-icons` takes forever to download and can be replaced with react-icons

### ISSUE THREAD

**Issue by harshzalavadiya** [jbetancur/react-data-table-component#211]
**Is your feature request related to a problem? Please describe.**
Whenever I am on low end network `yarn install` gets stuck forever due to `react-material-icons` package because package is really huge ~31MB

**Describe the solution you'd like**
Instead of using `react-material-icons` which is font-icon based solution we can replace it with https://www.npmjs.com/package/react-icons which is SVG based icons so it improves performance of storybook as it will only import only requested icons instead older font icon loading all icons as once

**Describe alternatives you've considered**
NA

**Additional context**
I already have made changes to remove `react-material-icons` completely and replace it with svg based `react-icons`
Sample Branch: https://github.com/harshzalavadiya/react-data-table-component/tree/refactor-react-icons

**Comment by jbetancur** [comment]
I agree that the size of material-icons is a pain during initial development, but react-md is just something I have as an example.  I've actually been wanting to remove react-md and material-icons and replace the examples with material-ui since that is what most people are using anyway. The icon lib for material-ui i much lighter weight

**Comment by harshzalavadiya** [comment]
Sounds Great,
I guess [material-ui](https://material-ui.com/) already has tree shakable [table](https://material-ui.com/components/tables/#tables) component
Then as of now no change required then :+1:

**Comment by jbetancur** [comment]
I mean use material-ui for examples ;) rdt is an alternative to material-ui table with functionality baked in, but you can use material-ui components with rdt which are the examples that would be cool to have
