### ISSUE TITLE
Programmatically set selected rows

### ISSUE THREAD

**Issue by mercurjl** [jbetancur/react-data-table-component#213]
**Is your feature request related to a problem? Please describe.**
Right now there doesn't seem to be a way to programmatically set selected rows. The only handlers that exist just allow the selected of rows via the interface by clicking the checkbox

**Describe the solution you'd like**
I would like to be able to pass the component a data set that has pre-selected rows. Right now you pass data for the rows that can intelligently map to a predefined selector:

`[{ id: 1, title: 'Conan the Barbarian', 
summary: 'Orphaned boy Conan is enslaved after his village is destroyed...',  
year: '1982', 
expanderDisabled: true, 
image: 'http://conan.image.png' }];`

 I would like to have another pre-defined property of the data array called "selected" or similar:
`[{ id: 1, title: 'Conan the Barbarian', 
summary: 'Orphaned boy Conan is enslaved after his village is destroyed...',  
year: '1982', 
expanderDisabled: true, 
image: 'http://conan.image.png',
selected: true
 }];`
That would pre-select the row for you when the table is displayed.

I dont think this is the end all or even proper solution to this, just one I had considered might be possible. Any insight is appreciated!

**Additional context**
I want to apologize in advance if this is already possible and I didn't see it in the readme.

**Comment by jbetancur** [comment]
@mercurjl I think this is a great suggestion for a feature and the way you describe adding a `selected` field is exactly how this can be implemented.

I'll add this as a feature for the next release.

**Comment by jbetancur** [comment]
Now available in 3.2.0!

You can use the `selectableRowsPreSelectedField` and tRDT will programmatically check rows for you. A caveat here is that you cannot use that field to control the checked state as that is still managed internally by design

**Comment by mercurjl** [comment]
Nice! Thanks for the quick turnaround on this. I'm currently trying to implement this and it doesn't seem to be working for me. When creating my data array I'm adding a field called `selectableRowsPreSelectedField` and setting it to true, but my rows are not selected when the table is rendered. Here is an example of what some of my data array might look like:
`[
  {
    "id": 0,
    "testParameter": "Peak Elongation (%)",
    "value": "12.95",
    "selectableRowsPreSelectedField": true
  },
  {
    "id": 1,
    "testParameter": "Residual Water (%)",
    "value": "2.56",
    "selectableRowsPreSelectedField": false
  },
  {
    "id": 2,
    "testParameter": "Absorbed Water (g)",
    "value": "2.46",
    "selectableRowsPreSelectedField": true
  }, ...]`

Thanks again for the quick turn around. Also, ps, in the readme for `selectableRowsPreSelectedField` the type column says it's a `string`, and the description says it's a `bool`.

**Comment by jbetancur** [comment]
NP! The Readme section on that is worded poorly. I'll fix that,. You can take a look at the example story for this https://jbetancur.github.io/react-data-table-component/?path=/story/basic--selectable-pre-selected-row but `selectableRowsPreSelectedField` is a prop that is set on `DataTable`. You would use that to reference a prop on your data 

```js
const myData =0[... {.... FieldIWantToUseForPreSelection: true }]

<DataTable 
  ....
  selectableRows
  selectableRowsPreSelectedField="FieldIWantToUseForPreSelection"

/>
```

**Comment by YoussefZidan** [comment]
> NP! The Readme section on that is worded poorly. I'll fix that,. You can take a look at the example story for this https://jbetancur.github.io/react-data-table-component/?path=/story/basic--selectable-pre-selected-row but `selectableRowsPreSelectedField` is a prop that is set on `DataTable`. You would use that to reference a prop on your data that is `boolean` on whether the row should be pre-selected.
> 
> ```js
> const myData =[... {.... FieldIWantToUseForPreSelection: true }]
> 
> <DataTable 
>   ....
>   selectableRows
>   selectableRowsPreSelectedField="FieldIWantToUseForPreSelection"
> />
> ```

It doesn't seem working for me
I added a key called `selected` to my data and added `selectableRowsPreSelectedField="selected"` and it's not working

**Comment by hiukky** [comment]
Same problem here! from what I saw it seems to be having some conflict with `onSelectedRowsChange` on the status is updated twice

**Comment by from81** [comment]
What's the status on this? It seems like it was closed, but the feature does not seem to be working as intended.
