### ISSUE TITLE
How to implement expand all, expand selected and collapse all

### ISSUE THREAD

**Issue by RossVertizan** [jbetancur/react-data-table-component#218]
We are having great success in using this component for developing a tabular display of data (obviously), it has almost everything we were looking for out of the box, and it worked the first time.

Our data rows have two levels of data beneath that can be expanded, and that also works nicely.  However, we would like to implement some buttons that will allow us to fully expand the selected rows and another to collapse all expanded rows, we will also implement an expand all button, though this is clearly a simpler case of the expand selected.

I have downloaded and looked through the code.  It is the first code I have looked at using the React memo method and the useState and useCallback.  I see that onRowClicked, appears to toggle the appearance, but I  don't see how.

How can we change the props to allow rows to be expanded or collapsed without clicking on them.

Thanks in advance for any time you take to look at this.

**Comment by rleslie1015** [comment]
Has this feature been added yet?

**Comment by jbetancur** [comment]
Not yet as I have not had the time, but I have this feature at the top pf my priority list. I wish it was easy, but this is going to required refactoring some things internally with how expandable row state is handled.

**Comment by glaucoheitor** [comment]
With the new update, is there any update on this feature?

**Comment by luciano1997** [comment]
is there currently a solution?

**Comment by mostafashabanelbanna** [comment]
i still want to expand the current row and collapse the other expanded one, is there's a way to do so?

**Comment by Matec12** [comment]
> i still want to expand the current row and collapse the other expanded one, is there's a way to do so?
yes.

I answered this question here

[https://stackoverflow.com/questions/71880759/expand-only-one-row-at-a-time-for-react-datatable-component](url)
