### ISSUE TITLE
Searchable Columns

### ISSUE THREAD

**Issue by jbetancur** [jbetancur/react-data-table-component#223]
A picture is worth a thousand words:
![](https://miro.medium.com/max/1600/1*jnENY_7hvq7iYlXayoQV3w.jpeg)

* One requirement is that the input component should have a property for custom inputs

**Comment by Angelk90** [comment]
@jbetancur :
Such a thing should work even if you use server-side pagination, right?

**Comment by realitas** [comment]
Hi, how to add text field under the column header like that?

**Comment by rishav-ss** [comment]
Any solution to this?
