### ISSUE TITLE
Styling issue

### ISSUE THREAD

**Issue by stelco** [jbetancur/react-data-table-component#229]
## Describe the bug
I am following the example here to add a custom checkbox.
https://github.com/jbetancur/react-data-table-component#overriding-with-a-3rd-party-ui-component-library
 It works but the native checkbox also appears.  The arrow on the expandable content is also hidden, although it does appear on page load then disappears. From my screenshot you can also see issues with the blue border on focus and the hover on the pagination.
I have included styled-components and react-md as dependencies (npm)

```
                                <DataTable className="pagination-align-left"
                                    columns={columns}
                                    data={this.state.data}
                                    pagination
                                    selectableRows
                                    selectableRowsComponent={Checkbox}
                                    selectableRowsComponentProps={{ inkDisabled: false }}
                                    sortIcon={<FontIcon>arrow_downward</FontIcon>}
                                    onRowSelected={handleChange}
                                    expandableRows
                                    expandableRowsComponent={<ExpandedSection />}
                                    customTheme={smallPadding}
                                />
```

## Expected behavior
Styling should work as expected. here: https://jbetancur.github.io/react-data-table-component/?path=/story/basic--expandable

## Screenshots
![image](https://user-images.githubusercontent.com/900574/64020059-932f6d00-cb28-11e9-8b84-9ad3051552c9.png)

## Versions (please complete the following information)
 - React
- react-md
 - Styled Components

**Comment by jbetancur** [comment]
Interesting... I kind of duplicated this in a codesandbox and looking at the DOM that is not the native checkbox but rather I think something is messed up with the way react-md is imported, or an import is missing. 

I recall that you needed to make sure your icons were correctly imported via css/sass or something like that, otherwise, you would get the native checkbox. I think the styles react-md requires are possibly not loading.

**Comment by jbetancur** [comment]
Ok, This appears to be a potential issue with how react-md is set up in your environment.

According to react-md docs https://react-md.mlaursen.com/getting-started/installation
*The Roboto font and material-icons should be included as well (or some equivalent). These fonts can be included via WebFontLoader or by locally hosting and using the provided Sass mixins to include them. See host-material-icons and host-google-font for more details.*

From past experience, I'm pretty resolving the issue with react-md will fix your checkbox issue, but let me know once that is resolved if the expander icons are still missing

**Comment by jbetancur** [comment]
Actually, I think I see the issue - still react-md related but you will notice if you inspect the DOM that `.md-selection-control-input` class for some reason is not being applied. If I uncheck the css values on that class it exhibits the same behavior you are describing

![react-md](https://user-images.githubusercontent.com/1385932/64038052-21095900-cb25-11e9-800a-644a44121a6a.PNG)

**Comment by stelco** [comment]
Hi, thanks for your quick reply.

If you look at my screenshot below, you will see that the material-icons arrow is loading ok so not sure why the other icons dont load like the expander arrow.
I am loading fonts from CDN in index.html...
```
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Roboto">
```
and importing like this...
`import { Checkbox, FontIcon } from 'react-md'`

With regards to the native checkbox displaying, do I need to import something else from react-md to fix this and hide them?

![image](https://user-images.githubusercontent.com/900574/64049638-5df93e00-cb6d-11e9-8486-312439884623.png)

**Comment by stelco** [comment]
Another quick question if thats ok...
I am already using MDB React for my layout and styling.
[](https://mdbootstrap.com/docs/react/)
Can this be used instead of react-md, or is there functionality required from this. e.g. the expander functionality, rotating icons etc?
Thanks.

**Comment by jbetancur** [comment]
Yea it’s not an icon issue as I initially thought but somehow the class for the input that react-md is not being applied. You. Can setup a codesandbox and see if you can supe it or log an issue with react-md.

As for your questions np! You can use whatever checkbox component or library you want as long as it’s built with React. Personally, I switched over to material-ui for other projects and will be moving over the examples for this library to that as well.

The expander uses no library as it’s just an svg icon wrapped in a react component. Note you can also override the default expander icon.

Hope that helps!

**Comment by stelco** [comment]
Hi, it turns out that I answered my own question!
The styles from mdb.scss were overriding react-md styles. I have created my own override styles to fix this as below...

```
//style overrides
.footer-hide footer {
  display: none;
}
.pagination-align-left footer.rdt_TableFooter {
  justify-content: flex-start;
}
.sites-dt .md-selection-control-input {
  display: none;
}
//override mdb.scss styles for react-md icons in datatables
svg {
  padding: 0!important;
}
button:focus {
  outline: 0!important
}
```

![image](https://user-images.githubusercontent.com/900574/64098316-7aa89800-cd5e-11e9-969a-6633886c5f99.png)

Thanks for your help though, pointed me in the right direction.

**Comment by stelco** [comment]
Something else I just noticed is that if I uninstall react-md it appears to work ok. I did need to keep styled-components installed though. My icons are now loaded from MDB. I was just wondering where the styled-components are used and will I come into issues not having react-md installed? Thanks.

**Comment by jvcastro** [comment]
![image](https://user-images.githubusercontent.com/8552367/64134287-3923f580-ce0f-11e9-8ea9-89e2c83ba87e.png)

Anyone who have a solution to get rid of these big gaps?

![image](https://user-images.githubusercontent.com/8552367/64134320-6a042a80-ce0f-11e9-9a3d-910b18c707c7.png)

**Comment by jbetancur** [comment]
@stelco rdt uses styled-components under the hood. It’s a peerDependancy which is why I have you install it separately.. This will not affect anything in your main app regardless of what css pre processor is used (react-md uses scams).

Rdt does use some internal classNames documented in the README, but they are unlikely to collide due to the way I named them.

Hope that clarifies!

**Comment by jbetancur** [comment]
@jvcastro I’d look into the column.grow  property and try setting it to 0,  or column.width for setting a fixed width.  Otherwise, Please use the issue template and submit a new issue with a codesandbox so I can better help you.

**Comment by jbetancur** [comment]
closing this as "answered" 😉
