### ISSUE TITLE
progressPending

### ISSUE THREAD

**Issue by stelco** [jbetancur/react-data-table-component#236]
Hi, I was just wondering how you configure progressPending to work correctly. When I add it to the Datatable params, it just freezes saying 'Loading...'

`                          <DataTable className="responsive-table site-headers pagination-align-left"
                                    columns={columns}
                                    data={this.state.sites}
                                    compact
                                    pagination
                                    highlightOnHover
                                    selectableRows
                                    selectableRowsComponentProps={{ inkDisabled: false }}
                                    onRowSelected={handleChange}
                                    expandableRows
                                    expandableRowsComponent={<ExpandedSection />}
                                    progressPending
                                />`

Thanks.

**Comment by stelco** [comment]
Hi, I was previously using this to show a loading spinner but it doesnt seem to work with your data table, I just get 'there are no records to display' before the data loads. Is there a work around for this? Thanks. https://medium.com/@pkellner/fetch-data-in-react-with-spinner-only-when-necessary-1ef2e451f541

**Comment by stelco** [comment]
I have created a codesandbox here.  If you uncomment the //progressPending on the datatable, you will see that it just says Loading...
Could you help with the re-render of this?
Thanks.

**Comment by jbetancur** [comment]
@stelco `data={rows}` loks like static data so `progressPending` does nothing here.  `progressPending` is meant for when you are loading your rows/data async. Simply adding it as a prop to `DataTable` does nothing. 

Here is an example where I use setTimeout to simulate a server call 

https://jbetancur.github.io/react-data-table-component/?path=/story/progress-indicator--custom

Another example of making a rest call (using class components) is here as well

https://jbetancur.github.io/react-data-table-component/?path=/story/pagination--server-side

e.g. componentDidMount loads the data and sets the progressPending to false when done.

Hope that helps!

**Comment by stelco** [comment]
working now and added a custom spinner. thanks.
https://jbetancur.github.io/react-data-table-component/?path=/story/progress-indicator--custom
