### ISSUE TITLE
handleClearRows

### ISSUE THREAD

**Issue by stelco** [jbetancur/react-data-table-component#237]
Hi, how would we use handleClearRows as per your example?..

`...
// set the initial state
state = { toggledClearRows: false }
...

const handleChange = (state) => {
  // You can use setState or dispatch with something like Redux so we can use the retrieved data
  console.log('Selected Rows: ', state.selectedRows);
};

// Toggle the state so React Table Table changes to `clearSelectedRows` are triggered
const handleClearRows = () => {
  this.setState({ toggledClearRows: !this.state.toggledClearRows})
}

class MyComponent extends Component {
  render() {
    return (
      <DataTable
        title="Arnold Movies"
        columns={columns}
        data={data}
        selectableRows // add for checkbox selection
        onRowSelected={handleChange}
        clearSelectedRows={this.state.toggledClearRows}
      />
    )
  }
);`

Thanks.

**Comment by jbetancur** [comment]
https://github.com/jbetancur/react-data-table-component/pull/245

Added storybook example for clearSelectedRows
