### ISSUE TITLE
DoubleClick

### ISSUE THREAD

**Issue by gsrosa** [jbetancur/react-data-table-component#239]
I was reading the documentation and I haven't find a function as "onRowDoubleClick". If you put this, it will be a good functionaly to make this a completed component.

**Comment by gsrosa** [comment]
I'm using this component in a project and one of requirements is a double click in the row to make an action. Would I want to know if it's possible to include this function in the component?

**Comment by jbetancur** [comment]
Ok, I’ll look into adding onRowDoubleClicked to 3.5.0

**Comment by MatheusLima7** [comment]
onRowDoubleClicked  not working in text

**Comment by MatheusLima7** [comment]
onRowDoubleClicked not working in text when I use **schema** with **cell** and div
