### ISSUE TITLE
Maintain header

### ISSUE THREAD

**Issue by gsrosa** [jbetancur/react-data-table-component#240]
I was thinking if is there the possibility to maintain the header when there isn't a noDataComponent

**Comment by B2alex** [comment]
I think maybe he is talking about the header row? I was wondering the same thing.

**Comment by jbetancur** [comment]
So if there is no data then still display the sortable TableHead?  It's certainly possible.

I'm curious what the use case for this is or if it is just preference?

I'd just want to weight out the demand for such a feature before adding new code and logic

**Comment by gsrosa** [comment]
yes, I was wondering in mantain the header row. Show the fields that the table has and if don't has data, show the fields and a custom component, for example:

![evidence](https://user-images.githubusercontent.com/34446944/64975149-b4ac8a80-d884-11e9-8e1c-6f19f4568cdb.png)

**Comment by gsrosa** [comment]
I'd want to know if this feature will be to implement in a future version?
