### ISSUE TITLE
PreSelected Rows after ajax request not working

### ISSUE THREAD

**Issue by Heydariiii128** [jbetancur/react-data-table-component#241]
i adding preSelected column to rows and set selectableRowsPreSelectedField="preSelected"  but in first time my rows is null because request is ajax call. when request is done and my rows is filled, pre selected not working.

i also test pre select option without ajax call and its work. i check source code and i understand rows must be filled in first time. but the most used for data table is ajax request.

1. selectableRowsPreSelectedField="preSelected"
2. clearSelectedRows={false}
3. selectableRows={true}
4. add preSelected field to all rows
5. call ajax request for fetch data
6. get data and set to rows
7. See rows not selected

## Expected behavior
after ajax request is done apply pre selected rows

Thank you for your efforts

**Comment by jbetancur** [comment]
How is your data being updated? State, redux? Where and when are you updating data? Your component code would be helpful or preferably a codesandbox

**Comment by jbetancur** [comment]
I think you are right in that when data is updated the table is not re-rendering to new pre-selected rows. The initial design intent for this was to be set only once.

I'll need to dig into this a bit more.

**Comment by jbetancur** [comment]
I should have a fix for this in the next day or so, but it seems that the preselected logic is not being handled in TableRow when the data changes

**Comment by jbetancur** [comment]
This is now fixed in 3.6.0!
