### ISSUE TITLE
i want to reset page of pagination to Default page after filter function

### ISSUE THREAD

**Issue by kishan143-jaiswal** [jbetancur/react-data-table-component#244]
how to  reset pagination to default page,didn't getting any docs to do so

 <DataTable
                            title="Arnold Movies"
                            columns={columns}
                            data={this.state.userList}
                            progressPending={this.state.isSpinner}
                            progressComponent={<Spinner style={{ width: '3rem', height: '3rem' }} />}
                            pagination={true}
                            expandableRows
                            fixedHeader={true}
                            fixedHeaderScrollHeight="50vh"
                            defaultExpandedField="defaultExpanded"
                            paginationPerPage={50}
                            customTheme={mySweetTheme}
                            onChangePage={this.updateData}
                            expandableDisabledField="disableStorageRowExpand"
                            expandableRowsComponent={<ExpandedSection activeTab={this.state.activeTab} />}
                          />

  filterUser = e => {
    let searchValue = e.target.value;
    if (this.state.typingTimeout) {
      clearTimeout(this.state.typingTimeout);
    }
    this.setState({
      searchValue,
      isSpinner: true,
      page: 1,
      typingTimeout: setTimeout(async function () {
        await this.props.unMountUserData()
        this.props.getUserData(this.state.activeTab, undefined, searchValue).then(() => {
          this.updateData(1)
          this.setState({ isSpinner: false })
        });
      }.bind(this), 500)
    });
  }

**Comment by jbetancur** [comment]
Try using paginationDefaultPage and updating it with state in your component .

**Comment by kishan143-jaiswal** [comment]
No its not working because this prop paginationDefaultPage is works only on Initial load of Table

**Comment by rtbishop** [comment]
+1
Running into a similar issue while implementing a search which updates the table data. I'm able to update the data, total rows, etc., just fine but the currentPage remains the same. Can there be a way to reset the currentPage back to 1? Thinking similar to how paginationTotalRows is.

**Comment by kishan143-jaiswal** [comment]
<DataTable
  title="Arnold Movies"
  columns={columns}
  data={userList}
  progressPending={this.state.isSpinner}
  progressComponent={<Spinner style={{ width: '3rem', height: '3rem' }} />}
  pagination={true}
  currentPage={this.state.page}
  fixedHeader={true}
  fixedHeaderScrollHeight="50vh"
  paginationPerPage={50}
  onChangePage={this.updateData}
  />
solved this issue by passing currentpage props dynamically ,please try this may it help you also @rtbishop

**Comment by kishan143-jaiswal** [comment]
i am using this library in other component ,i am managing two different arrays on Click of Tab,but again the issue is for reseting the pagination current page = 1 ,but can't able to do so

**Comment by allencazar** [comment]
I have the same issue:
- Pagination is not updating after new data is loaded.
- dynamic setting of "currentPage" is also not working for me.

**Comment by jbetancur** [comment]
You will now be able to reset pagination to the `paginationDefaultPage` setting using a toggle in version 3.7.0

This works exactly like the `clearSelectedRows` props in that it must be toggled by react state:

```js
// hooks
setResetPaginationToggle(!resetPaginationToggle);
// class
setState(resetPaginationToggle: !resetPaginationToggle);
```

```js
 <DataTable
     ....
     pagination
     paginationResetDefaultPage={resetPaginationToggle}
  />
```
or a different page, but just be careful the page will always exist!
```js
 <DataTable
     ....
     pagination
     paginationDefaultPage={2}
     paginationResetDefaultPage={resetPaginationToggle}
  />
```

**Comment by jorge-llanque** [comment]
I'm using this version `"antd": "^4.16.13"` and there are a property called **current** and I can used to manage this behavior. :-)
