### ISSUE TITLE
Search on column

### ISSUE THREAD

**Issue by stelco** [jbetancur/react-data-table-component#247]
## Describe the bug
Implementing search on a particular column.

## To Reproduce
https://codesandbox.io/embed/wizardly-cannon-w7z5b
Please uncomment lines 244,245 and 263 to see the error.

**Comment by jbetancur** [comment]
This code would never work because you are trying to use React hooks within a class component.

**Comment by stelco** [comment]
ah right ok thanks, I am fairly new to React and React Hooks is something I plan to learn more about. Is it possible to do this in a standard component?

**Comment by jbetancur** [comment]
Yep, you can certainly use a class component. Hooks just let you do things in a more declarative manner. There is nothing wrong with either approach.
