### ISSUE TITLE
Server side search and filtering

### ISSUE THREAD

**Issue by raitalharehman** [jbetancur/react-data-table-component#249]
please add Server side search and filtering

**Comment by jbetancur** [comment]
You can implement searching client or server, in (using the subHeaderComponent)  or outside of DataTable.

Here is an example of doing this client-side but you could easily just make this an API call.

http://localhost:6006/?path=/story/filtering--using-subheader

**Comment by jvcastro** [comment]
@jbetancur how to set the pagination to 1st page when you do the filtering https://jbetancur.github.io/react-data-table-component/?path=/story/filtering--using-subheader

**Comment by raitalharehman** [comment]
@jvcastro  server side or client side?

**Comment by jvcastro** [comment]
@raitalharehman client side

**Comment by raitalharehman** [comment]
@jvcastro so whats the issue?  just pass the filtered data to data in tables options

**Comment by jvcastro** [comment]
When i filter, the pagination doesnt update unless i go to 1st page

![image](https://user-images.githubusercontent.com/8552367/66150371-9e098000-e647-11e9-99a9-e30740ece622.png)

![image](https://user-images.githubusercontent.com/8552367/66150537-fc366300-e647-11e9-857a-112c1ba17c84.png)

**Comment by raitalharehman** [comment]
@jvcastro  try clear data array  and then add filtered data

**Comment by stelco** [comment]
Hi, I am using a Class based Component on my page and need to include searching. eg. class Sites extends React.Component {...} 
I noticed your example uses Hooks I think. https://jbetancur.github.io/react-data-table-component/?path=/story/filtering--using-subheader
Im not sure how to include this within my class...

const BasicTable = () => {
  const [filterText, setFilterText] = React.useState('');
  const filteredItems = data.filter(item => item.title.includes(filterText));
  const subHeaderComponentMemo = React.useMemo(() => <Filter onFilter={value => setFilterText(value)} />, []);

Any help appreciated thanks.
