### ISSUE TITLE
sort asc by default

### ISSUE THREAD

**Issue by stelco** [jbetancur/react-data-table-component#251]
## Describe the bug
Is it possible to sort a column asc by default. Eg. so that the latest date is at the top. See screenshot. Currently sorts desc by default as code below.

## Reproduce

`                                <DataTable className="responsive-table site-headers pagination-align-left"                                   
                                    columns={columns}
                                    data={this.state.sites}                                   
                                    defaultSortField="lastMaintenance"
                                    defaultSortAsc
                                    subHeader
                                    compact
                                    pagination
                                    highlightOnHover
                                    expandableRows
                                    expandableRowsComponent={<ExpandedSection />}
                                    progressPending={loading}
                                    progressComponent={<CustomLoader />}`

## Screenshots
![image](https://user-images.githubusercontent.com/900574/65413380-3ce0e180-dde9-11e9-8d31-08cc45999e81.png)

## Versions (please complete the following information)
 - React
 - Styled Components

**Comment by jbetancur** [comment]
Sorry, I don't follow entirely, but if you set `defaultSortAsc={false}` your dates will sort descending - in other words, the most recent date on top.

From your example, I can't tell what the timestamp format is so I've no idea how it would sort.

**Comment by jbetancur** [comment]
btw here is an example of sorting ISO 8601 dates

https://jbetancur.github.io/react-data-table-component/?path=/story/expandable--custom-cells

desc is the most recent date on top
