### ISSUE TITLE
Storybook addon incorrectly required as dependency

### ISSUE THREAD

**Issue by sumnerwarren** [jbetancur/react-data-table-component#252]
## Describe the bug
`@storybook/addon-docs` listed as a dependency instead of devDependency. This was added by e5944bb64b6b6726ba6d05993ea912b9cac7a3cb and seems like it shouldn't be a transitive dependency for consumers of this package (and also is possibly unused).

Can this be moved to `devDependencies` or removed? It adds a lot (~200) of unnecessary packages for consumers.

**Comment by jbetancur** [comment]
good catch! that lib isn't even being used.
