### ISSUE TITLE
Column width with maximum size, at the maximum content of the text

### ISSUE THREAD

**Issue by Angelk90** [jbetancur/react-data-table-component#253]
**Is your feature request related to a problem? Please describe.**
The width of the colon is divided equally from what I think, but sometimes the text is too little and therefore given too much space to the column or too little the text is greater.

**Describe the solution you'd like**
Try to adapt if you want the width of the text with the maximum size represented at that time.

**Comment by jbetancur** [comment]
This issue (to add documentation) might be helpful:
https://github.com/jbetancur/react-data-table-component/issues/234
