### ISSUE TITLE
Features: Download csv, Print, View Columns, Filter table

### ISSUE THREAD

**Issue by Angelk90** [jbetancur/react-data-table-component#254]
**Is your feature request related to a problem? Please describe.**

I found the following module for React, example: [Codesandbox](https://codesandbox.io/embed/xrvrzryjvp?autoresize=1&hidenavigation=1)
I thought it would be interesting that the fantastic module you created could implement the following features.
Which would be very useful if they were implemented, further enriching the project.

**Comment by jbetancur** [comment]
You can 100% implement CSV download, Print, and even Filter and filter specific columns using something like `subHeaderComponent` with your own custom components and some React state.

I do like the idea of column options that can be used as hooks or for some column related feature though but that is something that needs a bit more thought.

This "spirit" of this library is to keep things un-opinionated as possible and I feel if we add something like our own filter table or download buttons then others will have opinions on how it should or should not be and it leads to more code bloat. Rather, there are props in RDT that you can insert custom components that interact with your data as you see fit.

**Comment by jbetancur** [comment]
I want to keep it un opinionated as possible. The chips are pretty, but not to everyone.
Perhaps some story book examples on how you can create this sort of feature using subHeaderComponent 😉 PRs welcome!
