### ISSUE TITLE
Pagination Icons on RTL direction 

### ISSUE THREAD

**Issue by yousefh85** [jbetancur/react-data-table-component#264]
## Describe the bug
The Arrow icons should not be changed when we switch to RTL direction

## Screenshots

![image](https://user-images.githubusercontent.com/799045/66237415-af14c880-e6fd-11e9-8718-80dd2f8ec113.png)

## Versions (please complete the following information)
version: 3.5.1

**Comment by jbetancur** [comment]
I believe this is a simple fix of just adding `direction: ltr;` to the buttons container. I will try to get a fix in soon
