### ISSUE TITLE
Pagination not visible

### ISSUE THREAD

**Issue by stelco** [jbetancur/react-data-table-component#265]
## Describe the bug
The pagination has disappeared. It is there on the server side but not on the client side.  This seems to have happened when Ive been adding new records to our API.
I can see that it is there in Chrome Dev tools by inspecting the elements but its just not visible.
Here is my settings...

                              <DataTable className="responsive-table site-headers pagination-align-left"
                                    columns={columns}
                                    data={this.state.sites}
                                    defaultSortField="lastMaintenance"
                                    defaultSortAsc={false}
                                    subHeader
                                    //subHeaderComponent={<Filter onFilter={value => setFilterText(value)} />}
                                    compact
                                    pagination
                                    highlightOnHover
                                    expandableRows
                                    expandableRowsComponent={<ExpandedSection />}
                                    progressPending={loading}
                                    progressComponent={<CustomLoader />}
                                />

## Versions (please complete the following information)
 - React
 - Styled Components

**Comment by dumapetrisor13** [comment]
Hi, any news on this?

**Comment by loyboy** [comment]
Please I am having this issue too.

**Comment by messcall** [comment]
The problem gets better usually  after building
