### ISSUE TITLE
Is it possible to use more than one table per page?

### ISSUE THREAD

**Issue by Heydariiii128** [jbetancur/react-data-table-component#266]
i using two table in one page but it looks are not working correctly? please help me to using two table in one page.

thanks

**Comment by jbetancur** [comment]
Short answer is it's probably likely something with your code than with RDT.  Each table should be encapsulated.

Aside from that, I can't really help without some code or details or a code sandbox. Please make sure you are using the issue template when logging an issue so I and others can better help you 😉
