### ISSUE TITLE
ExpandTable function needed

### ISSUE THREAD

**Issue by cakerake** [jbetancur/react-data-table-component#267]
How would i expand table whena  button or a row is clicked?

I tried a few tricks but nothing worked

the expander is always an arrow on the left

**Comment by jbetancur** [comment]
I am working on this but to be honest I have been swamped. There is an existing issue for this

https://github.com/jbetancur/react-data-table-component/issues/248

**Comment by cakerake** [comment]
> I am working on this but to be honest I have been swamped. There is an existing issue for this
> 
> #248

Ah okay, thank you for taking the time to reply!!
