### ISSUE TITLE
Empty header div being generated

### ISSUE THREAD

**Issue by cakerake** [jbetancur/react-data-table-component#272]
hey i have this empty header section being generated by the datatable im not using any header titles and ive even tried setting header to false but it still keeps popping up and adding 48px in the above the actual table header

`<header class="sc-kAzzGY gXlqCi rdt_TableHeader"><div class="sc-chPdSV ksKbuS"></div><div class="sc-kgoBCf hFJClG"></div><div class="sc-cSHVUG jJknLL"><div class="sc-jzJRlG cChDHo"></div><div></div></div></header>`

can you please tell me how to remove this?

**Comment by jbetancur** [comment]
It's hard to help you without some code or a codesandbox. I can't really tell much from the html you pasted. 

If you are trying to remove the column titles use `noTableHead`
https://github.com/jbetancur/react-data-table-component#basic

If you need to remove the title headers and context make sure you are using the property `noHeader` which should remove the top table header:
https://github.com/jbetancur/react-data-table-component#header

Hope that helps
