### ISSUE TITLE
Row right click event & Context Menu

### ISSUE THREAD

**Issue by mahathir85** [jbetancur/react-data-table-component#280]
**Is your feature request related to a problem? Please describe.**
Everything seems good. But the only feature missing is right click event on rows. I believe if you can add this feature, it might be a helpful feature.

**Describe the solution you'd like**
I want to have a right click event on rows. This event can be use to show context menu instead of adding buttons, links etc to the cell itself. 

**Describe alternatives you've considered**
Currently i just able to add this context menu trigger component into the cell. But the problem is, the event only can be active within the string of the cell. So i was thinking the right click event can be same as onRowClick that offer in this package.

**Additional context**
It will be a bonus if you can add context menu together with the right click event.

**Comment by jbetancur** [comment]
`onRowClicked` also passes back the event `onRowClicked(row, event)`. I believe you can detect a right click using `event.type === 'contextmenu'` then just handle calling some menu or action in your component

```js
handleRowClick = (row, event) => {
 if (`event.type === 'contextmenu') {
   console.log('right clicked!')
 }
}
return (
   <DataTable 
   ...
    onRowClicked={handleRowClick}

/>
)

**Comment by tonthon** [comment]
> `onRowClicked` also passes back the event `onRowClicked(row, event)`. I believe you can detect a right click using `event.type === 'contextmenu'` then just handle calling some menu or action in your component
> 
> ```js
> handleRowClick = (row, event) => {
>  if (`event.type === 'contextmenu') {
>    console.log('right clicked!')
>  }
> }
> return (
>    <DataTable 
>    ...
>     onRowClicked={handleRowClick}
> 
> />
> )
> ```
That solution doesn't work.
onRowClicked used the onclick event that (on most browsers) will not be fired in case of Right click.

A solution could be to attach the onRowClicked with onContexMenu
Here for example
https://github.com/jbetancur/react-data-table-component/blob/master/src/DataTable/TableRow.js#L104

```javascript
onClick={handleRowClick}
onContextMenu={handleRowClick}
```

**Comment by madmunky** [comment]
Is there any solution to this yet?

I could add a listener for the contextmenu click but not sure how to get the datatable row/data that was underneath/target

  componentDidMount = () => {
    document.addEventListener('contextmenu', this.handleChange);
  }

**Comment by hajnalbendeguz** [comment]
I'm also missing this feature. My targeted browsers don't invoke onClick when using the right mouse buttion either. @tonthon 's solution seems like a good workaround.
