### ISSUE TITLE
What should be the keyField value

### ISSUE THREAD

**Issue by edoteee** [jbetancur/react-data-table-component#282]
It's mentioned in the docs that `keyField` should be a unique value. If my array has an object as follows 
```
{
PolicyCategoryID
CategoryName
}
```

here PolicyCategoryID is the unique property. 

So is the following syntax correct ?

```
<DataTable
              keyField="PolicyCategoryID"
            />
```

**Comment by jbetancur** [comment]
It should be the property name of a field in your data that is unique for each record

**Comment by edoteee** [comment]
Thanks @jbetancur

**Comment by indefinitelee** [comment]
can keyField be a concatenation of two fields or must it be a single field?
