### ISSUE TITLE
In responsive hiding columns, is the below possible?

### ISSUE THREAD

**Issue by mjacobm** [jbetancur/react-data-table-component#284]
I was looking for a feature wherein responsive hiding columns.
The hidden/all columns are displayed as a popup when a button + is clicked on smaller screens.
 I am attaching the screenshots for reference.
![2](https://user-images.githubusercontent.com/56995472/67588501-e7934980-f773-11e9-9f3c-d4fe76ca5af4.JPG)
![1](https://user-images.githubusercontent.com/56995472/67588502-e82be000-f773-11e9-9c96-862233e2ac93.JPG)
I could not find anything like this. I feel would be great if you could include this.

**Comment by jbetancur** [comment]
You could implement a custom cell component button that displays a modal in column.cell.  You'll have access to the `row` data.

https://github.com/jbetancur/react-data-table-component#columns

My only hesitation implementing this natively is that everyone will have a different opinion on how it should be implemented versus just giving the developer the choice. Add to that the complexities of dealing with modal cross-platform.

It would make for a good storybook/documentation example though
