### ISSUE TITLE
sorting options should be asc desc and none

### ISSUE THREAD

**Issue by raitalharehman** [jbetancur/react-data-table-component#285]
in sorting there is only two option asc and desc after selecting column there should be option to deselect column

**Comment by jbetancur** [comment]
Are there examples of other libraries that implement this? Seems like this could be a possible feature.

**Comment by raitalharehman** [comment]
not remember the library

**Comment by asnaseer-resilient** [comment]
Tri-state sort would be a great feature to add. The Tabulator library (http://tabulator.info/) has this feature
