### ISSUE TITLE
Export the table as CSV file

### ISSUE THREAD

**Issue by Muhzn** [jbetancur/react-data-table-component#286]
Is it possible to add a feature to export the table as a CSV or Excel file?

**Comment by jbetancur** [comment]
I've gotten a lot of questions and PR's on this feature, but I think that adding this sort of thing natively makes RDT a more heavy and opinionated than its original intention.  At the very least though, I could add a storybook showing how you can use `subHeaderComponent` or `actions` props to extend RDT to easily add this sort of functionality.

**Comment by Muhzn** [comment]
That will be great

**Comment by jbetancur** [comment]
Here you go!

https://jbetancur.github.io/react-data-table-component/?path=/story/export-csv--using-act

**Comment by more03625** [comment]
Export with remote data is not working https://jbetancur.github.io/react-data-table-component/?path=/story/examples-export-csv--export-csv


TypeError: Cannot convert undefined or null to object

const keys = Object.keys(data[0]); // got error here but I have my all table data present in data Variable

**Comment by somendrasomu** [comment]
yes, I have the same problem
