### ISSUE TITLE
hight number of rows best practices 

### ISSUE THREAD

**Issue by aufgussmeister** [jbetancur/react-data-table-component#294]
Hi, 
I would like to improve my table that has +1k rows, what is the best way to update record directly on the table, update a row an typical crud actions?

For smaller table I render the entire data every time, but isn't so performant for a lot of rows. 
maybe it could be better to work with an initial redux state and manage the difference between states. there is a way to re-render only the row had chanced?

What are your suggestion for large amount of rows?

I would like to give a no-rerender experience

Thanks in advance

**Comment by jbetancur** [comment]
There is really no such thing as a no-re-render experience. Although, while React handles render optimizations for you under the hood, RDT also takes advantage of memoization hooks thereby preventing certain expensive components within RDT to render fully UNLESS a prop being passed to RDT changes.

This means that whatever props you are passing to DataTable should not be re-created when your parent component re-renders (ie state changes).  If this is the case then RDT should not perform a full re-render on the entire table when you change the state (ie CRUD action of adding or deleting a row). Examples of props changing are inline functions, objects or arrays or that are defined within the render method.

I attempt to explain *that whatever props you are passing to DataTable should not be re-created* here:
https://github.com/jbetancur/react-data-table-component#optimizing-for-performance-and-caveats
and here:
https://johnbetancur.com/optimizing-react-components/

Btw, 1k rows is a lot to display on a browser and that will certainly cause performance issues regardless of what is re-rendering or not. You may want to look into the `pagination` feature on this table library and limit the rows you present on the screen. This will help you more than worrying about re-rendering.
