### ISSUE TITLE
Methods in columns data

### ISSUE THREAD

**Issue by impactcolor** [jbetancur/react-data-table-component#295]
In the examples and on my code I have a Datatable inside a classs like so:
`class MembersAttendance extends React.Component {
.... code in here
                <DataTable
                columns={columns}
                data={this.state.data}
                customTheme={rowTheme}
                noHeader
                />
}`

Then OUTSIDE of the class i have the column data like so:
```
const columns = [
  {
    name: 'ATTENDANCE',
    sortable: true,
    cell: row => <div style={{ fontWeight: 'bold' }}>
        <button
          className="btn-icon-clipboard"
          data-clipboard-text="check-bold"
          id="tooltip204269497"
          type="button"
          onClick={() => this.logMemberAttendance(row.uid)}
        >
          <div>
            <i className="ni ni-check-bold" />
            <span>PRESENT</span>
          </div>
        </button>
    </div>
  }]
```
Notice the use of () => this.logMemberAttendance(row.uid)
This causes problems because it won't read it in the class.  The question is how could I use a method inside of columns like the onClick above?  I can create the method outside the class and it works but then I won't have access to the state of the class.  Are there any examples on how I can do this?

**Comment by jbetancur** [comment]
Checkout
https://github.com/jbetancur/react-data-table-component#optimizing-for-performance-and-caveats

The short answer is there are a couple ways to do this with class components.; 

You could just define columns on `this`, meaning you can define them in a class constructor.

Also (my prefered method) is that you could make columns a method outside of the class and pass in yourlogMemberAttendance handler and/or any state you need. 

In both cases, you should then memoize your function it so it is not re-executed every time your table renders (this prevents unnecessary re-renders)

```js
import React, { Component } from 'react';
import DataTable, { memoize } from 'react-data-table';

const columns = memoize(handleAction => [
  ...
  {
    cell: () => <Button raised primary onClick={handleAction}>Action</Button>,
    ignoreRowClick: true,
    allowOverflow: true,
    button: true,
  },
  ...
]);

class MyComponent extends Component {
  updateState = state => {
    this.setState({ selectedRows: state.selectedRows });
  }

  render () {
    return (
      <DataTable
        data={data}
        columns={columns(this.updateState)}
        onRowSelected={this.updateState}
        selectableRows
      />
    );
  }
}
```

Another way is adopting React Hooks and the useMemo or useCallback hooks. This way you can define the columns within your render but React can memoize them for you

**Comment by impactcolor** [comment]
That's perfect, I missed that part in the docs.  Actually I didn't miss it, I just didn't understand it.  Thank you!!!
