### ISSUE TITLE
Alternating row background color

### ISSUE THREAD

**Issue by robwma** [jbetancur/react-data-table-component#297]
I am not sure if this already exists but I could not figure it out.  I am looking for a way to simply define an alternating background color for each row in the table.  

I am guessing it is using   stripedColor but this doesn't seem to make any difference.

`const contentTheme = {
    rows: {
        stripedColor: 'rgba(0,100,255,.12)',
    }

  }

...
                   <DataTable customTheme={contentTheme} ...

`

**Comment by jbetancur** [comment]
You need to add the `striped` property to enabled alternating rows
https://github.com/jbetancur/react-data-table-component#basic

Your theme code looks good if you want to change the default color.

**Comment by robwma** [comment]
D'oh!  Thanks! it worked.
