### ISSUE TITLE
Custom background to a specif row

### ISSUE THREAD

**Issue by vinniimiranda** [jbetancur/react-data-table-component#300]
![Screenshot_1](https://user-images.githubusercontent.com/33462844/68148930-b527e000-ff1b-11e9-9b32-aee63fee3781.png)

Hi, i am trying to use a custom css in a specif row when this row is the current that i am using, i have attach an example, atm i can just colorize the text and the 'td' element, but i want to colorize the whole 'tr'.

Thanks anyaway.

**Comment by jbetancur** [comment]
see https://github.com/jbetancur/react-data-table-component/issues/293

you currently cannot do this, but I am working on adding a way for you to use style objects to format a row

**Comment by vinniimiranda** [comment]
Thanks for the quick reply, i'll be waiting then

**Comment by jbetancur** [comment]
NP. Closing as a dupe - check https://github.com/jbetancur/react-data-table-component/issues/293 for updates on this feature.

**Comment by jbetancur** [comment]
Now available in 3.8.0
