### ISSUE TITLE
state change not updating table.

### ISSUE THREAD

**Issue by BaiMaoLi** [jbetancur/react-data-table-component#302]
I am removing one rows from array element of state by button clicking, 
this is updating state, but datatable not updating.
below code is the cell to remove row

 {
                name: 'Action',
                button: true,
                width:'150px',
                cell: row => <div style={{alignItems:'center', justifyContent:'center', textAlign:'center'}}>
                                <a href={`/categories/edit/${row._id}`} target="_blank"><i style={{fontSize:20}} 
                                     className="fa fa-edit"></i></a>
                                <a href="javascript:void(0)" style={{margin:'0 auto'}} onClick={()=> 
                                      {this.removeSection(row._id)}}>
                                    <i style={{fontSize:20, color:'#ff0000', marginLeft:10}} className="fa fa- 
                                        trash"></i>
                                </a>
                                <a href={`/categories/edit/${row._id}`} target="_blank" className="nav- 
                                   link">View Sub Sections</a>
                            </div>
  },

this is handler function.
removeSection = id =>{
        let male_sections=this.state.sections.male_sections;
        let female_sections=this.state.sections.female_sections;
        let exist=false;
        for(let i=0;i<male_sections.length;i++){
            if(male_sections[i]._id==id){
                male_sections.splice(i,1);
                exist=true;
                break;
            }
        }
        if(!exist){
            for(let i=0;i<female_sections.length;i++){
                if(female_sections[i]._id==id){
                    female_sections.splice(i,1);
                    break;
                }
            }
        }
        this.setState({sections:{male_sections:male_sections, female_sections:female_sections}});
    }

now I am showing male sections and female sections in datatable
    let male_sections=this.state.sections.male_sections;
    let female_sections=this.state.sections.female_sections;

**Comment by jbetancur** [comment]
Hard to tell without the complete component code. I would paste that or preferably use a the code sandbox link when you open an issue.

**Comment by jbetancur** [comment]
You can also take a look at this example:
https://jbetancur.github.io/react-data-table-component/?path=/story/selectable-rows--selected-row-toggle
