### ISSUE TITLE
Hide Rows Per Page

### ISSUE THREAD

**Issue by RocMark** [jbetancur/react-data-table-component#303]
Is there Any option to set for Hiding Rows Per Page Text & DropDown?
I didn't find this option in Pagination Section.

thx for making this awesome plugin.
sorry for my bad english.
feel free to close this. if there is a option to set i missed

**Comment by jbetancur** [comment]
There is currently no option, however, you can use `paginationComponent` to pass your own pagination component for the time being.

The default pagination component is a good start:
https://github.com/jbetancur/react-data-table-component/blob/master/src/DataTable/Pagination.js

I think this could be a feature though, at least that you can pass through `paginationComponentOptions`

**Comment by jbetancur** [comment]
I will be merging this shortly. expect it in a 3.8.0 version coming soon!
e.g.

`paginationComponentOptions={{ noRowsPerPage: true }}`

**Comment by jbetancur** [comment]
Now available in 3.8.0

**Comment by rohit-limepay** [comment]
this option still appears in mobile view but works in desktop.

**Comment by kbultman** [comment]
can we also add a rowsPerPage prop if the control is removable? always defaulting to 10 is difficult, and also does not work if `paginationRowsPerPageOptions` does not include 10.

**Comment by joao-miguel-inacio** [comment]
> even after setting:
> 
> paginationComponentOptions={{ noRowsPerPage: true }}
> 
> this option still appears in mobile view but works in desktop.

issue persists
