### ISSUE TITLE
[Feature] - Conditional cell styling via columns

### ISSUE THREAD

**Issue by jbetancur** [jbetancur/react-data-table-component#310]
This will be a new feature for allowing conditional css styling on cells using the `columns` defininitions

**Comment by sarahrara18** [comment]
@jbetancur i am using this feature right now, i tried to resize the column it worked but the head cell has not been resized , do i need to add something so that it wloud be the same size as the other cells?
here is my code
```
  export const iconCell=[
    {
      when: row => row.user!=null,
        style: {
          width:"22px !important",
          maxWidth:" 22px !important",
          minWidth:" 22px !important",
        }
    }, 
  ]
```

**Comment by jbetancur** [comment]
Don't use style for width. Columns already have width, minWidth, and maxWidth props which work on the entire column
