### ISSUE TITLE
progress-indicator style google under the column menu

### ISSUE THREAD

**Issue by Angelk90** [jbetancur/react-data-table-component#313]
**Is your feature request related to a problem? Please describe.**
At the moment the type of progress-indicator takes all the space of the table, so until you have a response with the data this progress indicator remains.

**Describe the solution you'd like**
What would be interesting as a solution is like that of the image below, the main columns that indicated the type of content element is displayed, it is under a google loading style that does its job, when the data arrives the progress bar disappears and are displayed paginated.

**Additional context**
Link: [url](https://cat-fact.herokuapp.com/#/cat/facts)

@jbetancur : 
![Screenshot_20191114_121431](https://user-images.githubusercontent.com/20476002/68852975-3f6d0280-06d9-11ea-8161-7770d2ab0464.png)

**Comment by jbetancur** [comment]
I've gotten a few requests. Seems we need both options. I'll see about enhancing this feature.

**Comment by jbetancur** [comment]
This is now available in 3.10.0! and can be enabled via the  `progressShowTableHead` prop
https://jbetancur.github.io/react-data-table-component/?path=/story/progress-indicator--show-table-head

**Comment by jbetancur** [comment]
Just a heads up - I am going to be releasing 4.0 later today and will be renamed `progressShowTableHead` to `persistTableHead` This will be called out in the release notes

**Comment by Angelk90** [comment]
@jbetancur : Ok, thank you.
There are news about the issue #318 ?
