### ISSUE TITLE
custom checkbox selected all not working

### ISSUE THREAD

**Issue by impactcolor** [jbetancur/react-data-table-component#314]
The link: See Advanced Selectable Component Options doesn't work on both npm and GitHub pages.

I setup a custom component for the checkbox like so using material ui.
```
                <DataTable
                columns={columns(this.logMemberAttendance)}
                data={this.state.data}
                selectableRows
                selectableRowsComponent={switchCheckbox}
                noHeader
                />
```

my switchCheckbox component looks like this:
```
const switchCheckbox = () => {
  return(
    <FormControlLabel
      control={
        <CustomSwitch
          value="checkedB"
        />
      }
      label="present"
    />
  )
}
```
It works individually but when I click on the top one which would be the "select all" it does not check all.  It only works on that individual element.  

On the regular checkbox it works.  Any idea what I'm missing?

**Comment by jbetancur** [comment]
You need to pass the onClick handler and any props needed by the the underlying input element of CustomSwitch 

Here is an example of how to do that. Take a look at the bootstrap4 example as that shows how you can integrate a custom checkbox

https://github.com/jbetancur/react-data-table-component#ui-library-integration

**Comment by jbetancur** [comment]
I’ll fix that link it should go to https://github.com/jbetancur/react-data-table-component#using-custom-checkboxes-and-indeterminate-state

**Comment by jbetancur** [comment]
README link fixed

**Comment by impactcolor** [comment]
You're awesome!  THANK YOU!
