### ISSUE TITLE
expandable should have option like Accordion  open one row only

### ISSUE THREAD

**Issue by raitalharehman** [jbetancur/react-data-table-component#317]
expandable row need an option to open only one row at a time like Accordion .

**Comment by jbetancur** [comment]
See my comments on #318 - It's likely we will want to keep the expandable rows simple on the animations. This feature alone could probably be its own library.

**Comment by LuisGnzlz1** [comment]
How to implement the accordion function to the datatable component, I need close all row expand is set true when open a new row?

**Comment by jbetancur** [comment]
See #398 - This will be implemented in 6.2

**Comment by yusrilfirza** [comment]
sorry, is this case is already fixed? cause I still can't found the solution in 7.4
