### ISSUE TITLE
how to add column resize or reordering?

### ISSUE THREAD

**Issue by niteshghumatkar** [jbetancur/react-data-table-component#319]
i'm looking for column resizing for reordering, may i know how to do it

**Comment by jbetancur** [comment]
This is not currently possible, but I’ve been thinking about implementing column resizing and possibly reorder. Also open to ideas/prs

**Comment by parisambush** [comment]
I'm looking for a column resize feature for this as well. Was trying to use column-resizer (https://www.npmjs.com/package/column-resizer), but couldn't get the ES6 implementation to work as DataTable components are function components. Maybe something like this could be leveraged for use in DataTable component directly?

**Comment by jbetancur** [comment]
#356 will attempt to add a re-order feature in 6.0.0

**Comment by rifatdegirmenci** [comment]
Hi John,
Can you information about column resizing feature ? Bc, " react-dta-table " is really good. but, we need to "column resizing feature" for our Corporate application. This feature is very important and primary for projects. Can you help us ? :)

**Comment by shsohel** [comment]
I need resizable column feature . It's important for our business.

**Comment by jbk75** [comment]
Would be great to have this feature
