### ISSUE TITLE
React Data Table Component should be accessible

### ISSUE THREAD

**Issue by jbetancur** [jbetancur/react-data-table-component#325]

**Comment by AtomicNoggin** [comment]
https://github.com/jbetancur/react-data-table-component/pull/343
Added aria attributes to help with a11y.

**Comment by jbetancur** [comment]
I never hear back on the original PR but I did add some accessibility to RDT as part of some other work. I think there is still work to be done though as far ass accessibility goes. I will close this for now and can revisit enhancing accessibility in a future PR.
