### ISSUE TITLE
Examples of storybook demos with possible codesandbox links

### ISSUE THREAD

**Issue by Angelk90** [jbetancur/react-data-table-component#330]
**Is your feature request related to a problem? Please describe.**

Thanks to storybook you can see an example of how to use the component, but I often want to try it on codesandbox.
Storybook has the story menu where you can see the code that was used.
But there are parts of imported components that you don't find and therefore either you go looking for them or you invent them.

Ex:
```
import data from '../constants/sampleMovieData';
import DataTable from '../../../src/index';
```

**Describe the solution you'd like**
My suggestion would be the possibility of integrating an "edit to codesandbox" button, so if the user wants can directly try the code, even with different data or settings different from those initially set by the type of element selected by the storybook, but starting from the base that user wanted to try.

Example: [Link](https://material-ui.com/components/skeleton/#youtube-example)
For each code, there is a section to try it on codesandbox.

**Comment by impactcolor** [comment]
This isn't really related to react-data-table-component.  This would be a feature you could request from storybook js.

**Comment by jbetancur** [comment]
@impactcolor is correct. This seems like it would be a MUCH needed plugin for storybook

**Comment by jbetancur** [comment]
Closing this as it needs to be a storybook enhancement. I may look at having more condesandbox examples though in the future
