### ISSUE TITLE
Does not recalculate the pagination position when the last item is deleted when paginationOnServer

### ISSUE THREAD

**Issue by sarathdr** [jbetancur/react-data-table-component#331]
## Describe the bug
When the server-side pagination is active it does not calculate the pagination position when last item is deleted. The current page number is not decreasing. 

## To Reproduce
1. Go to [(code sandbox link)](https://codesandbox.io/s/beautiful-pasteur-16n73?fontsize=14&hidenavigation=1&theme=dark)
2. Go to second page
3. Click delete button
4. Check range below it shows 11 - 20 of 10, it should be 1-10 of 10

## Code Sandbox
[(code sandbox link)](https://codesandbox.io/s/beautiful-pasteur-16n73?fontsize=14&hidenavigation=1&theme=dark)

## Versions (please complete the following information)
 - React: 16.8.4
 - Styled Components: 4.4.1
 - Version: 4.0.0

## It seems the position should be recalculated when the total changes

```
  if(paginationServer) {
    React.useEffect(function () {
      if(paginationTotalRows > 0 && paginationServer) {
        var updatedPage = getNumberOfPages(paginationTotalRows, rowsPerPage);
        var recalculatedPage = recalculatePage(currentPage, updatedPage);
        handleChangePage(recalculatedPage);
      }
    }, [paginationTotalRows]);
  }
```

**Comment by jbetancur** [comment]
Fixed by #337
