### ISSUE TITLE
Types are not included in npm package?

### ISSUE THREAD

**Issue by omasback** [jbetancur/react-data-table-component#338]
I'm still getting a typescript error `Could not find a declaration file for module 'react-data-table-component'.` I'm not seeing a typedefs file in the downloaded npm package. Maybe need to tweak the build to include it?

**Comment by janhartmann** [comment]
Yes, I think they need to be bundled inside the `dist` folder. 

Could be it is just a matter of changing the `package.json` to include it like `dist/index.d.ts` and moving the `index.d.ts` inside the `src` folder. 

Or having a build script to move the `index.d.ts` inside `dist` after build.

**Comment by janhartmann** [comment]
Wait, I think it is easier just include the `index.d.ts` in the `files` section in the package.json.

**Comment by jbetancur** [comment]
Actually, I think you could do that. If that works let’s revert this change

**Comment by janhartmann** [comment]
I tested it and it did not work. Had to copy the file.

**Comment by jbetancur** [comment]
Release 4.0.1 is now available
