### ISSUE TITLE
onSelectedRowsChange doesn't fire

### ISSUE THREAD

**Issue by impactcolor** [jbetancur/react-data-table-component#340]
According to the documentation.
`Callback that fires anytime the rows selected state changes. Returns ({ allSelected, selectedCount, selectedRows }).`

Following the Material UI example I have this in my code.

```
class MembersAttendance extends React.Component {
  static contextType = AuthDetailsContext;
  constructor(props) {
    super(props)

    this.state = {
      loading: false,
      currentOrganization: null,
      data: [],
      startDate: new Date(),
     };
  }

  updateState = state => {
    console.log(state);
    console.log('this in state');
      this.setState({ selectedRows: state.selectedRows });
    }

// render stuff and then the DataTable
                <DataTable
                columns={columns}
                data={this.state.data}
                selectableRows
                selectableRowsComponent={Checkbox}
                selectableRowsComponentProps={{ indeterminate: isIndeterminate }}
                onSelectedRowsChange={this.updateState}

                />

}
```

My expected behavior would be that when a row is selected that the function would fire.  I need to do some additions to my db when row is selected so I expected to be able to fire off that onSelectedRowsChange method.  Am I missing something here?  Maybe I'm not understand the way this should work.

**Comment by timberlakegregg** [comment]
I’m experiencing the same issue, with redux, have you made any progress here? I’m able to get onRowClicked to fire, but can’t capture data about selected rows

**Comment by impactcolor** [comment]
Not yet still struggling with it.  I'll let you know if I figure it out . @timberlakegregg

**Comment by timberlakegregg** [comment]
Ok, I’ll be working on this next few days. If I come up with anything I’ll post here too. Good luck!

**Comment by jbetancur** [comment]
`onSelectedRowsChange` will fire when the checkbox is selected/deselected or if internally RDT decides to change the selectedRows state (pagination, sorting, etc..) The purpose of `onSelectedRowsChange` is to keep your component state synced to RDT selected row state. There are a few storybook examples that showcase this.

From the looks of your code, though, I don't see why it would not fire.  One thing to note is you should set your selectedRows in state to [] though I doubt that has anything do with your issue.

**Comment by jbetancur** [comment]
Here is a sandbox where you can see it is firing every time.:
https://codesandbox.io/s/react-data-table-sandbox-39weq

It might be easier to troubleshoot if I can see the full code or even better if you could dupe this in a codesandbox

**Comment by timberlakegregg** [comment]
Are there any examples with Redux? The UI is working, but I can't seem to get data regarding selected rows to be able to update application state. I figure the right approach is... keep selectedRows in application state defaulting to [], trigger updates to selectedRows with a dispatch initiated from onSelectedRowsChange. Until now I haven't even been able to log the row ids of selected rows to see how a dispatch like that would work. onRowClicked seems to work fine and I can capture the ID of the clicked row. I may be missing something trivial...

**Comment by jbetancur** [comment]
Currently, there are no redux examples but it would not be hard to set one up in codesandbox or storybooks once I get some time to do so.

If you are using Redux you don't want to manage with the internal state using this.setState, Rather, you want to dispatch an action with your selectedRows to Redux state and then have your component read it from redux state props.

**Comment by jbetancur** [comment]
@timberlakegregg Sorry, I misunderstood your issue with the original ques. 
`onSelectedRowsChange` returns all the rows that are selected at any one time. What exactly are you trying to do with the row when a record is selected?

The following storybook has a good example of to handle something like row deletion and selectableRows

https://jbetancur.github.io/react-data-table-component/?path=/story/material-ui--override-default-components

and 

https://jbetancur.github.io/react-data-table-component/?path=/story/selectable-rows--selected-row-toggle

In both examples am just using differenceBy, but in a RL scenario you would have a for loop go through each row and perform whatever action.

**Comment by jbetancur** [comment]
Actually, contrary to what I mentioned previously, I would not even bother with redux for your selectedRows state, just use your local component state to track your selectedRows and then loop  the dispatch actions as needed.

**Comment by timberlakegregg** [comment]
I may just handle the selectedRows state within the component, although I'm far enough along it might be cool to get it working with redux. I'm fairly new to redux so i may just be making a stupid mistake somewhere.

I have 'setSelectedRows' and 'selectedRows' as props in my DataTable Component. setSelectedRows dispatches an action with  'SET_SELECTED_ROW_SUCCESS' and passes selectedRows as an argument. I am attempting to use the selectedRows reducer to accept that action and update the state with a list containing the ids of selected rows (this may be incorrect - I'm still debugging here, I imagine theres a more concise way to write this reducer). In my root reducer I'm including selectedRows reducer, and exporting a function 'getSelectedRows' which takes state as an argument and returns the ids of selected rows. This 'getSelectedRows' function is what gets called in the DataTable component to define selectedRows as a prop.

DataTable Component:
`class TodosTable extends Component {

  componentDidMount() {
    this.fetchData();
  }

  componentDidUpdate(prevProps) {
    if (this.props.filter !== prevProps.filter) {
      this.fetchData();
    }
  }

  fetchData() {
    const { filter, fetchTodos } = this.props;
    fetchTodos(filter);
  }

  render() {

    const { isFetching, errorMessage, todos, toggleTodo, toggleShowModal, toggleShowFilter, showFilter, setSelectedRows, selectedRows } = this.props;
    const actionButtons = []
    const ADD_TODO_BUTTON = <Button key='addTodo' variant="primary" onClick={ toggleShowModal }> + Create New Todo </Button>
    const FILTER_BUTTON = <FilterButton key='filter' toggleFilter= { toggleShowFilter } show={ showFilter } filters={ filters } />

    function handleRowsSelected() {
      setSelectedRows(selectedRows)
    };

    actionButtons.push(FILTER_BUTTON, ADD_TODO_BUTTON)

    if (errorMessage && !todos.length) {
      return (
        <FetchError
          message={errorMessage}
          onRetry={() => this.fetchData()}
        />
      );
    }
      return (
        <DataTable
          title="Todos"
          columns={TodosTableColumns}
          data={todos}
          actions={ actionButtons }
          conditionalRowStyles={TableRowStyle}
          progressPending= {isFetching && !todos.length}
          progressComponent= {<Loader/>}
          onSelectedRowsChange={this.handleRowsSelected}
          selectableRows
          pagination
        />
    );
  }
}


TodosTable.propTypes = {
  filter: PropTypes.oneOf(['all', 'active', 'completed']).isRequired,
  errorMessage: PropTypes.string,
  todos: PropTypes.array.isRequired,
  isFetching: PropTypes.bool.isRequired,
  fetchTodos: PropTypes.func.isRequired,
  toggleTodo: PropTypes.func.isRequired,
  toggleShowModal: PropTypes.func.isRequired,
  toggleShowFilter: PropTypes.func.isRequired,
  showFilter: PropTypes.bool.isRequired
};

const mapStateToProps = (state, { params }) => {
  const filter = params.filter || 'all';
  return {
    isFetching: isFetchingTodos(state, filter),
    errorMessage: getError(state, filter),
    todos: getVisibleTodos(state, filter),
    showFilter: isShowingFilter(state),
    selectedRows: getSelectedRows(state),
    filter,
  };
};

TodosTable = withRouter(connect(
  mapStateToProps,
  actions
)(TodosTable));

export default TodosTable;`

Dispatched action:
`
export const setSelectedRows = (selectedRows) => (dispatch) => {
  dispatch({
      type: 'SET_SELECTED_ROW_SUCCESS',
      selectedRows
    });
}`

Selected Row Reducer:
`import { combineReducers } from 'redux';

const selectedRows = () => {
 
  const ids = (state = [], action) => {
    switch (action.type) {
      case 'SET_SELECTED_ROW_SUCCESS':
        return action.selectedRows
      default:
        return state;
    }
  };

  return combineReducers({
    ids
 });
};

export default selectedRows;

export const getIds = (state) => state.ids;`

Root Reducer:
`import { combineReducers } from 'redux';
import byId, * as fromById from './byId';
import createList, * as fromCreateList from './createList';
import interactions, * as fromInteractions from './interactions';
import selectedRows, * as fromSelectedRows from './selectedRows';


const filterList = combineReducers({
  all: createList('all'),
  active: createList('active'),
  completed: createList('completed'),
});

const todos = combineReducers({
  byId,
  selectedRows: selectedRows(),
  filterList,
  interactions: interactions(),
});

export default todos;

export const getSelectedRows = (state) => {
  const ids = fromSelectedRows.getIds(state.todos.selectedRows);
  return ids.map(id => fromById.getTodo(state.todos.byId, id));
}`

**Comment by impactcolor** [comment]
Ok for me the problem was   `"react-data-table-component": "^3.10.3",` once I updated it to  `"react-data-table-component": "4.0.1"`, as the example shows, I now get the `onSelectedRowsChange={({ selectedRows }) => console.log(selectedRows)}` firing.

**Comment by jbetancur** [comment]
oh wow - yes that will do it. The prop was renamed in 4.0.0.

**Comment by keshavsharma07** [comment]
it does not work when we have  selectableRowsComponent
