### ISSUE TITLE
Draggable reorderable Columns

### ISSUE THREAD

**Issue by jbetancur** [jbetancur/react-data-table-component#356]
Column re-ordering using the draggable event handlers.

**Comment by jbetancur** [comment]
This will initially involve exposing the event handlers for drag to do so and perhaps some base animation and a storybook

**Comment by israel-gir** [comment]
Has this function already been added? or is it in process?

**Comment by arfath77** [comment]
Any planned date for this feature to go live?

**Comment by arochedy** [comment]
good idea : is it useable ?

**Comment by ramyakrishnai** [comment]
how can I use that feature, any example..?

**Comment by jbetancur** [comment]
This feature is still definitely planned but, unfortunately, is not going "live" anytime soon due to a busy schedule.

**Comment by jbetancur** [comment]
Not promising anything! But I am going to try to get this into version 7-rc2

**Comment by KS2632** [comment]
is that column resize option in progress ? when it release?

**Comment by jbetancur** [comment]
No exact ETA sorry, but soon. The good news is that I've made quite some progress on this and still need to iron out some bugs and edge cases before cutting the next release.
