### ISSUE TITLE
[6.0.0] - Grid lines

### ISSUE THREAD

**Issue by jbetancur** [jbetancur/react-data-table-component#357]
Depends on #355 
Grid lines - either through theming or via a helper prop

**Comment by blacksmoke26** [comment]
Yeah, That will be cool. I am really impressed by this library. :)

**Comment by jbetancur** [comment]
Instead of a prop, this will actually be implemented via the new `customStyles` prop with accompanying storybook examples

**Comment by blacksmoke26** [comment]
Yes, that's the better approach! Since it's related to the styles, adding it to `customStyles` is the best decision.

**Comment by jbetancur** [comment]
Implemented in release/v6 branch
