### ISSUE TITLE
Rows have a small area where expandOnRowClicked does not have an effect

### ISSUE THREAD

**Issue by erikt9** [jbetancur/react-data-table-component#361]
## Describe the bug
Rows have an area around the expand icon where they do not expand when expandOnRowClicked is true.  

## To Reproduce

Go to https://jbetancur.github.io/react-data-table-component/?path=/story/expandable--expandable-on-row-click

Click around in the area between the expand icon `>` and the title.  There is an area where clicks do not toggle row expansion.  

## Expected behavior
Clicking anywhere in the row should trigger expansion

## Code Sandbox
Part of this project's storybook

## Versions (please complete the following information)
Most recent Safari, Chrome, and Firefox on Mac OS 10.14.

**Comment by jbetancur** [comment]
Thanks - I'll get this fixed as a bug in the 6.0.0 release

**Comment by jbetancur** [comment]
This is resolved as part of the cleanup in #355 and will be in the 6.0 release
