### ISSUE TITLE
Ability to customize cell component at table level

### ISSUE THREAD

**Issue by harshzalavadiya** [jbetancur/react-data-table-component#362]
**Is your feature request related to a problem? Please describe.**
I already know that there's way to customize cells but it's at column level

**Describe the solution you'd like**
For Example: Generally when cell has large data it will be trimmed by elipsis (this is expected behaviour) this can be customized by providing custom cell that will wrap value with `title` attribute but it has to be done at every column level but might be nice to have ability to customize default cell template at table level

**Describe alternatives you've considered**
Write custom func and pass it as cell arguement at every column props,

**Additional context**
NA

**Comment by jbetancur** [comment]
Not sure I follow.  Can you post some use cases or examples?

**Comment by harshzalavadiya** [comment]
Hi,
Here's an CSB Link
https://codesandbox.io/s/inspiring-pine-ohv72

**Comment by blacksmoke26** [comment]
```js
const cell = ( row ) => (
  <span title={row.title}>{row.title}</span>
);

const columns = [
  {
    name: "Something else",
    selector: "somethingelse",
    sortable: true,
    maxWidth: "400px",
    cell,
  },
  {
    name: "x",
    selector: "somethingelse",
    sortable: true,
    maxWidth: "400px",
    cell,
  },
  {
    name: "y",
    selector: "somethingelse",
    sortable: true,
    maxWidth: "400px",
    cell,
  },
  {
    name: "z",
    selector: "somethingelse",
    sortable: true,
    maxWidth: "400px",
    cell,
  }
];
```

Why not create a component and pass it to each column? This may confuse other users.

**Comment by harshzalavadiya** [comment]
Hi @blacksmoke26 
Oh, I guess I wasn't able to clearly explain in example. but I don't want to render the same field again and again so if we respect selector prop it will be something like below

```jsx
const Cell = ({v}) => (
  <span title={v}>{v}</span>
);

const columns = [
  {
    name: "Field 1",
    selector: "sel1",
    cell: row => <Cell v={row.sel1} />,
  },
  ...
  {
    name: "Field X",
    selector: "selX",
    cell: row => <Cell v={row.selX} />,
  },
];
```

Of course this still works there's absolutely no problem with it as well but I want to avoid repeating `cell: row => <Cell v={row.*someSelector*} />`

Current idea is similar to [`selectableRowsComponent`](https://github.com/jbetancur/react-data-table-component#overriding-with-ui-component-library)  but instead for normal cell

**Comment by jbetancur** [comment]
@harshzalavadiya It's a good suggestion and I suppose there could be something like a customCell or defaultCell prop, but I am not entirely convinced that the cost of adding that feature plus tests, maintenance, etc, outweighs saving on some "repetition"  @blacksmoke26  is a has a good example on how to make it cleaner though.

If I get more votes or requests on this perhaps we can re-consider.

**Comment by harshzalavadiya** [comment]
Hi @janhartmann, 
I understand this is not essential feature.
@blacksmoke26 's answer doesn't satisfy the problem. because that way can't avoid repeatation, we have to wrap it twice because key changes every time.

p.s. may be adding tooltip to cell will be nice for truncated data that way we can see what is there in that cell

**Comment by jbetancur** [comment]
I feel you on having tooltips but I think this is something best left to be implemented by the library user in a custom cell, otherwise, folks start having opinions that the tooltip should no XY or Z. In other words, I'd rather focus essential features that allow you the developer some leeway for your own creativity 😉 

btw you could also try this to reduce some of the repetition, hope it helps:

```
const Cell = field => row => (
  <span title={row[field]}>{row[field]}</span>
);

const columns = [
  {
    name: "Field 1",
    selector: "sel1",
    cell: Cell(sel2),
  },
  ...
  {
    name: "Field X",
    selector: "selX",
    cell: Cell(sel2),
  },
];
```

**Comment by harshzalavadiya** [comment]
That should do the trick
Thanks

**Comment by slimandslam** [comment]
Since adding "cell" to a column seems to negate `allowOverflow: false` and  `wrap: false`,
I had to make the cell like this to make tooltips practical:

```
const Cell = field => row => (
  <span style={{whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"}} title={row[field]}>{row[field]}</span>
  );
...
...
const columns = [
    {
      name: "Filename",
      selector: "originalFileName",
      width: "250px",
      cell: Cell("originalFileName"),
    },
```

**Comment by karimdakroury** [comment]
hello, why does filter not work on custom cell?
