### ISSUE TITLE
Is it possible to implement colspan kind of feature?

### ISSUE THREAD

**Issue by ymihir** [jbetancur/react-data-table-component#367]
Is there anyway that i can achieve col span kind of feature in this good plugin? I want to show some of the rows as headers in between so i need expand column for whole row.

**Comment by jbetancur** [comment]
No not currently but this would be a very nice feature that can be added

**Comment by jbetancur** [comment]
I’ll flag this as a feature for 6.1

**Comment by ymihir** [comment]
When can I expect 6.1 release. Based on this i will choose the plugin

**Comment by abdulmateentechbits** [comment]
> No not currently but this would be a very nice feature that can be added

How can i add the row record dynamically using loop

**Comment by edgarklepek** [comment]
+1 needed feature!

**Comment by dev-patel** [comment]
+1 needed feature!
