### ISSUE TITLE
How to prevent reloading the whole page when clicking next page in paginated table

### ISSUE THREAD

**Issue by allen-ig** [jbetancur/react-data-table-component#372]
I want to make a paginated datatable and the render function is as below

`render = () => {
        return this.state.showSplicingDatatable && <DataTable
            columns={this.state.columns}
            data={this.state.data}
            customTheme={{rows: {height: '15px'}}}
            noHeader={true}
            subHeader
            pagination
            paginationPerPage={30}
            paginationRowsPerPageOptions={[30, 50, 100, 200]}
            id="splicingDatatable"/>
    }`
The pagination looks fine but when I click the next page button, the whole page get refreshed and there is a question mark appended to the end of the url.

**Comment by EswarNandam** [comment]
Hi allen-ig, Facing the same issue. Can you please let me know how you have done the problem resolved.

**Comment by EswarNandam** [comment]
> I want to make a paginated datatable and the render function is as below
> 
> `render = () => { return this.state.showSplicingDatatable && <DataTable columns={this.state.columns} data={this.state.data} customTheme={{rows: {height: '15px'}}} noHeader={true} subHeader pagination paginationPerPage={30} paginationRowsPerPageOptions={[30, 50, 100, 200]} id="splicingDatatable"/> }`
> The pagination looks fine but when I click the next page button, the whole page get refreshed and there is a question mark appended to the end of the url.


Hi allen-ig, Facing the same issue. Can you please let me know how you have done the problem resolved.
