### ISSUE TITLE
[Docs/Readme] - Clean up

### ISSUE THREAD

**Issue by jbetancur** [jbetancur/react-data-table-component#38]
e.g. make the props alphabetic
and/or integrate them into storybooks

**Comment by inactivist** [comment]
Also, I think `yarn storyboard` should be `yarn storybook` etc

![image](https://user-images.githubusercontent.com/1195074/52178636-e35a7280-2785-11e9-9455-c027e2300924.png)


```
$ yarn storyboard
yarn run v1.13.0
error Command "storyboard" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jbetancur** [comment]
Done
