### ISSUE TITLE
Docs/example for custom paginationComponent

### ISSUE THREAD

**Issue by Teomik129** [jbetancur/react-data-table-component#384]
As of right now, neither the docs nor the storybook contain implementation details for a custom paginationComponent e.g. props provided, styles, overrides, etc. It would be a helpful addition.

**Comment by jbetancur** [comment]
Yea I agree. It hasn't been the more popular request. I've thought about just creating a couple of built-in pagination components. I know some folks want a bootstrap one

In any case, when you create your custom pagination component you just need to satisfy this API

```js
           <MyAwesomePaginationExtremeEdition
                onChangePage={handleChangePage}
                onChangeRowsPerPage={handleChangeRowsPerPage}
                rowCount={paginationTotalRows || data.length}
                currentPage={currentPage}
                rowsPerPage={rowsPerPage}
              />
```

You can look at the existing pagination component for ideas and what those call backs are
https://github.com/jbetancur/react-data-table-component/blob/master/src/DataTable/Pagination.js

**Comment by jbetancur** [comment]
Yea I agree. It hasn't been the most popular request though.

In any case, when you create your custom pagination component you just need to satisfy this API

```js
MyAwesomePaginationExtremeEdition.propTypes = {
  rowsPerPage: PropTypes.number.isRequired,
  rowCount: PropTypes.number.isRequired,
  onChangePage: PropTypes.func.isRequired,
  onChangeRowsPerPage: PropTypes.func.isRequired,
  currentPage: PropTypes.number.isRequired,
};
```

You can look at the existing pagination component for ideas and what those call backs are
https://github.com/jbetancur/react-data-table-component/blob/master/src/DataTable/Pagination.js

**Comment by jbetancur** [comment]
Also, This would be a good storybook or readme.  I am open to PR's if someone beats me to the finish line.

**Comment by rjgux** [comment]
Did anything come from this? I would really appreciate a custom pagination example for reference (I'm struggling to work it out from the existing pagination component, in particular the callbacks)

(Apologies for commenting on a closed issue)

**Comment by jbetancur** [comment]
No, I just have not had the time and was hoping someone could contribute to the docs. I wanted to have something like a bootstrap style pagination to show that you can do that.

As for handlers you just need to worry about passing the right page up to DataTable (the parent component).

`onChangePage(<pageNumberYou wish to move to>)` So if you have back or previous or actual numbers just pass into the handle `<button onClick={() => onChangePage(1)}>Go to Page 1</button>`

and if you are implementing per pages dropdown
`onChangeRowsPerPage(<Updated rowsPerPage>, currentPage)`

The parent component takes care of the "math" will re-calculate everything for you

Note that I will be moving away from `useTableContext` on line 61 and just passing these in as props instead in a 7.0 release - just to make the interface easier (good first PR as well if anyone wants to move these to props).

https://github.com/jbetancur/react-data-table-component/blob/3ccbfae5005047a3a27fe7d60a83269b75ea88b7/src/DataTable/Pagination.js#L61

**Comment by jbetancur** [comment]
I will reopen this and try to fit it in unless someone wants to take a stab at it

**Comment by Teomik129** [comment]
@jbetancur I went ahead and created an Storybook example using Material UI. Also linked to `Pagination.js` in the docs for reference. You can review it at your convenience.

**Comment by jbetancur** [comment]
Thanks @Teomik129 ill take a look this week
