### ISSUE TITLE
How to implement collapse all when expand only a new row?

### ISSUE THREAD

**Issue by LuisGnzlz1** [jbetancur/react-data-table-component#389]
## Describe the bug
I wish close all row expanded,  when expand a new row?

**Comment by erikt9** [comment]
I believe you could do this by using `expandableRowExpanded` and `onRowExpandToggled`.  Keep track of which row you want opened with `onRowExpandToggled` and only return true in `expandableRowExpanded` for that one row.

**Comment by jbetancur** [comment]
It should be possible as @erikt9 state, but I kind of think this would be a good feature to have as a prop `expandableCloseAllOnExpand` or something like that

**Comment by luciano1997** [comment]
> expandableCloseAllOnExpand

was this added?
