### ISSUE TITLE
Edit row of the table not activate re-render of the table

### ISSUE THREAD

**Issue by ariel262626** [jbetancur/react-data-table-component#39]
if i adding or removing entity the table re-render and shown the update data but when i edit some entity of the table the table not re-render until i refresh the page manualy
my edit  action update the state to fix it i need to delete the entire row call setState and than add the updated row and than call setState again.

thanks.

**Comment by jbetancur** [comment]
Hi,

I'm not sure I follow your issue. Can you post a sandbox with the issue?

You can use this template to get started:
https://codesandbox.io/s/737x8vj8l0
