### ISSUE TITLE
Broken Link in Readme

### ISSUE THREAD

**Issue by erikt9** [jbetancur/react-data-table-component#392]
The styles.js link from this line of the readme gets a 404.  

> View [styles.js](https://github.com/jbetancur/react-data-table-component/blob/master/src/styles.js) for a detailed catalog of RDT styles that you can override or extend using css-in-js objects.

Second broken link

> [styles.js](https://github.com/jbetancur/react-data-table-component/blob/master/src/styles.js) for a detailed catalog of RDT styles that you can override or extend using css-in-js objects

**Comment by jbetancur** [comment]
Thanks! Will be fixed in the next release

**Comment by erikt9** [comment]
This looks to be fixed now.
