### ISSUE TITLE
Allow conditionalRowStyles to be applied to Expander rows

### ISSUE THREAD

**Issue by erikt9** [jbetancur/react-data-table-component#394]
**Is your feature request related to a problem?**
conditionalRowStyles can only target regular rows and skips expander rows (those with the `rdt_ExpanderRow` class).

**Describe the solution you'd like**
conditionalRowStyles function is called for expander rows and receives another parameter indicating whether the row is an expander row.  The function would still receive the same row object the base row received.  

**Describe alternatives you've considered**
Create a whole new property for targeting expander rows (`conditionalExpanderRowStyles`).

**Comment by jbetancur** [comment]
So you want to target the Expander Row itself? Have you tried just using a custom `expandableRowsComponent`?  Whatever component you pass into `expandableRowsComponent` will have access to your data via `props.data` and you can do whatever logic you need.

**Comment by jbetancur** [comment]
e.g.

```js
const MyCustomComponent = ({ data }) => (
  <div>
     // use your data to set your classnames or style-component props etc..
  </div>
);

```

**Comment by jbetancur** [comment]
Actually, I think this should be possible - I could add a conditional prop to allow the `conditionalRowStyles to optionally propagate down to Expander Row. The only issue here is that if you have a custom Expander row (which I think is the common case) then the styles would not apply to it unless you specifically inherited them in your css.

**Comment by erikt9** [comment]
Your code example is similar to what I am currently doing as a workaround.  Mostly it seems incomplete to have a `conditionalRowStyles` method that in reality is only hitting half the available rows.  

My use case is I have a filter where (for various reasons) instead of removing elements from the table's `data`, I'd like to keep the rows in the DOM with a `display:none` on them.  It would be nice to have the logic for hiding the base row and the expander row all in the same method.

**Comment by jbetancur** [comment]
I think that should be possible. I’ll add this to the 6.2 release

**Comment by jbetancur** [comment]
I will be merging this into the 6.2.0 release branch but you now have a new prop with quite an egregious name :)

`expandableInheritConditionalStyles`

This will allow the conditionalRow Styles to apply to the ExpandableRow.
