### ISSUE TITLE
Context Menu when using selectable rows should support options for localization

### ISSUE THREAD

**Issue by jbetancur** [jbetancur/react-data-table-component#406]
FYI @dinizime

possible solutions
- make the "items" section title a component
- make the "items" a call back

**Comment by jbetancur** [comment]
This is now implemented! You can now pass in a config object with your localization using `contextMessage`. If you need some more hardcore customization you can  also create your own `contextComponent`which has access to the selectedCount.

See the release notes/README for 6.1.0 for more details.

**Comment by nickallenjr** [comment]
I there any way to access rowsSelected from contextComponent? Similarly how you can with onSlectedRowsChange.

I submitted an issue request, but I was still trying to hunt down a solution in the meantime.

Thanks for everything?
