### ISSUE TITLE
Change display:table in TableWrapper.js to display: block or flex

### ISSUE THREAD

**Issue by erikt9** [jbetancur/react-data-table-component#407]
**Is your feature request related to a problem? Please describe.**
I had a bug (only in Safari) where some animation that changed the height of an expander cell would leave the `TableWrapper.js` &lt;div&gt; and the actual `.rdt_Table` elements at slightly different heights.  It seems like the `display: table` in TableWrapper is what was triggering this bug in Safari.  

**Describe the solution you'd like**
Change `display:table` in TableWrapper.js to `display: block` or `display: flex`.  Given that no `display: table-row` or `table-cell` are defined afterwards, the `display:table` is unnecessary and can be simpler.

**Comment by jbetancur** [comment]
I know what you mean but this breaks responsive tables. For example Try a really wide table and change to block. The columns will be broken. This Is one of the challenges with trying to make a table built on flex. What I could do is allow you to use customeStyles on the table wrapper, unless you find a solution.

**Comment by jbetancur** [comment]
in 6.1.1 which I will release shortly, you can override this via customStyles tableWrapper prop
https://github.com/jbetancur/react-data-table-component/pull/413

**Comment by jbetancur** [comment]
Docs on customStyles
https://github.com/jbetancur/react-data-table-component#1629-theming-and-customization
