### ISSUE TITLE
Changing the Icon for expandable rows

### ISSUE THREAD

**Issue by PKrishnamurthy1** [jbetancur/react-data-table-component#410]
The props option for changing the icon for expandable rows as described in the documentation does not work,
expandableIcon: { collapsed: <svg>{myicon}</svg>, expanded: <svg>{myicon}</svg>}
Is it because its not included in the IDataTableProps interface.

**Comment by jbetancur** [comment]
If you are using typescript then yes. I'll patch a 6.1.1 later today
