### ISSUE TITLE
Non existing file or path './src/DataTable/themes'

### ISSUE THREAD

**Issue by thobishi** [jbetancur/react-data-table-component#417]
When I use the 'react-data-table-component' library I discovered the following.

the `import { createTheme, defaultThemes } from './src/DataTable/themes'; ` is referencing a none existing path of   `'./src/DataTable/themes'` I checked the library directory `'react-data-table-component/dist'` and `'src/DataTable/themes'` does not exist.

<img width="638" alt="Screenshot 2020-01-05 at 03 49 55" src="https://user-images.githubusercontent.com/19746512/71774013-f5cdc500-2f6f-11ea-8eb7-5de0578a37f7.png">

This is throwing exception of the following, I would like to use the library but I am stuck with the exception below:
<img width="1040" alt="Screenshot 2020-01-05 at 04 04 33" src="https://user-images.githubusercontent.com/19746512/71774050-86a4a080-2f70-11ea-9817-c29c6793569f.png">

**Comment by jbetancur** [comment]
yea definitely busted - Should be a quick fix

**Comment by jbetancur** [comment]
fixed in 6.1.2
