### ISSUE TITLE
Error when custom header contains period (exp: "2.1")

### ISSUE THREAD

**Issue by rezkyal** [jbetancur/react-data-table-component#425]
## Describe the bug
Error happen when i try to use custom header with period in it (columns) (exp: "2.1") (screenshot below)
![Screenshot from 2020-01-12 21-10-46](https://user-images.githubusercontent.com/25602049/72220158-697b5d80-3580-11ea-917e-be812e9fffff.png)

Example:
![Screenshot from 2020-01-12 21-17-23](https://user-images.githubusercontent.com/25602049/72220205-f7574880-3580-11ea-9d34-7279c50e0457.png)

Header going to be used (basicTableColumn):
![Screenshot from 2020-01-12 21-14-23](https://user-images.githubusercontent.com/25602049/72220175-8fa0fd80-3580-11ea-99f4-e37be3534e57.png)

## To Reproduce
1. Create the table using columns property

## Expected behavior
No error happen

## Versions (please complete the following information)
- React
- Styled Components
- Typescript
- OS: [linux]
- Browser [chrome]
- Version [chrome 73]

**Comment by jbetancur** [comment]
What does your data look like? I notice you are using the decimal value for the `selector`. The selector should be the dot notation path for you data. e.g. 

`selector="number.value"`
```js
data = { values: number: { value: "5.1 }}
```

Alternatively, if your key has a dot in it then for such an edge case you can use a function as your row selector"
`selector={row => row['5.1']}`

**Comment by rezkyal** [comment]
I am using your alternative solution and it is working! Thanks! My data is using dot as one string, not as notation (ss below)
<img width="388" alt="Capture" src="https://user-images.githubusercontent.com/25602049/72261732-f76e4b80-3647-11ea-9c2d-3754a85126ec.PNG">
