### ISSUE TITLE
Performance when selecting rows in a large list

### ISSUE THREAD

**Issue by rafaelmaiach** [jbetancur/react-data-table-component#426]
## Describe the bug
I have a list of around 500 items. I'm showing 200 items per page. In this scenario, when I try to select one row (or all of them), I have a delay of almost 2 seconds for the item be selected (even if it's just 1 item being selected).

My component:
```js
    const preSelectedRow = () => true; // This is outside my component function

    const [selectedRows, setSelectedRows] = useState([]);
    const handleRowSelected = useCallback((state) => {
        setSelectedRows(state.selectedRows);
     }, []);

    <DataTable
          title={totalResultText}
          columns={columns}
          data={data}
          selectableRows
          selectableRowsHighlight
          pagination
          paginationRowsPerPageOptions={[10, 25, 50, 100, 200]}
          dense
          onSelectedRowsChange={handleRowSelected}
          selectableRowSelected={preSelectedRow}
      />
```
I noticed, that when I select one row, all the rows are updated in the dom, this may be the cause for the bad performance

## To Reproduce
1. Have a big list of items rendered
2. Enable the selectable option
3. Select one item, it should take a long time (~1.5 - 2seconds)

## Expected behavior
To have a better performance

## Code Sandbox
Please include a codesandbox to help duplicate your issue

https://codesandbox.io/embed/react-data-table-sandbox-ccyuu

## Versions (please complete the following information)
 - React: 16.10.2
 - Styled Components: 4.4.1
 - OS: MAC OS
 - Browser: Chrome
 - Version 79.0.3945.117 

## Additional context
Maybe it's not a bug, but the way I'm using the component. Any advice of performance improvement are welcome.

**Comment by jbetancur** [comment]
I'm not able to dupe this. Here is a codesandbox I use for bench marking:

https://codesandbox.io/s/react-data-table-sandbox-benchmark-d9md1

Also, instead of setting `paginationRowsPerPageOptions` inline move the array of options outside of your component. That will save RDT a whole re-render since the array reference will no longer change.

**Comment by rafaelmaiach** [comment]
Hey @jbetancur thank you for your quick reply.
It was the array that was causing the re-render on every select row.
Now it's everything working fine!
