### ISSUE TITLE
Changing state does not update table or re-render it

### ISSUE THREAD

**Issue by cakerake** [jbetancur/react-data-table-component#427]
I have my table data in a State called Data

this has been fed to the Table component and works normally

I'm trying to update the data - get more details about current data and then set the state again after loading it

when i do this the table does not update by itself

i have this filter function as well for the table and when i enter any letter (which filters the table data) the table data immediately updates

ive tried quite a few things and im left scratching my head - how do i get the table data to be re-rendered or updated each time i update teh state?

If you have a working example that'd be great!

**Comment by cakerake** [comment]
So i got a solution that i think is the most hacky and stupid way of doing it

everytime i update the array that the table is showing -> i update another state that is not being used ANYWHERE in the ui at all with a random value

this forces the entire thing to re-render and therefore working...

please correct me i know this is wrong

**Comment by impactcolor** [comment]
It appears as if issue #103 would be related to this.
