### ISSUE TITLE
Data Table came out with scroll bar. 

### ISSUE THREAD

**Issue by oakkar8** [jbetancur/react-data-table-component#428]
The data table come out with the scroll bar. It doesn't matter how big the table is. This happens when I use pagination.

This is how it came out.
![1](https://user-images.githubusercontent.com/35274540/72385815-15ce5880-36d5-11ea-9f70-d927bb61075e.png)

This is the expecting result.
![2](https://user-images.githubusercontent.com/35274540/72385829-19fa7600-36d5-11ea-85e4-d534d2405390.png)

## Versions (please complete the following information)
 - React: 6.13.4
 - Styled Components: 4.4.1
 - OS:  Ubuntu 18.0.4
 - Browser chrome
 - Version  79.0.3945.117 (Official Build) (64-bit)

**Comment by Hugoo** [comment]
I noticed the same problem yesterday after updating to latest Chrome: Version 79.0.3945.117 (Official Build) (64-bit) / Mac OS 10.15.2

Here is a simple repo:
https://codesandbox.io/s/github/Hugoo/bug-report
https://github.com/Hugoo/bug-report

The problem doesn't occur on the Sandbox.

The problem occurs locally (when I access the project on localhost:3000).
It doesn't happen when using Safari or when I access the project from my local ip, which first lead me to think it was a problem related with my local cache but it seems I'm not the only one having this problem.

On first load (pagination is hidden): 
![image](https://user-images.githubusercontent.com/477945/72412487-b5d7c080-376d-11ea-9729-faa99dd6f6ac.png)

On scroll:
![image](https://user-images.githubusercontent.com/477945/72412505-c5efa000-376d-11ea-983c-0e47164f07e3.png)

**Comment by oakkar8** [comment]
The problem still exists in Firefox now..

**Comment by oakkar8** [comment]
Any Suggestions or Helps would be appreciated.... 
Thanks.

**Comment by jbetancur** [comment]
I've had issues in the past scroll bars and resolved it by setting `box-sizing: border-box` on RDT's internal components. Also, since box-sizing is different across browsers that's what sanitize.css and normalize libraries are there that help with this so you may give these a try to validate/troubleshoot your CSS is consistent across browsers. 

Aside from that, I have not been able to duplicate this.

**Comment by Hugoo** [comment]
> Any Suggestions or Helps would be appreciated....
> Thanks.

check zoom of your browser

**Comment by jbetancur** [comment]
I think I was able to duplicate this in the Firefox browser I use at work, but strangely my Firefox on my home PC and MAC are fine. Stay tuned...

**Comment by oakkar8** [comment]
Yeah it is wired.. not happening everytime....

**Comment by jbetancur** [comment]
Ok, I think I have a fix for this.  In firefox, if I add 

```css
overflow-y: hidden;
````
 to `ResponsiveWrapper` it seems to fix the issue.

I am going to do some more testing and work on a 6.2.4

For those of you having issues try giving that wrapper in your inspector overflow-y: hidden; and see if that works for you too.

**Comment by jbetancur** [comment]
Wow ok this happens when the parent wrapping RDT uses 

```css
display: flex;
```

**Comment by jbetancur** [comment]
Keeping open for now until this can be verified as fixed
