### ISSUE TITLE
Use column but keep hidden

### ISSUE THREAD

**Issue by impactcolor** [jbetancur/react-data-table-component#433]
Is there away to use data that is not visible in columns?
I'll explain:
```
const columns = [
  {
    name: 'FIRST',
    selector: 'first',
    sortable: true,
    cell: row => <div style={{ fontWeight: 'bold' }}> <Link to={`member/${row.uid}`}>{row.first}</Link></div>,
  },
  {
    name: 'LAST',
    selector: 'last',
    sortable: true,
    cell: row => <div style={{ fontWeight: 'bold' }}> <Link to={`member/${row.uid}`}>{row.last}</Link></div>,
  },
  {
    name: 'PHOTO',
    selector: false,
    cell: row => householdPics(row),
    sortable: true,
  },
];
```
Here if I use:
`selectableRowSelected={rowSelectCritera}`
`const rowSelectCritera = row => row.first == "David";`

Anything with the name of David would be selected.  That's great.  However I want to use part of my data that is not presented in columns.  I don't want that to show.
So I would like:
`const rowSelectCritera = row => row.didAttend == true;`
However this does not work since 'didAttend' is not in the columns, it's in the data but not in the columns.  A console.log of row shows that it's there.  How can I accomplish this?

**Comment by impactcolor** [comment]
I figured out from looking at another post that I can hide it like so:
`hide: 6000,`
So I would allow that column to be there but hide it.  Thank you!

**Comment by jbetancur** [comment]
You can also look at column.style and just set display: none

Are you saying that if a column is not in the columns array it doesn’t show up on the conditinsalRowStyles?

**Comment by impactcolor** [comment]
Yes that's what I was saying but i read in another post here that it wouldn't be good for RDT to handle all data as that would be cover overload.
