### ISSUE TITLE
Datatable camera expandableRowsComponent parking

### ISSUE THREAD

**Issue by Angelk90** [jbetancur/react-data-table-component#434]
## Describe the bug

I have a list of cameras, each room must contain a set of parking spaces.
So I thought of using only one table, the main cameras table which contains all the cameras with the attributes:
`name, lat, lng
`
Then using `expandableRowsComponent`, when clicking on a specific camera they had to see the parking lots of that specific camera, always in the form of a table.
The attributes are the same: `name, lat, lng`.

The problem is that when I click to open the expandableRowsComponent component, it doesn't open.

## Expected behavior
What I would like to get is a table that when I click on a row, it opens and it has another table with parking lots as component.

## Code Sandbox
Please include a codesandbox to help duplicate your issue

https://codesandbox.io/s/drawingmode-null-onoverlaycomplete-cwxvz

**Comment by impactcolor** [comment]
The sandbox shows a google map and that's all.
