### ISSUE TITLE
Make pagination responsive

### ISSUE THREAD

**Issue by allencazar** [jbetancur/react-data-table-component#435]
Is it possible to make the default pagination responsive? or a prop/option to do so with certain breakpoints. 

![image](https://user-images.githubusercontent.com/13835411/72760051-97147680-3c12-11ea-88d9-291d657988ce.png)

**Comment by jbetancur** [comment]
This was implemented in 6.8.0. If you reach a width of less than 599px the built-in pagination now goes into a mobile mode.  If you require anything more custom than that you can also create your own pagination component or use a 3rd party lib that specializes in this.

But, at least for now, the pagination shouldn't look terrible on mobile devices 😉 

![Screen Shot 2020-04-27 at 12 02 22 AM](https://user-images.githubusercontent.com/1385932/80332941-65670900-881a-11ea-971a-3781c09947a7.png)
