### ISSUE TITLE
Calculate column field values

### ISSUE THREAD

**Issue by Eithcowich** [jbetancur/react-data-table-component#440]
I need to calculate the value of fields in my table. Something like this: 

    {
      name: 'Winning%',
      selector: '(timesWon / timesLost) * 100',
      sortable: true,
    },

I also tried putting the calculation in brackets: 

    {
      name: 'Winning%',
      selector: {(timesWon / timesLost) * 100},
      sortable: true,
    },

But now luck. Is this possible? I haven't seen it in the docs.

**Comment by jbetancur** [comment]
Selector also takes a function ‘selector: row => // calculate your field’

**Comment by Eithcowich** [comment]
Thanks, works perfectly.
