### ISSUE TITLE
A keyField containing 0 or other falsey value in your data results in react errors and bad renders

### ISSUE THREAD

**Issue by erikt9** [jbetancur/react-data-table-component#442]
I believe this is caused by line 343 in DataTable.js:

{calculatedRows.map((row, i) => {
**const id = row[keyField] || i;**
const selected = isRowSelected(row, selectedRows, keyField);

I believe the check should be against undefined / null instead of just truthy / falsey value.

**Comment by jbetancur** [comment]
Related to #469
