### ISSUE TITLE
TypeError: React.useReducer is not a function

### ISSUE THREAD

**Issue by iusamakhan** [jbetancur/react-data-table-component#446]
## Describe the bug
I am using react 16.7.0 and  i am facing this issue "TypeError: React.useReducer is not a function"
i am not using any state management. i just implemented the simple example given in the documentation.
## To Reproduce

import DataTable, { createTheme } from 'react-data-table-component';

createTheme('solarized', {
  text: {
    primary: '#268bd2',
    secondary: '#2aa198',
  },
  background: {
    default: '#002b36',
  },
  context: {
    background: '#cb4b16',
    text: '#FFFFFF',
  },
  divider: {
    default: '#073642',
  },
  action: {
    button: 'rgba(0,0,0,.54)',
    hover: 'rgba(0,0,0,.08)',
    disabled: 'rgba(0,0,0,.12)',
  },
});

const MyComponent = () => (
  <DataTable
    title="Arnold Movies"
    columns={columns}
    theme="solarized"
  />
);

## Expected behavior
A data table should have been rendered.

## Versions (please complete the following information)
 - React 
 - simple functional and class Components
 - OS:  Windows 10
 - Browser : chrome, 
 - Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by jbetancur** [comment]
https://github.com/jbetancur/react-data-table-component#13-requirements

You need to React 16.8.0 to use RDT
