### ISSUE TITLE
Border between cells - but only on some columns

### ISSUE THREAD

**Issue by Eithcowich** [jbetancur/react-data-table-component#448]
My table has some logical separations and I'd like to highlight them by having a border between them. Something like this: 

    Section 1.1 | Section 1.2 | Section 1.3 ||| Section 2.1 | Section 2.2 ||| Section 3.1

The border should be only for the cells between the sections, denoted above with `|||`. 

I'm using the custom styles, and able to have the border on all cells. But is it possible to choose only some of them? 

My `customStyles`: 

     const customStyles = {
        rows: {
         style: {
          minHeight: '72px', // override the row height
        }
    },
     headCells: {
        style: {
            paddingLeft: '8px', // override the cell padding for head cells
            paddingRight: '8px',
        },
     },
      cells: {
          style: {
            paddingLeft: '8px', // override the cell padding for data cells
            paddingRight: '8px',
            borderRight: '1px solid gray',
        },
     },
    };

**Comment by jbetancur** [comment]
`conditionalCellStyles`

https://github.com/jbetancur/react-data-table-component#161-columns

also

https://jbetancur.github.io/react-data-table-component/?path=/story/conditional-styling--conditional-cells

**Comment by Eithcowich** [comment]
Perfect, thanks.
