### ISSUE TITLE
[FEATURE]: Allow columns with string sorting, ignore uppercase or lowercase to order alphabetically 

### ISSUE THREAD

**Issue by diego-unanue-globant** [jbetancur/react-data-table-component#450]
## Issue Check list
- [x ] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

At this moment when you sort the table, lets say order desc, it orders the table (first orders lowercase desc and then uppercase desc). It would be useful to the users to ignore if it's an uppercase or lowercase, and just order the text alphabetically by default. And set an option if you want the uppercase and lowercase to be take in care in the ordering.

**Comment by jbetancur** [comment]
Take a look at the prop `sortFunction`. This allows you to override the sort behavior however you need.

This example just converts everything to lowercase within the sort to get the behavior you want. I am using lodash orderby here to do the sort but am convertint the value  to lowercase using the lodash orderby handler
e.g.
```js
const customSort = (rows, field, direction) => {
  const handleField = row => {
    if (row[field]) {
      return row[field].toLowerCase();
    }

    return row[field];
  };

  return orderBy(rows, handleField, direction);
};
```
See storybook example here:
https://jbetancur.github.io/react-data-table-component/?path=/story/sorting--custom-sort-function
