### ISSUE TITLE
When loading a row image doesn't update

### ISSUE THREAD

**Issue by impactcolor** [jbetancur/react-data-table-component#454]
current I have my component like so:
 ```
               <DataTable
                defaultSortField="last"
                sortIcon={<SortIcon />}
                pagination={true}
                columns={columns(this.props)}
                data={this.state.data}
                noHeader
                />
```

I set my data like so:
```
const columns = memoize(props => [
  {
    name: 'FIRST',
    selector: 'first',
    sortable: true,
    cell: row => <div style={{ fontWeight: 'bold' }}><Link to={`member/${row.uid}`}>{row.first}</Link></div>,
  },
  {
    name: 'LAST',
    selector: 'last',
    sortable: true,
    cell: row => <div style={{ fontWeight: 'bold' }}><Link to={`member/${row.uid}`}>{row.last}</Link></div>,
  },
  {
    name: 'PHONE',
    selector: 'phone',
    sortable: false,
  },
  {
    name: 'EMAIL',
    selector: 'email',
    sortable: false,
  },
  {
    name: 'PHOTO',
    selector: 'photo',
    cell: row => <HouseholdPics data={row}/>,
    sortable: false,
  },
  {
    name: 'LAST PRESENT',
    selector: 'lastpresent',
    sortable: true,
  },
]
);
```
The line: `cell: row => <HouseholdPics data={row}/>,`
Passes row details to HouseholdPics.  In this I have row.profilePic which is different.  however when I console log or execute this on some it changes on others it doesn't.  In the data each is different but when RDT passes it over sometimes it is correct, other times it's reusing a previous one.  Any idea why it's doing this?

**Comment by jbetancur** [comment]
I'm having a hard time duplicating without some environment, steps to reproduce, your exact workflow or at least more complete code, etc. 

I started one here against a remote API:
https://codesandbox.io/s/react-data-table-sandbox-remote-api-qp4os

I might have a slight suspicion of what it might be though, but it will be hard to verify without something to test against.

Out of curiosity, can you remove the memoization and see if you get the same behavior? Where is your columns defined outside of the render or within? In any case if we can get this duplicated in the codesandbox that would be the most helpful

**Comment by impactcolor** [comment]
I removed memoization.  After digging more into and comparing it to your sandbox, I can see the problem is related to the firebase call.  

```
const HouseholdPics = props => {
  const [imgRef, setImgRef] = useState(require("../../assets/img/empty-avatar.png"));

  if (props.data.profilePic && props.data.profilePic != 'NULL') {
    props.firebase.storageRef(`images/${props.data.profilePic}`).getDownloadURL().then(url => {
      setImgRef(url);
    });
  }

  return(
    <div>
    <a
      className="avatar avatar-sm"
      id={props.data.uid}
      onClick={e => popUp(imgRef, props.data.first)}
    >
      <img
        alt={props.data.last}
        className="rounded-circle"
        src={imgRef}
      />
    </a>
    <UncontrolledTooltip
      delay={0}
      target={props.data.uid}
    >
      {props.data.first} {props.data.last}
    </UncontrolledTooltip>
    </div>
  )
}
```
I `setImgRef(url);` after the firebase call is completed but then I think that's what's throwing everything out of wack.

**Comment by impactcolor** [comment]
The main difference I see is that in mine I do the call when the household component loads.  On yours it loads the img uri before with all the data.  I can also do it like that since it appears that doing the call on the household component causes it to not render properly.

**Comment by jbetancur** [comment]
I think I see the issue you need to wrap your asynchronous call into a useEffect. See the REACT docs for more info. But simply useEffect(() => { your code to setImgRef....}, []); the empty brackets are kind of like a componentDidMount. Or you can specify which prop will re execute useEffect.

**Comment by jbetancur** [comment]
@impactcolor I'm assuming that #436 resolves this? Otherwise, let me know.
