### ISSUE TITLE
The pagination looks fine but when I click the next page button, the whole page get refreshed and there is a question mark appended to the end of the url.[DESCRIPTION]

### ISSUE THREAD

**Issue by EswarNandam** [jbetancur/react-data-table-component#455]
## Issue Check list
- [ ] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [ ] Read the README
- [ ] You are using React 16.8.0+
- [ ] You installed `styled-components`
- [ ] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Code Sandbox, Screenshots, or Relevant Code
Please include a codesandbox to help **expedite** troublshooting.

https://codesandbox.io/embed/react-data-table-sandbox-ccyuu

Otherwise, add screenshots and/or complete sample code to help explain your problem.

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+)
 - Styled Components
 - Browser [e.g. chrome, safari, firefox]

**Comment by pensphreak** [comment]
Why was this closed?  I'm having the exact same problem
