### ISSUE TITLE
Footer: Add a footer row to the table.

### ISSUE THREAD

**Issue by essencient** [jbetancur/react-data-table-component#456]
I am not sure if this is possible already but would be good to have a footer row where totals, etc could be added.

**Comment by jbetancur** [comment]
this is sort of what `pagination` already does. You could create a custom pagination component https://jbetancur.github.io/react-data-table-component/?path=/story/pagination--custom-component-material-ui 

If you have a specific use case or examples that would be helpful to understand

**Comment by lucaspokaz** [comment]
> this is sort of what `pagination` already does. You could also create a custom pagination component https://jbetancur.github.io/react-data-table-component/?path=/story/pagination--custom-component-material-ui
> 
> If you have a specific use case or examples that would be helpful to understand


The link is broken!
 Can anyone show me how to customize the pagination to suit the layout of the rows as in the image?

![image](https://user-images.githubusercontent.com/13064616/154096628-dd0b5d79-2a49-4a82-b07b-b065252f005c.png)
