### ISSUE TITLE
Problems using Custom Input Control for Checkboxes - Cannot use Functional Component

### ISSUE THREAD

**Issue by Intelliflex** [jbetancur/react-data-table-component#459]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [ ] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
I'm loving this library so far. One major issue I have is that integrating a UI library (in my case MDBREACT) using the example provided in Storybook https://jbetancur.github.io/react-data-table-component/?path=/story/material-ui--override-default-components does not work. If I try and create my own vanilla checkbox component using a functional component there is an error that Refs cannot be passed to functional components. If I re-write my checkbox as a class based component, I avoid error, but still cannot get it to work. An example using selectableRowsComponent={Component} based around standard HTML checkbox would be useful here

## Code Sandbox, Screenshots, or Relevant Code
Please include a codesandbox to help **expedite** troublshooting.

https://codesandbox.io/embed/react-data-table-sandbox-ccyuu

Otherwise, add screenshots and/or complete sample code to help explain your problem.

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+)
 - Styled Components
 - Browser [e.g. chrome, safari, firefox]

**Comment by Intelliflex** [comment]
Actually - I found it in example inside main documentation (for Bootstrap) - using React.forwardRef
https://codesandbox.io/s/react-data-table-sandbox-z6gtg

**Comment by jbetancur** [comment]
It would be good to have another example using MDB as Ive been meaning to do this for more libraries. If you have some time can you post your select component code? I’ll get a new sandbox created and linked in the Readme.
