### ISSUE TITLE
Sorting formatted numbers

### ISSUE THREAD

**Issue by Eithcowich** [jbetancur/react-data-table-component#460]
I'm sorting on a column of formatted numbers. Like this: 

    724.73
    54.56
    1,181.73

Sort descending should have 1,181.73 on top, but it seems to sort on the first digit only. I tried 

          selector: row => Number(row.formattedNumber),

but this generates NaNs for anything with a decimal point, or a comma. 

Is there a way around this, without using a custom sorting function?

**Comment by jbetancur** [comment]
What does your data look like? are you trying to convert from strings to float? Your selector function will need to handle conversion to deal with commas Etc.. and if you want to convert a string to decimal you may want to look at using paraeFloat and .toFixed

Please post some code so I can see how your data looks before you pass it to rdt.

**Comment by Eithcowich** [comment]
The above is real data. There are more rows involved, but these should clarify the picture: 

    selector: row => row.total,
    724.734125670
    54.56
    1181.72594199

This sorts correctly. 

When I add a `toFixed`:

    selector: row => Number(row.total.toFixed(2)), 
    724.73
    54.56
    1181.73

Sorts correctly. 

Now I'm formatting the numbers to something more readable: 

    selector: row => formatNumber(Number(row.total.toFixed(2))),
    724.73
    54.56
    1,181.73

this no longer sorts correctly, and stays as is. In a general case the sorting would generate something like this: 
 
    9, 8, 7, 790, ... 1000, 1

**Comment by jbetancur** [comment]
Try doing the format in columns[].format - the intention of format is a quick was to change your data visually without changing how it’s sorted

**Comment by Eithcowich** [comment]
I'm sorry, could you please show an example?

**Comment by jbetancur** [comment]
```js
const columns = [
 {
   ...
   selector: row => row.total, // or just the string 'total' to select the data as is
   format: row => formatNumber(Number(row.total.toFixed(2))), // format the data without affecting the value
   ...
 }
]
```

**Comment by jbetancur** [comment]
The point is don't format the data you want to sort if it is sorting the way you like already. Just use the column prop `format`

An example is here (albeit hard to find): https://jbetancur.github.io/react-data-table-component/?path=/story/custom-cells--example-1

Here we truncate `plot` but the internal sorting still sees the full string
```js
  {
    name: 'Plot Format',
    selector: 'plot',
    wrap: true,
    sortable: true,
    format: row => `${row.plot.slice(0, 200)}...`,
  },
````

**Comment by Eithcowich** [comment]
Excellent, thanks. I was hoping there's some way to format the data regardless of the sorting -- and indeed there is!

**Comment by jbetancur** [comment]
Glad that helped!
