### ISSUE TITLE
Table is not update when updating the data.

### ISSUE THREAD

**Issue by oakkar8** [jbetancur/react-data-table-component#461]
I have two tables on single page and trying to move around the data between those two tables. 
`handleLink = row => e => { `
`   let zoneList = this.state.zoneList;
    let linkedZonesList = this.state.linkedZonesList;
    zoneList = zoneList.filter(x => x.zone_id !== row.zone_id);
   if (!linkedZonesList.find(x => x.zone_id === row.zone_id)) {
      linkedZonesList.push(row);
    }
    this.setState({
      zoneList : zoneList,
      linkedZonesList : linkedZonesList
    })`
`}`

that is how I update the data for two tables
but Only the table that use zoneList is updated and linkedZonesList's table is not updating untill clicking the table header to sort the rows.

## Versions (please complete the following information)
React: 6.13.4
data-table-component 1.7.4
Styled Components: 4.4.1
OS: Ubuntu 18.0.4
Browser chrome
Version 79.0.3945.117 (Official Build) (64-bit)

**Comment by jbetancur** [comment]
@oakkar8 this seems like a React/JavaScript issue, but it's really hard to tell without the whole picture. Is there a specific issue with RDT that we can help with?

**Comment by oakkar8** [comment]
Not really.
