### ISSUE TITLE
Side by Side Columns

### ISSUE THREAD

**Issue by emin-karadag** [jbetancur/react-data-table-component#462]
Hello,
I want to arrange the columns in the table side by side according to the text inside.
If there is a long text, take more space. But if there is a short text, it will take less space.
Can we make such a painting? Or will there be such a feature in the future?
Thnaks :)

**Comment by jbetancur** [comment]
Hey @emin-karadag, so if you can take a look at there columns doc section:

https://github.com/jbetancur/react-data-table-component#161-columns

There are a few column props in there that will get you started, but I can tell you that it is challenging to have detect the width from the amount of text and have that all render correctly.

I would try playing around with grow, wrap, minWidth, maxWidth and width and see if those suffice.


Here is a sort of sandbox I use to test column widths etc. that may be of use:

https://codesandbox.io/s/react-data-table-sandbox-custom-growwtap-9upub
