### ISSUE TITLE
Uncheck Rows with the use of a button outside of RDT

### ISSUE THREAD

**Issue by nickallenjr** [jbetancur/react-data-table-component#464]
## Issue Check list
- [ x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [ x] Read the README to ensure the feature is not already present
- [ x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x ] Considered if this can be a storybook or documentation example

So this may have been answered if it is please excuse me, but i've scoured the docs and the issues for the entire day.

I was wondering if there is a way to uncheck rows in my RDT by clicking a button outside of RDT. 

See image attached. 

I want to be able to click the trash can and have it unselect/uncheck that row.

<img width="799" alt="Screen Shot 2020-02-19 at 3 40 21 PM" src="https://user-images.githubusercontent.com/28235579/74874341-ceb83080-532e-11ea-875e-2f9b679db46d.png">

**Comment by nickallenjr** [comment]
`<DataTable 
                                columns={[
                                    {name: "Facility ID", selector: "facilityId", sortable: true}, 
                                    {name: "Inn Code", selector: "innCode", sortable: true},
                                    {name: "Name", selector: "name", grow: 2},
                                    {name: "Country", selector: "country", sortable: true}
                                ]}
                                noHeader={true}
                                defaultSortField={"facilityId"}
                                defaultSortAsc={true}
                                data={filteredItems}
                                striped={true}
                                selectableRows={true}
                                selectableRowsNoSelectAll={true}
                                // selectableRowSelected={row => console.log(row)}
                                fixedHeader={true}
                                onSelectedRowsChange={(rows) => {this.setState({checkedProperties: rows.selectedRows})}}
                                persistTableHead={true}
                                pagination={true}
                                
                            />`

**Comment by jbetancur** [comment]
This is not currently possible, but perhaps you can target the checkbox name and fire the checkbox to unselect? Hacky, but possible in the short term if you need this.

Otherwise, from a UX perspective, why have the user select/unselect things twice in two different places? 🤔

**Comment by nickallenjr** [comment]
Thanks for the response and that's actually a good question. I am simply cutting over an angular app to react and the angular app had that functionality. I will probably be able to get away with not implementing it, just thought I'd ask. 

Thanks again for the awesome package.
