### ISSUE TITLE
Change the order of the elements of the pagination

### ISSUE THREAD

**Issue by Angelk90** [jbetancur/react-data-table-component#468]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

**Is your feature request related to a problem? Please describe.**
In the part relating to pagination I would like to be able to change the order of the elements as seen in the image.

**Describe the solution you'd like**
As a solution it could be done that through a `paginationComponent 'props the possibility to change this part too.

@jbetancur :
![Schermata da 2020-02-22 10-37-52](https://user-images.githubusercontent.com/20476002/75090072-86cc2000-555f-11ea-80ba-0a2a6e369b4e.png)

**Comment by jbetancur** [comment]
Yes, this is where you would use a custom Pagination component. The current Pagination component that is built-in is based on Material Design. I may include other components in the future (e.g. bootstrap style)

**Comment by Angelk90** [comment]
@jbetancur : I did not understand correctly, so to make sure to put the values ​​of the pages in the center between the forward and back buttons of the pagination, how can I do?

**Comment by jbetancur** [comment]
You cannot change the order of the built in pagination component controls. You will need to build a custom one.
