### ISSUE TITLE
Rows duplicated after sorting if a row has id 0

### ISSUE THREAD

**Issue by benceszikora** [jbetancur/react-data-table-component#469]
## Describe the bug
If the `keyField` of a row is 0, it gets duplicated when it gets sorted multiple times.

## To Reproduce
Click on the column name to sort multiple times.

## Expected behavior
The row is not duplicated.

## Code Sandbox, Screenshots, or Relevant Code
Reproducer: https://codesandbox.io/embed/nervous-moore-hnc2s?fontsize=14&hidenavigation=1&theme=dark

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+): `1.16.12`
 - Styled Components `5.0.1`
 - OS: [e.g. iOS] `macOS`
 - Browser [e.g. chrome, safari, firefox] `chrome`

**Comment by jbetancur** [comment]
Nice catch - I think I know what this might be
