### ISSUE TITLE
Use of TablePagination not possible to change paginationComponentOptions 

### ISSUE THREAD

**Issue by Angelk90** [jbetancur/react-data-table-component#470]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
Hi @jbetancur, I am modifying `paginationComponent` following the example, but the problem is that using it I cannot use paginationComponentOptions to be able to change the language of the pagination.

## Expected behavior
Being able to use both, that is, changing the style of the pagination but also the language of the components of the pagination.

## Code Sandbox, Screenshots, or Relevant Code

App.js

```
<DataTable
columns={columns}
data={data}
highlightOnHover
defaultSortField="id"
defaultSortAsc
pagination
paginationServer
paginationTotalRows={totalRows}
onChangeRowsPerPage={handlePerRowsChange}
onChangePage={handlePageChange}
onSort={handleOnSort}
paginationComponent={CustomMaterialPagination}
paginationResetDefaultPage={resetPaginationToggle}
subHeader
subHeaderComponent={subHeaderComponentMemo}
progressPending={pending}
progressComponent={
  <div className={classes.root}>
    <LinearProgress />
  </div>
}
persistTableHead
noHeader
paginationComponentOptions={{
rowsPerPageText: 'Filas por pagina',
rangeSeparatorText: 'de'
}}
/>
```

CustomMaterialPagination.js

```
import React from 'react';
import { IconButton, TablePagination } from '@material-ui/core';
import { FirstPage, KeyboardArrowLeft, KeyboardArrowRight, LastPage } from '@material-ui/icons';

function TablePaginationActions({ count, page, rowsPerPage, onChangePage }) {
	const handleFirstPageButtonClick = () => {
		onChangePage(1);
	};

	// RDT uses page index starting at 1, MUI starts at 0
	// i.e. page prop will be off by one here
	const handleBackButtonClick = () => {
		onChangePage(page);
	};

	const handleNextButtonClick = () => {
		onChangePage(page + 2);
	};

	const handleLastPageButtonClick = () => {
		onChangePage(getNumberOfPages(count, rowsPerPage));
	};

	const getNumberOfPages = (rowCount, rowsPerPage) => Math.ceil(rowCount / rowsPerPage);

	return (
		<>
			<IconButton onClick={handleFirstPageButtonClick} disabled={page === 0} aria-label="first page">
				<FirstPage />
			</IconButton>
			<IconButton onClick={handleBackButtonClick} disabled={page === 0} aria-label="previous page">
				<KeyboardArrowLeft />
			</IconButton>
			<IconButton
				onClick={handleNextButtonClick}
				disabled={page >= getNumberOfPages(count, rowsPerPage) - 1}
				aria-label="next page"
			>
				<KeyboardArrowRight />
			</IconButton>
			<IconButton
				onClick={handleLastPageButtonClick}
				disabled={page >= getNumberOfPages(count, rowsPerPage) - 1}
				aria-label="last page"
			>
				<LastPage />
			</IconButton>
		</>
	);
}

const CustomMaterialPagination = ({ rowsPerPage, rowCount, onChangePage, onChangeRowsPerPage, currentPage }) => (
	<TablePagination
		component="nav"
		count={rowCount}
		rowsPerPage={rowsPerPage}
		page={currentPage - 1}
		onChangePage={onChangePage}
		onChangeRowsPerPage={({ target }) => onChangeRowsPerPage(Number(target.value))}
		ActionsComponent={TablePaginationActions}
	/>
);

export default CustomMaterialPagination;

```

## Versions (please complete the following information)
React (RDT requires 16.8.0+)
Styled Components
OS: Ubuntu
Browser Chrome 79.0.3945.130

**Comment by jbetancur** [comment]
`paginationComponentOptions`  is only really applicable to the built-in Pagination. In fact, this is the case with the following props that have no effect when using a custom Pagination component:

```js
    paginationRowsPerPageOptions,
    paginationIconLastPage,
    paginationIconFirstPage,
    paginationIconNext,
    paginationIconPrevious,
    paginationComponentOptions,
```

The above is meant for convenience to the built-in component. There is probably a better design or this can be improved about but I digress...

So, a custom Pagination component gives you the leverage to do what you need. You can either embed your prefered language into that component or create your own prop system to pass to your custom Pagination component.

**Comment by jbetancur** [comment]
I will amend the readme on this since it is confusing

**Comment by Angelk90** [comment]
@jbetancur : I am getting confused for a moment, I am using the Component layout to customize the pagination, but I would like to change the language of the two elements of the pagination `lines per page:` and `of`, could you give me an example of how I should do it?

**Comment by jbetancur** [comment]
You will need to ask the material ui team that since you are using their pagination component. 😉
