### ISSUE TITLE
Group columns

### ISSUE THREAD

**Issue by Angelk90** [jbetancur/react-data-table-component#474]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe
Hi @jbetancur, I have elements that are part of a group for example, I have an element called Payload, which contains many elements.

## Describe the solution you'd like
As a proposal, the one in the figure would be adopted as a solution.

## Additional context

![](https://i.stack.imgur.com/GpBSG.png)

**Comment by jbetancur** [comment]
There is already an issue open for this. https://github.com/jbetancur/react-data-table-component/issues/367

to be honest not sure when this will happen as I need to prioritize things like expand all, fixing foxed header and grouping.

**Comment by Angelk90** [comment]
Hi @jbetancur , take a look at this trivial example that I did quickly:
Link: https://codesandbox.io/s/winter-hill-m3teh

Let's put the table, have a `colspans` attribute, so declared.

```
  const colspans = [
    {
      name: "",
      colspan: 1
    },
    {
      name: "Contact",
      colspan: 2
    }
  ];
```

**Comment by Angelk90** [comment]
@jbetancur :  Is there any news?

**Comment by jbetancur** [comment]
Sorry, not yet. I have been a bit busy.  At a glance this is a lot of work, but I will keep in on the roadmap!

**Comment by sagargolait** [comment]
@jbetancur Is this issue been taken care of?

**Comment by mangowi** [comment]
@jbetancur Any news about this feature?

**Comment by indracip** [comment]
@jbetancur hi, any update about this feature ? thank you

**Comment by jbetancur** [comment]
No news yet. I'm focused on finishing version 7 and then 8 which will have some breaking changes. A lot of design changes need to happen before this feature can be implemented.

**Comment by shaan360** [comment]
Any progress with this feature or some implemented this while using this package?

**Comment by edgarklepek** [comment]
+1 very needed feature!

**Comment by yestoall** [comment]
I love to have this feature too!

**Comment by avdhootpatil** [comment]
Any updates on this feature?

**Comment by nevermind89x** [comment]
Is this actually supported? Or was never implemented? Thank you! @jbetancur
