### ISSUE TITLE
Have expanded row content be sub-table aligned with parent columns

### ISSUE THREAD

**Issue by ashgh** [jbetancur/react-data-table-component#483]
I am trying to find out if it is possible to have the expanded row content contain a sub table or look like a sub table of child rows that are aligned with the column cells. Is this possible? Right now I have an expanded component that is rendering a table, but getting the styling to align with the parent is difficult. Wondering if there are some classes I can inherit or a better way to do this.

**Comment by luanpanno** [comment]
Hey, I know it's been past a year, but how did you fix it?

**Comment by sam17896** [comment]
Have expanded component as another datatable with noHeader and noTableHead
