### ISSUE TITLE
Pagination: Should force render pagination component

### ISSUE THREAD

**Issue by ghost** [jbetancur/react-data-table-component#484]
## Description
When data prop supplied to `DataTable` is an empty array, the Pagination component does not render.

In scenarios when user wants to handle pagination in the absence of data, it becomes impossible.

## Describe the solution you'd like
Add a simple `shouldShowPagination` prop to force render pagination component regardless of any related prop

**Comment by jbetancur** [comment]
Yea this should really be a feature - I will try to get this into the next minor release
