### ISSUE TITLE
Long sentence will overflow the table cell after reduce window size

### ISSUE THREAD

**Issue by topex-psy** [jbetancur/react-data-table-component#487]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [ ] You installed `styled-components`
- [ ] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
Long sentence will overflow the table cell after reduce window size.

## To Reproduce
1. Put long sentence in one of the datatable cell, e.g. "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas a aliquam neque. Mauris ultricies volutpat ligula et rutrum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id nisi euismod."
2. Resize window to smaller size

## Expected behavior
I want the table cell content to be truncated by ellipsis or simply hidden in overflow area.

## Code Sandbox, Screenshots, or Relevant Code
![Untitled15b](https://user-images.githubusercontent.com/14989865/76920518-419cd300-68fe-11ea-859d-84f10865c977.png)
![Untitled15](https://user-images.githubusercontent.com/14989865/76920524-45305a00-68fe-11ea-90d9-330a39f1c2fd.png)

## Versions (please complete the following information)
 - React: 16.13.0
 - OS: Windows 10, Linux Ubuntu
 - Browser: Opera

**Comment by jbetancur** [comment]
What do your columns look like? You may also want to consider a custom Cell components that does what you need. Otherwise, you can control the truncation by using a `format` and `wrap` combo:

```js
  {
    name: "Name",
    selector: "name",
    format: row => `${row.name.slice(0, 10)}...`
   wrap: true,
  },
```


Take a look here if this helps: https://codesandbox.io/s/react-data-table-sandbox-custom-growwrap-9upub

I use that as a playground for working with cells width and it has the example above

**Comment by s-devaney** [comment]
You can also use a custom cell component to wrap your cell values in a div which enables ellipsis truncation.

`
		{
			name: "Name",
			cell: row => <div style={{textOverflow: "ellipsis", whiteSpace: "nowrap", overflow: "hidden"}}>{row.value}</div>,
		}
`
