### ISSUE TITLE
ExpanableRow stay open when I change the page

### ISSUE THREAD

**Issue by FraFio** [jbetancur/react-data-table-component#488]
I may not have read the documentation well, but when I change the page with one or more expanablerow open, it remains open with the old data. Is there a way to close them when I change the page?

**Comment by Intelliflex** [comment]
MAke sure you have a unique key value for each row

Mike Thomson
Intelliflex Software
Ph: 0431 817772

________________________________

**Comment by FraFio** [comment]
> MAke sure you have a unique key value for each row 


I tried to insert keyfield both as attribute of datatable and as attribute of expanablecomponent, the result does not change ... wrong approach??
