### ISSUE TITLE
When update data in expanablerow

### ISSUE THREAD

**Issue by FraFio** [jbetancur/react-data-table-component#489]
inside expanablerow, I receive data from props.data. these data inside are modified or deleted through my calls to the server. these calls in turn modify the data of props.data. is there a way to update the data without reloading the page or component? like using a callback on the row?

I use react 16 and redux 4

**Comment by jbetancur** [comment]
Are the calls modified per `expandableComponent`? I would think you could just use React state in each component and make the calls there and just re-render for that individual component
