### ISSUE TITLE
Missing types selectable

### ISSUE THREAD

**Issue by VictorHAS** [jbetancur/react-data-table-component#492]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
Property 'selectableRowsComponent' and 'selectableRowsComponentProps' does not exist on type  IDataTableProps

## Code Sandbox, Screenshots, or Relevant Code
https://codesandbox.io/s/react-data-table-sandbox-rlszy

**Comment by jbetancur** [comment]
Nice catch will fix
