### ISSUE TITLE
Pagination with number

### ISSUE THREAD

**Issue by kiennguyen278** [jbetancur/react-data-table-component#493]
Hi Jbetancur,
i'm very interest this component, it is useful,
however, i don't know how to setting pagination with number, as: 1,2,3,4....
is it possible to do that? or if it is not available, could you make this pagination

Thank you so much.

**Comment by jbetancur** [comment]
Do you mean like bootstrap? You can develop your own custom Pagination Component. Here is an example using material ui:

https://jbetancur.github.io/react-data-table-component/?path=/story/pagination--custom-component-material-ui

**Comment by smammadov1994** [comment]
But how?! I have been trying to understand the documentation. What do we have to do to get the pagination with numbers. I do not understand after countless days of trying...
