### ISSUE TITLE
conditionalRowStyles does not work when update needed

### ISSUE THREAD

**Issue by atadevos** [jbetancur/react-data-table-component#495]
## conditionalRowStyles does not work in some cases
When conditionalRowStyles is used the data table is not updated in some cases because of React.memo.
For example if you have a simple table and want to highlight some row or rows when appropriate url variable set while using react-navigation (in this example "highlightedRow")
Suppose you have this kind of conditionalRowStyles

```
        [
            {
                when: row => {
                    return parseInt(row.id, 10) === parseInt(this.props.match.params.highlightedRow, 10)
                },
                style: {
                    backgroundColor: 'ghostwhite',
                },
            },
        ]
```

and suppose there is a link inside some cell that will navigate to the page with some other highlighted row

                cell: row => {
                        const path = generatePath("<path>/:highlightedRow?", {
                            highlightedRow: <highlightedRowId>
                        });
                        return <Link to={path}>Click to go to row</Link>
                }
after clicking the link the page url changes the table is redrawn but the conditionalRowStyles does not work because of the table rows does not redrawn, because of nothing changed in the specified row
One need to change something in the row to be redrawn.

**Comment by jbetancur** [comment]
Could you sandbox this? This would help me to track down the issue much faster.

https://codesandbox.io/embed/react-data-table-sandbox-ccyuu

**Comment by atadevos** [comment]
Yes, sure, here is the link

https://codesandbox.io/s/react-data-table-sandbox-5lvjo

**Comment by jbetancur** [comment]
Instead of adding conditional styles to the constructor, you can try breaking it out into its own method.  This will force RDT to re-render since each time the function is invoked it will have a new reference. 

Can you try:

https://codesandbox.io/s/react-data-table-sandbox-test-conditionalrowsre-render-2gvhu

**Comment by atadevos** [comment]
Oh, thanks for nice solution. It surely solves the problem.
