### ISSUE TITLE
Radio selection for selectableRows

### ISSUE THREAD

**Issue by Ownmarc** [jbetancur/react-data-table-component#497]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

Not a problem

## Describe the solution you'd like

Make it possible to enable radio selectable rows. Something similar to this https://www.lightningdesignsystem.com/components/data-tables/#Single-row-selection

## Describe alternatives you've considered

Could probably work something with selectableRowsComponent, but I think this should be easier then that.

## Additional context

No

**Comment by jbetancur** [comment]
This would not be hard to do if we add a new prop for the native checkbox type=radio. The only caveat will beT. That being said `indeterminate` state with radio buttons won't work.

If you need something more custom then `selectableRowsComponent` is where it's at.

**Comment by Ownmarc** [comment]
@jbetancur out of curiosity, how could I do it using selectableRowsComponent ?

I've managed to make the type of the checkbox radio, but not sure how to force only 1 option to be selected at a time. Where should I manage the state and how can I pass it to have this behavior ?

![image](https://user-images.githubusercontent.com/24617457/77687876-83202480-6f75-11ea-91f5-078a2b22a60b.png)

**Comment by jbetancur** [comment]
I may have misunderstood. Do you want to have radio buttons but only be able to select one radio at a time? 

This actually would be quite a bit more effort to implement.

**Comment by Ownmarc** [comment]
Yes, the goal would be to only let the user the choice of selecting 0 or 1 line, but not multiple line. When a new line is selected, it unselects the previous one if there was one and select the new one.

See this for example : https://www.lightningdesignsystem.com/components/data-tables/#Single-row-selection

**Comment by kishore075** [comment]
Any update on how to select single radio button, i tried by setting element.allSelected = false;
      element.selectedCount = 1;
      element.selectedRows.length = 1;
but on second click it doesn't work

**Comment by Ownmarc** [comment]
@kishore075 I think it is not directly possible from the props. May have to use the onChange of the selected and do something to update the selected rows by yourself. Thats what I plan to do.

**Comment by kishore075** [comment]
@Ownmarc thansks for your response i written like onSelectedRowsChange={this.handleRowSelected.bind(this)}

 private handleRowSelected(element) {
      element.setSelectedValue = [element.selectedRows[0]];
      element.selectedRows.splice(1)
      
      element.allSelected = false;
      element.selectedCount = 1;
      element.selectedRows.length = 1;
  } 

it works for one time and second time when i choose second radio button onchange event is not getting trigger and upon 3rd radio button choosing it triggers and reset to one

**Comment by Ownmarc** [comment]
Pretty sure the "element" you are changing is a state and should not be updated directly like this. I didn't dive into this just yet, lets keep each other updated here if we find something working. 

I still think it would be a greate feature to have for this projet.

**Comment by kishore075** [comment]
Yes having single selection option will be very great feature to have in, I understand "element" is state object but how to update that state object in my local file. I thought of updating like above help me with some suggestion if you thought of any I am stuck for 2 day now

**Comment by Ownmarc** [comment]
@kishore075 i'll check it tonight and update

**Comment by kishore075** [comment]
thats great thank you!!!

**Comment by kishore075** [comment]
I am using import Radio from "@material-ui/core/Radio";
with DataTable props as below
selectableRowsComponent={Radio}

**Comment by Ownmarc** [comment]
> I am using import Radio from "@material-ui/core/Radio";
> with DataTable props as below
> selectableRowsComponent={Radio}

Thats only for the "appearance" of the button to select, it doesn't apply to logic of a radio-group

**Comment by kishore075** [comment]
yeah on selected change i have written my logic to reset to one

onSelectedRowsChange={this.handleRowSelected.bind(this)}

private handleRowSelected(element) {
element.setSelectedValue = [element.selectedRows[0]];
element.selectedRows.splice(1)

  element.allSelected = false;
  element.selectedCount = 1;
  element.selectedRows.length = 1;
}

this code i placed in above comment too

**Comment by Ownmarc** [comment]
i'm seeing something possible with selectableRowSelected . I think that the onChange should update your data and that in your data you should be specifying if a row is selected or not. I'll get it to work tonight

**Comment by Ownmarc** [comment]
Got it, here is how I did it:

My data has a isSelected property, they are all false at first.

Then you need to set a function to handle changes in your DataTable Props and tell it to check for the isSelected like this : 
```
onSelectedRowsChange={handleRowSelected}
selectableRowSelected={(row) => row.isSelected}
```

Here is my handleRowSelected function : 

```
const [dataForTable, changeDataForTable] = useState(null)
const handleRowSelected = (whatsChanging) => {
    if (!isEmpty(whatsChanging.selectedRows[0])) {
      setFolderToFetch(whatsChanging.selectedRows[0].folder)
      changeDataForTable((prevState) =>
        prevState.map((row) => {
          console.log(row)
          if (whatsChanging.selectedRows[0].id === row.id) {
            row.isSelected = true
          } else {
            row.isSelected = false
          }
          return row
        })
      )
    } else {
      setFolderToFetch(null)
      changeDataForTable((prevState) =>
        prevState.map((row) => {
          row.isSelected = false
          return row
        })
      )
    }
  }
```

**Comment by kishore075** [comment]
wow thats great, you made my day I will try to implement and let you know if any issues i face.

**Comment by kishore075** [comment]
Hi I dont see this property getting imported, do i need to import any controls for this property row.isSelected 

I tried to maintain in state but that doesn't work

**Comment by Ownmarc** [comment]
Its a property of datatable

**Comment by kishore075** [comment]
![Untitled](https://user-images.githubusercontent.com/63319261/78732445-7eedf280-78f7-11ea-92a9-597f1dcca26e.png)

**Comment by Ownmarc** [comment]
Oh it has to be a property you add to your data, it can be anything

**Comment by kishore075** [comment]
I am getting properties in screenshot from list and i tried to send RequestID which even i used in sortField above, is that i need to add boolean variable in my list
![Capture](https://user-images.githubusercontent.com/63319261/78732826-98dc0500-78f8-11ea-9f3f-1597522bcca7.JPG)

**Comment by kishore075** [comment]
![Capture](https://user-images.githubusercontent.com/63319261/78732964-f1130700-78f8-11ea-8e6d-16262059f6e0.JPG)

**Comment by kishore075** [comment]
[DataTable.txt](https://github.com/jbetancur/react-data-table-component/files/4447659/DataTable.txt)

This is my code please let me know if i miss something

**Comment by kishore075** [comment]
[DataTable.txt](https://github.com/jbetancur/react-data-table-component/files/4447666/DataTable.txt)
This is my code, please help if i miss something

**Comment by kishore075** [comment]
[DataTable.txt](https://github.com/jbetancur/react-data-table-component/files/4447673/DataTable.txt)
This is my code, please help if i miss something

**Comment by prasadregula** [comment]
i am also facing the same type issue. could you please help when we can except the release for this fix

**Comment by Ownmarc** [comment]
SelectableRowSelect need to be given a true or false for each row. It has to be a property in the data you are passing to the table.

**Comment by kishore075** [comment]
Yeah i created as below 

const columns = [
  { name: 'AWARD #', selector: 'RequestID', sortable: true },
  { name: 'AWARD GIVER', selector: 'Title', sortable: true },
  { name: 'AWARD RECIPIENT', selector: 'RecName', sortable: true },
  { name: 'DEPARTMENT', selector: 'ReqDEPT', sortable: true },
  { name: 'ATTRIBUTE', selector: 'AwardAttribute', sortable: true },
  { name: 'isSelected', selector: 'isSelected', cell: row => false }
];

and this is my rowchange function

private handleRowSelected = (rowChanging) => {
    try {
      if (rowChanging.selectedRows[0] != null) {
        this.state.searchslicedAwarditems.map((item) => {
            if (rowChanging.selectedRows[0].ID === item.ID) {
              item.isSelected = true;
            } else {
              item.isSelected = false;
            }
            return item;
          });
      }
    }     
  }

It sets to true based on selection but it doesn't reset to one i checked your code you are using prevstate is that makes difference in my code

**Comment by Ownmarc** [comment]
You map function returns an array. You need to update the state with this new array. I am wrapping my map function with the changeDataForTable to update the state. The prevState is simply giving me access to the previous state to set the new one.

**Comment by kishore075** [comment]
@Ownmarc Thanks for your help but i am really sorry i am not getting the output as expected

Error: TypeError: changeDataForTable is not a function

[SingleSelection.txt](https://github.com/jbetancur/react-data-table-component/files/4448707/SingleSelection.txt)

Attached my code I am using as you been used. Please review my code and help me

**Comment by Ownmarc** [comment]
changeDataForTable is my function to update my data that are a state. You must use the function to update your searchsliceAwarditems

**Comment by kishore075** [comment]
Sorry I am not getting it, this is my 3rd day I am working on this. Would you mind sending me the changeDataForTable to me. So i change my code accordingly

**Comment by kishore075** [comment]
Hi one more question in columns

I need to hide second column ("Is Checkbos Disabled") but i need that column to disable checkbox to be chosen based on my status from other column i tried hide, omit but still i get column in my datatable


const rowDisabledCriteria = row => row.selectedAwardStatus;

selectableRowDisabled={rowDisabledCriteria}

const columns = [
  { name: 'AWARD #', selector: 'RequestID', sortable: true },
  { name: 'Is Checkbos Disabled', selector: 'selectedAwardStatus', cell: row => 
                                                                          <div>
                                                                            { row.AwardStatus.toLowerCase().trim() =="Approved".toLowerCase().trim() || 
                                                                              row.AwardStatus.toLowerCase().trim() =="Rejected".toLowerCase().trim() ? 
                                                                              row.selectedAwardStatus = true : row.selectedAwardStatus = false
                                                                            }
                                                                            </div>
                                                                          },
  { name: 'AWARD STATUS', selector: 'AwardStatus', sortable: true },
  { name: 'AWARD GIVER', selector: 'Title', sortable: true },
  { name: 'AWARD RECIPIENT', selector: 'RecName', sortable: true }, 
  { name: 'DEPARTMENT', selector: 'ReqDEPT', sortable: true },
  { name: 'ATTRIBUTE', selector: 'AwardAttribute', sortable: true }
];

**Comment by kishore075** [comment]
![Capture](https://user-images.githubusercontent.com/63319261/78850897-3a348b00-79cd-11ea-8ff6-cbd74867a922.JPG)
When I install styled components my app doen't work in IE, any suggestions

**Comment by anaskhan23** [comment]
@kishore075 Did You get any solution to select single entry (radio) instead of checkbox?

**Comment by ivanThePleasant** [comment]
@Ownmarc Thanks for the code! It certainly works for me as intended, however I am confused about the prevState here. Looking at React hooks documentation, they don't support prevState. And yet you are using it. Where is it coming from? Is it the same prevState as in componentDidUpdate lifecycle? Also, I'm slightly confused as to why prevState.map is passed in as an expression (as in it is not wrapped in {} after "(prevState) => " ). If I write above code this way, I get an error "Can't read property map of undefined: 

changeDataForTable((prevState) => {  // <---
        prevState.map((row) => {
          if (whatsChanging.selectedRows[0].id === row.id) {
            row.isSelected = true
          } else {
            row.isSelected = false
          }
          return row
        })
     }) // <---
    } else {
      changeDataForTable((prevState) => { // <---
        prevState.map((row) => {
          row.isSelected = false
          return row
        })
      }) // <---
    }

Would be glad if you could explain this to me, thank you.

**Comment by feiraelectronica** [comment]
anyone have the solution for this?

**Comment by feiraelectronica** [comment]
Already removed from To do list? will this be fixed then?

**Comment by slimandslam** [comment]
This is a high priority for our project. We want to be able to select just one row unambiguously.

**Comment by feiraelectronica** [comment]
> This is a high priority for our project. We want to be able to select just one row unambiguously.

hm same goes to me, really need this asap

**Comment by jbetancur** [comment]
I hear you guys. I'd like this feature as well. But just as much I'd like to write it for you, I'd like just as much to have the time to implement it 😉. 

I'm going to try my very best and move this feature back into alpha ver 7(next). But the implementation is not a trivial task. 

I appreciate that you rely on this project but it's just me working on this for the time being unless someone wants to take a shot at a PR that has a sound implementation.

**Comment by slimandslam** [comment]
I'd rather contribute money as my React chops are not up to this task (probably obvious :-) ). I'd also like to point out that we needed the single row selection so badly, that I was going to find a different table project, but then I realized that we could implement single row selection by using two columns with buttons (each button does something different to the row data). In the future, though (Sept/Oct?), we'll need to move to a radio button with a menu selection.

**Comment by slimandslam** [comment]
Is there a temporary workaround where you use your current checkboxes, but you just add a prop to your table component that lets the user choose "single selection only", so then your code automatically de-selects all other checkboxes when a user selects a checkbox?
So, just a a prop like:    checkbox=single || normal   (normal is default)
You could even add the CSS necessary to make the square checkboxes into circles. 
As long as it looks and works like a radio button, who cares?

**Comment by jbetancur** [comment]
Yea, that's sort of implementation at a high level. For the radio button, you can do that already by using `selectableRowsComponentProps={{ type: 'radio' }}`, or by passing in your own Radio Component from some library.

I actually (finally) had some time this afternoon to take a peek at the implementation and I think it may not be too bad. I should be able to turn something around in a few days at most. Stay tuned...

**Comment by jbetancur** [comment]
OK! THis is the basic usage:

```js
<DataTable data={yourData} columns={yourColumns} selectableRows selectableRowsSingle selectableRowsComponentProps={{ type: 'radio' }} />
```
`selectableRowsComponentProps` can also be a Radio button from another lib. For example material-ui

I just need to wrap up the tests and I should be able to cur alpha-14 version tonight.

**Comment by slimandslam** [comment]
Is v7 backwards compatible to the current version (outside of new features, obvi).

**Comment by jbetancur** [comment]
@slimandslam about 98%. Please check all the v7 release notes on the releases page for breaking changes.  

I don't plan on back-porting to v6 since v7 is pretty close to being done.

**Comment by jbetancur** [comment]
@slimandslam There is a bit of a bug atm. You can't deselect a single select row. I'm going to push a v7-alpha-15 in a few.

**Comment by feiraelectronica** [comment]
Hi @jbetancur , i tried the solution you provide

this is my code 
`<DataTable
            columns={columns}
            data={decryptMenuAttrib.searchResult.filter((WLRec, index, self) => self.findIndex(t => t.ENTITY_ID === WLRec.ENTITY_ID) === index)}
            noHeader={true}
            onSelectedRowsChange={this.updateState}
            selectableRows
            selectableRowsSingle={true} 
            keyField="ENTITY_ID"
            customStyles={customStyles}
            pagination
            selectableRowsNoSelectAll
            paginationPerPage={10}
            paginationRowsPerPageOptions={[5, 10, 25, 50, 100]}
          />`

but the output is still the same. did i missed out anything?

![image](https://user-images.githubusercontent.com/72189108/121834560-aad9e480-cd01-11eb-9212-5bf9c14f1326.png)

**Comment by feiraelectronica** [comment]
Hi @jbetancur ,

I tried it, but it not working. i'm not sure what do i do wrong.

here is my code

` <DataTable
            columns={columns}
            data={decryptMenuAttrib.searchResult.filter((WLRec, index, self) => self.findIndex(t => t.ENTITY_ID === WLRec.ENTITY_ID) === index)}
            noHeader={true}
            onSelectedRowsChange={this.updateState}
            selectableRows
            selectableRowsSingle={true} 
            keyField="ENTITY_ID"
            customStyles={customStyles}
            pagination
            selectableRowsNoSelectAll
            paginationPerPage={10}
            paginationRowsPerPageOptions={[5, 10, 25, 50, 100]}/>`

and here is the output 

![image](https://user-images.githubusercontent.com/72189108/121837391-0ad38980-cd08-11eb-81f0-ed1284b351a8.png)

and this is my package.json. already updated to the latest version

![image](https://user-images.githubusercontent.com/72189108/121837434-263e9480-cd08-11eb-864f-fb16cbf92c80.png)

Thank you John

**Comment by slimandslam** [comment]
Where is this prop?
`selectableRowsComponentProps={{ type: 'radio' }}`

**Comment by feiraelectronica** [comment]
> Where is this prop?
> `selectableRowsComponentProps={{ type: 'radio' }}`

you reply to me is it? i also tried to use that. but still

![image](https://user-images.githubusercontent.com/72189108/121839027-b8946780-cd0b-11eb-9842-7342a6e9a01e.png)

![image](https://user-images.githubusercontent.com/72189108/121839041-c21dcf80-cd0b-11eb-8a70-ffaeeff63368.png)

**Comment by slimandslam** [comment]
Just a thought, try removing 
`selectableRowsNoSelectAll`

**Comment by feiraelectronica** [comment]
> Just a thought, try removing 
> 
> `selectableRowsNoSelectAll` 

Also tried it 😅 and still. You tried yours? Is it working?

**Comment by feiraelectronica** [comment]
> ```js
> ```js
> <DataTable data={yourData} columns={yourColumns} selectableRows selectableRowsSingle selectableRowsComponentProps={{ type: 'radio' }} />
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

when i copy exactly like this code, it become like this

![image](https://user-images.githubusercontent.com/72189108/121847341-01075180-cd1b-11eb-8f0c-e9f990813426.png)

**Comment by jbetancur** [comment]
Are you 100% positive that you updated your dependancies? 

Try deleting your node_modules and re running npm install or yarn if you use that. If you use npm also delete package-lock.json

**Comment by feiraelectronica** [comment]
hi @jbetancur , finally it works. thank you so muchhhhh.

**Comment by feiraelectronica** [comment]
hi @jbetancur , sorry to bother you again. my onSelectedRowsChange only trigger once. 

![image](https://user-images.githubusercontent.com/72189108/122000506-83f2df80-cde1-11eb-92d6-37aa2777483c.png)

i put the alert in this function, but it only trigger one time. if i check another box, this will not trigger.

**Comment by feiraelectronica** [comment]
> hi @jbetancur , sorry to bother you again. my onSelectedRowsChange only trigger once.
> 
> ![image](https://user-images.githubusercontent.com/72189108/122000506-83f2df80-cde1-11eb-92d6-37aa2777483c.png)
> 
> i put the alert in this function, but it only trigger one time. if i check another box, this will not trigger.

anyone have the same problem?

**Comment by edoteee** [comment]
> > hi @jbetancur , sorry to bother you again. my onSelectedRowsChange only trigger once.
> > ![image](https://user-images.githubusercontent.com/72189108/122000506-83f2df80-cde1-11eb-92d6-37aa2777483c.png)
> > i put the alert in this function, but it only trigger one time. if i check another box, this will not trigger.
> 
> anyone have the same problem?

I am facing the same issue. The function triggers only when I deselect the previous selected checkbox

**Comment by danirupe** [comment]
Same issue

**Comment by jbetancur** [comment]
Please open a new ticket with a code sandbox showing the issue, please. There is a code sandbox link when you open a new issue in the template.  Also, note that I rarely if ever check closed tickets.

**Comment by feiraelectronica** [comment]
> Please open a new ticket with a code sandbox showing the issue, please. There is a code sandbox link when you open a new issue in the template. Also, note that I rarely if ever check closed tickets.

Hi @jbetancur, i already created a new ticket. Here you go. #837

Thank you.

**Comment by AlexanderPershin** [comment]
Hello,
I know that question was asked long time ago, but maybe my info will be useful for someone
First I used two props
```
onSelectedRowsChange={(e) => onVideoSelected(e)}
selectableRowSelected={rowSelectCritera}
```
where
```
const onVideoSelected = (data) => {
    setSelectedVideosList([data.selectedRows[0]]);
};
```
And
```
    const rowSelectCritera = (row) => {
        const selected = selectedVideosList.filter((item) => {
            const isSelected = item._id === row._id;

            return isSelected;
        });
        return selected.length > 0;
    };
```
Therefore only one row is selected at the time and click on header "Select all" checkbox will lead to only first row selected
Also I used Radio component instead of checkbox
```
import Radio from "@material-ui/core/Radio";
...
// And add prop to table component
selectableRowsComponent={Radio}
```
