### ISSUE TITLE
Show div in custom cell on row hover

### ISSUE THREAD

**Issue by AndrewSB** [jbetancur/react-data-table-component#499]
I'm trying to show a div inside a custom cell when the row is being hovered on.

In my custom cell I can figure out if the cell is being hovered on since I own that div. I can't figure out the right way for me to add an event listener on the row and then forward mouse{enter, leave} to the cell so it can decide to show the div or not.
Basically I want to access the row div from within the custom cell, how would you recommend doing that?
My apologies if this is super obvious and done with basic js/css, independent of this library. Thank you for your work 😄

**Comment by jbetancur** [comment]
NP! 

So you just need to add a custom cell and whatever mouse event you need. The events do not need to bubble up

I just created a custom div that is centered vertically and takes up 100% space, but this is totally up ro you as it is a custom cell:
```js
    cell: row => (
      <div
        style={{
          display: "flex",
          alignItems: "center",
          height: "100%",
          width: "100%"
        }}
        onMouseEnter={() => console.log("hey!!")}
      >
        {row.title}
      </div>
    )
```

Here is a basic sandbox I setup showing that you can do this with a custom cell. Feel free to adapt it to your use case:

https://codesandbox.io/s/react-data-table-sandbox-cell-with-listener-7ni9e

**Comment by AndrewSB** [comment]
ahh, super simple. thanks!
