### ISSUE TITLE
Pagination isn't working with Chrome but work well with Microsoft Edge

### ISSUE THREAD

**Issue by Kamez** [jbetancur/react-data-table-component#500]
Pagination isn't working with Chrome but work well with Microsoft Edge.

I used Chrome version 80.0.3987.149 (Windows 10 64-bit) and it's not show pagination but when I open it via Microsoft Edge it shows the pagination. 

Can you check it ?

**Comment by Phonbopit** [comment]
@Kamez I just found the same issue today when zoom in/out of the browser, but for 100% display it's working fine.

The problem is `display: table` of the table wrapper, so I resolve by custom style by change `display: block`

```js
import DataTable from 'react-data-table-component';

const customStyle = {
  tableWrapper: {
    style: {
      display: 'block'
    }
  }
};

const MyComponent = () => (
  <DataTable
    title="Hello"
    columns={columns}
    data={data}
    customStyles={customStyles}
  />
);
```

Hope this help.

**Comment by jbetancur** [comment]
@Phonbopit thanks for the additional context - will investigate. `display: table` has been troublesome, to say the least but it is needed to support horizontal responsiveness.

**Comment by jbetancur** [comment]
I'm really curious if display: grid solves the issue as well.

**Comment by jbetancur** [comment]
I am getting more reports on this issue so bumping it up in priority. Basically, zoom in/out and pagination disappears
