### ISSUE TITLE
Table with lots of columns unable to scroll horizontally

### ISSUE THREAD

**Issue by baymac** [jbetancur/react-data-table-component#502]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
I am trying to use the table with a lots of columns (~20-30). Since 20-30 columns wouldn't fit the viewport of a normal laptop screen. I have used `Paper` Component of material ui to wrap the `React Data Table` Component. The Paper is styled with `overflow: scroll`. Now the table is horizontally scrollable within the Paper component but it still leaves a big right margin. 

### Here is the code:

```html
<Paper style={{ overflow: 'scroll', width: "70%" }}>
    <DataTable
        title={'CSV Sample Data'}
        columns={getTableColumns(querySampleResults[0])}
        data={getSampleJson2(querySampleResults)}
     />
</Paper>
```

### Here are a few screenshots of the problem:

When table is not rendered:

<img width="1678" alt="Screenshot 2020-03-31 at 4 17 19 PM" src="https://user-images.githubusercontent.com/23079344/78019280-09b97500-736d-11ea-972f-395f57979fb8.png">

When table gets rendered:

<img width="1678" alt="Screenshot 2020-03-31 at 4 32 46 PM" src="https://user-images.githubusercontent.com/23079344/78019405-4be2b680-736d-11ea-80d9-86bcb4c529c3.png">

You can see that editor and other elements are stretched. Btw the table is rendered below so cannot be seen in the screen, so a little scrolling looks like:

<img width="1678" alt="Screenshot 2020-03-31 at 4 40 16 PM" src="https://user-images.githubusercontent.com/23079344/78020237-b516f980-736e-11ea-9e8d-053a9e134177.png">

My guess is the table is wrapped inside paper so it is horizontally scrolling but it still takes up some that amount of space which looks like a big right margin. But inspecting it, I see it is not a right margin of table, inside some blank space in the <div> element which wraps the Paper. 

<img width="1680" alt="Screenshot 2020-03-31 at 4 46 48 PM" src="https://user-images.githubusercontent.com/23079344/78020624-687fee00-736f-11ea-9690-6e57d28aabac.png">

I am not sure what is the issue, some css can fix this issue or it some issue with this library?

## Code Sandbox, Screenshots, or Relevant Code
Please include a codesandbox to help **expedite** troublshooting.

https://codesandbox.io/embed/react-data-table-sandbox-ccyuu

Otherwise, add screenshots and/or complete sample code to help explain your problem.

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+)
 - Styled Components
 - Browser [e.g. chrome, safari, firefox]

**Comment by jbetancur** [comment]
Honestly, it's hard to tell without the complete picture and surrounding CSS, but the issue may be the surrounding elements. Is there anyway you could dupe this in a sandbox?  You can use this one for reference that I use to troubleshoot uses cases similar to yours:

https://codesandbox.io/s/react-data-table-sandbox-custom-growwrap-9upub

**Comment by baymac** [comment]
Hi @jbetancur, thanks for the reply. I am using an underlying private repo that provides a container to render my react components so I think it has issues. Not sure what it could be exactly. I tested with a few other table libraries and ended up with the same overflow issue. I will close this issue for sometime and get back after some testing.
