### ISSUE TITLE
A ghost column and warning inside console  browser

### ISSUE THREAD

**Issue by AlAnwari-ari** [jbetancur/react-data-table-component#503]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [ ] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
Thank you for this amazing library, this lib help me a lot of stuff to complete and save my time.
I have 2 issues. 
1. there is a column that im not initialize inside `const column`. I guess this is an index value but somehow this value pop up in my table. 

![image](https://user-images.githubusercontent.com/53512385/78032698-9ffe9280-738f-11ea-81b1-ab0fb619670f.png)
desc: the most left column

`
const columns = [
        {
            name: 'Kode Item',
            selector: 'code',
            sortable: true,
            center: true
        },
        {
            name: 'Nama Produk',
            selector: 'name',
            sortable: true,
            center: true
        },
        {
            name: 'Deskripsi',
            selector: 'description',
            sortable: true,
            center: true
        },
        {
            name: 'Qty',
            selector: 'qty',
            sortable: true,
            center: true,

        },
        {
            name: 'Satuan',
            selector: 'satuan',
            sortable: true,
            center: true
        },
        {
            name: 'Harga Beli',
            selector: 'harga_beli',
            sortable: true,
            center: true

        },
        {
            cell: row => <IconsContainerPODetail>
                            <MessageSquareEdit onClick={() => editModeProductPO(row.id)} size={size+15}/>
                        </IconsContainerPODetail>,
            center: true
        },
        {
            name : <Checkbox onChange={handleCheckAll} style={{transform:'scale(1.2)'}} />,
            cell: row => <Checkbox checked={row.isChecked} onChange={handleCheckChild} value={row.id} style={{transform:'scale(1.2)'}}/>,
            center: true
        }
    ]`
`<DataTable 
                columns={columns}
                data={data}
 />`

2. Second Issue is I got warning inside the console browser like this:

![image](https://user-images.githubusercontent.com/53512385/78033556-c113b300-7390-11ea-9ea2-974a8d3daab6.png)
I guess this warn belong to datatable component. 

Thank you for your library and your time to see my issues. Sorry if my issues are beginner issue and maybe the problem is my fundamental about react because im new in react,  but im stuck and dont know what im gonna solve these and i hope somebody could help me. Thank you :)

## Code Sandbox, Screenshots, or Relevant Code
Please include a codesandbox to help **expedite** troublshooting.

https://codesandbox.io/embed/react-data-table-sandbox-ccyuu

Otherwise, add screenshots and/or complete sample code to help explain your problem.

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+)
 - Styled Components
 - Browser [e.g. chrome, safari, firefox]

**Comment by sridaradappt** [comment]
Yes, I too get the same extra column with the warning message in the console. Any help would be appreciated.

![image](https://user-images.githubusercontent.com/54019357/78040114-a0e1f500-738c-11ea-9271-958ed0f373fc.png)

**Comment by reginaldBarnabas** [comment]
I see the same issue since this morning in Chrome. How to remove this index column?

**Comment by jbetancur** [comment]
See https://github.com/jbetancur/react-data-table-component/issues/504
Short story update to 6.3.4

I accidentally tagged the wrong branch with a feature that was not ready for primetime.

**Comment by AlAnwari-ari** [comment]
thank you :)
