### ISSUE TITLE
How to hide the column

### ISSUE THREAD

**Issue by LuisGnzlz1** [jbetancur/react-data-table-component#504]
[](url)
![Screenshot](https://user-images.githubusercontent.com/8292814/78043544-17ed9e00-7339-11ea-98a2-87b6549be069.png)

How to hide or remove that column?

**Comment by reginaldBarnabas** [comment]
I see the same issue since this morning in Chrome. How to remove this index column?

**Comment by jbetancur** [comment]
RDT is not adding an arbitrary column with indexes. What is your code, versions, sandbox? More details would be appreciated.

**Comment by jbetancur** [comment]
I think I know what happened here. I may have accidentally tagged an experimental branch. patching now and releasing a 6.3.4

**Comment by jbetancur** [comment]
Ok this was a mistake on my part where I tagged the wrong branch when I published. Please update to 6.3.4 for a fix

**Comment by LuisGnzlz1** [comment]
thnaks bro
