### ISSUE TITLE
Clicking on expand button triggers form submit

### ISSUE THREAD

**Issue by RonyDkid** [jbetancur/react-data-table-component#506]
## Describe the bug
If the DataTable component is wrapped in a form tag, it will trigger the submission of that form. 

## To Reproduce
1. Wrap the <DataTable expandableRows /> component in a <form> tag
2. Click on the expand icon

## Expected behavior
Clicking on the expand icon shouldn't trigger a form submit. It should only collapse the table row.

## Code Sandbox, Screenshots, or Relevant Code
Please include a codesandbox to help **expedite** troublshooting.

https://codesandbox.io/s/react-data-table-sandbox-gl5f0

Otherwise, add screenshots and/or complete sample code to help explain your problem.

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+)
 - Styled Components
 - OS: any
 - Browser: any

**Comment by jbetancur** [comment]
Ihanks for catching this.  The fix is simple enough to add `type="button"` to the expander. I'll get a hotfix for this out soon.

**Comment by jbetancur** [comment]
This also happens with pagination buttons

**Comment by RonyDkid** [comment]
> Ihanks for catching this. The fix is simple enough to add `type="button"` to the expander. I'll get a hotfix for this out soon.

Thanks for the tip!

**Comment by jbetancur** [comment]
NP - 6.3.5 has the fix
