### ISSUE TITLE
Pagination buttons should be of type=button so it doesn't send forms by default

### ISSUE THREAD

**Issue by slcastroj** [jbetancur/react-data-table-component#508]
## Issue Check list
- [X] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [X] Read the README
- [X] You are using React 16.8.0+
- [X] You installed `styled-components`
- [X] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
Pagination buttons have no type specified, so when you put a table with pagination inside a form, the form gets submitted as the default behavior for a button inside a form is to submit it.

## To Reproduce
1. Create a form element with an onSubmit handler
2. Put a Datatable inside, with pagination enabled and some data so you can use pagination
3. Change page, the form gets submitted and the onSubmit handler gets called

## Expected behavior
Form doesn't get submitted

## Code Sandbox, Screenshots, or Relevant Code
https://codesandbox.io/s/react-data-table-sandbox-s58hd

## Versions
 - Sandbox versions
 - Firefox Developer

**Comment by jbetancur** [comment]
This has been addressed in #506  and #507 

You just need to upgrade to 6.3.5 for the fix
