### ISSUE TITLE
[FEATURE]: Is there any way to make a column position fixed ?

### ISSUE THREAD

**Issue by dytra** [jbetancur/react-data-table-component#510]
@## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

I want to make a quick datatable so I use react-data-table-component
but the problem is my client want the last of the column position to be fixed 
Is there any way to do this with react-data-table-component?

## Describe the solution you'd like

a boolean prop in the column object. eg :

```json
{
  "name": "column",
  "fixed": true,
}

```

## Describe alternatives you've considered

css snippets hint would also help

## Additional context

Refference : https://engineering.shopify.com/blogs/engineering/building-data-table-component-react

**Comment by jbetancur** [comment]
Going to be honest here in that I not certain that this feature will be supported anytime soon as I have quite a backlog of things. I'm very open to PR's if they make sense.
