### ISSUE TITLE
selectableRowsNoSelectAll property is missing on index.d.ts

### ISSUE THREAD

**Issue by gnomewoood** [jbetancur/react-data-table-component#513]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [ ] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
While using the react-data-table-component with TypeScript, I noticed the following issue.

Property `selectableRowsNoSelectAll` is missing in interface `IDataTableProps<T>`
I suggest to correct the `index.d.ts` as below.

```javascript
export interface IDataTableProps<T> {
  ...
  selectableRowsNoSelectAll?: boolean;
}
```

## To Reproduce
1. Add `selectableRowsNoSelectAll` property to the DataTable component in typescript project.
2. Then you can see the error:
```
[...]
  Property 'selectableRowsNoSelectAll' does not exist on type 'IntrinsicAttributes & 
IDataTableProps<DictStringNumber>'.
```

## Expected behavior
Possibility to use the `selectableRowsNoSelectAll` with typescript project.

## Versions (please complete the following information)
 - React 16.12.0
 - Styled Components 5.0.0
 - OS: macOS
 - Browser Chrome 80.0.3987.149

**Comment by jbetancur** [comment]
fixed in 6.4.0
