### ISSUE TITLE
Support rtl from prop

### ISSUE THREAD

**Issue by net-bet** [jbetancur/react-data-table-component#514]
Hi,

The lib determines rtl, via searching a root with an rtl direction settings.
But sometimes you can change direction through the DOM so this behavior might not be always accurate.
Is there a possibility to option to pass the direction direcly via rtl or direction prop on the table?
It will help for whoever uses a direction context, so he can jast map the direction context value to this prop and keep the behavior he wants 

I also saw this approach in other libs in react.

**Comment by jbetancur** [comment]
This will be available in 6.6.0
