### ISSUE TITLE
Bulk Editing: Similar to gmail

### ISSUE THREAD

**Issue by prasannavijayan** [jbetancur/react-data-table-component#518]
## Feature Check list

- [X] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [X] Read the README to ensure the feature is not already present
- [X] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [X] Considered the value versus complexity for all users of the library as well as library maintenance
- [X] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

Fantastic library, Thanks for this and I have been using data-table for a sometime now and I would like to propose this feature. In RDT (Selectable Rows), if user checks to select all items, it selects all the items in the table irrespective of items. If user checks to select all items, it selects only the visible ten or perPage items and user will be prompted in context menu with "Select all 146 data" similar to gmail.

## Describe the solution you'd like

I have made minor changes and deployed in https://rdtc.netlify.com/?path=/story/general--kitchen-sink. Please check "Visible Selectable Rows". to see this feature.

## Describe alternatives you've considered

I tried to extend this library and write it but I thought it's a nice feature to enable only if sortServer is true.

**Comment by jbetancur** [comment]
Thank you! This is a great feature request and one I've been thinking about this for some time.  

It should be pretty easy to do this and introduce a way to make it opt in. I'll flag this as a feature into the next minor release.

**Comment by jbetancur** [comment]
Here is what I am thinking, let me know if you have additional thoughts:

- New property named `selectableRowsVisibleOnly` (we may rename that, but let's go with that for now)
- On sort, have a way to opt into having the selected rows clear out when sorted. UX best practice is to invalidate the view state when it changes, but I want RDT to be unopinionated in this sense.
- On sort with `sortServer` always clear out the selected items

**Comment by jbetancur** [comment]
I created a PR for this, but I still need to add all the tests later today before it is merged.

Feel free to try for yourself:
https://github.com/jbetancur/react-data-table-component/pull/520

**Comment by jbetancur** [comment]
This will be available in 6.5.0 which will be published sometime this week.
