### ISSUE TITLE
Custom sort icon not animating

### ISSUE THREAD

**Issue by vinayp21** [jbetancur/react-data-table-component#519]
## Issue Check list

Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)- Yes
Read the README - Yes
You are using React 16.8.0+ -Yes
You installed `styled-components` -yes

## Describe the bug
As per the documentation using the component as sortIcon which returns  a down arrow svg icon.
The Icon gets displayed on the table next to the column title, but on click the sortIcon doesn't update to indicate ascending or descending sort.

## To Reproduce
1. Once the table renders click on column to sort with custom sort icon

## Expected behavior
Custom sort Icon should animate on click of sort (column title)

## Code Sandbox, Screenshots, or Relevant Code

**Data table component**-  
<DataTable
        title="List"
        columns={columns}
        data={data}
        sortIcon={<ChartTableSortIcon />}
      />

**custom sort component** - 

const ChartTableSortIcon = () => {
  return <img src={sortDownArrow} alt="collapsed" className="chart--table-sort-icon" />;
};

## Versions (please complete the following information)
React: 16.12.0
Styled Components: 5.0.1
OS: MacOS
Browser: Chrome

**Comment by cliffordp** [comment]
FYI: I could not reproduce this issue with all the same except React 16.9.0

**Comment by jbetancur** [comment]
@vinayp21 I am also unable to duplicate this. Can you provide a codesandbox?

https://codesandbox.io/embed/react-data-table-sandbox-ccyuu

**Comment by vinayp21** [comment]
Hi, I am actually trying to replace material icon(import SortIcon from "@material-ui/icons/ArrowDownward";) with a custom sort component - 

import React from "react";
import sortDownArrow from "../../images/icon_downarrow_black.svg";

const ChartTableSortIcon = () => {
  return <img src={sortDownArrow} alt="collapsed" className="chart--table-sort-icon" />;
};

export default ChartTableSortIcon;

**Comment by jbetancur** [comment]
This will not work with img as the logic looks for the usual i or svg tags. In any case, you will want to pass in SVG as a React component.

For example, convert your svg file to look like this (the icon here is something else):
```js
import React from 'react';

export default () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
    <path d="M7 10l5 5 5-5z" />
    <path d="M0 0h24v24H0z" fill="none" />
  </svg>
);
```

**Comment by vinayp21** [comment]
Thanks, issue is resolved
