### ISSUE TITLE
[FEATURE]: Sticky Table Header

### ISSUE THREAD

**Issue by ashgh** [jbetancur/react-data-table-component#526]
## Feature Check list

- [x ] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [ x] Read the README to ensure the feature is not already present
- [x ] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [ x] Considered the value versus complexity for all users of the library as well as library maintenance
- [ x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

Would like the ability to have a sticky header as the page scrolls instead of just the table body. The current fixed header and fixed height will make the table body scrollable separate from the page scroll. 

## Describe the solution you'd like

Ability to have a sticky header that works with page scroll instead of just table body scroll.

## Describe alternatives you've considered

overriding head row style to use position: sticky and top: 0, but no luck. Suspect because it is inside a flex box that it is not working.

**Comment by jbetancur** [comment]
Yea this has been a thorn in my side. The whole fixed header thing needs to be refactored, but it's a lot of work and I have not had the time lately. I'll flag this as a feature so it doesn't go stale. There is an existing issue as well that I will link as a dupe.

**Comment by jbetancur** [comment]
I should have fixed this a while back `fixedHeader` should now work correctly. https://github.com/jbetancur/react-data-table-component#header
