### ISSUE TITLE
Styled component not working in IE 11[DESCRIPTION]

### ISSUE THREAD

**Issue by kishore075** [jbetancur/react-data-table-component#528]
![Capture](https://user-images.githubusercontent.com/63319261/78851829-a7e1b680-79cf-11ea-9a57-67cb0176208c.JPG)
npm install --save styled-components

With out styled component this component is not working and if I install it works in chrome and not in ie 11. 

I have polly fill installed and all other were working after installing polly fill

Please advice

![Capture](https://user-images.githubusercontent.com/63319261/78851296-4e2cbc80-79ce-11ea-8575-da56b8135d6f.JPG)

**Comment by jbetancur** [comment]
Take a look here https://github.com/styled-components/styled-components/issues/2190 and see if that is relevant still.

Basically, you need to make sure that you are importing your polyfills into the index of your app for old browsers like IE11

**Comment by kishore075** [comment]
Hi Thanks for your response, unfortunately still it doesn't work. Without using styled components I mean without this data grid I can load my app in IE. But with this data grid I couldn't, i use pollyfill to load my app in IE and it was working any help is appreciated
