### ISSUE TITLE
detectRTL method breaks when server side rendering

### ISSUE THREAD

**Issue by erikt9** [jbetancur/react-data-table-component#532]
The `detectRTL` method uses `document` which will not be available when rendering in a server side environment.  Probably allowing the user to specify RTL as a prop as suggested by #514 and skip the `document` check if the prop is present is the best solution.  
My use case is enabling pagination which breaks when server side rendered because it always calls the detectRTL method (both with / without the paginationServer property).

**Comment by jbetancur** [comment]
Sure, since there is a duplicate can you close this and just comment on the existing issue?

**Comment by jbetancur** [comment]
implemented in 6.6.0
