### ISSUE TITLE
map function inside a single cell

### ISSUE THREAD

**Issue by razked** [jbetancur/react-data-table-component#535]
It would be great if I could map an array inside my data to present it's content inside a cell to show more than one item.
something like this:

![Untitled-1](https://user-images.githubusercontent.com/39411034/79058106-0d54d200-7c72-11ea-8ca4-a22753c21360.jpg)

**Comment by jbetancur** [comment]
You can:
https://jbetancur.github.io/react-data-table-component/?path=/story/custom-cells--example-1
https://github.com/jbetancur/react-data-table-component#columns

This is what custom cells do:

```js

const columns = [
...
  {
    name: 'Genres',
    
    cell: row => <div>{row.genres.map((genre, i) => <div key={i}>{genre}</div>)}</div>,
  },
...
];
```

**Comment by razked** [comment]
Thank You :)
