### ISSUE TITLE
TypeError: styled_default.div is not a function.....

### ISSUE THREAD

**Issue by surajmdl** [jbetancur/react-data-table-component#537]
I am getting some kind of error while using this component. Kindly see the screenshot for error detail. Below is the code which I'm using.

--------Installed Component-------------
npm i react-data-table-component
npm install react-data-table-component styled-components
-------------------Below is the code-----------------------------------------------

`import React, {Component} from 'react';
import DataTable from 'react-data-table-component';

const data = [{id: 1, title: 'Conan the Barbarian', year: '1982'}];
const columns = [
  {
    name: 'Title',
    selector: 'title',
    sortable: true,
  },
  {
    name: 'Year',
    selector: 'year',
    sortable: true,
    right: true,
  },
];

export default class DataTable2 extends Component {
  render() {
    return <DataTable title="Arnold Movies" columns={columns} data={data} />;
  }
}
`

![React Data Table Component Error](https://user-images.githubusercontent.com/11940579/79078074-819b7e00-7d23-11ea-9891-3f69b30c5a00.jpeg)

**Comment by jbetancur** [comment]
I think you are using React Native or something similar. RDT and styled-components only support cases when you are rending in the web DOM or SSR

**Comment by surajmdl** [comment]
Yes

> I think you are using React Native or something similar. RDT and styled-components only support cases when you are rending in the web DOM or SSR

Yes. I am using React Native for Mobile App. I am testing this in Android Mobile. Please help me.

**Comment by jbetancur** [comment]
@surajmdl unfortunately, to make this work all HTML tags would need to be converted to React native `Views`

I think you may be conflating two things here. React Native is meant to have components that map to the native UI components for mobile platforms whereas RDT is designed specifically for the browser.

Furthermore, while RDT is responsive enough for web layouts on modern mobile devices it is by no means a mobile library. It would be cool to develop one though if I had the time/need or if someone wanted to contribute.

Closing this for now as I am not sure that I can help, but I hope this answers your question.

**Comment by surajmdl** [comment]
> @surajmdl unfortunately, to make this work all HTML tags would need to be converted to React native `Views` and even then mobile/web may not map well.
> 
> I think you may be conflating two things here. React Native is meant to have components that map to the native UI components for mobile platforms whereas RDT is designed specifically for the browser.
> 
> Furthermore, while RDT is responsive enough for web layouts on modern mobile devices it is by no means a mobile library. It would be cool to develop one though if I had the time/need or if someone wanted to contribute.
> 
> Closing this for now as I am not sure that I can help, but I hope this answers your question.

So, For displaying tabular data (Data table)in mobile app react native what component I can use?

**Comment by surajmdl** [comment]
Kindly provide me solution. I'm new in Mobile app development.
