### ISSUE TITLE
Suspected bug in striped styling

### ISSUE THREAD

**Issue by net-bet** [jbetancur/react-data-table-component#542]
Hi,

when I set custom style like this:

  rows: {
    stripedStyle: {
      backgroundColor: 'purple',
    },
  },

I get purple color for the even row, and not for the odd row, which is the stripe row.

the problem, when I try to set now the color for the even row, it also affecing the even row, so de facto I can't control the striped grid styling:

  rows: {
    style: {
      backgroundColor: 'yellow',
    },
    stripedStyle: {
      backgroundColor: 'purple',
    },
  },

the background yellow has not affect, I just get the same result as before.

If I just set the style background color to be yellow, then again, it affects every even row.

  rows: {
    style: {
      backgroundColor: 'yellow',
    },
  },

I tried several other variations, always same result (in the styles.js the stripedStyle is under row/style, so I also tried this)

**Comment by jbetancur** [comment]
Can you post this in a code sandbox? Also keep in mind the striped styling uses css nth selectors so make sure you are doing something similar to what is built into styles.js

**Comment by net-bet** [comment]
Ok, indeed it was my mistake, I didn't consider the css selector as part of the style object hierarchy.
Thanks !
    stripedStyle: {
      **'&:nth-of-type(odd)': {**
        backgroundColor: 'purple',
      },
    },
