### ISSUE TITLE
[On the fly column.omit change feature]: [user can select from dropdown which columns he want to see & hide the remaining]

### ISSUE THREAD

**Issue by kartiknegandhi** [jbetancur/react-data-table-component#543]
Basically i need a custom dropdown from where i can select the columns to be shown and hide the others which are not required.(This should work even after the data has been loaded.) If that wasn't required, then columns.omit would have sufficed by requirement.Any hints or suggestions,pl let me know.
Thanks in advance

**Comment by jbetancur** [comment]
You can do this with you existing array of columns by adding them to react state. Then Use your drop down to setState on  columns with an omit however you need. If you want the drop down to feel more I integrated you can look at subHeaderComponent and subHeader
