### ISSUE TITLE
Styling Sortable Columns Only

### ISSUE THREAD

**Issue by net-bet** [jbetancur/react-data-table-component#546]
Hi,

When I set customStyles for activeSortStyle and inactiveSortStyle, they apply also for the non sortable columns.

In the default implementation of the library, there are those conditions that guarantees for some of the styles to apply only on sortable styles (but some of them appear to affect, I assume it is intended).

  &:hover {
    ${({ column }) => **column.sortable** && 'cursor: pointer'};
    ${({ column, theme }) => **column.sortable** && theme.headCells.activeStyle};
    span,
    span.__rdt_custom_sort_icon__ * {
      ${({ sortActive, column }) => !sortActive && **column.sortable** && 'opacity: 1'};
    }
  }

Is there a possibility to give the sortable and non-sortable different css classes, so it could be controlled in the costomStyles level?

[To be more specific, I don't need those styles on the none sortable columns at all, which seems reasonable according their names, though it is matter of opinion, and obviously will be a breaking change.]

**Comment by jbetancur** [comment]
Can you wire up a https://codesandbox.io/s/ccyuu to make sure we are on the same page on this issue?

**Comment by net-bet** [comment]
https://codesandbox.io/s/react-data-table-sandbox-yo0c3?file=/src/index.js

You can see in the example, that the runtime head cell gets the styling of activeSortStyle and inactiveSortStyle despite it is not sortable. I am not sure this is a desired behavior (also in cases no custom styling is declared, it has some of the sortable attributes), but anyway it would be nice if could be worked around.

Thanks !

**Comment by net-bet** [comment]
Hi, What about it? do you think it is something can be added?

Thanks!
