### ISSUE TITLE
Customize every columns header : Is there a way to customize ever columns header?

### ISSUE THREAD

**Issue by bhatvikrant** [jbetancur/react-data-table-component#547]
## Feature Check list

- [ ] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [ ] Read the README to ensure the feature is not already present
- [ ] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [ ] Considered the value versus complexity for all users of the library as well as library maintenance
- [ ] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

A clear and concise description of what the feature is.

**Comment by Samiam519** [comment]
I'm interested in this feature, has there been any update?
