### ISSUE TITLE
[FEATURE]: Is there anyway to move the pagination to the top of the table?

### ISSUE THREAD

**Issue by srinivasvardhan** [jbetancur/react-data-table-component#551]
## Feature Check list

- [ ] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [ ] Read the README to ensure the feature is not already present
- [ ] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [ ] Considered the value versus complexity for all users of the library as well as library maintenance
- [ ] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

I would like to display pagination at the top of the table, also I want to customize the pagination to show number like 1 2 3... instead of next icon. Is there any way to achieve this?

## Describe the solution you'd like

A position top attribute in the Datatable component props and a custom component

**Comment by jbetancur** [comment]
Yes. I've thought about this. I'll flag this as a future feature.

**Comment by diegodesouza** [comment]
@jbetancur would it be possible to have the pagination at the top and bottom option?

**Comment by jbetancur** [comment]
Yes, that is my thinking as well. There would be an option to have the pagination on top and bottom or top/bottom.  I've been quite busy so have not had time to pick this up. PR's are welcome (and with tests)

**Comment by amitpatel9169** [comment]
@jbetancur 
Is there any update on this in the new version?

**Comment by akaufman3** [comment]
@jbetancur Hi! Any progress on this? I see this PR was closed? https://github.com/jbetancur/react-data-table-component/pull/678
