### ISSUE TITLE
How can I access the current iteration inside columns?

### ISSUE THREAD

**Issue by bhatvikrant** [jbetancur/react-data-table-component#555]
I want to access the ROW INDEX

For example: 

```javascript
    const columns = [
			{
				name: 'Cook ID',
				selector: 'cook_id',
				sortable: true,
			},
			{
				name: 'Name',
				selector: 'name',
				sortable: true,
				cell: (row) => (
					// I want to access the current iteration here <------------------------
				),
			},
]
```

**Comment by jbetancur** [comment]
What do you expect with a row index? The current index? The sorted index? The static index?

Also, I am curious about your use case for having an index.

I've had other requests for passing the index back, the result will always be no matter what the sort is.

0
1
2
3
4
5
6
7
8
9
...

**Comment by bhatvikrant** [comment]
hey, thanks for the reply! I found the answer. I looped over my data and added an index field to it.

**Comment by bhatvikrant** [comment]
btw, with row index, I meant the current index of that element in that array.

**Comment by jbetancur** [comment]
glad you found a solution. That is what I usually recommend is to map an index field in.
