### ISSUE TITLE
[FEATURE]: Tooltip for column headers

### ISSUE THREAD

**Issue by MFarejowicz** [jbetancur/react-data-table-component#557]
## Feature Check list

- [X] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [X] Read the README to ensure the feature is not already present
- [X] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [X] Considered the value versus complexity for all users of the library as well as library maintenance
- [X] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

Somewhat? I'm developing a table where I'm trying to keep the column names short to save space, but this makes the meaning less obvious.

## Describe the solution you'd like

A tooltip on column name hover with additional text would be perfect. I could see an additional property being added to the columns object such as `tooltip` or `tooltipText` of type `string`, which when provided adds a tooltip that appears whenever you hover over the column name.

## Describe alternatives you've considered

I could have a legend explaining the columns before, after, or to the side of my table, but this is less intuitive and fairly space inefficient. 

I don't believe this is possible given the current props we can provide to the table (and if it can be, I'm not sure how), so it can't simply be an example in the documentation.

## Additional context

Example of a table that implements this behavior:
<img width="987" alt="Screen Shot 2020-04-27 at 12 34 37 PM" src="https://user-images.githubusercontent.com/10686713/80402410-7d26a780-8883-11ea-943b-c4ae87d2908f.png">

Thanks for your time!

**Comment by jbetancur** [comment]
I generally think we also need this feature, my concern is all the extra overhead to make this work. Like a lib that already does this adds deps. (Popper.js!?) Also how do I know when to show the tool tips. What about mobile? Can we opt in the overhead. Alternatively, I could allow you to set a title on the column header which moat browsers will convert to a top tip. The ux is clunky on the browser title based tool tips but its better than nothing.  I’m open to suggestions or ideas on implementing.
