### ISSUE TITLE
cahnge color of row on onRowClicked method

### ISSUE THREAD

**Issue by rupal-gt** [jbetancur/react-data-table-component#560]
There is option for conditional styles but there are no examples for this. I need to change color of row when onrowclick happend. Can anybody help is there any way to do that?

Also there is no example of conditionaltCell styles. How to use that?

**Comment by jbetancur** [comment]
https://jbetancur.github.io/react-data-table-component/?path=/story/conditional-styling--conditional-cells

**Comment by rupal-gt** [comment]
Thanks. got it.

**Comment by TinoOnline** [comment]
Hi, it seems that the example for conditional row stying is the same for cells and when attempting to apply the styling to a single cell, the entire row is styled. 

**example for conditional cells styling:**
https://jbetancur.github.io/react-data-table-component/?path=/story/conditional-styling--conditional-cells

**example for conditional row styling:**
https://jbetancur.github.io/react-data-table-component/?path=/story/conditional-styling--conditional-rows
