### ISSUE TITLE
[PaginationServerOptions not working as expected]

### ISSUE THREAD

**Issue by AronZeng** [jbetancur/react-data-table-component#561]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
I recently upgraded to the latest version and used the paginationServerOptions prop so that my selection can persist on page change. However, it seems like applying that prop did not achieve that. Below is component that I am rendering. 

`        <DataTable
          columns={tableColumns}
          data={ARRAY OF ITEMS}
          onChangePage={setPage}
          onChangeRowsPerPage={setLimit}
          onRowClicked={VIEW ITEM}
          onSort={setSort}
          pagination
          paginationServer={true}
          paginationDefaultPage={query.page}
          paginationTotalRows={totalCount}
          pointerOnHover
          progressPending={isLoading}
          selectableRows
          sortServer
          onSelectedRowsChange={handleSelectedRowsChange}
          noDataComponent={<WorkersTableEmptyState />}
          paginationServerOptions={{
            persistSelectedOnPageChange: true,
            persistSelectedOnSort: true,
          }}
        />`

Upon page change, my API renders a new set of items and upon selected rows change I store the values into state variables. Currently, upon a page change, the selectedRows are being cleared. I'm new to reporting issues so please let me know if anymore information is required from my end.

## To Reproduce
Shown above

## Expected behavior
Upon changing the page, the selectedRows should persist.
## Code Sandbox, Screenshots, or Relevant Code

Sample code shown above

## Versions (please complete the following information)
 - React (16.8.6)
 - Styled Components (4.4.0)
 - Browser [Chrome]

## Additional context
It seems that onSort, the selection also does not persist.

**Comment by jbetancur** [comment]
I am not able to dupe this. Can you confirm you are running at 6.9.0?

**Comment by AronZeng** [comment]
Hi @jbetancur thanks for your response. I was running 6.9.0 but just reinstalled and seemed to work now. Perhaps I just did some silly the first time in the process. 

Thanks for the help though, really appreciate it! 💯
