### ISSUE TITLE
Storybook: Filtering example does not work

### ISSUE THREAD

**Issue by cliffordp** [jbetancur/react-data-table-component#563]
Just a heads up that your Filtering example does not work as expected:
* 1min demo: https://share.getcloudapp.com/WnuGBG7x
* Storybook: https://jbetancur.github.io/react-data-table-component/?path=/story/filtering--example-1
* filtering code: https://github.com/jbetancur/react-data-table-component/blob/v6.9.0/stories/DataTable/Basic/Filtering.stories.js#L81

**Comment by jbetancur** [comment]
I think the assumption is that it filters case insensitive,  it does not. The code is not converting the text to lower case which is why it is not filtering. This is an easy fix to PR.

Btw thanks for the details and 1 min video - wish more issues were logged like that ;)

**Comment by cliffordp** [comment]
Ah! Totally didn't catch the casing. Maybe it's as simple as just adding the "case-sensitive filtering" to the demo?

**Comment by jbetancur** [comment]
Yup. Just a toLowercase In 2 places, on the filter input output and includes
