### ISSUE TITLE
[FEATURE]: Optional prop to always display the sort icons

### ISSUE THREAD

**Issue by diegodesouza** [jbetancur/react-data-table-component#567]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

Firstly, thank you for putting your time and effort into this work. So far this has been one of the best experience implementing a third party package. 
I would suggest having an optional prop that would always display the sort icons in the header. Currently this works on hover. 

## Describe the solution you'd like

A prop for the sort icon to either display on hover like the current implementation or have it always be displayed regardless of hovering or not. This way the user would know that that field is sortable from the get go.

## Describe alternatives you've considered

Selecting the fields manually and overriding the css. 

## Additional context

I believe it's a better user experience to have the icon alway be shown. This way the user knows what is and isn't sortable.

**Comment by jbetancur** [comment]
Hey, @diegodesouza! Thanks for logging a feature request. 

I'm not sure that I agree that this is the best UX though. Perhaps some solid working examples from other implementations? I do tend to stick to material design and have found IMHE that showing the sort icon other than on the selected column is confusing since only one column can be sorted at a time.
