### ISSUE TITLE
[FEATURE]: Support for rxjs/mobx properties

### ISSUE THREAD

**Issue by diegodesouza** [jbetancur/react-data-table-component#568]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

Right now I'm passing a `mobx` property of with an `@observable` decorator. 
This in turn gives me a `warning`

```
Warning: Failed prop type: Invalid prop `data` of type `object` supplied to `<<anonymous>>`, expected `array`.
    in Unknown (at Dashboard.js:208)
    in Dashboard (created by Context.Consumer)
    in withRouter(Dashboard) (at Layout.js:47)
    in Route (at Layout.js:45)
    in Switch (at Layout.js:19)
    in Route (at Layout.js:57)
    in Router (created by HashRouter)
    in HashRouter (at Layout.js:55)
    in div (at Layout.js:53)
    in Layout (created by inject-Layout-with-Store)
    in inject-Layout-with-Store (created by App)
    in Provider (at App.js:121)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp (at app/index.js:9)
``` 
## Describe the solution you'd like

Support multiple type of `Array` like attributes.

## Describe alternatives you've considered

N/A

**Comment by jbetancur** [comment]
Can you elaborate a bit more?  Do you have a codesandbox where you can demonstrate this? Admittedly, I am not that familiar with mobx. I can tall you the RDT takes an Array of objects as the data prop so not sure why that would not work.
