### ISSUE TITLE
Datatables Editor: Modals Which Allow Edit Of Clicked Or Selected Rows

### ISSUE THREAD

**Issue by doverradio** [jbetancur/react-data-table-component#572]
After seeing https://editor.datatables.net/ (Datatables Editor), I compared to your library but didn't see any examples showing modal pop up editing as they have in their [Custom form layout / templates (tags) example](https://editor.datatables.net/examples/simple/template.html).

Is this Custom form layout / templates (tags) example possible with your library?

**Comment by jbetancur** [comment]
@doverradio the goal of this library is to be as unopinionated as possible so you can use whatever ui library you want for things like modals. With RDT you can define custom components within cells using  `colums.cell`. If you want modals to pop in action buttons you can use the `subHeader` and `subHeaderComponent` props as well as `actions` and `contextActions` to embed buttons/components that call a modal.

In the future, I plan on adding some examples calling modals but the API should be straightforward.

**Comment by doverradio** [comment]
thank you so much for letting me know! Already adding new functionality.

Another question, I want to move the items that I have selected into an
object that I can send away to another API. How does one use these items
that got selected with a checkbox from the data table?

**Comment by jbetancur** [comment]
NP! 

You can find aa similar example here on using `onSelectedRowsChanged`
https://jbetancur.github.io/react-data-table-component/?path=/story/selectable-rows--selected-row-toggle

Basically, the `onSelectedRowsChanged` callback returns the selected rows.

Also documented here:
https://github.com/jbetancur/react-data-table-component#row-selection

**Comment by doverradio** [comment]
Wow!  Things are working fantastically for me now.  One thing I am stumped now on is how to get multiple buttons/fields (export to csv, filter text field) to appear together.  Can you help me?

(taken from [storybook export csv](https://jbetancur.github.io/react-data-table-component/?path=/story/export-csv--using-actions))  
How do I get export csv, which uses this...

```const actionsMemo = React.useMemo(() => <Export onExport={() => downloadCSV(data)} />, []);```

to be a button before or after the filtering example text field [found here in storybook](https://jbetancur.github.io/react-data-table-component/?path=/story/filtering--example-1)...

because when I put the datatable together like so:

```  <DataTable
                title={`Category: ${category.name}`}
                columns={columns}
                data={filteredItems}
                pagination
                paginationResetDefaultPage={resetPaginationToggle} // optionally, a hook to reset pagination to page 1
                subHeader
                subHeaderComponent={subHeaderComponentMemo}
                // actions={actionsMemo}
                selectableRows
                persistTableHead
              />```

If I uncomment `actions` it results in only the Export to CSV button to appear and the filter by text is no longer visible.  I want it so both appear and not only that but I want further options like export to PDF and eventually export to google sheets.  How can I accomplish this with this library?

**Comment by jbetancur** [comment]
actions and subHeaderComponent can take an array of components (make sure you key them) or just create a component that contains all your actions

for example:
```js
actions={[
  <Component1 key="button1" ..../>,
  <Component2 key="button2" ..../>,
]}
```

or

```js
actions={<MyComponentWithActions />}
```

or with fragments 

```js
actions={(
<>
  <Component1 ..../>,
  <Component2 ..../>,
</>
)}
```
