### ISSUE TITLE
Is it possible to use virtualized rendering?

### ISSUE THREAD

**Issue by UberMouse** [jbetancur/react-data-table-component#573]
From my investigation it appears the answer is no, react-data-table-component could not currently use virtualized-rendering to support rendering millions of rows at a time.

I just wanted to confirm there was nothing I missed. Some way to render the table body into a virtualized container.

**Comment by jbetancur** [comment]
Take look here. Someone managed to implement this. I would love to integrate this but I have not had the time

https://github.com/jbetancur/react-data-table-component/issues/496

**Comment by UberMouse** [comment]
Hmm, that only seems to be infinite scrolling? I don't see any virtualized rendering going on there unless I'm missing something. That's a requirement for us and we will have 10s to 100s of thousands of row items commonly.

**Comment by jbetancur** [comment]
Aren't those the same concept (I could be missing something too)? Infinite scrolling uses windowing to preload items as you scroll thus infinitely

**Comment by UberMouse** [comment]
I'm referring to something like [react-window](https://github.com/bvaughn/react-window) which only renders enough items to fill your viewport and updates what is rendered as you scroll. This is required to efficiently render tens of thousands of rows at once since you only have to pay the fixed cost of rendering however many are in your viewport.
