### ISSUE TITLE
Pagination not displaying in Chrome and Other Browsers

### ISSUE THREAD

**Issue by loyboy** [jbetancur/react-data-table-component#574]
The pagination list is no longer displayed in some Sections of my App. I believe some other developers are having the same issue. Please help thanks

**Comment by loyboy** [comment]
Hey Guys, Please i need a solution to this issue....Thanks

**Comment by Dragate** [comment]
Same problem here. Pagination has vanished from pretty much every datatable I've used it in. The pagination component seems to exist in the dom but is, unfortunately, hidden.

**Comment by jbetancur** [comment]
It's hard to help without any details or if you are not following the Issue [Issue Checklist](https://github.com/jbetancur/react-data-table-component/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) I've tried to duplicate this in Chrome, Firefox, and Safari latest versions with no luck. 

- What do you mean it disappears? On scrolling? On page? Steps to reproduce?
- What version of RDT were you using? 
- What browsers and versions?
- Can you duplicate this with a certain config only?  
- Have you tried to setup the issue? https://github.com/jbetancur/react-data-table-component/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

On the last button sometimes it's the components around the table that can cause this. eg some div component with whatever css that makes this worse etc...

**Comment by jbetancur** [comment]
Yea, it's a wrapping element that is the catalyst and I only see it in Firefox and Safari when I enclose the table in a flex element. @loyboy  and @Dragate can you confirm this is the case on your end?

```js
const Div = styled.div`
  display: flex;
`;

const BasicPaginationTable = () => (
  <Div>
    <DataTable
      title="Movie List"
      columns={columns}
      data={data}
      pagination
    />
  </Div>
);
```

**Comment by jbetancur** [comment]
Please try updating to 6.9.2 and let me know if this solves your issues

**Comment by Dragate** [comment]
Fixed, indeed. Tyvm.

**Comment by AllenNguyen0417** [comment]
![image](https://user-images.githubusercontent.com/71422583/196846896-23ba3a15-31bb-44bf-8da0-312558bd68e4.png)
Does anyone know how to fix this issue? The pagination is displaying but not working.
    "react-data-table-component": "^7.5.3",
    "react-dom": "^18.2.0",
