### ISSUE TITLE
Allow a Select All Checkbox outside TableHeader: If a user checks off Table Header, he will no longer have access to the select all checkbox, can we create 

### ISSUE THREAD

**Issue by MohamedWael8** [jbetancur/react-data-table-component#576]
First thought that came to mind was the "useRef" and "useImperativeHandler" hooks, but I feel like there is a simpler method to solve this and I can't wrap my head around it.

**Comment by jbetancur** [comment]
You could try having your own select all control that syncs with `onSelectedRowsChange` which gives you the selected row state and then put that checkbox component anywhere you want.

I'm open to ideas on how to export parts of RDT using hooks, but have not had the time to invest.
