### ISSUE TITLE
Action buttons can't take a Fragment component

### ISSUE THREAD

**Issue by cliffordp** [jbetancur/react-data-table-component#584]
## Describe the bug
It seems the Action buttons can't take a component that wraps in Fragment.

## Expected behavior
I have an "Add Keyword" button component that is wrapped in a `<Fragment>`, which causes this error:
> Element type is invalid: expected a string

However, if I wrap with `<div>` or `<span>` instead, then it works.

## Code Sandbox, Screenshots, or Relevant Code
```js
const DtActions = ( { row, callbackOnceDeleted } ) => {
	return (
		<div>
			<ButtonAddKeyword /> // works if <div> or <span> but I want it to be <Fragment>
		</div>
	);
};
```

## Versions (please complete the following information)
 - React & ReactDOM both at 16.9.0
 - OS: Mac OS X
 - Browser: Chrome

## Additional context
Possibly related to https://github.com/jbetancur/react-data-table-component/issues/93

**Comment by jbetancur** [comment]
Does it work and you just get a warning?

**Comment by cliffordp** [comment]
No. It causes this console error:
> Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Does not work (but works if replace `<Fragment>` with `<div>`):
![image](https://user-images.githubusercontent.com/1812179/83224389-ec254380-a142-11ea-9485-d0dc6c2e11fe.png)

**Comment by Intelliflex** [comment]
What if you wrap with <></>

Mike Thomson
Intelliflex Software
Ph: 0431 817772

________________________________

**Comment by cliffordp** [comment]
Oh, wow, that worked. Why? I thought `<>` was just shorthand for `<Fragment>`?

I guess the empty tag comes through as a string but Fragment comes through as a component to render?

Is this a bug then? Or is it still correct to demand a string result instead of a component?

**Comment by jbetancur** [comment]
I'm not seeing this, but I don't see all of your code here.

Sandbox here: https://codesandbox.io/s/react-data-table-sandbox-fragment-9lgt1?file=/src/index.js

Can you dupe it there?

**Comment by cliffordp** [comment]
Thanks for getting that started.

So I _was_ able to get it working here: https://codesandbox.io/s/rdt-fragment-working-11tc0
But _not_ here: https://codesandbox.io/s/rdt-fragment-not-working-gqsth

I wonder if there's something with useMemo or the way the component call is structured... any ideas?

**Comment by jbetancur** [comment]
Yea weird. I think the difference is when you declare DTActions outside of App its just a function so where react expects a component <DTActions />, whereas useMemo or even not using useMemo works when you declare a component within App because it returns a react component. (check by console.logging out)

I wonder if this is something that can be answered better by looking at the React source code

**Comment by cliffordp** [comment]
OK, thanks.
