### ISSUE TITLE
How to get data row on button click row ?

### ISSUE THREAD

**Issue by cgarrotti** [jbetancur/react-data-table-component#585]
How to get data row on button click row ? 

![Capturar](https://user-images.githubusercontent.com/56283778/82845645-b7ec2180-9ebb-11ea-809c-75368abea91a.PNG)

**Comment by apoorv-kumar** [comment]
You might be looking for something like this - 

`const columns = [
{
    name: "Col1",
    selector: "col1",
    sortable: true
}, {
    name: "Col2",
    selector: "col2",
    sortable: true,
},
{
    name: "",
    cell: (row: any) => <button onClick={() => alert(row.col1) }>Editar</button>,
    ignoreRowClick: true,
    button: true
}
]`
