### ISSUE TITLE
Scroll bar takes up space in windows so cause disorientation of table

### ISSUE THREAD

**Issue by baymac** [jbetancur/react-data-table-component#586]
## Issue Check list
- [ x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x ] Read the README
- [x ] You are using React 16.8.0+
- [ ] You installed `styled-components`
- [x ] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## To Reproduce
Steps to reproduce the behaviour:
1. Access a windows system
2. Go to https://codesandbox.io/embed/react-data-table-sandbox-wf7n8?fontsize=14&hidenavigation=1&theme=dark
3. Scroll down in the table

## Expected behavior
In Mac the scrollbar doesn't take up space in the table data columns, but in windows it takes up space so the table is disoriented.

## Code Sandbox, Screenshots, or Relevant Code

https://codesandbox.io/embed/react-data-table-sandbox-wf7n8?fontsize=14&hidenavigation=1&theme=dark

On Windows:

<img width="777" alt="Screenshot 2020-05-27 at 11 44 14 AM" src="https://user-images.githubusercontent.com/23079344/82984292-7e2c2f80-a00f-11ea-921c-d59c14cedbb0.png">

On Mac:

<img width="777" alt="Screenshot 2020-05-27 at 11 45 26 AM" src="https://user-images.githubusercontent.com/23079344/82984352-a2880c00-a00f-11ea-8112-de5a5f5714d5.png">

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+)
 - Styled Components
 - OS: Windows
 - Browser Chrome

## Additional context
Is there a way to override windows scrollbar and not make it behave like in mac?

**Comment by jbetancur** [comment]
Thanks for including a code sandbox. This is an issue with the way `fixedHeader` is implemented and how the table is wrapped internally.  The short of it is that the way `fixedHeader` is designed needs to be re-thought. I think there are a couple open issues on this but I will flag this as an enhancement.

**Comment by baymac** [comment]
@jbetancur Can we use 
```
::-webkit-scrollbar {
  display: none;
}
```
If yes what class should this be applied in order for data table (without header row) scrollbar is hidden?

**Comment by TreyBastian** [comment]
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/virtualized-rows?file=/src/scrollbarWidth.js

This might be of interest.

**Comment by jbetancur** [comment]
This is FINALLY fixed  here https://github.com/jbetancur/react-data-table-component/pull/874

Available in 7.0.0-rc6
