### ISSUE TITLE
Edit text on table

### ISSUE THREAD

**Issue by incrusio21** [jbetancur/react-data-table-component#591]
how to change text on table? cause nothing happen when iam try use setState

`
editrow= (row) => {
        const { data } = this.state
// You can use setState or dispatch with something like Redux so we can use the retrieved data
        data.find(el => (el.id == row) ? el.last_name = '2000' : false)
        this.setState({
            data : data
        })
    };
`

but when i go to the next page n go back.. text has change

![Capture](https://user-images.githubusercontent.com/31911793/83330325-c45bea00-a2c0-11ea-944c-ca03b00f14ec.PNG)

**Comment by nekdev** [comment]
I was also wondering about this. How can we update row data without re-assigning the data array or at least keep table state like the current page and scrolling position when applying a new/updated data array.

**Comment by jbetancur** [comment]
This may help: https://github.com/jbetancur/react-data-table-component/issues/597

TableCells will only re-render if the data reference has actually changed. In Javascript, (and in general) to change the reference you need to produce a new array/object.
