### ISSUE TITLE
DataTable doesn't re-render when using with mobx-state-tree

### ISSUE THREAD

**Issue by kruyvanna** [jbetancur/react-data-table-component#595]
## Issue Check list
- [x ] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [ x] Read the README
- [x ] You are using React 16.8.0+
- [x ] You installed `styled-components`
- [ x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/s/sad-haslett-mq9lh?file=/src/App.js
)

## Describe the bug
DataTable doesn't re-render after state change

## To Reproduce
1. Click on Toggle button
2. Check the console, you can see the state change
3. DataTable doesn't re-render

## Expected behavior
DataTable should re-render after mobx-state-tree state changes

## Code Sandbox, Screenshots, or Relevant Code
https://codesandbox.io/s/sad-haslett-mq9lh?file=/src/App.js

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+): 16.12.0
 - Styled Components: 5.1.1
 - OS: MacOS
 - Browser: Chrome

**Comment by kruyvanna** [comment]
It works with below method:
https://github.com/mobxjs/mobx-react-lite/issues/290

**Comment by jbetancur** [comment]
Glad you figured it out. Is this something that we can document or PR into the Readme?

**Comment by kruyvanna** [comment]
That would be nice!

**Comment by MarcDAFrame** [comment]
This is a great fix for individual cells, however it doesn't work for rows, specifically using the conditionalRowStyles. Any thoughts on a work around for this?
