### ISSUE TITLE
beforeSelectedRowChange

### ISSUE THREAD

**Issue by Intelliflex** [jbetancur/react-data-table-component#598]
It would be nice to have a beforeSelectedRowChange() callback
In my case I want to allow rows to be selected until such time as a total accumulator reaches a certain value. If I go over that value then I do not want the checkbox checked.

[https://miteholdings-my.sharepoint.com/:i:/g/personal/miteholdings_miteholdings_onmicrosoft_com/ER_zPhVXRWpCmriG5Yr6kgsBVl7PEKpA6L90knWutmVBFg?e=JnpoDg](url)

**Comment by jbetancur** [comment]
You may be looking for `selectableRowDisabled`  which takes a callback against the data to determine if the row select should be disabled

https://github.com/jbetancur/react-data-table-component#row-selection

**Comment by jbetancur** [comment]
@Intelliflex I am just going over open tickets and I realized my answer is not what you were asking 😬 

I suppose we could have some call back that is exposed as you suggest to pre-check the number of rows checked.

**Comment by Intelliflex** [comment]
Thanks John,

I am working around this issue ok, I just try and avoid reiterating over table unless I have to.

Cheers Mike and thanks for the great library

Ps: At some stage I might package my crud (editor, entry grids ) library built around RDT. It would need to be reworked a bit to remove dependence on MDB (and is also functional component reliant, extensively using hooks) but would be a good side project to accompany RDT.

Mike Thomson
Intelliflex Software
Ph: 0431 817772

________________________________
