### ISSUE TITLE
multi-column sorting

### ISSUE THREAD

**Issue by Epicurean** [jbetancur/react-data-table-component#600]
Hi there, I love your library. It is very feature rich and simple to use. I am submitting this as more of a feature request, or a request for a way to implement using current features. Can we have multi-column sorting so that there is a primary, secondary, etc.. sort? If there is a way to do this with current features and usage of state that would be fantastic. Look forward to hearing from you.

Thanks

**Comment by jbetancur** [comment]
Thank you! And Thanks for the suggestion. Do you have examples of this being done elsewhere with other libraries that we can reference, or even some basic requirements/mock?
