### ISSUE TITLE
Custom cells rendering triggers React error

### ISSUE THREAD

**Issue by crapougnax** [jbetancur/react-data-table-component#601]
The given example in the doc [here](https://github.com/jbetancur/react-data-table-component#custom-cells) states that a custom rendering may be obtained with a function in the _cell_ key of a column definition.

This code generates either:
- a compilation error if _bold_ is not enclosed in simple or double quotes.
- a React Error (_Objects are not valid as a React child (found: object with keys {used}). If you meant to render a collection of children, use an array instead_)

## To Reproduce
1. add `cell: row => <div><div style={{ fontWeight: 'bold' }}>{row.title}</div>{row.summary}</div>` to any column definition
2. render table

## Expected behavior
Cell content should be rendered properly from the return of the function

## Versions (please complete the following information)
 - React 16.13.1
 - OS: MacOS
 - Browser: All

**Comment by jbetancur** [comment]
Thanks. will update the README. PR's welcome too.

**Comment by crapougnax** [comment]
Will definitely do when I have some time to analyze and propose a fix.
