### ISSUE TITLE
I need a little help changing data in rows dinamically

### ISSUE THREAD

**Issue by nicoloso100** [jbetancur/react-data-table-component#603]
Hello everyone, i have two columns in my table that interact each other:

![image](https://user-images.githubusercontent.com/31171164/84415430-5e346880-abd8-11ea-8ac7-e45b8b839946.png)

when you select a "Forma de pago", it will affect the column "Fecha vencimiento", for example if i select in "Forma de pago" the option "15 días", the "Fecha vencimiento" cell will change by adding 15 days to the date.

I will appreciate any idea to make this works, thank you so much

**Comment by jbetancur** [comment]
You’ll need to manage updating your data and then storing that in state. If your data changes rdt will rerender and achieve what you are looking for. This might be helpful: https://github.com/jbetancur/react-data-table-component/issues/597
