### ISSUE TITLE
Displaying lot of white space while scrolling right side

### ISSUE THREAD

**Issue by Altimetrik-Rahul** [jbetancur/react-data-table-component#604]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [ ] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
Displaying a lot of white space while horizontal scroll. 
This is my full screen here not showing white space
![image](https://user-images.githubusercontent.com/36156890/84493886-286dad80-acc6-11ea-9952-c6bf1e3482c6.png)
After scroll right side getting double white space
![image](https://user-images.githubusercontent.com/36156890/84494014-5fdc5a00-acc6-11ea-8af8-d2ca2d429da2.png)
using this for responsive 

`overflowY={true} responsive={true}`

and for all column using

` grow:0 `

## Expected behavior
White space should not display

**Comment by jbetancur** [comment]
Which browser/version. Version of rdt?

**Comment by Altimetrik-Rahul** [comment]
> Which browser/version. Version of rdt?

Chrome - Version 83.0.4103.61
RDT - 6.4.0

**Comment by jbetancur** [comment]
I would upgrade to 6.9.3 if possible and see if you still have the same issue. Some things with the TableBody layout changed that may help.
