### ISSUE TITLE
sortFunction column not work

### ISSUE THREAD

**Issue by GalAmiati** [jbetancur/react-data-table-component#605]
I have a problem with sorting numbers for example I have: **1, 22, 3, 4, 55, 6,7** etc..
Need to be **1,3,4,6,7,22,55**.
I tried to add sortFunction to the relevant column :

`          {
                name: 'Conv.T', selector: 'conversions_today', sortable: true, wrap: true, maxWidth: '40px',
                cell: row => row.conversions_today,
                sortFunction: (a, b) => a.conversions_today - b.conversions_today
            },
`

This function doesn't work, any ideas?
Thanks.

**Comment by Intelliflex** [comment]
Sound like you are sorting text as text field left to right. Use parseInt or parseFloat

Mike Thomson
Intelliflex Software
Ph: 0431 817772

________________________________

**Comment by GalAmiati** [comment]
@Intelliflex I tried to add parseInt to the sortFunction, but unfortunately the functino doesn't work at all..
 `{
                name: 'Conv.T', selector: 'conversions_today', sortable: true, wrap: true, maxWidth: '40px',
                cell: row => row.conversions_today,
                sortFunction: (a, b) => parseInt(a.conversions_today) - parseInt(b.conversions_today)
            },`

I Tried to add console log into the sortFunction and i didn't see nothing.

**Comment by FiveOFive** [comment]
I also ran into my sortFunction not being called. For me it was just an out of date package issue. The feature was just released on May 28th - https://github.com/jbetancur/react-data-table-component/releases/tag/v6.9.3
Updated and the custom sortFunction is now being called
