### ISSUE TITLE
clickable rows

### ISSUE THREAD

**Issue by doverradio** [jbetancur/react-data-table-component#606]
Is there a way to make it where anywhere on the row that you click it will open? Already I have it display link for each record but I want instead to click anywhere on the row and direct it to the same place my current link is pointing. I was checking in the story book but maybe I missed it.

**Comment by jbetancur** [comment]
If you mean click a row and expand then:
`expandOnRowClicked`

https://github.com/jbetancur/react-data-table-component#row-expander

**Comment by doverradio** [comment]
I don't think so.  I know row expander but it's not the one.  I'm trying to make it so by clicking on any part of the rectangle shape of the datatable row, even whitespace between the cells, that can trigger selection of that row.  The reason is I want to put a handler for that event which opens that item in a new page (my datatable represents various web pages per each row).  Can it be done?

**Comment by erikt9** [comment]
There's an `onRowClicked` property that I think does what you're looking for.

**Comment by jbetancur** [comment]
Marking this as resolved @erikt9 hit the nail on the head.

**Comment by a8t** [comment]
Are we willing to add a prop to change the TableRow element to an anchor tag that can receive a link? `onRowClicked` is not quite sufficient for making the table row an actual link. It would be as simple as adding a `rowProps` prop where a user can pass in `as` (for Styled Component) and `href`, etc.

reference: https://github.com/jbetancur/react-data-table-component/blob/master/src/DataTable/TableRow.js#L24

**Comment by feiraelectronica** [comment]
> rowWrapperProps

hi, do you have solution for this?
