### ISSUE TITLE
[FEATURE]: Option not to disable TableHeadRow when there's no data

### ISSUE THREAD

**Issue by philipnery** [jbetancur/react-data-table-component#612]
## Feature Check list

- [X] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [X] Read the README to ensure the feature is not already present
- [X] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [X] Considered the value versus complexity for all users of the library as well as library maintenance
- [X] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

We have buttons placed inside table row headers. 

Unfortunately, if the table has no data (and we're using `persistTableHead` BTW), it gets disabled so we can't anymore click the buttons inside.

## Describe the solution you'd like

Either we add another props for this or modify `TableHeadRow`'s `disabled` when `persistTableHead` is true.

Maybe something like this?

```javascript
                  <TableHeadRow
                    className="rdt_TableHeadRow"
                    role="row"
                    dense={dense}
                    disabled={progressPending || (data.length === 0 && !persistTableHead)}
                  >
```

##
Thanks,
Philip

**Comment by jbetancur** [comment]
Thanks for raising this. I've not has as much time as I'd like to work but I will try to get to it the next week. PR's are welcome if you'd like to contribute and get a fix in sooner.

**Comment by jbetancur** [comment]
I had a chance to take a lok. Can you share code or preferable a codesandbox https://codesandbox.io/embed/react-data-table-sandbox-ccyuu of how you are adding elements to TableHeadRow? 

TableHeadRow is meant to be internally controlled.

In any case, I think the disabled can be moved to `TableCol` `ColumnSortable` since it is the sort button that should be disabled or hidden if there is nothing to sort.

The

**Comment by mathieupetrini** [comment]
Thanks for your library.
Any updates on this ?

**Comment by jbetancur** [comment]
Implemented this in RDT `next` branch/alpha-6.
https://github.com/jbetancur/react-data-table-component/pull/776
