### ISSUE TITLE
Header has extra divs and extra space

### ISSUE THREAD

**Issue by kevinmamaqi** [jbetancur/react-data-table-component#614]
## Issue Check list
- [X] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [X] Read the README
- [X] You are using React 16.8.0+
- [X] You installed `styled-components`
- [X] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
The header of the table is generating new divs that cause a misalignment and weird spacing on it. See: https://imgur.com/YZmGCGQ

## To Reproduce
1. Create a new table
2. Put 4 columns and 89 rows.

Header styles defined in customStyles:
```
header: {
		style: {
			fontSize: "22px",
			color: defaultThemes.default.text.primary,
			backgroundColor: defaultThemes.default.background.default,
			minHeight: "56px",
			paddingLeft: "16px",
			paddingRight: "8px",
			textAlign: "left",
		},
	},
```

## Expected behavior
I expect it to have only one div for the header to properly style it. If it is not possible at least not have the space seen in clear blue in the picture..

## Code Sandbox, Screenshots, or Relevant Code
Screenshot and relevant code included above. I'm just using a basic example.

## Versions (please complete the following information)
 - React: 16.13.1
 - Styled Components 5.1.1
 - OS: [e.g. iOS] Mac OS
 - Browser: Chrome

## Additional context
It is shown in a TAB from material-ui

**Comment by jbetancur** [comment]
Do you have a codesandbox with a working example? I can't seem to duplicate this on my end.
