### ISSUE TITLE
How should I implement "selectallrows" when using the persist onpagechange feature? 

### ISSUE THREAD

**Issue by AronZeng** [jbetancur/react-data-table-component#616]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

I recently adopted the persist onpagechange feature. However, I would like to still be able to select all rows on the current page. How should this be done? I tried having a separate checkbox to add the rows to my "selectedrows" state but that doesn't seem to be doing what I need. The state is being updated properly but I need the other checkboxes to be checked when clicking on the "selectall" checkbox. 

I guess another way to word this would be how can I directly modify the state of the check boxes in every row of the table?

**Comment by AronZeng** [comment]
No longer need

**Comment by andikosumi** [comment]
@AronZeng What did you do in this case?
