### ISSUE TITLE
When having the columns array outside the component that renders the Grid, the table doesn't reflect data changes.

### ISSUE THREAD

**Issue by javier-brenes-gap** [jbetancur/react-data-table-component#621]
## Issue Check list
- [X] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [X] Read the README
- [X] You are using React 16.8.0+
- [X] You installed `styled-components`
- [X] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
I got a component that renders the Grid and I have the columns array in its own .js file, so I import the columns array into the component and pass it to the Grid. 
This component contains the data but when I modify it the table doesn't reflect my data changes.

## To Reproduce
1. Go to https://codesandbox.io/s/update-data-2csjw?file=/src/App.js
2. Click on the dropdown next to "Edit Stack" and select any stack-id
3. Add any text in a new line on the text area.
4. Click the "update data" button.

## Expected behavior
The grid should reflect the changes that were made by clicking the "update data" button

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+): 18.12.0
 - Styled Components: Yes
 - OS: [e.g. iOS]: Windows
 - Browser [e.g. chrome, safari, firefox] Chrome, Firefox, Opera

**Comment by jbetancur** [comment]
This is a JS/React specific usage issue. Instead of mutating the array, you need to pass a new one with the changes.

This will not work.
```js
    data[index].stack = selectedStack.stack;
    setData([...data]);
```
Also, see this pinned issue:
https://github.com/jbetancur/react-data-table-component/issues/597


As well as a working example based on #597 
https://codesandbox.io/s/update-data-31xcm?file=/src/App.js

**Comment by javier-brenes-gap** [comment]
thanks a lot!
