### ISSUE TITLE
Animations: How to add animations to Expandable Components?

### ISSUE THREAD

**Issue by nirmalhk7** [jbetancur/react-data-table-component#623]
## Feature Check list

- [ x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [ x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe
No
A clear and concise description of what the feature is.
How do you implement animation for expandable components? I'm not able to understand how to animate that expandable component so that the animation is more cleaner than what it looks on the storyboard

**Comment by jbetancur** [comment]
There is no easy way to do this via the API. The main reason I left out animations for the expander was performance. Having many cells/rows and expanding only compounds the issue. 

If someone has the time to figure out how to make this work and performance PR's are welcome.
