### ISSUE TITLE
react data  table lose input focus on change in cell

### ISSUE THREAD

**Issue by lakshmi24111990** [jbetancur/react-data-table-component#624]
on typing each character in Input text box  loosing focus on onchange . Can you Please help me on this as early as possible.

1. Click first input in a table cell
2. try to write more than 1 letter in input
3. check that input has lost focus

**Comment by prescottbreeden** [comment]
My team just ran into the same issue.  We were hoping to render one cell as editable text.  Using version 3.4.1.
