### ISSUE TITLE
[Column Omit]: Should allow a callback

### ISSUE THREAD

**Issue by jbetancur** [jbetancur/react-data-table-component#626]
columns[0].omit currently allows for a Boolean. It should also accept a callback that returns a boolean that has access to a data row. 

e,g

```js
...
{
  omit: row => row.somefield,
}
...
```

**Comment by neslxzhen** [comment]
excuse me, is this issue abandoned?

i need `row` to decide whether to hide the column.
or tell me with the best practice of overwriting the specified `row component`.

any help from anyone is greatly appreciated.
