### ISSUE TITLE
When pagination is selected screen goes white and app crashes

### ISSUE THREAD

**Issue by impactcolor** [jbetancur/react-data-table-component#631]
I have this strange issue.  It's hard to even debug it.
On an iphone, safari browser when I click on the pagination of a datable which contains about 200 records the screen will go white.  No error just goes white.  

I'm using `"react-data-table-component": "6.2.1",`

The only hint I get is in Chrome the warning:
`[Violation] 'click' handler took 224ms`

The data I'm using is about 212 objects with about 12 key / values each.  I wouldn't suspect that would be too much to cause a crash but maybe I'm wrong?

Appears each time I click on the pagination button.  Any ideas what's causing this?

**Comment by jbetancur** [comment]
I would suggest upgrading to the latest version of RDT. Also, I would suggest not having 200 records as that tends to slow the browser down. Lastly, you want to ensure the props you are passing to DataTable are memoized, otherwise, RDT will needlessly re-render. See the README for more info.

Other than that without sufficient code or a working example this would be difficult to troubleshoot.

**Comment by impactcolor** [comment]
Those are some great tips.  I’ll try that

**Comment by jbetancur** [comment]
Here's the link for performance optimization:
https://github.com/jbetancur/react-data-table-component#optimizing-for-performance-and-caveats

**Comment by impactcolor** [comment]
I've done the performance optimization.
Memoized and also using pagination of 50 for the records.  I also filtered the data so I only have the columns to display.  
```
        <DataTable
        progressPending={this.state.loading}
        columns={columns()}
        data={this.state.data}
        defaultSortField="last"
        sortIcon={<SortIcon />}
        pagination
        paginationPerPage={50}
        paginationRowsPerPageOptions={[25, 50, 100]}
        selectableRows
        selectableRowsComponent={Checkbox}
        selectableRowsComponentProps={{ indeterminate: isIndeterminate }}
        onSelectedRowsChange={this.updateState}
        selectableRowSelected={rowSelectCritera}
        />
```
I'm writing to the db (firebase) each time I get a hit so the user doesn't have to save.  Right now I rewrite the whole group of 200 records to the db. When `this.updateState` runs it gives me all the records.  Is there any way that I can just get the record that has been checked?  That way I can just run that record to the db as opposed to the whole lot.

**Comment by jbetancur** [comment]
I definitely need to understand your use case more. 

onSelectedRowsChange returns a list of selected rows which you can save to your component state, which you can filter on that and loop through the rows you want to update.
