### ISSUE TITLE
[FEATURE]: [Add the index to the cell function]

### ISSUE THREAD

**Issue by MGMike0** [jbetancur/react-data-table-component#633]
## Feature Check list

- [ +] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [ +] Read the README to ensure the feature is not already present
- [ +] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [ +] Considered the value versus complexity for all users of the library as well as library maintenance
- [+ ] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

I'm using the table, but we want to add the row number on the left of the table but there is no way to access this value.
It can also be used to call other information.

## Describe the solution you'd like

The Cell function receives only the row value, but it can change to be (row, rowIndex) 
## Describe alternatives you've considered

Counting on my own, adding the row index to my data and try to update it every time new data is added.

**Comment by jbetancur** [comment]
I think this should be easily possible - Ill add it as a feature. Can't promise a data but PR's are welcome 😉

**Comment by jbetancur** [comment]
https://github.com/jbetancur/react-data-table-component/pull/642

Implements rowIndex. on column: cell, selector and format
