### ISSUE TITLE
Responsive example?

### ISSUE THREAD

**Issue by blacksmoke26** [jbetancur/react-data-table-component#635]
Thanks for the plugin, I have some responsive issues on smaller screens

![image](https://user-images.githubusercontent.com/425744/88448628-36802380-ce59-11ea-8888-6240c67c981f.png)

Is there a proper responsive example I can follow?

**Comment by marlosirapuan** [comment]
I have a different problem about responsive..

![image](https://user-images.githubusercontent.com/802722/88462652-69d7a800-ce83-11ea-8f7b-14da70fe3d21.png)

column:
```
{
  name: 'CNPJ',
  selector: 'cnpj',
  sortable: false,
  hide: 'sm'
},
```

If I change 'sm' to any number (`hide: 10`), works..

**Comment by jbetancur** [comment]
@blacksmoke26 can you be more specific for that you are looking for?

Responsive for this lib means a few things.

- You can a horizontal scroll on the table if the width is too small
- you have the ability to hide columns using `hide`
- The pagination is more mobile friendly on smaller screens

**Comment by jbetancur** [comment]
@marlosirapuan Yea I need to fix that. A workaround, for now, is to use `hide: 'sm' as const`

**Comment by marlosirapuan** [comment]
> 'sm' as const

nice! worked! thank you 🥇

**Comment by blacksmoke26** [comment]
@jbetancur Sorry for the late response.

is there a way to split columns on small screens?

Like this one

```
Large screen (row):
+----+----+----+----+
+----+----+----+----+

Small screen (row):
+----+
+----+
+----+
+----+
+----+
+----+
+----+
+----+
```

**Comment by jonrrivera** [comment]
I am mainly looking to have media queries. Any way I can detent screen size and conditionally set the cell size?
