### ISSUE TITLE
Format function keep on executing after every second- generated 13K logs in  a minute 

### ISSUE THREAD

**Issue by choudharyamit34** [jbetancur/react-data-table-component#636]
format: row =>  <div>{ isMoment(row.newValue)? formatDate(row.newValue):row.newValue}</div>

am using format function for row cell s
![error](https://user-images.githubusercontent.com/13592283/88466586-75cb6600-ce93-11ea-98aa-ea2567ff7e91.PNG)

**Comment by jbetancur** [comment]
Can you provide a code sandbox for this? It’s hard to tell what the issue is with 1 line of code.
