### ISSUE TITLE
When table has many columns and scroll right, pagination section is moved and gets hidden eventually

### ISSUE THREAD

**Issue by robi-ng** [jbetancur/react-data-table-component#639]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [ ] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
When table has many columns, horizontal scroll is available. Initial load looks okay like below.
![image](https://user-images.githubusercontent.com/6182673/88885649-78e79d00-d26b-11ea-9775-cd20ffa6c4da.png)

However, when user scroll to the right, the pagination section get scrolled too and will eventually be hidden.
![image](https://user-images.githubusercontent.com/6182673/88885715-99175c00-d26b-11ea-8ab8-b8acdd84c2c7.png)

Is there any way to fix this?

## Expected behavior
Pagination section should not be scrolled along and should remain on the right.

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+): 16.13.1
 - Styled Components: 5.1.0
 - OS: Mac
 - Browser: Chrome

**Comment by wagnertimo** [comment]
Has anyone already created custom styles for this and wants to share it? 

Ideally as @robi-ng mentioned, it would be more preferable that the horizontal scrollbar is placed in the table section and not underneath the pagination section.

**Comment by seho0808** [comment]
This is the only bug that just made our team lose days of work to restart with another table component library

**Comment by Intelliflex** [comment]
You are using a free public source library that is excellent and well supported. It is not your job in a support forum to be complaining about your team losing hours of work and moving to another library. Be grateful there are people her who give their time freely and don’t deserve to be put down. This is the real world, accept problems and hours of bug solving and work arounds and embrace the learning, collaboration and satisfaction that resolution provides - or your in the wrong industry. My thanks go to John Betancur, RDT is an essential part of my app and I am very pleased with it.

Mike Thomson
Intelliflex Software
Ph: 0431 817772

________________________________

**Comment by jbetancur** [comment]
@seho0808 sorry you and your team lost days of work but last I checked this library is free and as @Intelliflex mentioned it's open-source and we do our best in our busy schedules to maintain, fix and improve it.

It must be "frustrating" that so many have built an open-source ecosystem out of their own time that you freely use and rely on. Instead of coming on here and complaining at least be constructive; you may even get some help. Even better, find the time contribute time back to the projects you are freely consuming.

Of course, you don't have to like or use this table library. So, if you found something that fits your needs better good for you.

**Comment by jbetancur** [comment]
@robi-ng @wagnertimo I may have a fix for this which involves something similar to your suggestion. It involves moving the Pagination outside of ResponsiveWrapper

```js
          </TableWrapper>
        </ResponsiveWrapper>

        {enabledPagination && (
          <div>
            <Pagination
              onChangePage={handleChangePage}
              onChangeRowsPerPage={handleChangeRowsPerPage}
              rowCount={paginationTotalRows || data.length}
              currentPage={currentPage}
              rowsPerPage={rowsPerPage}
            />
          </div>
        )}
      </DataTableProvider>
    </ThemeProvider>
```

I need to test this to make sure I didn't introduce any new bugs or regressions so hopefully I can have a fix soon

**Comment by jbetancur** [comment]
This has been fixed. Please update to 6.11.4

**Comment by seho0808** [comment]
My apologies. I will try to contribute next time instead of complaining.
