### ISSUE TITLE
change language

### ISSUE THREAD

**Issue by alimusavi67** [jbetancur/react-data-table-component#646]
is there any feature for changing table localization?

**Comment by alimusavi67** [comment]
paginationComponentOptions={{ rowsPerPageText: 'Filas por pagina', rangeSeparatorText: 'de' }}
this fixes my issue

**Comment by innv-imtinan** [comment]
i would like to localize columns headers e,g Name | Age | Gender,

**Comment by juninhodeluca** [comment]
1) Install i18next and react-i18next libraries and folllow de documentation to setup it.
2) On the DataTable columns definitions do something like that:

```
const columns = React.useMemo( () => [

        {
            id: 'username',
            selector: row => row.username,
            cell: row => row.username,
            name: props.i18n.t('columns.username'), // <--- 
            sortable: true,
            center: false
        },
        {
            id: 'createdAt',
            selector: row => row.createdAt,
            cell: row => row.createdAt,
            name: props.i18n.t('columns.createdAt'), // <--- 
            sortable: true,
            center: true
        }

        ....

], [ props ] )

3) Add the respective localization definition to the json

/src/i18n/locales/en.json 
```
{
    "columns": {
         "username": "User Name",
         "createdAt": "Created At",
     }
}
```
/src/i18n/locales/it.json
```
{
    "columns": {
         "username": "Nome Utente,
         "createdAt": "Creato da",
     }
}
```
That should work
