### ISSUE TITLE
[BUG] selectableRowDisabled + select all the rows

### ISSUE THREAD

**Issue by wrbutros** [jbetancur/react-data-table-component#650]
In the demo page:
https://jbetancur.github.io/react-data-table-component/?path=/story/selectable-rows--disabled-row-selection

If you press the checkbox to select all the rows, the counter shows "10 items selected",
even if given to the "selectableRowDisabled" condition only 8 rows get selected.

I guess when you press the checkbox to select all the rows, it just shows the total rows as counter,
without use the "selectableRowDisabled" criteria.

**Comment by jbetancur** [comment]
That is definitely a bug. Thanks for logging it.
