### ISSUE TITLE
[FEATURE]: Responsive expandable rows

### ISSUE THREAD

**Issue by Angelk90** [jbetancur/react-data-table-component#654]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

When I view the site on devices as a device, the table does not fit entirely so I have to scroll down the page.

So I use the responsive hiding columns technique, so I omit some columns, but I would like one or more columns to be displayed but using the expandable rows technique.

## Describe the solution you'd like

the solution would be that through an attribute defined in the columns, therefore with a dimension of type "sm" or "md", the columns are not hidden but given the possibility to define a component that allows them to be seen.

**Comment by Angelk90** [comment]
@jbetancur : Are there any news?

**Comment by Angelk90** [comment]
@jbetancur : Are there any news?

**Comment by Angelk90** [comment]
@jbetancur : Are there any news?

**Comment by Angelk90** [comment]
@jbetancur : Are there any news?

**Comment by cecicifu** [comment]
Same problem, any news ?
