### ISSUE TITLE
Conditional Row Styles Not Being Applied To All Cases

### ISSUE THREAD

**Issue by Julius-ERCM** [jbetancur/react-data-table-component#657]
I seem to be having an issue with the conditional row styling.
I follow the example in the storybook and my row styling only seems to be using the last "when" case and ignoring anything before it

`const conditionalRowStyles = (one, two) => {
  return [
    {
      when: row => row.value === one,
      style: {
        backgroundColor: '#21ba45',
        color: 'white',
      },
      when: row => row.value === two,
      style: {
        backgroundColor: 'orange',
        color: 'white',
      }
    }
  ]
}`

**Comment by vasuchawla** [comment]
if you are also using "stripped" attribute,

you need to add `!important` to your  background colors else the stripped's style's background color takes priority.

**Comment by jbetancur** [comment]
@Julius-ERCM before opening an issue please make sure you read: https://github.com/jbetancur/react-data-table-component/issues/387

Since https://github.com/jbetancur/react-data-table-component/releases/tag/v6.11.1

striped rows are no longer generated via css so make sure you are using 6.11.1+.
