### ISSUE TITLE
[BUG] onRowClicked callback not triggered when clicking on row's data

### ISSUE THREAD

**Issue by kevinRoomies** [jbetancur/react-data-table-component#658]
## Describe the bug
I don't really know if it's a bug or the normal behavior, but I added an onRowClicked callback to the datatable, but the callback is called only when I'm clicking on the row, outside of the row's elements, i.e. if I click on a name on the column name it doesn't trigger the onClick event while clicking next to it does.

## To Reproduce
- Make a datatable with an onRowClicked callback
- Fill it with data
- Click on a data - nothing happens

## Expected behavior
I expected the callback to be triggered wherever I click on the row.

## Versions (please complete the following information)
 - React 16.13.1
 - Styled Components 5.1.0
 - OS: Windows 10
 - Browser: Brave

**Comment by Oxicode** [comment]
Comparte el código de ejemplo para poder ayudarte
