### ISSUE TITLE
RowExpander Infinite Looping - How Do I Stop This From Looping

### ISSUE THREAD

**Issue by doverradio** [jbetancur/react-data-table-component#666]
Hi I am trying to implement a row expander component that keeps going into an infinite loop and I need some help.  

I have created a datatable using react-data-table-component and am stuck with an infinite loop after clicking on the Row Expander button.
Prior to adding a fetch call it worked nomally. (using a placeholder I put).
But after adding the fetch, it goes into an infinite loop and page crashes.
I just want it to load the data from the item in the database in this expander component without the infinite loop.

Here's the state:
```
    const [tempItem, setTempItem] = useState([]);
    const [rowGotClicked, setRowGotClicked] = useState(false)
```
To control what happens, I thought to set a variable `rowGotClicked` to `true` upon row expander button click. Then I used an if statement to check if it's true, which would execute fetch when true, ... then set it back to false. Here's that fetching function getTheData:
```
    const getTheData = (slug) => {
      if(slug) {
         singleData(slug)
        .then(r => r)
        .then(response => {
          console.log(`This is the response: `, response)
          setTempItem(response)
          return response
        })
      }
    }
```

Here is the function producing the datatable:
```
const BasicTable = () => {
    const filteredItems = datatableThoughts().filter(item => item.view && item.view.toLowerCase().includes(filterText.toLowerCase()));          
      
            return (
              <DataTable
                title="thoughts"
                columns={columns}
                data={filteredItems}
                pagination
                paginationResetDefaultPage={resetPaginationToggle}
                subHeader
                subHeaderComponent={subHeaderComponentMemo}
                defaultSortField="updatedAt"
                defaultSortAsc={false}
                selectableRows
                responsive
                onSelectedRowsChange={handleRowSelected}
                expandableRows
                expandableRowsComponent={<ThoughtsExpandedComponent />}
                persistTableHead
              />
            );
          };
```
Below is `ThoughtsExpandedComponent`. It gets called by `expandableRowsComponent` above, resulting in ThoughtsExpandedComponent being rendered directly below the row where `>` is clicked). **It is here where I believe the source of the problem is**:
```
          const ThoughtsExpandedComponent = ({ data }) => {
            console.log(`data: `, data);
              let slug0 = data.title.props.href.split('/')[2]
              let itemData
              setRowGotClicked(true)
              if(rowGotClicked) { 
                setTempItem(getTheData(slug0))
                setRowGotClicked(false)
               }
              
              console.log(`itemData: `, itemData)
            return (
            <Row>
              <Col lg="12">
                  <Card > 
                  <CardTitle><h5>{data.title}</h5></CardTitle>
                <CardBody>
                <p>{`slug: /${slug0}`}</p>
                <h6>Details</h6>
                {tempItem ? tempItem.details : null}
                {JSON.stringify(tempItem)}
                  </CardBody>
                  </Card>
              </Col>
            </Row>            
            )
          };
```

What should I do to ensure the fetch is executed when the row expander is clicked and prevent the infinite loop?

**Comment by jbetancur** [comment]
I do not think this is not RDT related, but I am thinking `getTheData` needs to be wrapped in a `useEffect` since it is an async call. This typically causes an infinite re-render symptom.

Run ONCE:
```js
useEffect(() => {
// your async code here
// only run code here once when component mounts
}, [])
```

Run ONCE:
```js
useEffect(() => {
// your async code here
// run code here once when component mounts and agaion only if the someprop or somestate changes
}, [someprop, somestate])
```

`useEffect` can be confusing to understand, so I will let the React folks do it for you here:

https://reactjs.org/docs/hooks-effect.html
