### ISSUE TITLE
noRowsPerPage option is not active on mobile version

### ISSUE THREAD

**Issue by ahmad-medhat** [jbetancur/react-data-table-component#668]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
When passing an object of pagination component options with key noRowsPerPage and value of (true), the rows per page is now invisible on desktop. However, on mobile, the dropdown is only visible without the label.

## To Reproduce
Add the following prop "paginationComponentOptions" with the following value
`{
    rangeSeparatorText: 'of',
    noRowsPerPage: true,
    selectAllRowsItem: false,
    selectAllRowsItemText: 'All'
}`

## Expected behavior
The rows per page **dropdown + label** should disappear on both mobile and desktop. It is working as expected on desktop but not on mobile

## Code Sandbox, Screenshots, or Relevant Code
https://codesandbox.io/s/quirky-field-xv5l9?file=/src/App.js

## Versions (please complete the following information)
 - React: 16.13.1
 - Styled Components: 5.1.1
 - OS: Windows 10
 - Browser: Firefox

## Additional context
I think the issue can be resolved in the Pagination.js component by using `!options.noRowsPerPage && shouldShow `condition on <Range></Range> as done on the label

**Comment by jbetancur** [comment]
I can confirm this is a bug - thanks for logging it.

**Comment by ysangkok** [comment]
@jbetancur Can this be reopened? Seems like it is still a bug.
