### ISSUE TITLE
How to add custom class name in columns/cell? 

### ISSUE THREAD

**Issue by hertzden** [jbetancur/react-data-table-component#672]
## Feature Check list

Currently there is only provision to add custom class using className on parent element, but there is no way to add custom class name in cell.

Is it possible?

**Comment by jbetancur** [comment]
You can just define a custom cell and apply any css/classnamesyou need.

**Comment by chrisdel101** [comment]
@jbetancur How can I define a custom cell to add a className? I've searched the docs and the columns section don't have code examples (https://react-data-table-component.netlify.app/?path=/docs/columns-cells-custom-cells--custom-cells). The conditional class names won't work for me either (type error:  Property 'style' is missing in type ).
