### ISSUE TITLE
How to pass state to cell?

### ISSUE THREAD

**Issue by rakeshshubhu** [jbetancur/react-data-table-component#673]
I want to pass a state to a button component inside of column or a click handler for that button.
In the below example whenever I do a click on a button it should trigger this handle click. Can this be done in react-data-table? Thanks.
```js
const BasicTable = () => (
  const [show, setShow] = React.useState(false)

 const handleClick = () => {
   setshow(!show)
}
  <DataTable
    title="Movie List - Custom Cells"
    columns={columns}
    data={data}
  />
);
```

**Comment by bhaveshdaswani** [comment]
Were you able to do that? If yes how?
