### ISSUE TITLE
Individual column searching

### ISSUE THREAD

**Issue by sushil173** [jbetancur/react-data-table-component#674]
Is individual column searching is available? IF not please add that feature too

Check For Link:
https://datatables.net/examples/api/multi_filter.html

Thanks

**Comment by MikeWillis** [comment]
agreed, this would be a handy feature. For now I'm going to see about implementing by filtering the rows object that gets passed to the datatable

**Comment by MikeWillis** [comment]
here's the result, I used lodash for the filtering. Just set up a text field and pass the value to the filterRows function on change.

    filterRows = (filter) => {
        let filteredData = _.filter(this.state.unfilteredData, (row)=>{
            let keep = false;
            _.forEach( row, (value,key)=>{
                if ( !keep && value.indexOf(filter) !== -1 ) {
                    keep = true;
                }
            });
            return keep;
        });
        this.setState({filteredData:filteredData});
    };

...

    <DataTable
        ...
        data={this.state.filteredData}
        ...
    />

**Comment by doverradio** [comment]
Something like this I need
![multipleSort](https://user-images.githubusercontent.com/27786802/97226005-a079d300-1790-11eb-92fe-d81feb4f420e.png)

**Comment by omryr** [comment]
is there any way to do this? i also need this feature and looking for a clean way to implement it

**Comment by chemseddine201** [comment]
hi everybody, any one has a solution for this requirement, or any alternatives ?
