### ISSUE TITLE
 Select Input for "Rows per page" does not change color with "Dark" mode

### ISSUE THREAD

**Issue by vieweg** [jbetancur/react-data-table-component#675]
## Describe the bug
Select Input for "Rows per page" does not change color with "Dark" mode

## To Reproduce
1. Go to https://jbetancur.github.io/react-data-table-component/?path=/story/theming--built-in-themes
2. Click on Select "Rows per Page"
3. See error

## Expected behavior
Options are expected to change color, to be visible

## Versions (please complete the following information)
-  RDT  6.11.2
 - React 16.13.1
 - Styled Components 5.1.0
 - OS:  Win 10
 - Browser [chrome]

**Comment by jbetancur** [comment]
Yea this is def a bug and a known issue. It's on the top of my list to fix for sure.
