### ISSUE TITLE
Sorting treats A different to a

### ISSUE THREAD

**Issue by svermaak** [jbetancur/react-data-table-component#677]
## Issue Check list
- [X ] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [X ] Read the README
- [ X] You are using React 16.8.0+
- [ X] You installed `styled-components`
- [ X] Include relevant code or preferably a [code sandbox](https://codesandbox.io/s/react-data-table-sandbox-forked-6f3ir
)

## To Reproduce
1. Go to 'https://codesandbox.io/s/react-data-table-sandbox-forked-6f3ir'
2. Click on 'Title' to sort column
3. Notice how AMERican is sorted differently from American

## Expected behavior
I expect sortint to treat A and a the same

## Code Sandbox, Screenshots, or Relevant Code
Please include a codesandbox to help **expedite** troublshooting.

https://codesandbox.io/s/react-data-table-sandbox-forked-6f3ir

Otherwise, add screenshots and/or complete sample code to help explain your problem.

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+)
 - Styled Components
 - Browser [e.g. chrome, safari, firefox]

**Comment by jbetancur** [comment]
This is the built in sorting. If you want more custom sorting then take a look at https://github.com/jbetancur/react-data-table-component#sorting `sortFunction`. You can also specify a custom sort per column https://github.com/jbetancur/react-data-table-component#columns

The following is an example of `customSort`

https://jbetancur.github.io/react-data-table-component/?path=/story/sorting--custom-sort-function

**Comment by svermaak** [comment]
Thank you jbetancur!
