### ISSUE TITLE
onRowClicked not triggered on custom cell

### ISSUE THREAD

**Issue by fctmolina1135** [jbetancur/react-data-table-component#684]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
`onRowClicked` is not triggered when clicking custom cells

## Expected behavior
`onRowClicked` should work on custom cells

## Code Sandbox, Screenshots, or Relevant Code

```
const VIDEO_COLUMNS: IDataTableColumn<Object>[] = [
  {
    name: words.videoHeaders.video,
    selector: 'videoItem',
    minWidth: '400px',
    // @ts-ignore
    cell: (row: VideoItemRow): ReactNode => <VideoItem {...row.videoItem} />,
  },
  {
    name: words.videoHeaders.publishSettings,
    selector: 'publishSettings',
    // @ts-ignore
    cell: (row: VideoItemRow): ReactNode => (
      <PublishItem
        setting={
          row.publishSettings === words.publishDropdownValue[0]
            ? 'private'
            : 'public'
        }
      />
    ),
  },
  {
    name: words.videoHeaders.limit,
    selector: 'limit',
    minWidth: '157.5px',
  },
  {
    name: words.videoHeaders.createdAt,
    selector: 'createdAt',
    sortable: true,
  },
  {
    name: words.projectHeaders.status,
    selector: 'status',
  },
];
```

```
<CustomDataTable
            data={data}
            columns={VIDEO_COLUMNS}
            onChangeSelect={onChangeSelect}
            onSort={onSort}
            sortField="createdAt"
            onRowClicked={this.onRowClick}
            sortServer
 />
```

```
import React, { PureComponent } from 'react';
import DataTable, { IDataTableColumn } from 'react-data-table-component';
import { customStyle } from './elements';
import { DownwardArrow } from '../../atoms/Icons';

type Props = {
  columns: IDataTableColumn<Object>[];
  data: IDataTableColumn<Object>[];
  onChangeSelect: (selected: {
    allSelected: boolean;
    selectedCount: number;
    selectedRows: IDataTableColumn<Object>[];
  }) => void;
  onSort?: (
    // @ts-ignore
    column: IDataTableColumn<T>,
    sortDirection: 'asc' | 'desc',
  ) => void;
  sortField?: string;
  sortServer?: boolean;
  selectableRows?: boolean;
  onRowClicked: (row: IDataTableColumn<Object>) => void;
} & Partial<DefaultProps>;
type DefaultProps = Readonly<typeof defaultProps>;

const defaultProps = {
  selectableRows: true as boolean,
};

class CustomDataTable extends PureComponent<Props & DefaultProps> {
  static defaultProps = defaultProps;

  render = (): React.ReactElement => {
    const {
      columns,
      data,
      onChangeSelect,
      onSort,
      sortField,
      onRowClicked,
      sortServer,
      selectableRows,
    } = this.props;

    return (
      <DataTable
        columns={columns}
        data={data}
        customStyles={customStyle}
        selectableRows={selectableRows}
        selectableRowsVisibleOnly
        onSelectedRowsChange={onChangeSelect}
        highlightOnHover
        noHeader
        overflowY
        responsive
        sortIcon={<DownwardArrow />}
        defaultSortField={sortField}
        onSort={onSort}
        defaultSortAsc={false}
        onRowClicked={onRowClicked}
        sortServer={sortServer}
      />
    );
  };
}

export default CustomDataTable;
```

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+) - 16.13.1
 - Styled Components - ^5.1.0
 - OS: [e.g. iOS] - macOS Mojave version 10.14.5
 - Browser [e.g. chrome, safari, firefox] - chrome & safari

**Comment by jbetancur** [comment]
Thanks for logging this. This is most definitely an issue that has to do with how events are bubbled up from the custom Cell to the internal TableCell.  I'll flag this as a bug and try to address.

**Comment by fctmolina1135** [comment]
Thank you. Hopefully this will be fixed soon.

**Comment by aricneto** [comment]
Any workarounds to this issue while we wait for an official patch?

**Comment by jbetancur** [comment]
Sorry, I've been quite busy so have not had time to look at this, but it is the first bug I will address. No workaround that I can think of.

**Comment by jbetancur** [comment]
I recall why this seems broken...

This was how it worked in an older version of RDT, i.e. that you could click a custom Cell and it would pass the click event. The implementation that allows this to work was an absolutely positioned div on the TableCell that intercepted the click event.

However, the tradeoff was that you could not select the inner TableCell contents to do things like say copy/paste. In fact, I had a lot of complaints about this and so I backed this out in a later release.

I'm not entirely sure it is possible to have both, that is to allow a custom cell to be clicked and be able to select its contents.

I need to think about this, but perhaps I should bring back the original implementation and allow an opt-in to be able to select (with the caveat that the click event will be ignored).

**Comment by jbetancur** [comment]
I have a fix for this finally... In your custom `cell` you just need to add a special tag to allow the click events to propagate up to the Row. Foe example:

```js
row => <h2 data-tag="allowEvents">{row.title}</h2>
```

If your component is more complex and has nested elements you want to add it to the innermost element or on the elements you want to propagate the click event.

```js
`row => <div><div data-tag="allowEvents">{row.title}</div></div>` 
```

This might feel weird, but it's the only way to allow `onRowClicked` to work properly with custom cell components and without any performance issues.

I will be releasing a 6.11.6 with this fix sometime today.
