### ISSUE TITLE
Cannot set or change cell's minimum width 

### ISSUE THREAD

**Issue by oakkar8** [jbetancur/react-data-table-component#686]
Trying to change the minimum cell's width with customStyles but it is not changed. 

## Relevant Code
  ` let customStyle = {
       subHeader: {
        style: {
          backgroundColor: "rgb(243, 250, 249)",
          borderWidth: "3px",
          borderStyle: "solid",
          borderColor: "rgb(172, 168, 153)",
          borderBottom: "none"
        }
      },
      headCells: {
        style: {
          minWidth: "30px",
        },
      },
      cells: {
        style: {
          minWidth: "30px",
        },
      },
    };
`
That is how i'm trying to set but when i resize the window the minimum cell width is 100px.

## Versions
 - React 16.12.0
 - Styled Components
 - Ubuntu 20.04.1 LTS
 - Chrome

**Comment by jbetancur** [comment]
No need for customStyles. You can change width, minWidth, or maxWidth in a column def

https://github.com/jbetancur/react-data-table-component#columns

**Comment by oakkar8** [comment]
> No need for customStyles. You can change width, minWidth, or maxWidth in a column def
> 
> https://github.com/jbetancur/react-data-table-component#columns

yeah at first it didn't work... not it's working .. thanks
