### ISSUE TITLE
Free form placement of Pagination

### ISSUE THREAD

**Issue by Intelliflex** [jbetancur/react-data-table-component#688]
I've seen posts relating to placement of Pagination at top, but it would be nice to have free form placement of pagination. In my case I have a page footer and would like pagination to appear there (as shown)

![Pagination Request](https://user-images.githubusercontent.com/50093911/94390646-90bd9d80-0196-11eb-845e-2e9a1d0e823f.png)

**Comment by Intelliflex** [comment]
OK I solved this one - so here is the solution.
I have written a wrapper for RDT that exposes a hook called usePagination and a wrapper called FlexTable
The usePagination hook exposes a method called **action** that can be called with, 'first',  'prev', 'next' and 'last' to perform pagination options and a method called rows that can be used to set the number of rows per page.

To use this,
a) Import RDT Wrapper and pagination Hook as follows 
`import FlexTable, { usePagination } from '../../library/FlexTable'`

b) In you component define a constant using usePagination hook
`const [pagination] = usePagination()`

c) Define RDT Table as normal, but use FlexTable instead 

d) Include a props called paginationFlex={pagination} 

IN YOUR COMPONENT (ANYWHER YOU LIKE) YOU CAN THEN ADD SOME JSX THAT WILL DEFINE EACH ACTION (The Example shown uses bootstrap styling

`    <div className='d-flex justify-content-end'>
                <PageBtn action={() => pagination.action('first')} icon='angle-double-left' />
                <PageBtn action={() => pagination.action('prev')} icon='angle-left' />
                <span className='px-2'>
                  Page {pagination.state.currentPage} of {pagination.state.totalPages}
                </span>
                <PageBtn action={() => pagination.action('next')} icon='angle-right' />
                <PageBtn action={() => pagination.action('last')} icon='angle-double-right' />
              </div>`

where PageBtn is 

`const PageBtn = (props) => {
    const { icon, action } = props
    return (
      <button
        onClick={() => {
          action()
        }}
        className='btn py-0 px-1 tp-hover btn-transparent'
      >
        <i className={`fas fa-${icon} ml-2`}></i>
      </button>
    )
  }
`

I hope this helps others looking for a solution to work with this excellent library

**Comment by Intelliflex** [comment]
`import React, { useEffect, useState } from 'react'
import RDT from 'react-data-table-component'

//DEFINE HOOK FOR STORING & SETTING PAGINATION VALUES AS WELL AS ACTION METHOD
export const usePagination = () => {
  const [state, setState] = useState({ currentPage: 0, totalPages: 0, rowCount: 0 })
  const [act, setAct] = useState(null)
  const [rowsPerPage, setRowsPerPage] = useState(null)
  const set = (obj) => {
    setState({ ...state, ...obj })
  }
  const action = (act) => {
    setAct(act)
  }
  const rows = (row) => {
    setRowsPerPage(row)
  }
  return [{ state: state, _action: act, _rows: rowsPerPage, set, action, rows }]
}

//COMPONENT PROVIDING PAGINATION METHODS & SETTING STATE
export const Pagination = (props) => {
  const { pagination, rowsPerPage, rowCount, onChangePage, onChangeRowsPerPage, currentPage } = props
  //PAGINATION ACTIONS
  useEffect(() => {
    if (pagination._action === null && !pagination.state.currentPage && currentPage) {
      pagination.set({ currentPage: currentPage, totalPages: totalPages, rowCount: rowCount })
    }
    if (pagination._action) adjustPage(pagination._action)
    pagination.action(null)
  }, [pagination._action])

  //ADJUSTMENT FOR NUMBER OF ROWS
  useEffect(() => {
    if (pagination && pagination._rows) {
      let totalPages = Math.ceil(rowCount / pagination._rows)
      onChangeRowsPerPage(pagination._rows)
    }
  }, [pagination._rows])

  useEffect(() => {
    if (pagination._rows && rowsPerPage !== pagination._rows) {
      let totalPages = Math.ceil(rowCount / pagination._rows)
      pagination.set({ currentPage: 1, totalPages: totalPages, rowCount: rowCount })
    }
  }, [rowsPerPage])

  let totalPages = Math.ceil(rowCount / rowsPerPage)
  const adjustPage = (mode, rows = 0) => {
    let newPage
    if (mode === 'first') newPage = 1
    else if (mode === 'last') newPage = totalPages
    else if (mode === 'next') newPage = currentPage >= totalPages ? totalPages : currentPage + 1
    else if (mode === 'prev') newPage = currentPage <= 1 ? 1 : currentPage - 1
    else currentPage = parseInt(mode)
    onChangePage(newPage)
    pagination.set({ currentPage: newPage, totalPages: totalPages, rowCount: rowCount })
  }
  //This component has no JSX (it has methods only - called by pagination.action() hook)
  return <></>
}

//WRAPPER FOR STANDARD RDT TABLE (WILL APPLY CUSTOM PAGINATION WHEN PAGINATIONFLEX PROPERTY SET)
const FlexTable = (props) => {
  const { children, paginationFlex, ...o } = props
  const CustomPagination = ({ ...o }) => <Pagination pagination={paginationFlex} {...o} />
  //IF PaginationFlex is set to useState Value then Bind Component to Datatable (otherwise act as default)
  if (props && paginationFlex) {
    return (
      <RDT paginationComponent={CustomPagination} {...o}>
        {children}
      </RDT>
    )
  } else return <RDT {...o}>{children}</RDT>
}

export default FlexTable
`

**Comment by jbetancur** [comment]
@Intelliflex I really like this idea.  It would be good to brainstorm a few other ways to make this work more OOB.

In theory, we could make the native Pagination component something that can just be imported. It may require a Context Provider to wrap the component so there is access to the internal state of RDT.

**Comment by Intelliflex** [comment]
HI John,

Yes I use the Context API throughout my App, but do like this solution since it is self contained and only one line to declare the hook. By exposing a hook to the top level component, it is easily passed to child components as a single named property or via inheritance and any action calls via children are propagated to RDT.  Happy for you to use this in your story book if that suits you.

Cheers Mike

**Comment by rebelspirit** [comment]
> 

Hi, I'm using your way to make pagination. And I try to change row per page option. Works good, after changing new data re-rendered on first page. But when i try to go next (second) page - nothing happens. On console i see the state with current page is 2, but the data shown on the page (2) is still from the first page. 
Can you help me, where the problem?
