### ISSUE TITLE
Close expanded row with an onclick event

### ISSUE THREAD

**Issue by smammadov1994** [jbetancur/react-data-table-component#690]
Hello,
I am fairly new to datatables. I am building an application and have hit a roadblock. I need to grab the unique id of a note when clicking on the expanded row. I managed to do this but when I click on a delete button, it deletes that row but the next row has its expanded component open. How do I close the expanded component programatically?

**Comment by jbetancur** [comment]
This is not currently possible since the Expander events are not exposed in the public API. There are plans to refactor expanders a to allow this but I don't have an ETA.

**Comment by geudrik** [comment]
I'd also love to see this functionality exposed. onClick events for the whole row would be a good thing as well

**Comment by feiraelectronica** [comment]
> I'd also love to see this functionality exposed. onClick events for the whole row would be a good thing as well (eg: for handling multi-row selection without the need to individually click check boxes)

hi @geudrik, have you found the solution for this?

**Comment by geudrik** [comment]
> > I'd also love to see this functionality exposed. onClick events for the whole row would be a good thing as well (eg: for handling multi-row selection without the need to individually click check boxes)
> 
> hi @geudrik, have you found the solution for this?
> 

Yeah, kind of. It's more of a hack than anything, and the state bubbling up issue (need to find it again) for custom cells is indeed an issue. 

I'll post code in a little bit, still going strong in coffee.

**Comment by geudrik** [comment]
```javascript
function rdt_func_onRowClicked(row, e) {
    let shift_key_pressed = e && e.shiftKey || false;

    // We're going to store the index of this row as our "last row clicked", since we need that to compute ranges
    let index_of_row_we_just_clicked = this.state.data.findIndex((stateful_row_data) => {
        return stateful_row_data[this.constructor.id_key_name] === row[this.constructor.id_key_name]
    })

    this.setState((prev) => {

        let data = prev.data;

        if(shift_key_pressed) {
            let low = prev.last_row_clicked;
            let high = index_of_row_we_just_clicked;
            if(prev.last_row_clicked >= index_of_row_we_just_clicked) {
                low = index_of_row_we_just_clicked;
                high = prev.last_row_clicked;
            }

            let updated_rows = Array(high - low + 1).fill().map((_, idx) => low + idx).reduce((acc, i) => {
                acc[i] = {rdt_selected: {$set: true}};
                return acc
            }, {})
            data = update(prev.data, updated_rows)
        }

        // Shift key is NOT pressed, so we're going to select/de-select a single row
        else {
            let currently_selected_state = !!prev.data[index_of_row_we_just_clicked].rdt_selected;
            data = update(prev.data, {[index_of_row_we_just_clicked]: {rdt_selected: {$set: !currently_selected_state}}})
        }

        return {
            data: data,
            last_row_clicked: index_of_row_we_just_clicked
        };
    }, function() {

    })
}
```
Full disclosure: this is definitely a hack and should be exposed as part of the core Lib, but hey, sometimes hacky is good, right? 😁 

This basically lets you pass in a callback to the underlaying Tabling lib `onRowClicked` prop that alters state, etc based on what's going on. This lets you not only bypass using checkboxes for row selection entirely, but also do things like register click events anywhere on the row, with the one caveat #684 

I should mention that we aren't using row click / multi selection to toggle the opening of foldable rows. We track selected rows and still rely on the drop-down toggle to open/close a given row. With that said however, to cause a row to open on click, you'd (somewhere in there, whip that debugger out) you'd just need to patch into the following two callback methods, similar to what we've done above for row selection

```javascript
        // Ensure that we're overriding the the built-ins
        //  See: https://www.npmjs.com/package/react-data-table-component#row-expander for docs
        table_props['onRowExpandToggled'] = this.on_row_expand_toggle;
        table_props['expandableRowExpanded'] = this.expandable_row_expanded;
```

**Comment by smammadov1994** [comment]
Is this supposed to stop the next row from expanding? I cannot really understand the code or where to put it.
