### ISSUE TITLE
how to change this kind of pagination?

### ISSUE THREAD

**Issue by feiraelectronica** [jbetancur/react-data-table-component#694]
is it possible to do this pagination instead of the bottom right pagination? thank you so much.

![image](https://user-images.githubusercontent.com/72189108/94779963-4a687880-03fa-11eb-80f4-504575941f77.png)

**Comment by smammadov1994** [comment]
I would like to know also please @jbetancur

**Comment by feiraelectronica** [comment]
> I would like to know also please @jbetancur

let me know if you have the answer. thank you
