### ISSUE TITLE
Order expandable icon

### ISSUE THREAD

**Issue by mateuszmaczynski** [jbetancur/react-data-table-component#697]
I consider,  how can I change the display order of the expandable icon to the last column?

**Comment by THE-EDDY** [comment]
I need to do this and would like to know how?

**Comment by mateuszmaczynski** [comment]
Unfortunately I didn't find any valid solution to this problem and left the dropdown icon in the first column. I think there is no such possibility unless you dig deep into the code and rewrite yourself.
