### ISSUE TITLE
Unable to display a boolean value and  create a conditional rendering.

### ISSUE THREAD

**Issue by joshtom** [jbetancur/react-data-table-component#700]
I have a boolean value that is coming from an API but it is not displaying in my data table, how can I achieve this? Also, I would like to set the conditional rendering based on the boolean value

Like so ```Assuming *emailVerified* returns a boolean value```
const columns = [
    {
      name: "Avatar",
      selector: "emailVerified ? User Verified : Not Verifiedl",
      sortable: true,
    }
]

**Comment by maximegheraille** [comment]
Hi, can't you do something like this 

```
`const columns = [
{
   name: "Avatar",
   selector:  `$emailVerified ? User Verified :  Not Verified}`,
   sortable: true,
}]`
```

**Comment by joshtom** [comment]
> Hi, can't you do something like this
> 
> ```
> `const columns = [
> {
>    name: "Avatar",
>    selector:  `$emailVerified ? User Verified :  Not Verified}`,
>    sortable: true,
> }]`
> ```

I have moved on to something else though. But I will definitely give this a look

**Comment by orion-pax** [comment]
I have used the following syntax successfully, I hope it helps:

```
const columns = [
{
   name: "Avatar",
   selector: d => d.emailVerified ? 'User Verified'  :  'Not Verified',
   sortable: true,
}]
```
