### ISSUE TITLE
Filter box blur issue

### ISSUE THREAD

**Issue by manavpandya-numantra** [jbetancur/react-data-table-component#702]
Installed the package, and everything works fine except the **FILTER FEATURE**.

When I try to type, the input accepts 1 character at a time and loses its focus. Let me know the workaround for that issue.

**Comment by manavpandya** [comment]
Installed the package, and everything works fine except the `FILTER FEATURE`.

When I try to type, the input accepts 1 character at a time and loses its focus. Let me know the workaround for that issue.
