### ISSUE TITLE
[FEATURE]: Ability to show/hide columns manually

### ISSUE THREAD

**Issue by kalinchuk** [jbetancur/react-data-table-component#703]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

A clear and concise description of what the feature is.

## Describe the solution you'd like

The table should be able to change column attributes (such as `omit`) to show/hide columns. Right now if the column array changes, DataTable does not respond to the change.

**Comment by feiraelectronica** [comment]
Hi @kalinchuk , have you got the solution for this?

**Comment by jbetancur** [comment]
@kalinchuk Here is a working example for hiding/showing columns manually:

https://jbetancur.github.io/react-data-table-component/?path=/story/general--omit-column-dynamically

**Comment by jbetancur** [comment]
@kalinchuk I'm going to close this out since this feature is already available. Let me know if you have any other questions.

**Comment by ibra4** [comment]
> @kalinchuk Here is a working example for hiding/showing columns manually:
> 
> https://jbetancur.github.io/react-data-table-component/?path=/story/general--omit-column-dynamically


The link is not working

```
No Preview
Sorry, but you either have no stories or none are selected somehow.
```
