### ISSUE TITLE
[SUPPORT REQUEST] Sorting state (column, direction) does not persist

### ISSUE THREAD

**Issue by JaffParker** [jbetancur/react-data-table-component#704]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
I was very much on the fence about opening this issue as it's very much a support request, but I'm out of options. I'm grateful for any help you'd be able to give.

I am creating a table with server-side pagination and sorting. No issues with pagination, however, sorting does not work as intended. When I click on a column to sort, it does pass the sorting parameters to my handler, but does not save the state. So if I go to click it a second time, it'll pass the exact same parameters (eg, id+asc).

## Expected behavior

Sorting order and column get persisted in the state.

## Code Sandbox, Screenshots, or Relevant Code

I was not able to reproduce it in a codesandbox, here's my attempt though: https://codesandbox.io/s/react-data-table-sandbox-forked-gu9rt. Might be because there's no actual server. Here's the code responsible for this table:

```ts
export const ListContainer: FC<ListContainerProps> = ({
  userId,
}) => {
  const [page, setPage] = useState(1)
  const [perPage, setPerPage] = useState(10)
  const [sort, setSort] = useState<StudyParticipantsSort>({
    id: SortOrder.ASC,
  })
  const { data, loading } = useListContainerQuery({
    variables: {
      userId,
      page: {
        count: perPage,
        page,
      },
      sort,
    },
    fetchPolicy: 'cache-and-network',
  })

  const handleRowsPerPageChange = useCallback(
    (currentRowsPerPage: number, currentPage: number) => {
      setPerPage(currentRowsPerPage)
      setPage(currentPage)
    },
    [],
  )

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const handleSort = useCallback((column: any, order: 'desc' | 'asc') => {
    setSort({ [column.id as string]: order.toUpperCase() })
  }, [])

  return (
    <DataTable
      progressPending={loading}
      progressComponent={<Loading />}
      pagination
      paginationServer
      paginationTotalRows={data?.participantsFeed.resourceInfo.totalCount}
      paginationPerPage={perPage}
      onChangeRowsPerPage={handleRowsPerPageChange}
      onChangePage={setPage}
      persistTableHead
      sortServer
      onSort={handleSort}
      defaultSortAsc
      defaultSortField="id"
      data={data?.participantsFeed.nodes ?? []}
      columns={[
        {
          id: 'id',
          name: 'ID',
          selector: ({ id }) => id,
          sortable: true,
        },
        {
          id: 'progressStatus',
          name: 'Status',
          selector: ({ progressStatus }) => (
            <span
              className={clsx({
                [`text-${ProgressStatuses[progressStatus].color}`]:
                  progressStatus === ProgressStatus.inProgress,
              })}
            >
              {ProgressStatuses[progressStatus].label}
            </span>
          ),
          sortable: true,
        },
      ]}
    />
  )
}
```

For sorting, I pass `sortServer`, `onSort={handleSort}` (which makes the data update and re-render), `defaultSortAsc`, `defaultSortField="id"` (the last one has no effect, there's no default sorting in the table).

## Versions (please complete the following information)
 - React v16.13.1
 - Styled Components v5.2.0
 - OS: Windows 10
 - Browser: Chrome 86

**Comment by jbetancur** [comment]
Sorry for the delay in replying. I can't seem to duplicate this in code sandbox. Can you provide a specific set of steps that trigger this in the sandbox example?  Have you tried using the latest version of RDT, it looks like you are using 6.9.6 but I would update to the latest to be sure

**Comment by jbetancur** [comment]
Oh sorry, I missed that you could not dupe this in a sandbox! If you remove the pagination does the same still happen?

**Comment by JaffParker** [comment]
@jbetancur hey, no worries! I understand maintaining open source projects requires a lot of effort 👍

Unfortunately the error stays when I remove the pagination.

**Comment by JaffParker** [comment]
I tried going into debugging the source of the lib, but unfortunately didn't have time to get to the bottom of it. It would help me greatly if you could just mention where is the sorting state stored? I mean file and line. I could probably then debug it in my instance and find the error.

**Comment by JaffParker** [comment]
I found the bug! Is there a reason that [here](https://github.com/jbetancur/react-data-table-component/blob/6e9d9246076f9b39663c942fc69848ec6744edde/src/DataTable/TableCol.js#L66) you check if it's the same column by selector instead of ID? What happened is that I define my columns inline right in the prop, so the selector functions get reinitialized on each render, thus they will never be the same. In the codesandbox on the other hand the columns were declared outside of the component body, so they would never be reinitialized.

Either switch to identifying columns by ID or specifically mention in the docs that columns cannot be declared inline in the prop. I can make a PR, but it'll take a bit of time for me to track down all the places where you identify column by selector.

**Comment by JaffParker** [comment]
By the way, check [this codesandbox](https://codesandbox.io/s/react-data-table-sandbox-forked-gu9rt?file=/src/index.js) for an example

**Comment by jbetancur** [comment]
@JaffParker nice catch!  That is indeed a bug. The selector has evolved from a string into a function/string so the comparison was def overlooked. The id for column only evolved due to server-rendered projects so was never really required to have an ID, but maybe it should be going forward. A workaround is to create the selectors external to the component or to memoize.

In any case, I'll look at getting this fixed.
