### ISSUE TITLE
I don't see filter in react datable component api.

### ISSUE THREAD

**Issue by Dineshkarki24** [jbetancur/react-data-table-component#705]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

A clear and concise description of what the feature is.

**Comment by maximegheraille** [comment]
Hi, there is one in the examples [https://jbetancur.github.io/react-data-table-component/?path=/story/filtering--example-1](url)
