### ISSUE TITLE
[FEATURE]: Refresh data event

### ISSUE THREAD

**Issue by Pfalbo1** [jbetancur/react-data-table-component#712]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

I have set my table data in a state, this allow me to add new rows to my table. The problem is that the table didn't fetch the new data unless a sort event is triggered.

## Describe the solution you'd like

Is it possible to maybe trigger a event that force the reload of the data ? Maybe this already exist but i can't figure out what it is.
Thanks

**Comment by jbetancur** [comment]
There is no way to really have such a feature and actually, RDT will re-render if `data` changes so I would look to y our React state to determine why the data is only changing on a sort. That being said,  u's really hard to help without a codesandbox or some working example to understand the problem better.

**Comment by Pfalbo1** [comment]
I don't have acces to my code right now to do a codesanbox, maybe a explication will be sufficient, my code is not really that complicated. 
In the dataTable settings my data is set like this `data={this.state.dataArray}` dataArray is my React state with all my data. When I want to add a row I simply copy my state dataArray into a temporary array, `.push` a new row in my temporary array and then `this.setState({
                dataArray: tmpArray,
            });`

**Comment by jbetancur** [comment]
As I mentioned it's a fundamental issue with how you are using react state. React state requires with immutability in your objects. In other words, you cannot mutate your array and instead need to create a new array with your new value. When the array has a new reference the react will rerender as expected. Otherwise, pushing to your existing array will not do anything.

Hope that helps!

**Comment by Pfalbo1** [comment]
Thanks !
