### ISSUE TITLE
For the love of god can someone just show me how to create a custom pagination.

### ISSUE THREAD

**Issue by smammadov1994** [jbetancur/react-data-table-component#713]
I have been trying to read the storybook and try anything and everything. I need to change the pagination to show numbers and be highlighted like the pagination in bootstrap table. I DO NOT understand the documentation for creating a custom pagination and it is frustrating. Can someone just show me how to go about changing the pagination?

**Comment by feiraelectronica** [comment]
hi @smammadov1994 , you found the solution yet? also need to customize my pagination.
