### ISSUE TITLE
Feature: Transpose of a table

### ISSUE THREAD

**Issue by mchennupati** [jbetancur/react-data-table-component#714]
Is there a way to display a table in transpose, so column names appear on the left and data on the right (instead of top and bottom) ? I am looking to display some financial information and I would like to use the features of RDT instead of using a html table. Is that possible ?  Am I missing something obvious here as it appears to be a common use case ? Thanks !

**Comment by jbetancur** [comment]
Sorry, this is not possible with this library. You probably want a library that is more excel-like. Maybe something like: https://github.com/nadbm/react-datasheet

**Comment by mchennupati** [comment]
Thanks a lot for getting back ! Appreciate that. Will take a look at datasheet !
