### ISSUE TITLE
How To Onclick the whole row instead of 1 field?

### ISSUE THREAD

**Issue by feiraelectronica** [jbetancur/react-data-table-component#721]
Hi @jbetancur , how do i do onclick for the whole row which i can click anywhere in that whole row instead of onclick to only 1 column in a row?

![image](https://user-images.githubusercontent.com/72189108/99640277-a3ac6a00-2a83-11eb-95f7-9243dd62ec7b.png)

this is an example. I don't want to use the checkbox, but user can click anywhere in the row to select.

**Comment by jbetancur** [comment]
OnRowClicked and onRowDoubleClicked will capture a click event. Please see the Readme for details

**Comment by feiraelectronica** [comment]
> onRowClicked and onRowDoubleClicked will capture a click event. Please see the Readme for details

can you show me the code for this? Readme too general.
