### ISSUE TITLE
How To Get Row Number?

### ISSUE THREAD

**Issue by feiraelectronica** [jbetancur/react-data-table-component#722]
How to get row number like this? Thank You @jbetancur 

![image](https://user-images.githubusercontent.com/72189108/99695912-155ad700-2ac9-11eb-8ebf-bc39a21d3d2c.png)

**Comment by jbetancur** [comment]
You can get the index of the row:
https://github.com/jbetancur/react-data-table-component#columns

Note that these will always be 0,1,2,3,4 regardless of sorting.

What you can do is just map through your data and add your own index before passing it to the table and the create a column config to display that

**Comment by feiraelectronica** [comment]
as for this

"You can get the index of the row:
https://github.com/jbetancur/react-data-table-component#columns"

which one ya? can it be more specific? how to use the index? thank you @jbetancur

**Comment by smammadov1994** [comment]
Yeah that was such an unclear response... @jbetancur  Would like to also know how this is done?

**Comment by jbetancur** [comment]
@feiraelectronica If you want to show the index add a new column definition with a custom cell. Something like:

```js
{
  name: '#',
  cell: (row, index) => index,
}
```

But this is a static index. So, just note that if you sort it will not change (unless that is your intent)

**Comment by Intelliflex** [comment]
Hi John,

Sorry to come in on a thread, but I do not have any other contact info for you.

I’m just reaching out regarding a new open source Library (npm Bootflex) I have development that I will be rolling out this month – Have a look at Github Pages site https://intelliflex.github.io/bootflex  - I still have a few things to wrap up and documentation to complete (but you will get a good idea)
It is a Bootstrap based Responsive  User Interface system, context management and form library. I have incorporated React-Data-Table-Component in this library adding context, external pagination, automatic row count and sizing to suit layouts as well as CRUD based form editing.

If you can respond to me privately it would be good to commence a dialog as I think the two libraries will complement each other nicely and be highly prevalent in the community.

Kind Regards,

Mike Thomson
Intelli-Flex Software Solutions
CEO & Chief Architect

[Intelli-Flex]
Intelligent and Flexbile Software Solutions
