### ISSUE TITLE
Expandable Rows problem with onClick

### ISSUE THREAD

**Issue by Pfalbo1** [jbetancur/react-data-table-component#727]
So I have my dataTable with my expandable rows enable. In that expandable row i have some buttons with a onClick event, and when I open the expandable row the onClick from the button is triggered instantly 

## To Reproduce
There is my code from my expandable row : 
```
const ExpandableComponent = ({ data }) => 
<div style={{ fontSize:"0.9em", backgroundColor: "#8080801f", marginBottom: "0%"}}>
    <center>
      <div style={{ marginTop: "2%", marginBottom: "0%", backgroundColor: "#d1d1d1"}}>
          <Button type="dashed" style={{ marginRight: "10%", borderColor: "#d1d1d1" }} block ghost>
            Récupération de mot de passe
          </Button>
          <Button type="dashed" style={{ marginRight: "10%", borderColor: "#d1d1d1" }} block ghost>
            Supprimer le compte
          </Button>
          <Button type="dashed" onClick={console.log("Test")} style={{ marginRight: "10%", borderColor: "#d1d1d1" }} block ghost>
            Modifier les Portefeuilles
          </Button>
          <Button type="dashed" style={{borderColor: "#d1d1d1" }} block ghost>
            Changer de Rôle
          </Button>
      </div>
    </center>
</div>
``` 

The problem is from the console.log("Test")

Have I done something wrong ?

**Comment by jbetancur** [comment]
You are using `onClick` incorrectly. 

`onClick={console.log("Test")}`

should be:

`onClick={() => console.log("Test")}`

in JavaScript onclick which is an event handler needs to take call back function otherwise, it will be immediately invoked when your expander is rendered (i.e. when. you expand the row)
