### ISSUE TITLE
Sorting with paginationServer true and sortServer false: [ Remove hardcoded currentPage: 1 from tablereducer ]

### ISSUE THREAD

**Issue by vijicode** [jbetancur/react-data-table-component#729]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

A clear and concise description of what the feature is.
Please refer to https://github.com/jbetancur/react-data-table-component/issues/466
This can be fixed by removing the hardcoded page "1" in tableReducer.js
If we want only the data displayed in the current page to be sorted, and user is already at a particular page, it will be nice to keep the user on the current page instead of sending them to page 1. 
 
## Describe the solution you'd like
If sortServer is false, and paginationServer is true, edit  logic to avoid setting currentPage to 1
OR
Create a new prop _persistCurrentPageOnSort_ that keeps currentPage on sort in case of server-side pagination.

In tableReducer.js -> SORT_CHANGE, add logic described in the solution.
Example:
_const keepPage = pagination && paginationServer && persistCurrentPageOnSort;
currentPage: keepPage ? state.currentPage : 1,_

**Comment by vijicode** [comment]
Made a PR https://github.com/jbetancur/react-data-table-component/pull/730
Could you please review whenever you get a chance. Thank you.

**Comment by jbetancur** [comment]
Hey, @vijicode thanks for the PR! It's been hectic but will look as soon as I can.
