### ISSUE TITLE
Unable to make the row expansion work like an accordion

### ISSUE THREAD

**Issue by shinub9** [jbetancur/react-data-table-component#732]
I am unable to implement the row expansion to work like an accordion.
My requirement is to close all the other expanded rows on opening a row and there would be only one row expanded at a time. 
I was unable to find a solution to implement this. 
If this feature is already there in the repo can someone guide me? 

Thanks in advance.

**Comment by jbetancur** [comment]
Sorry @shinub9 this is not a feature that is currently available, but I will keep this open as a feature request.

**Comment by ryjogo** [comment]
+1 here

**Comment by ShaneHudson** [comment]
@jbetancur Is this feature still unavailable? Are there any known workarounds?
