### ISSUE TITLE
Can user manipulate column widths?

### ISSUE THREAD

**Issue by mjvalade** [jbetancur/react-data-table-component#735]
I looked through but can't tell if there is a property to allow a user to manipulate the column widths similar to columns in Google Sheets or Excel? I see we can set our own `column.width` or even use `grow` but is it possible for the user to make any changes in the UI by dragging anything around?

Thanks! This library has been a great add to our project!

**Comment by jbetancur** [comment]
Hey not this time. This is a planned feature, but I've been focusing most of my time converting RDT over to typescript.

**Comment by mjvalade** [comment]
@jbetancur thanks for the quick response. Wanted to make sure I wasn't missing something. And I totally support the TS conversion!

**Comment by arjunsundaram4** [comment]
Will this be coming anytime soon? @jbetancur 
Also is there any workaround for this temporarily?
