### ISSUE TITLE
searching: searching abilities in DataTables

### ISSUE THREAD

**Issue by ishwarvarma** [jbetancur/react-data-table-component#736]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe
want to implement searching feature same as https://datatables.net/ has

A clear and concise description of what the feature is.

## Describe the solution you'd like

Searching in DataTables is "smart" in that it allows the end user to input multiple words (space separated) and will match a row containing those words

This option should allow the search abilities of DataTables to be enabled or disabled.

**Comment by jbetancur** [comment]
Take a look at https://jbetancur.github.io/react-data-table-component/?path=/story/filtering--example-1

You can implement your own filtering/searching using RDT's existing feature set
