### ISSUE TITLE
Tick not showing

### ISSUE THREAD

**Issue by feiraelectronica** [jbetancur/react-data-table-component#748]
Hi, any idea why my tick not showing? happens for both one row or all rows ticked,

![image](https://user-images.githubusercontent.com/72189108/103630438-9d634600-4f7c-11eb-863f-74b9d43614ef.png)

**Comment by feiraelectronica** [comment]
this is another example. it is already selected, but the tick not showing.

![image](https://user-images.githubusercontent.com/72189108/103632414-398e4c80-4f7f-11eb-91f9-cc59ba6ac09a.png)

and this is the code. i'm using class component.


<DataTable
            columns={columns}
            data={decryptMenuAttrib.searchResult}
            selectableRows
            onSelectedRowsChange={this.updateState}
/>

**Comment by feiraelectronica** [comment]
import .........

export default class WlMatchRec extends React.Component {

cons column = [{......}];
 
return (
.......
<DataTable
            columns={columns}
            data={decryptMenuAttrib.searchResult}
            noHeader={true}
            onSelectedRowsChange={this.updateState}
            selectableRows
          />

**Comment by feiraelectronica** [comment]
`import .........

export default class WlMatchRec extends React.Component {

cons column = [{......}];
 
return (
.......
DataTable
            columns={columns}
            data={decryptMenuAttrib.searchResult}
            noHeader={true}
            onSelectedRowsChange={this.updateState}
            selectableRows
          />`

sorry cannot put < in the comment, should be <datatable...

**Comment by jbetancur** [comment]
Does your data have a ‘id’ field? I believe you need a unique identifier for selectable rows to work. By default rdt looks for id but if that is a different key in your data you can use the ‘keyField’ prop to specify.

**Comment by feiraelectronica** [comment]
Do you mean in the column? 

![image](https://user-images.githubusercontent.com/72189108/103849994-25626080-50e1-11eb-8a86-6f8bd45b7288.png)

this?

the problem is only the tick not showing. but still, if I select, it selects the correct id.

**Comment by feiraelectronica** [comment]
![image](https://user-images.githubusercontent.com/72189108/103872374-4b9bf680-5109-11eb-8071-ca58a67b55ce.png)

i think i followed all this. but still.

**Comment by feiraelectronica** [comment]
![image](https://user-images.githubusercontent.com/72189108/103872943-062bf900-510a-11eb-9c76-0aab0b0a776b.png)

and just found out i can click the same checkbox multiple times. and this is the result. i click 10 times, then 10 records selected. what would be the problem ya?

**Comment by jbetancur** [comment]
`data` needs an `id` does your data have a unique identifier? 

For example:

```js
	{
		id: 1,
		name: 'Frozen yogurt',
		type: 'Ice cream',
		calories: 159,
		fat: 6.0,
		carbs: 24,
		protein: 4.0,
		sodium: 87,
		calcium: 14,
		iron: 1,
	},
```

RDT looks for `id` by default. If your keyField is something other than `id` then you need to use the `keyField` prop

```js
	{
		uuid: 1,
		name: 'Frozen yogurt',
		type: 'Ice cream',
		calories: 159,
		fat: 6.0,
		carbs: 24,
		protein: 4.0,
		sodium: 87,
		calcium: 14,
		iron: 1,

	},

...
<DataTable data={...} columns={...} keyField="uuid" ... />
```

Can you post an example of your data model? Also your component source would be helpful

**Comment by feiraelectronica** [comment]
hi @jbetancur . thank you so much for the help. using keyField fixed it. i will close this issue now.

**Comment by feiraelectronica** [comment]
urm 1 more thing @jbetancur ,what if i want to avoid multiple select?
