### ISSUE TITLE
[FEATURE]: Can we have an attribute to select multiple records or just a single records.

### ISSUE THREAD

**Issue by feiraelectronica** [jbetancur/react-data-table-component#752]
hi @jbetancur , can we have an attribute to select multiple or single records? or this attribute is already in the component? couldn't find it. saw there is a component like this.

for example

```
 <
DataTable
columns={...}
data={...}
multipleRowSelect={true} //if true, then can select multiple records. if false then can select only 1 record at a time.
/>

**Comment by feiraelectronica** [comment]
hi, is there any feature for this? currently, I can only select multiple records. not sure how to select only 1 at a time.

**Comment by feiraelectronica** [comment]
hi @jbetancur , is there any feature for this? currently, I can only select multiple records. not sure how to select only 1 at a time.

**Comment by jbetancur** [comment]
There is an open issue for this we can possibly look to implementing on the next branch (7.x).

**Comment by jbetancur** [comment]
https://github.com/jbetancur/react-data-table-component/issues/497

**Comment by jbetancur** [comment]
@feiraelectronica I am going to close this in favor of the original issue: https://github.com/jbetancur/react-data-table-component/issues/497

I'll tag this as a feature in 7.0

**Comment by feiraelectronica** [comment]
noted. thank you @jbetancur

**Comment by feiraelectronica** [comment]
Hi, Is this feature ready?

**Comment by feiraelectronica** [comment]
hi @jbetancur . may I know where will this feature will be completed? really need it. currently, i cannot select 1 record. but requirement only allows the user to click only 1 record.

**Comment by slimandslam** [comment]
We have everything spec'ed out for radio buttons in the table but I guess version 7 is too far off?

**Comment by jbetancur** [comment]
Im quite a busy person and have not had the time to finish this. But it's on the radar for 7.0 after I address some old issues and long standing bugs.

Design and implementation is something that is going to take some effort as a lot of old code needs to get cleaned up to make this work. If anyone wants to propose some ideas this is the place to discuss; which might move things along faster ;)
