### ISSUE TITLE
[FEATURE]: [Custom Look for each row, not like a table of cells]

### ISSUE THREAD

**Issue by mdodge-ecgrow** [jbetancur/react-data-table-component#757]
I am not sure if this is a feature request or if it is possible to do currently.  I would like to make a list of data look custom, not like a table of cells.  But maintain the sorting and filtering capabilities.
So it might look like this:
![image](https://user-images.githubusercontent.com/57459547/104941409-a2f75d80-5978-11eb-92f2-01f6025df929.png)

I am not sure if that is beyond the scope of this package or not.

**Comment by jbetancur** [comment]
Custom Styled Rows are possible using `customStyles` which allows you to override the default css/styled-components styling. See https://jbetancur.github.io/react-data-table-component/?path=/story/custom-styling--google-sheets-esqe

That being said something like the above is pretty custom so it's likely that it's beyond the scope of this library.
