### ISSUE TITLE
Expandable Child Rows: Enable Ability for Expandable Rows to have child Expandable rows

### ISSUE THREAD

**Issue by Asylian1** [jbetancur/react-data-table-component#758]
I've noticed that this particular feature was absent from the documentation. Knowing how clean this component is already, it would be really great to have this implemented as there are few alternatives out there without delving deep into the DOM and tearing things up.

**Comment by stevepetebruce** [comment]
I have child rows inside an expandable row, but when I try to expand a child, all the children expand. Has anyone else had this problem and is there a way to only expand the child row selected?
