### ISSUE TITLE
UI Width Manipulation

### ISSUE THREAD

**Issue by arjunsundaram4** [jbetancur/react-data-table-component#759]
I see we can set our own column.width or even use grow but is it possible for the user to make any changes in the UI by dragging anything around?
Also if planned will this be coming anytime soon?
And if not is there any workaround for this?

**Comment by jbetancur** [comment]
There are already a few issues/feature requests for this. Not sure when it will be done since I have been focused on migration to Typescript and stability fixes.

**Comment by arjunsundaram4** [comment]
Is there a way to manually implement this?

**Comment by jbetancur** [comment]
No. It needs to be implemented.

**Comment by arjunsundaram4** [comment]
Okay thanks, will you please include this asap if possible?

**Comment by faheemhameed** [comment]
Hi there,

Thanks for your great work. I am just evaluating the data table now. It sounds promising. I am wondering if we can have a drag function to resize the column width after the RDT is rendered.

Thanks.
