### ISSUE TITLE
Server Side Filtering?

### ISSUE THREAD

**Issue by doverradio** [jbetancur/react-data-table-component#761]
Hello, I recently figured out how to implement server side pagination (amazing).  

However, in doing so, it knocked out my beloved Filter By Text feature which is taken from your Filtering - Example 1 Storybook https://jbetancur.github.io/react-data-table-component/?path=/story/filtering--example-1

Is there a way for Filter By Text to work together with server side pagination?  

Previously, I had been loading all the data (took a long time) into the datatable but then, once there, it was lightning fast to drill down to the rows I needed but after server side pagination it only acts upon what has been loaded to the frontend and so I don't get to filter across all the records like before.

**Comment by jbetancur** [comment]
Personally, I would combine server-side pagination with server-side search if your API supports it.  Filtering is great for simple use cases and smaller data sets, but if you have a server-side use case it's best that you have something like a search that returns a list of data that you can then pagination. You obviously can't filter what you don't have in the UI state but a good API can allow you to combine pagination and search
