### ISSUE TITLE
React.Children.only expected to receive a single React element child.

### ISSUE THREAD

**Issue by Alvaresx** [jbetancur/react-data-table-component#764]
Boa tarde.

Estou tentando compilar meu código com DataTable mas estou tendo o seguinte erro: 

React.Children.only expected to receive a single React element child.

Abaixo segue o meu código:

const data = [
  { id: 1, 
    callstart: 'Conan the Barbarian', 
    calldirection: '1982',
    callerid: 'teste',
    callednum: 'hjfas',
    duration: 'gfyis',
    debit: 'gydfhsagdlf',
    disposition: 'khfosid',
    uniqueid: 'hfsjkdh',
  }
];
const columns = [
  {
    selector: "callstart",
    name: "Data",
    width: "20px",
  },
  {
    selector: "calldirection",
    name: "Tipo",
    width: "20px"
  },
  {
    selector: "callerid",
    name: "Origem",
    width: "20px"
  },
  {
    selector: "callednum",
    name: "Destino",
    width: "20px"
  },
  {
    selector: "duration",
    name: "Duração",
    width: "20px"
  },
  {
    selector: "debit",
    name: "Custo",
    width: "20px"
  },
  {
    selector: "disposition",
    name: "Status",
    width: "20px"
  },
  {
    selector: "uniqueid",
    name: "Gravação",
    width: "20px"
  },
];
class Tabela extends Component {
  render(){
    return (
      <div className="App">
        <Card>
          <DataTable
            title="Movies"
            columns={columns}
            data={data}
            defaultSortField="title"
            sortIcon={<SortIcon />}
            pagination
            selectableRows
          />
        </Card>
      </div>
    )
  }
}

export default Tabela;

Já tentei envolver o <DataTable> entre <div>, entre <>, entre <Card> mas sem sucesso.

**Comment by sanwalfarooque** [comment]
@Alvaresx any solution ? I simply upgraded from 3.x to 7.x and I see this error
