### ISSUE TITLE
[FEATURE]: Is there anyway to move the per page to the top of the table?

### ISSUE THREAD

**Issue by amitpatel9169** [jbetancur/react-data-table-component#765]
## Feature Check list

- [ ] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [ ] Read the README to ensure the feature is not already present
- [ ] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [ ] Considered the value versus complexity for all users of the library as well as library maintenance
- [ ] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe
I would like to display per page dropdown at the top left of the table, Is there any way to achieve this?

Is that available with **perPage = 'top'** and **perPage = 'bottom'**  that one is very helpful for all the users.

**Comment by jbetancur** [comment]
Not at this time, but there are plans to do so
