### ISSUE TITLE
defaultSortField not working (v7.0.0-alpha-5)

### ISSUE THREAD

**Issue by nesklada** [jbetancur/react-data-table-component#768]
**Hi John :)** 

In v7.0.0-alpha-5 prop **defaultSortField** not working 
In previos stable version (6.11.6) prop **defaultSortField** woorking good.

https://codesandbox.io/s/react-data-table-sandbox-forked-dftjk

thank you for attention

**Comment by jbetancur** [comment]
Yea this was one of the only real API changes, but`defaultSortField` has been renamed to `defaultSortFieldId` You just need to correlate the column id to either one you set in the column definitions or if you did not set `id` for each column the default 1,2,3... cols from left to right.

https://github.com/jbetancur/react-data-table-component/releases/tag/7.0.0-alpha-4


Hope that helps!
