### ISSUE TITLE
[FEATURE]: Infinite scroll instead of pagination

### ISSUE THREAD

**Issue by rabpeter** [jbetancur/react-data-table-component#769]
## Infinite scroll instead of pagination

It will be great if there is an option to set the infinite scroll instead of pagination. 

I think the easiest way is to add an API like "onLastRow" that can be used to call a custom function when the user is on the last row of the table.

**Comment by jbetancur** [comment]
I agree that this would be a great feature though I am not sure the level of effort involved. We'd have to implement some windowing and other things to make it work and not break everything else like serverside pagination, sorting, etc.  Being totally transparent, I don't have much time these days for new features like this but if you do feel free to write up a proposal on how it could be implemented or a PR (based on the `next` branch).
