### ISSUE TITLE
[DESCRIPTION]

### ISSUE THREAD

**Issue by robertveloso** [jbetancur/react-data-table-component#771]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
Styled components it's not a dependency of react-data-table-component.
I use emotion which is lightweight!

## To Reproduce
1. Create a CRA with react-data-table-component
2. It won't work

## Expected behavior
To work.

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+)
 - Styled Components N.A.
 - Browser [e.g. chrome, safari, firefox]

**Comment by jbetancur** [comment]
RDT is built using styled-components so you need to manually install it. It's not a dependency because then you could potentially be running 2 versions of styled-components.

https://github.com/jbetancur/react-data-table-component#installation

**Comment by robertveloso** [comment]
Understood, I could make a PR using emotion, would it be possible to be merged?
Maybe test if styled-components or emotion is installed and use dynamic import.

**Comment by jbetancur** [comment]
I'd be open to it for sure if you can make it work. If you do please use the `next` branch as that will become version 7 of RDT.
