### ISSUE TITLE
[API CALL]: [CAN I MAKE A API CALL ON ROW EXPANSION]

### ISSUE THREAD

**Issue by praveennetcity** [jbetancur/react-data-table-component#774]
## Feature Check list

- Is there possibility to make a API call on each row expansion
- How do we pass API data to expandableCompoent for display

**Comment by jbetancur** [comment]
Sure, when you create your `expandableRowsComponent` You can have that component make an API call out when it is rendered (the row is expanded) `expandableRowsComponent` also has access to the row data
