### ISSUE TITLE
sortServer does not disable internal sorting

### ISSUE THREAD

**Issue by elben10** [jbetancur/react-data-table-component#775]
## Issue Check list
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
Internal sorting is not disabled when using `sortServer`. It seems that the internal sorting was disabled in version 6, but in version 7 internal sorting is not disabled when receiving `sortServer`

## To Reproduce
1. [Working example](https://codesandbox.io/s/react-data-table-sandbox-forked-uhxce?fontsize=14&hidenavigation=1&theme=dark) version 6.11.6
2. [Non Working example](https://codesandbox.io/s/react-data-table-sandbox-forked-ueqbs?fontsize=14&hidenavigation=1&theme=dark) version 7.0.0-alpha-5

## Expected behavior
Internal sorting is disabled when receiving `sortServer`

## Code Sandbox, Screenshots, or Relevant Code
Two code sandboxes is provided in the `To Reproduce` section

## Versions (please complete the following information)
 - React: 16.13.1
 - Styled Components: 5.1.1
 - OS: iOS
 - Browser: Chrome

## Additional context
No additional context

**Comment by jbetancur** [comment]
Nice catch and thank you for providing details. I've added this as a bug to the `next` branch and will have a fix in alpha 6

**Comment by jbetancur** [comment]
Fixed in https://github.com/jbetancur/react-data-table-component/pull/776
