### ISSUE TITLE
RDT has peer dependency of styled-components@>= ^4.0.0

### ISSUE THREAD

**Issue by Intelliflex** [jbetancur/react-data-table-component#779]
Can package.json of RDT be changed to allow version 5 of styled components?
I am using V5.2.1 this and it seems to be OK

**Comment by jbetancur** [comment]
@Intelliflex yes RDT is meant to work with the latest styled-components so it's safe to use it (I always use the latest) . But yea it looks like the `peerDependancy` needs to be updated. I'll add this to work being done on the next branch

**Comment by jbetancur** [comment]
fixed in alpha-8
