### ISSUE TITLE
Center in column definition only centers body not header in version 7

### ISSUE THREAD

**Issue by elben10** [jbetancur/react-data-table-component#780]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
The header is not centered in version 7

## To Reproduce
1. [Working example](https://codesandbox.io/s/react-data-table-sandbox-forked-5ittn?fontsize=14&hidenavigation=1&theme=dark) - Version 6.11.6
2. [Non working example](https://codesandbox.io/s/react-data-table-sandbox-forked-zw23i?fontsize=14&hidenavigation=1&theme=dark) - Version 7.0.0-alpha-6

## Expected behavior
The header should also be centered

## Code Sandbox, Screenshots, or Relevant Code
A working and a non working example is available in the `To Reproduce` section

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+): 16.13.1
 - Styled Components: 5.1.1
 - OS: [e.g. iOS]: iOS
 - Browser [e.g. chrome, safari, firefox]: Chrome

## Additional context
None

**Comment by jbetancur** [comment]
Thank you for logging this! Def a bug that will be fixed in alpha-7

**Comment by jbetancur** [comment]
This has been fixed in alpha-7
