### ISSUE TITLE
React.Children.only expected to receive a single React element child error in <Themeprovider Component>

### ISSUE THREAD

**Issue by praveennetcity** [jbetancur/react-data-table-component#781]
I am trying to use a React DataTable , It works as expected when try  with SandBox. 

When  trying to integrate with the Application getting the below error.

<Uncaught Error > : Error React.children.only expected to receive a Single React element Child
The above error occurred in <ThemeProvider> component.

I am using react Version : 16.13.0

import React, {Component} from 'react';
import DataTable from 'react-data-table-component';
import Output from '../UserQuery/UserQuery';

class Table extends Component {

    state = {
        columns :  [
            {
              name: 'Title',
              selector: 'title',
              sortable: true,
            },
            {
              name: 'Year',
              selector: 'year',
              sortable: true,
              right: true,
            },
          ],
        data : [{ id: 1, title: 'AVVDDF the Barbarian', year: '1982' },
        { id: 2, title: 'Conan the Barbarian', year: '1982' },
        { id: 3, title: 'Aonan the Barbarian', year: '1982' }
       
    }

    render() {
      return (
       
        <DataTable
          title="Test Movies"
          columns={this.state.columns}
          data={this.state.data}
          expandableRows
          expandableRowsComponent = {<Output/>}
        />
        
      )
      }
    }

export default Table;

**Comment by jbetancur** [comment]
Hard to say without more detail/example but I would check `expandableRowsComponent ={<Output/>}`. If you remove it does the error go away? What does that component look like?

**Comment by praveennetcity** [comment]
> Hard to say without more detail/example but I would check `expandableRowsComponent ={<Output/>}`. If you remove it does the error go away? What does that component look like?

The same works with version 6.11.6 , when  trying to use version 7 getting this issue.
