### ISSUE TITLE
how can i get references to  rdt_TableBody and rdt_TableHead ?

### ISSUE THREAD

**Issue by GrzegorzNecka** [jbetancur/react-data-table-component#786]
Hello, 

I have added vertical scrolling to rdt_TableBody and rdt_TableHead and try to get references to them using "useRef - such a solution doesn't work. I need a reference because I want to set sync scrolling like in this example https://codepen.io/dannievinther/pen/exvOda.  The fixedHeader property unsatisfactory to me, because my sticky-position reference point must be body.

thaks, for help

**Comment by VirtualDOMinic** [comment]
Sorry to get your hopes up with a notification @GrzegorzNecka - did you find a good solution to getting a ref for the table (ideally without patching the package)? My hopes aren't high but thought I should ask!
