### ISSUE TITLE
TableHead align: Alignement of a column table head

### ISSUE THREAD

**Issue by kevinRoomies** [jbetancur/react-data-table-component#788]
## Feature Check list

- [X] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [X] Read the README to ensure the feature is not already present
- [X] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [X] Considered the value versus complexity for all users of the library as well as library maintenance
- [X] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe
I can align my column content left, center or right but not its header.

## Describe the solution you'd like
A tableHeaderAlign attribute with left|center|right as possible value for the columns prop we're passing to the datatable.

## Describe alternatives you've considered
I didn't find any alternative as I can't access a specific column header with CSS, it's gonna modify them all.

**Comment by tyddynonn** [comment]
Just looking at this component as a replacement for jqGrid - I'd love this feature too.

**Comment by MohsinGhani** [comment]
+1
