### ISSUE TITLE
Set fixed a column in react-data-table-component

### ISSUE THREAD

**Issue by InfiniteCoder96** [jbetancur/react-data-table-component#789]

**Comment by nazimjamil** [comment]
I think this would be a really handy feature.

I'm thinking that where the columns are defined there's a property called `fixed` and this is what is used to identify what column is sticky.

e.g.
```
const columns = [
  {
    name: 'Title',
    selector: 'title',
    sortable: true,
    // the new property
    fixed: true,
  },
  {
    name: 'Year',
    selector: 'year',
    sortable: true,
    right: true,
  },
];
```

Not being super familiar with the codebase, I think the solution may reside with a CSS solution that could possibly `position: sticky` all of the columns flagged as being `fixed`.

**Comment by ttejas123** [comment]
No (Fixed : true) is not working in even if you write any css code still other colums are overlapping each other, and header cells are not fixed as column.
