### ISSUE TITLE
Goruping rows in data table

### ISSUE THREAD

**Issue by thanniermalai** [jbetancur/react-data-table-component#792]
Can we group the rows in the react data table component?

**Comment by davebrown1975** [comment]
Trying to discover this myself,  any comment from the devs would be appreciated. thanks.

**Comment by jbetancur** [comment]
Is there an example of what you mean by "group the rows"? Do you mean row headers or column spans? There are issues to do this col spans in the future, but I have not had the time to dedicate to it.
