### ISSUE TITLE
highlight row during onRowClicked

### ISSUE THREAD

**Issue by feiraelectronica** [jbetancur/react-data-table-component#794]
Hi @jbetancur , is there any ways to highlight the row when using the onRowClicked function? any example?

![image](https://user-images.githubusercontent.com/72189108/115105835-fe46e500-9f93-11eb-926f-4d88a16ff247.png)

for example, i clicked on id 3, the highlight will remain until i pick the next row.

**Comment by jbetancur** [comment]
Only when you use checkboxes there is a selectable rows highlight option

**Comment by feiraelectronica** [comment]
hm so it is not possible? at all?

**Comment by jbetancur** [comment]
Not currently - would need to be a new feature

**Comment by feiraelectronica** [comment]
hope to have it soon. thank you.
