### ISSUE TITLE
Bootstrap Styling........?

### ISSUE THREAD

**Issue by slimandslam** [jbetancur/react-data-table-component#795]
I see your note on how to inject a specific Bootstrap component into a table here:
https://www.npmjs.com/package/react-data-table-component#ui-library-integration

But is there a straightforward way to simply get overall Bootstrap 4 table styling?
https://react-bootstrap.github.io/components/table/

**Comment by jbetancur** [comment]
You mean bootstrap css? RDT is built around css-in-js so making it work with bootstrap is not super straight forward, but as you mentioned you can use bootstrap based react components and then just tweak the overall table styles to match via the customStyles prop.

Perhaps if we had a full on bootstrap example? But again not straightforward either way

**Comment by slimandslam** [comment]
Yes, a full-on bootstrap styling example would be great.
