### ISSUE TITLE
Documentation Bug - unclear how to style "title"

### ISSUE THREAD

**Issue by slimandslam** [jbetancur/react-data-table-component#799]
When styling DataTable:

```
 <DataTable
      title="Your Files"
      customStyles={fileTableStyles}
 />
```

It is unclear how to style the "title". 

Looking here for clues yields nothing that seems to style the "title":
https://github.com/jbetancur/react-data-table-component/blob/master/src/DataTable/styles.js

**Comment by jbetancur** [comment]
https://github.com/jbetancur/react-data-table-component/blob/master/src/DataTable/styles.js#L32

I agree it's not intuitive, but you are looking for the `head` style.

**Comment by slimandslam** [comment]
It was intuitive enough. I had already tried it and if didn't work. The headCells did style correctly though.
Am I doing something wrong?

```
const fileTableStyles = {
  table: {
    style: {
      height: "400px",
    },
  },
  head: {
    style: {
      fontSize: "36px",
      fontWeight: "bold",
    },
  },
  headCells: {
    style: {
      fontSize: "20px",
      fontWeight: "bold",
    },
  }
}

<DataTable
      title="Your Files"
      columns={columns}
      data={tableData}
      customStyles={fileTableStyles}
      fixedHeader={true}
      fixedHeaderScrollHeight="50"
/>
```

**Comment by jbetancur** [comment]
@slimandslam Sorry I was wrong. The style is labeled `header` 🤦 .

```js
	header: {
		style: {
                    fontSize: "36px",
                    fontWeight: "bold",
		},
	},

```

should work

**Comment by slimandslam** [comment]
That worked. I thought I had tried that one too, but I guess not. Thanks!
