### ISSUE TITLE
Sort Icon not changing direction but sorting is working correctly

### ISSUE THREAD

**Issue by fctmolina1135** [jbetancur/react-data-table-component#800]
## Issue Check list
- [ x ] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [ x ] Read the README
- [ x ] You are using React 16.8.0+
- [ x ] You installed `styled-components`
- [ x ] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## To Reproduce
I set the `defaultSortAsc` props to `false`
Table is loaded in descending order -> Click sort icon -> table is loaded in ascending order but icon is still in descending direction -> Click sort icon -> Sort icon changes direction -> Click Sort Icon -> Table is loaded in descending order and sort icon changes direction

## Expected behavior
Sort Icon should point upwards after clicking sort icon to sort it in ascending order

## Code Sandbox, Screenshots, or Relevant Code
```
<DataTable
        columns={columns}
        data={data}
        customStyles={customStyle}
        selectableRows={selectableRows}
        selectableRowsVisibleOnly
        onSelectedRowsChange={onChangeSelect}
        highlightOnHover
        noHeader
        responsive
        sortIcon={<DownwardArrow />}
        defaultSortField={sortField}
        onSort={onSort}
        defaultSortAsc={false}
        onRowClicked={onRowClicked}
        sortServer={sortServer}
      />
```

## Versions (please complete the following information)
 - React: ^16.13.1
 - Styled Components: ^5.1.0
 - OS: [e.g. iOS]: macOS Mojave version 10.14.5
 - Browser: Google Chrome

**Comment by jbetancur** [comment]
Which version of RDT? Are you using the next version 7x alpha or 6x?

**Comment by jbetancur** [comment]
If you are using version version 7 `defaultSortField={sortField`} is now `defaultSortFieldId={columnId]` where the column id is the column you wish to have presorted.  You can either set a column id manually in your column definition or RDT will do it for you starting from id: 1 in order of the columns you specified

**Comment by fctmolina1135** [comment]
@jbetancur The version of RDT we were using was `^6.9.7`. We used the selector as the `sortField` that we passed in the `defaultSortField` as stated in the readme. I updated the version right now using npm, `npm install react-data-table-component`. It was updated to `^6.11.7`.
