### ISSUE TITLE
How to add a row -- best practice?

### ISSUE THREAD

**Issue by slimandslam** [jbetancur/react-data-table-component#803]
There are numerous examples of how to delete rows from a table, but I can't find a
single example of adding a row to an existing table. 

This approach works ok if you want the new row to be at the top of the table.
Note that setTableData is part of a useState() hook. 
Is this a recommended method?

```
const newRow = {
      file: filename,
      status: 'UPLOADED',
      addedOn: Date.now(),
      fileId: fid,
    };

tableData.unshift(newRow);
setTableData(tableData);
```

**Comment by jbetancur** [comment]
In your example, unshift (to the top) or push (to the end) of the array would not work.  You can create a new array and pass it to `setTableData` RDT will re-render the data rows.

There are numerous ways to do this with your example:

You can slice the array which is a trick to create a new array with a new reference:

```js
const newList = tableData.slice(0);

newList .unshift(newRow);

setTableData(newList );
```

Or if  you can use a spread operator `...`:

```js
const newList = [...tableData];

newList .unshift(newRow);

setTableData(newList );
```

**Comment by slimandslam** [comment]
My example does work. Why do you think that it wouldn’t ?
The component looks like:
 `<DataTable title="Files" columns={columns} data={tableData} />;`
