### ISSUE TITLE
defaultSortFieldId triggers client side sorting even when sortServer is on

### ISSUE THREAD

**Issue by jisensee** [jbetancur/react-data-table-component#805]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
Using `defaultSortFieldId` with server side sorting still appears to trigger the build-in client side sorting.

## To Reproduce
Create a server side sorting table and set `defaultSortFieldId`.
See that the selected column is not sorted like the data that is passed in, but sorted by the internal sorting.
Manually specifying a sortingFunction that simply copies the data fixes the issue.

## Expected behavior
The internal sorting should never be triggered when `sortServer` is enabled.

## Code Sandbox, Screenshots, or Relevant Code
https://codesandbox.io/s/react-data-table-sandbox-forked-754lb?file=/src/index.js
Runtime is sorted client side here even though `sortServer` is on.

## Versions (please complete the following information)
See Codesandbox

**Comment by jbetancur** [comment]
Thank you for logging this. I'll take a look at fixing this soon in version 7 and 8
