### ISSUE TITLE
How get click on innermost element of a button

### ISSUE THREAD

**Issue by sineverba** [jbetancur/react-data-table-component#813]
## Issue Check list
- [x ] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [ x] Read the README
- [x ] You are using React 16.8.0+
- [x ] You installed `styled-components`
- [ x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
Not a bug but an issue.

The click event is listend on click on button (every pixel of red square) but not on icon itself.

![enter image description here](https://i.stack.imgur.com/GHlnF.png)

There are my columns:

```js
const columns = [
        {
            name: 'ID',
            selector: 'id',
            sortable: true,
        },
        {
            name: 'Place',
            selector: 'place',
            sortable: true,
        },
        {
            name: 'Created at',
            sortable: true,
            selector: 'created_at',
            cell: row => new Date(row.created_at).toLocaleDateString()
        },
        {
            name: '',
            sortable: false,
            cell: () => <Button variant="danger" data-tag="allowRowEvents" data-action="delete"><FontAwesomeIcon icon={faTrash} /></Button>,
        }
    ]
```
And in another separate component this is the relevant part of my Datatable:

```js
const handleRowClicked = ({id}, e) => {
        e.stopPropagation()
        const action = e.target.getAttribute('data-action')
        switch (action) {
            case 'show':
                props.openModalDetail(id);
            break;
            case 'delete':
                props.delete(id)
            break
            default:
                return
        }
        return
    }
```

I did try also to move the `data-tag="allowRowEvents"` down to the icon OR up to another `<div>` wrapping the button, without luck.

## Versions (please complete the following information)
 - React  17.0.2
 - Styled Components 5.3.0
 - OS: Ubuntu
 - Browser Chrome

**Comment by jbetancur** [comment]
`allowRowEvents` simply just allow forwarding the table row click events down to nested custom `cell` components, so not sure it will be much help here.

Can you set this up in a code sandbox showing the issue? https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
