### ISSUE TITLE
Can't set default sorting

### ISSUE THREAD

**Issue by Miro8896** [jbetancur/react-data-table-component#814]
Hello,

I'm trying to set a default sort to the Table, but for some reason the ```defaultSortField``` field doesn't seem to do anything. This is my code, and how the data is being passed. 
![image](https://user-images.githubusercontent.com/73107396/120642097-207dbf00-c47d-11eb-815c-d53474104c11.png)

Any idea why that might be happening? This is the Table code. 
![image](https://user-images.githubusercontent.com/73107396/120642212-47d48c00-c47d-11eb-9f67-9740d3de8a2c.png)

Let me know if there's anything I can do. Thanks!

**Comment by jbetancur** [comment]
Which version of RDT? In version 7-alpha this has been renamed to `defaultSortFieldId` where you pass the column id (or by default 1,2,e, and so on if no column id is specified.

**Comment by Miro8896** [comment]
Hello @jbetancur,

Thanks a lot for your answer. You are right, I was using the wrong field for it, and the ID of the field was actually the integer index, I wasn't aware which to use. I was using the `defaultSortField` which took on a string, based on the [npmjs.com](www.npmjs.com) documentation: https://www.npmjs.com/package/react-data-table-component (this should perhaps be updated).

Thanks a lot for your help. This can be closed now. 
Kind regards,
Miro.

**Comment by jbetancur** [comment]
NP, yea the npm docs do not reflect the next ver 7 you are using. As a note you can provide your own column ids as well.
