### ISSUE TITLE
Multiple Conditions on ConditionalRowStyles

### ISSUE THREAD

**Issue by ryjogo** [jbetancur/react-data-table-component#826]
## Issue Check list
- [ x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [ x] Read the README
- [ x] You are using React 16.8.0+
- [ x] You installed `styled-components`
- [ x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
ConditionRow Styles is not highlighting a movie above 120mins when a condition exists for that row which is for Alfred Hitchcock. 

## To Reproduce
having two conditions on a single row. 

## Expected behavior
Alfred Hitchcock movie North by Northwest is above 120min, should also be highlighted yellow.

## Code Sandbox, Screenshots, or Relevant Code
https://codesandbox.io/s/conditionalrowstyles-oy9pr?file=/src/index.js

## Additional context
I'm not sure if this is the correct way to achieve what i'm trying to accomplish here.. I wish to highlight on two conditions.

**Comment by ryjogo** [comment]
Actually, after messing around a little i managed to fix it - however, i'm still not 100% sure this is the correct way.. 


`  const conditionalRowStyles = [
    {
      when: (row) => row.runtime > 120 & longRuntimeHighlights,
      style: (row) => ({
        backgroundColor: longRuntimeHighlights ? "yellow" : ""
      })
    },
    {
      when: (row) => row.director === "Alfred Hitchcock" & hitchcockHighlights,
      style: (row) => ({
        backgroundColor: hitchcockHighlights ? "pink" : ""
      })
    }
  ];
`

**Comment by jbetancur** [comment]
Yea something is not right. It seems like having multiple styles overrides the previous. This is definitely unintended. I'll look into it.

Side note, I noticed sorting on run time is now working correctly, it looks like runtime is a string in the sample movie data set and not a number. We can convert it.

```js
  {
    name: "Runtime (m)",
    selector: row => parseInt(row.runtime),
    sortable: true,
    right: true
  }
```

I'd also make sure that when you compare that runtime is wrapped in parseInt

**Comment by jbetancur** [comment]
@ryjogo Actually I think I see the issue. You are replacing the previous style because your `when` prop  is what decides whether to apply the style and you need `when` to also account for your React state `longRuntimeHighlights` and `hitchcockHighlights` (I think you were on the right track with your last example)


Also, you don't need to callback syntax here unless you need access to the row props nor the ternary. Try this:
```js
  const conditionalRowStyles = [
    {
      when: (row) => longRuntimeHighlights && parseInt(row.runtime) > 120, // if false style is never applied
      style: { backgroundColor: "yellow" }
    },
    {
      when: (row) => hitchcockHighlights && row.director === "Alfred Hitchcock", // if false style is never applied
      style: { backgroundColor: "pink" }
    }
  ];
```

or if you prefer the callback syntax
```js
  const conditionalRowStyles = [
    {
      when: (row) => longRuntimeHighlights && parseInt(row.runtime) > 120,
      style: () => ({ backgroundColor: "yellow"}),
    },
    {
      when: (row) => hitchcockHighlights && row.director === "Alfred Hitchcock",
      style: () => ({ backgroundColor: "pink"}),
    }
  ];
```
