### ISSUE TITLE
There is a way to leave the component in Portuguese?

### ISSUE THREAD

**Issue by antoniorrm** [jbetancur/react-data-table-component#83]
I would like to leave the messages as "Rows per page:" in Portuguese.

**Comment by jbetancur** [comment]
Not sure what you are asking?

**Comment by antoniorrm** [comment]
sorry, I improved the question.

**Comment by jbetancur** [comment]
I may look to adding a prop for overriding that value, but I am re-thinking some of the internal architecture.  If you need this ASAP you can just create a custom paging component re: https://github.com/jbetancur/react-data-table-component/issues/84

**Comment by hiukky** [comment]
@jbetancur 
I am brazilian too : )
I discovered this fantatic component yesterday! I'm looking for a way to translate too.
adding a custom prop to the user would be a good ..

example **rowsPerPage = {'Linhas por página'}** 

and set the table with these custom values ​​.... would be a good option in relation to the various languages

**Comment by antoniorrm** [comment]
that's just what I was thinking @hiukky
Atenciosamente,

*Antonio Raimundo Rocha Mendonça*
Estudante de Engenharia de Software UFC/ Campus Quixadá
Técnico em Redes de Computadores



Em qua, 12 de jun de 2019 às 07:47, H i u k k y <notifications@github.com>
escreveu:

**Comment by hiukky** [comment]
@antoniorrm Hello Antonio..
I made some personal changes and I'm using them right now!

as Jhon told me here

https://github.com/jbetancur/react-data-table-component/pull/100#issuecomment-501696408 we can expect this feature in the next updates

vx can check my fork later with this change .. it will be available until the next release

**Comment by jbetancur** [comment]
`paginationComponentOptions` are now available in 1.5.4+
