### ISSUE TITLE
Header for Checkbox Column

### ISSUE THREAD

**Issue by feiraelectronica** [jbetancur/react-data-table-component#833]
Hi @jbetancur , how do i change the header for checkbox column? something like this

![image](https://user-images.githubusercontent.com/72189108/123197946-e08b8400-d4de-11eb-8231-e6f5f86dcc2e.png)

is it possible? 

Thank you.

**Comment by jbetancur** [comment]
It's not something that I believe we would be implemented in RDT. I would make sure the UX makes sense in your app though. IMHO a table is not the best for allow listing "things"

**Comment by feiraelectronica** [comment]
understood. it's okay, nothing big. i can close this now. Thanks John.
