### ISSUE TITLE
On Sort Goes to Page 1 

### ISSUE THREAD

**Issue by Zeeshan49** [jbetancur/react-data-table-component#834]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [ ] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [ ] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Bug
On Sort loses the state 

## To Reproduce
1. Go to 'https://jbetancur.github.io/react-data-table-component/?path=/story/general--kitchen-sink...'
2. Go to page other than 1 
3. Click on sort column  than it will go to again page 1 

## Expected behavior
page should not lose the state 

## Code Sandbox, Screenshots, or Relevant Code
https://jbetancur.github.io/react-data-table-component/?path=/story/general--kitchen-sink

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+)
 - Styled Components
 - Browser [e.g. chrome, safari, firefox]

**Comment by AlexMoutonNoble** [comment]
This isnt my code but this behavior seems reasonable to me.  Theres nothing to say that the items on the 3rd page of a list will be the same when you change the sort order, so staying on the 3rd page is unhelpful.

**Comment by jbetancur** [comment]
@Zeeshan49 this works as designed/intended.

**Comment by Zeeshan49** [comment]
@jbetancur  thank you so much 
and sorry for creating that as an issue

**Comment by Zeeshan49** [comment]
Hi Team,
I m Sorry for that i didn't get that my bad
But you are doing Awesome work and that library is great & very
helpful also easy to use
i work for welbee and now we are also using that library

Thanks.
