### ISSUE TITLE
rdt_TableHeader element styles?

### ISSUE THREAD

**Issue by AlexMoutonNoble** [jbetancur/react-data-table-component#835]
## Feature Check list

- [ X] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [X ] Read the README to ensure the feature is not already present
- [ ] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [X ] Considered the value versus complexity for all users of the library as well as library maintenance
- [X ] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? 
There is a usecase for more elaborate custom styling of elements in the rdt_TableHeader.  (My code is currently using the styled-component hashes and I want to atone.)

## Describe the solution you'd like

Add classes to the immediate children of rdt_TableHeader

## Describe alternatives you've considered

Pushing back on design has not yielded any results.

## Additional context

Happy to make a PR but thought to ask first

**Comment by jbetancur** [comment]
Have you tried the `customStyles` prop?  

https://github.com/jbetancur/react-data-table-component/blob/master/src/DataTable/styles.js

You can override any of these. particularly `header` and `contextMenu` which are children of header.

**Comment by AlexMoutonNoble** [comment]
Thanks Jb. Let me look. Im sorry I missed them!

**Comment by smammadov1994** [comment]
How exactly do you add these changes to the object to datatables? I want to remove the padding on the subheader component.
