### ISSUE TITLE
Single Row Selection Issue (Ref : #497)

### ISSUE THREAD

**Issue by feiraelectronica** [jbetancur/react-data-table-component#837]
Hi @jbetancur ,

You can refer to this sandbox for this issue. currently the problem is, i need to uncheck the checkbox for the first one, and the check the next one, only the value change.

https://codesandbox.io/s/react-data-table-sandbox-forked-lh2pl?file=/src/index.js

**Comment by jbetancur** [comment]
That is most definitely a bug 😞 I should have a fix soon

**Comment by jbetancur** [comment]
fixed in 7.0.0-rc2

**Comment by feiraelectronica** [comment]
Hi @jbetancur . Tested it. Working fine now. Thank you so much. 👍🏻👍🏻👍🏻👍🏻👍🏻
