### ISSUE TITLE
Override default pagination click handlers

### ISSUE THREAD

**Issue by paschaldev** [jbetancur/react-data-table-component#84]
I'll like to use your pagination style but I need to override the whole click handlers so I can paginate over an API.

**Comment by jbetancur** [comment]
Could you provide more details or specific handlers you want to "override"?

Not sure if this helps, but, you have the `onChangePage` and `onChangeRowsPerPage` which you can use on DataTable if you need access to the callback from those handlers.

Also, if you need more control you could provide a custom pagination component using `paginationComponent` and implement whatever methods you want as long as you satisfy the prop requirements

The existing pagination component can be used for reference: https://github.com/jbetancur/react-data-table-component/blob/master/src/DataTable/Pagination.js

**Comment by paschaldev** [comment]
Thanks @jbetancur I just copied the existing Pagination components and edited it to my taste. Works as I want for now.
