### ISSUE TITLE
The component styled.div with the id of "" has been created dynamically

### ISSUE THREAD

**Issue by sarahrara18** [jbetancur/react-data-table-component#840]
Hello everyone, i am using react-data-table component with server side pagination filtering and ordering, everything is working just fine, but ia mgetting these warning that i can't understand how to solve , i looked for a solution but i only found anwers about declaring styled component outside the function , but the problem is i was not me who used styled component , it is react-data-table which is using it .
here is the warnings that i am getting:

`
Keyframes.js:20 The component styled.div with the id of "sc-bdnxRM" has been created dynamically.
You may see this warning because you've called styled inside another component.
To resolve this only create new StyledComponents outside of any render method and function component.
Pe @ Keyframes.js:20
Keyframes.js:20 The component styled.div with the id of "sc-gtsrHT" has been created dynamically.
You may see this warning because you've called styled inside another component.
To resolve this only create new StyledComponents outside of any render method and function component.
Pe @ Keyframes.js:20
Keyframes.js:20 The component styled.div with the id of "sc-dlnjwi" has been created dynamically.
You may see this warning because you've called styled inside another component.
To resolve this only create new StyledComponents outside of any render method and function component.
Pe @ Keyframes.js:20
Keyframes.js:20 The component styled.div with the id of "sc-hKFxyN" has been created dynamically.
You may see this warning because you've called styled inside another component.
To resolve this only create new StyledComponents outside of any render method and function component.
Pe @ Keyframes.js:20
Keyframes.js:20 The component Styled(styled.div) with the id of "sc-eCApnc" has been created dynamically.
You may see this warning because you've called styled inside another component.
To resolve this only create new StyledComponents outside of any render method and function component.
`

could anyone please help me in this one please? i am new to react and react-data-table, i would be very thankful

**Comment by jbetancur** [comment]
@sarahrara18 It's hard to help you if you don't provide more details when opening an issue: e.g. your code or a code sandbox. But off the top of my head, it looks like a styled-components usage issue. This article may prove helpful.

https://github.com/styled-components/styled-components/issues/3117

**Comment by sarahrara18** [comment]
sorry about that, here is my code:

`import React,{ useState, useEffect ,useCallback, Fragment,useMemo} from "react";
import DataTable from "react-data-table-component";
import ContentEditable from 'react-contenteditable';
import TextField from '@material-ui/core/TextField';
import Grid from '@material-ui/core/Grid';
import {Search,Lock,LockOpen} from '@material-ui/icons';
import DraggableDialog from './modals/ref_mrq_add'
import axios from "axios"


export default function AdvancedPaginationTable (){
  const param=require('/param.json')
  const Gfunc=require('/Gfunc')
  const librery=require('./data_table_librery')

  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(false);
  const [totalRows, setTotalRows] = useState(0);
  const [perPage, setPerPage] = useState(10);
  const [currentPage, setCurrentPage] = useState(1);
  const [search,setSearch]=useState('');
  const service='service'
  
 
  const fetch= useCallback(async(page,servic = service, size = perPage) => {
    //fetch data
  },[Gfunc,perPage]);

  useEffect(() => {
    fetch(1);
  }, [fetch]);
  

const handleOnEdit=async(e,row)=>{
    //some code

}

  const columns =useMemo(
    () => [   
      {
          name: "NOM",
          selector: "marque",
          sortable: true,
          cell: (row, index, column, id) => {

            return (
            <ContentEditable
            html={row.marque}
            name="mrq"
            data-column="item"
            className="content-editable"
            disabled={false} 
            onBlur={e => handleOnEdit(e,row,column,e.target.value)}
          />
             );
           },
      },
      {
        name: "DATE",
        selector: "date",
        sortable: true
      },
      {
        name: "UTILISATEUR",
        selector: "user",
        sortable: true
      }
    ],[handleOnEdit]);
  
  const  conditionalRowStyles  =  [ 
      {
        when: row => row.activ!==1,
          style: {
                backgroundColor: "lightgray",
                color:"gray"
          }
      }
    ]; 
 
  const handleOnSort=async(column, sortdirection,page=currentPage, size = perPage)=>{
          //handle sort 
          
  }
  
  const handleSearch=async(e,page=currentPage, size = perPage)=>{
    //handle search
}
 function handlePageChange (page) {
  fetch(page);
  setCurrentPage(page);
};

 const handlePerRowsChange = async (newPerPage, page) => {
  fetch(page, newPerPage);
  setPerPage(newPerPage);
};
function liveSearch(e,search){
  //some code
}
  
  return (
    <Fragment>
        <div className='table-header'>
          <div className='btn'><DraggableDialog /></div>
          <div className='search'>
            <Grid container spacing={1} alignItems="flex-end" onKeyUp={e=>liveSearch(e)} placeholder='rechercher' onChange={e =>setSearch(e.target.value)}>
              <Grid item>
                <Search />
              </Grid>
              <Grid item>
                <TextField id="input-with-icon-grid" label="search" />
              </Grid>
            </Grid>
            </div>
        </div>
        
            <DataTable 
              columns={columns}
              data={data}
              noDataComponent={param.ErreurData}
              paginationRowsPerPageOptions={[10, 15, 20,25,30,-1]} // i also want to label -1 as All 
              progressPending={loading}
              pagination
              paginationServer
              paginationTotalRows={totalRows}
              paginationDefaultPage={currentPage}
              onChangeRowsPerPage={handlePerRowsChange}
              onChangePage={handlePageChange}
              selectableRows
              onSort={handleOnSort}
              onSelectedRowsChange={({ selectedRows }) => console.log(selectedRows)}
                />
    </Fragment>    

  );
}`

the problem is it was not me who used styled component so i didn't know how to fix that ,react-data-table-component is using it so i wonder what it could be the problem , maybe i missed something

**Comment by jbetancur** [comment]
The code looks fine, but I don't see all the components? Are you sure you are not nesting styled components within a render in the components you are importing?

Refer to the following issue on the matter from styled-components: https://github.com/styled-components/styled-components/issues/3117

**Comment by sarahrara18** [comment]
@jbetancur  yeah i didn't use styled component at all, and when i tried to look for where component style is used i found that it is in data-table that's why i posted the issue here. about the component these are all the component i used

**Comment by sarahrara18** [comment]
@jbetancur hello agin, i wanted to add to my problem, you said that maybe i have some other component that maybe causing this problem, so i tried and deleted everything , i even deleted the dataTable, but the warnings were still there, it only disapeard as soon as i deleted the import of DataTable, and when i add it back they appear again

**Comment by sarahrara18** [comment]
@jbetancur I solved my problem by adding import "react-data-table-component"; in App.js ,but  i don't really unserstand what happened
