### ISSUE TITLE
[FEATURE]: Disable sort/restore initial state

### ISSUE THREAD

**Issue by AXeL-dev** [jbetancur/react-data-table-component#841]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

I just noticed that there is no way to cancel sorting & restore the original/initial state.

## Describe the solution you'd like

Asc & desc sort icons to be deactivated when we click on them? 

## Describe alternatives you've considered

Since first user click sorts by asc direction & the 2nd sorts by desc, maybe just cancel sort on the third click?

Example: https://github.com/AXeL-dev/react-data-table-component/commit/1e0217c1604757169e81a651b7c4eafb06ff4165

**Comment by jbetancur** [comment]
Yes, I've actually thought about adding the ability to "reset" the sort on the 3rd click. My only hesitation was that UX-wise there does not seem to be a consensus on what the best behavior is? Some libraries do and some don't. In any case,  I'll add this as a feature to v7

**Comment by AXeL-dev** [comment]
> Yea, I've actually thought about adding the ability to "reset" the sort on the 3rd click. My only hesitation was that UX-wise there does not seem to be a consensus on what the best behavior is?

Indeed, from a UX view using a third click might not be the best solution, one other possibility is to have both asc & desc icons which can be toggled on icon click, as below:

![image](https://user-images.githubusercontent.com/30635693/124838922-b7a7cc00-df7f-11eb-8b99-f5fbcbe2ce6e.png)

**Comment by Mangor1no** [comment]
Yes, I'm absolutely agree that's the missing feature. Looking forward to see this one to be applied into the library.
