### ISSUE TITLE
[SELECTOR]: Warning in selector

### ISSUE THREAD

**Issue by janaanimator** [jbetancur/react-data-table-component#845]
Sandbox Link: https://codesandbox.io/s/ccyuu

I have used the sample code from the sandbox. After I run its throws me an error like this.

" **Warning: title is a string based column selector which has been deprecated as of v7 and will be removed in v8. Instead, use a selector function e.g. row => row[field]...** "

Version:
React : 17.0.2
React-Data-table-Component : 7.0.0-rc2

Browser View:
![error-1](https://user-images.githubusercontent.com/15716445/125666630-4b98eba0-e74e-4955-9a7c-1f1cf4296b97.PNG)

Code View:
![error-2](https://user-images.githubusercontent.com/15716445/125666741-dde8bb5f-af1b-4977-bc57-426690edf915.PNG)

**Comment by jbetancur** [comment]
Thanks for raising this. The codesandbox just needs to be updated to to functions. Eg row => row.title

**Comment by jbetancur** [comment]
Sandbox updated
