### ISSUE TITLE
unable to change fontWeight

### ISSUE THREAD

**Issue by changsheng1239** [jbetancur/react-data-table-component#846]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
Using the customStyles below, I was able to change the fontSize of both header and headCells but not fontWeight. Both the header and headCells are having another fontWeight properties that are overriding its fontWeight properties.

```js
const customStyles = {
	header: {
		style: {
			fontSize: 30,
			fontWeight: 1000,
		},
	},
	headCells: {
		style: {
			fontSize: 14,
			fontWeight: "bold",
		},
	},
};
```

![image](https://user-images.githubusercontent.com/29444534/125728749-e3945e00-de40-4c9c-bba6-d0fec36d6aec.png)

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+) 17.0.2
 - Styled Components 5.3.0
 - RDT 7.0.0-rc2
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari, firefox] Brave (chromium)

**Comment by mmtang** [comment]
I'm running into the same issue. fontSize works, but fontWeight does not.

**Comment by hsdhillon** [comment]
+1

**Comment by ttejas123** [comment]
Same But, I Only want to apply this style to specific headCell

**Comment by ttejas123** [comment]
I think Conditional Style Work Well But it's not Available for Head cells

**Comment by jbetancur** [comment]
It's a bug - very easy to fix. I'll have this addressed in the next release
