### ISSUE TITLE
Putting filtering box under column name

### ISSUE THREAD

**Issue by somguyth** [jbetancur/react-data-table-component#849]
Is there a way we can move the filter box into the column header (in this case, under the "Name" column header)?

![image](https://user-images.githubusercontent.com/37128022/126040741-64f0324a-3db9-4db3-8271-85da83155d23.png)

It's a feature in `react-table`: https://react-table.tanstack.com/docs/examples/filtering

![image](https://user-images.githubusercontent.com/37128022/126040773-1387fc37-5cfb-479c-b8fe-b3d9c0c39280.png)

This is ideal if we want to have multi-column filtering instead of it applying only to a single column.

**Comment by jbetancur** [comment]
you should be able to pass a component to `title`.

**Comment by davebrown1975** [comment]
> you should be able to pass a component to `title`.

What is 'title'?   Thanks
