### ISSUE TITLE
How to Filter ?

### ISSUE THREAD

**Issue by cgarrotti** [jbetancur/react-data-table-component#85]
How to Filter ?

**Comment by jbetancur** [comment]
What kind of filtering? I was planning on per column filtering with a callback that you could use to control filtering from within your component. onFilter(column, value)

I'm also open to PR's on this :)

Although built in filtering is not currently supported, you can use a custom`subHeaderComponent` or the `actions` property to place your own filtering fields in the table headers. Changing your data in your component should update the data in DataTable accordingly.

**Comment by jbetancur** [comment]
Closing this as it was a question.
