### ISSUE TITLE
[FEATURE]: [SHORT DESCRIPTION]

### ISSUE THREAD

**Issue by GrzegorzNecka** [jbetancur/react-data-table-component#851]
Hi, is there way to add on a selected header cell a specific component instead a 'string"? I have to add anchor with icon to one header cel.

![image](https://user-images.githubusercontent.com/34622107/126174840-b8aa59be-c88f-4a2f-b8f0-b3d48264c70a.png)

**Comment by jbetancur** [comment]
Should be. In addition to a string,  `title` also takes a component. Admittedly, the naming is not intuitive but this part of a refactor I am working on in version 7 or 8

**Comment by GrzegorzNecka** [comment]
Yes, it works: D. I had the old version "7.0.0-alpha-4" and when I changed it to "^ 7.0.0-rc2" it worked. 

Thank You very very much
