### ISSUE TITLE
problem with  Expanded Row  ? 

### ISSUE THREAD

**Issue by GrzegorzNecka** [jbetancur/react-data-table-component#852]
I use "react-data-table-component": "^7.0.0-rc2"

i set expanding row the same as in storybook
![image](https://user-images.githubusercontent.com/34622107/126387433-e52a0a6d-0c20-4529-b0d9-570dfc843253.png)

and that is the component 
![image](https://user-images.githubusercontent.com/34622107/126387522-118d2287-c2c3-4c2d-a701-8e7e4e3c9ab8.png)

when click on expand icon react throw this bug :
![image](https://user-images.githubusercontent.com/34622107/126387697-ae507209-5b06-4ca5-8fea-0b6004198b26.png)

i used this code with previous version of data table component and then it  worked !
I tried to use a class component but it still not working 

please help me

**Comment by jbetancur** [comment]
You're getting this error because you are passing the component as JSX but you just need to pass the function.  E.g.

'expandableComponent={DataTableSummary}'

**Comment by GrzegorzNecka** [comment]
Mate, You're saving my life again .. thank you very much
