### ISSUE TITLE
Pagination : Separate out Page and rows per page

### ISSUE THREAD

**Issue by feiraelectronica** [jbetancur/react-data-table-component#855]
Hi @jbetancur ,

can we separate out the pagination into two? like this.

![image](https://user-images.githubusercontent.com/72189108/126626949-a0312156-c804-4133-bac7-136172762890.png)

so it can be configured if they want to put the rows per page at the top, and the pagination at the bottom. I'm not sure if RDT already has this feature or not. this will give flexibility to the user to configure wherever they want to put these 2 items (top left/top right/top center/bottom left/bottom right/bottom center). thank you.

**Comment by jbetancur** [comment]
You should be able to build your own custom pagination component per the docs. You can look at the source code for the built in pagination for reference.

**Comment by feiraelectronica** [comment]
which one ya? paginationComponentOptions? can show me an example of it, please?

**Comment by feiraelectronica** [comment]
how do I style all the pagination content? to put border, align, and everything.
