### ISSUE TITLE
react-data-table-component Pagination 

### ISSUE THREAD

**Issue by mary118** [jbetancur/react-data-table-component#857]
Hello, i'm still a beginner in react component , I wanted to use the server-side pagination to display all the rows of the table but the problem starts there when I add (-1)   ' paginationRowsPerPageOptions={[10,20,30,-1]}' as a value of 'all' it doesn't  work exectaly ,knowing that I have associated this value in the database to return all the rows

![issue](https://user-images.githubusercontent.com/87940290/126953089-0ae7eb5e-c199-4870-8e9d-4839290410bb.PNG)

**Comment by jbetancur** [comment]
Please refer to https://github.com/jbetancur/react-data-table-component#pagination `paginationComponentOptions` for enabling `All` and also for localization

**Comment by jbetancur** [comment]
Just set `selectAllRowsItem` to true

For example



```js
const paginationOptons = { rowsPerPageText: 'Elements par page:', rangeSeparatorText: 'sur', selectAllRowsItem: true, selectAllRowsItemText: 'Toute' }

<DataTable ... pagationComponentOptions={paginationOptions} />
```

**Comment by mary118** [comment]
@jbetancur thanx you

**Comment by mary118** [comment]
@jbetancur thank you
