### ISSUE TITLE
[FEATURE]: Collapse all expanded rows when page changes

### ISSUE THREAD

**Issue by fm1randa** [jbetancur/react-data-table-component#858]
## Describe the solution you'd like

Collapse all expanded rows when page changes. I'm facing a problem that the expand component still the same when navigating through table pages when he should change for every row.
e.g: If user expands the first row of page 1 and navigates to page 2, the second page's first row will be expanded too. It can be a problem if you can't update `ExpandableRowsComponent` when `data` props changes.

**Comment by lok225** [comment]
I know I am a bit late, but did you find a solution to this @fm1randa ? Currently dealing with the same problem. It isn't really a nice user experience..
