### ISSUE TITLE
Using styled components, how can I add new css properties to the Table Row?

### ISSUE THREAD

**Issue by JugglerX** [jbetancur/react-data-table-component#86]
Using styled components, how can I add _new_ css properties to the Table Row? (as opposed to just overriding existing ones, I can achieve that with the theme)

In a fashion similar to below.

```
import DataTable from 'react-data-table-component';

const MyDataTable = styled(DataTable)`
  background: blue;
 .TableRowClass {
    float: left
 }
`;

class DashboardPage extends React.Component {
  render() {
    return (
      <div className="page page-dashboard">
            <MyDataTable spacing title="Arnold Movies" columns={columns} data={data}  />
      </div>
    );
  }
}
```

I'd like to do this without modifying the source code of the library.

Some of the sub components (like the rows) do not have class that I can target.

I have explored using the component itself in the styled template literal, ie

```
import TableRowStyle from 'react-data-table-component';

const MyDataTable = styled(DataTable)`
  background: blue;
  ${TableRowStyle} {
    float: left
  }
`;
```

But I cannot seem to get that work. I think for a start the import doesnt even work because the sub components are not exported.

Any feedback on how to achieve this is welcome. Thankyou.

**Comment by jbetancur** [comment]
I could pass through something like a `classNameRow` prop so that you can apply custom css to TableRow. Would that work?

**Comment by JugglerX** [comment]
It seems like you are confirming there is no way for me to target the TableRow unless there are changes to the library components themselves.

If that is the case, then I'd suggest you just add preset classes to all the components that are rendered. I believe the TableCell already has one? So just something like that on each of the key component divs would be sufficient?

**Comment by jbetancur** [comment]
Ye, pretty much.

So, for the root component, I'll add a top-level className, something like e.g. `<div className="rdt_TableRow" />`. While a collision is unlikely I would feel better with some unique prefix.

This is not a quick change so look for it this week. PR's are welcome too :)
