### ISSUE TITLE
Specific Column Sticky

### ISSUE THREAD

**Issue by ttejas123** [jbetancur/react-data-table-component#860]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [ ] Considered if this can be a storybook or documentation example
I want to make Specific Columns Sticky like Excel Table, I Tried to Adding Style in Column Cells But it's only Applicable for Data cell I Also Want Header Cell to Do the same Please Help

**Comment by caseyjhol** [comment]
I'm looking for this exact thing. I'm trying to keep the leftmost column in place when scrolling horizontally. I'm using style on the column definition to accomplish this:

```js
			style: {
				position: "sticky",
				left: 0,
				zIndex: 1,
			},
```

However, this has no effect on the header cell, and while there is the option to override styling for all header cells, there's no way to target just the first header cell. I ended up applying a class on a div that wraps the table, and set the style via the rdt_TableCol class.

```js
		tableWrapper: {
			width: "100%",
			display: "grid",
			marginTop: 10,
			borderRadius: "0 0 5px 5px",
			boxShadow: "0px 3px 6px rgba(0, 0, 0, 0.16)",

			"& .rdt_TableCol:first-child": {
				position: "sticky",
				left: 0,
				zIndex: 1,
			},
		},
```

This seems potentially brittle/prone to error, but it works.

**Comment by ttejas123** [comment]
Thank you for your respnse, I tried to Apply this and it worked but, I want to Apply this style to (second-child) & (fourth-child)

**Comment by ttejas123** [comment]
`const customStyles = {
  headRow: {
    when: row => row.id === 5033,
    style: {
      paddingTop: '2rem',
      paddingBottom: '2rem',
      alignItems: 'center',
      "& .rdt_TableCol:first-child, second-child": {
        position: "sticky",
        left: 0,
        zIndex: 1
      }
    }
  },
  headCells: {
    style: {
      fontSize: '12px',
      fontWeight: 500,
      paddingTop: '5rem',
      paddingBottom: '5rem'
    }
  }
}`

**Comment by ttejas123** [comment]
`const customStyles = {
  headRow: {
    when: row => row.id === 5033,
    style: {
      paddingTop: '2rem',
      paddingBottom: '2rem',
      alignItems: 'center',
      "& .rdt_TableCol:first-child, second-child": {
        position: "sticky",
        left: 0,
        zIndex: 1
      }
    }
  },
  headCells: {
    style: {
      fontSize: '12px',
      fontWeight: 500,
      paddingTop: '5rem',
      paddingBottom: '5rem'
    }
  }
}`

I applied This Way

**Comment by ttejas123** [comment]
But it's Not working

**Comment by ttejas123** [comment]
Thank You for This solution. This Helped me a Lot.

**Comment by jbetancur** [comment]
Is there only ever a need to freeze the first column? I could possibly make this a feature

**Comment by caseyjhol** [comment]
That's all I need, but I could see how somebody might want more columns to be sticky as well (e.g. the first 2).

**Comment by murilo-campaner** [comment]
Hmm... It's related to something like this?

https://github.com/jbetancur/react-data-table-component/pull/967

**Comment by irehmanullah** [comment]
Is this issue solved?

**Comment by diwosuwanto** [comment]
@caseyjhol solutions are works, 

use `.rdt_TableCol` selector for styling the header and `rdt_TableCell` for styling the cell table.

This css will sticky the first column of header and row
```css
.rdt_TableCol:first-child,
.rdt_TableCell:first-child {
  position: sticky;
  left: 0;
  z-index: 1;
  background: inherit;
}
```

This css will sticky the first and second column of header and row
```css
.rdt_TableCol:first-child,
.rdt_TableCell:first-child,
.rdt_TableCol:nth-child(2),
.rdt_TableCell:nth-child(2) {
  position: sticky;
  left: 0;
  z-index: 1;
  background: inherit;
}

.rdt_TableCol:nth-child(2),
.rdt_TableCell:nth-child(2) {
  left: 48px;
}
```

**Comment by prasannakulal16** [comment]
> Is there only ever a need to freeze the first column? I could possibly make this a feature

Any update on this?
