### ISSUE TITLE
Conditional Style for header Cells

### ISSUE THREAD

**Issue by ttejas123** [jbetancur/react-data-table-component#861]

**Comment by ttejas123** [comment]
I want to Give custom Style to Specific Header Cell / Head Cell same as Data cell

**Comment by jbetancur** [comment]
https://github.com/jbetancur/react-data-table-component#overidding-styling-using-css-in-js

**Comment by ashokraghu14** [comment]
@jbetancur The documentation doesn't have a conditional styling for the col header. I have a use case where I need to give a color for a row header based on a column object property. For example I have a below column array:
`const column = [{name:"column1"
                    selector: "col1",
                    required: true},{name:"column2"
                    selector: "col2",
                    required: false}]`

So when required is true, I should show a color( eg: red) and when it's false, it should be green.

cc:// @ttejas123
