### ISSUE TITLE
Column name need to be more extensible

### ISSUE THREAD

**Issue by arifemir** [jbetancur/react-data-table-component#862]
## Is your feature request related to a problem? Please describe
I can not set react node for column name property.

## A clear and concise description of what the feature is.
I think column name needs to be more flexible, at least it should be able to accept react node

**Comment by jbetancur** [comment]
`name` takes a React Component. Otherwise, please provide more specific detail or a use case with some code to show what you want.

**Comment by arifemir** [comment]
```
{
  selector: 'name',
  name: () => <b>name</b>,
  ...
}
```

its render nothing name must be inside the pointed area its true ?
![image](https://user-images.githubusercontent.com/53263905/129460382-fc64a0c3-927b-4aa2-acab-07898ed01f90.png)

**Comment by jbetancur** [comment]
Pass it a React component 

```js
const Name = () => <b>name</b>

{
  selector: 'name',
  name: <Name />,
  ...
}
```

**Comment by arifemir** [comment]
hmm thanks it's my bad. I wondering about why does not accept jsx
