### ISSUE TITLE
[FEATURE]: [The format of the range text of pagination]

### ISSUE THREAD

**Issue by ryan85118** [jbetancur/react-data-table-component#863]
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

Hope to add formatting options to range text in pagination.

## Describe the solution you'd like

Maybe we can add formatting function to paginationComponentOptions.

## Describe alternatives you've considered

Maybe we can add formatting string in paginationComponentOptions.

## Additional context

![Screen Shot 2021-08-10 at 3 29 05 AM](https://user-images.githubusercontent.com/54787650/128763125-75e71bac-609c-4c0c-b14e-a31fbea26d51.png)

**Comment by jbetancur** [comment]
This is an interesting idea. The code that does this currently:

```js
	const range =
		currentPage === numPages
			? `${firstIndex}-${rowCount} ${options.rangeSeparatorText} ${rowCount}`
			: `${firstIndex}-${lastIndex} ${options.rangeSeparatorText} ${rowCount}`;
```

Could potentially be a formatter function. We wouldn't need the `rangeSeparatorText` option. This would be the default:

```js
({ count, first, last, currentPage, totalPages } ) => {
   return  currentPage === totalPages ? `${firstIndex}-${rowCount} to ${rowCount}` : `${firstIndex}-${lastIndex} to ${rowCount}`;
}
```

Is this what you are proposing?

**Comment by ryan85118** [comment]
> This is an interesting idea. The code that does this currently:
> 
> ```js
> 	const range =
> 		currentPage === numPages
> 			? `${firstIndex}-${rowCount} ${options.rangeSeparatorText} ${rowCount}`
> 			: `${firstIndex}-${lastIndex} ${options.rangeSeparatorText} ${rowCount}`;
> ```
> 
> Could potentially be a formatter function. We wouldn't need the `rangeSeparatorText` option. This would be the default:
> 
> ```js
> ({ count, first, last, currentPage, totalPages } ) => {
>    return  currentPage === totalPages ? `${firstIndex}-${rowCount} to ${rowCount}` : `${firstIndex}-${lastIndex} to ${rowCount}`;
> }
> ```
> 
> Is this what you are proposing?

This looks great, if you don’t have time I can try,
I hope to use the cool features earlier

**Comment by jbetancur** [comment]
@ryan85118 go for it. You can probably start by defining the default function in the Pagination Component and/or defaultprops.

**Comment by ryan85118** [comment]
@jbetancur 
I have some problem when yarn install.
<img width="1126" alt="Screen Shot 2021-08-30 at 11 40 26 AM" src="https://user-images.githubusercontent.com/54787650/131281926-df6fa74d-46b9-4deb-80b2-6dcf85d5b33e.png">

**Comment by ryan85118** [comment]
@jbetancur  need help

**Comment by jbetancur** [comment]
As the error reads you  are running too old a version of nodejs - I would recommend upgrading to node v14 I will reflect this in the docs
