### ISSUE TITLE
Custom Pagination Component Docs Confusion

### ISSUE THREAD

**Issue by smammadov1994** [jbetancur/react-data-table-component#870]
Hi everyone, 
The documentation for the react pagination component is unclear. What does it mean to satisfy the following API (proptypes). Like do I need to create my own functions that handle the page and do all of the transitions. Is there no way to access the functionality of that and just provide it to a basic html pagination component for it to work? I am really confused on this.

**Comment by jbetancur** [comment]
Agree the docs are not clear on this. I am working on new documentation, but time has not been on my side.

The `paginationComponent` prop allows you to pass whatever pagination component want and allows you to access internal props used in RDT for tracking pagination. In the example below we use material-ui pagination to replace RDT pagination. Notice that `rowsPerPage, rowCount, onChangePage, onChangeRowsPerPage, currentPage ` are props that you can pass to material ui's pagiantion component.

```js
const CustomMaterialPagination = ({ rowsPerPage, rowCount, onChangePage, onChangeRowsPerPage, currentPage }) => (
	<TablePagination
		component="nav"
		count={rowCount}
		rowsPerPage={rowsPerPage}
		page={currentPage - 1}
		onChangePage={onChangePage}
		onChangeRowsPerPage={({ target }) => onChangeRowsPerPage(Number(target.value))}
		ActionsComponent={TablePaginationActions}
	/>

...
const CustomPaginationTable = () => (
	<DataTable
		title="Movie List"
		columns={columns}
		data={data}
		pagination
		paginationComponent={CustomMaterialPagination}
	/>
);
);
```


Here is a full working example:

```js
import React from 'react';
import TablePagination from '@material-ui/core/TablePagination';
import IconButton from '@material-ui/core/IconButton';
import FirstPageIcon from '@material-ui/icons/FirstPage';
import KeyboardArrowLeft from '@material-ui/icons/KeyboardArrowLeft';
import KeyboardArrowRight from '@material-ui/icons/KeyboardArrowRight';
import LastPageIcon from '@material-ui/icons/LastPage';
import { getNumberOfPages } from '../../../src/DataTable/util';
import DataTable from '../../../src/index';
import data from '../constants/sampleMovieData';

const columns = [
	{
		name: 'Title',
		selector: 'title',
		sortable: true,
	},
	{
		name: 'Director',
		selector: 'director',
		sortable: true,
	},
	{
		name: 'Year',
		selector: 'year',
		sortable: true,
	},
];

function TablePaginationActions({ count, page, rowsPerPage, onChangePage }) {
	const handleFirstPageButtonClick = () => {
		onChangePage(1);
	};

	// RDT uses page index starting at 1, MUI starts at 0
	// i.e. page prop will be off by one here
	const handleBackButtonClick = () => {
		onChangePage(page);
	};

	const handleNextButtonClick = () => {
		onChangePage(page + 2);
	};

	const handleLastPageButtonClick = () => {
		onChangePage(getNumberOfPages(count, rowsPerPage));
	};

	return (
		<>
			<IconButton onClick={handleFirstPageButtonClick} disabled={page === 0} aria-label="first page">
				<FirstPageIcon />
			</IconButton>
			<IconButton onClick={handleBackButtonClick} disabled={page === 0} aria-label="previous page">
				<KeyboardArrowLeft />
			</IconButton>
			<IconButton
				onClick={handleNextButtonClick}
				disabled={page >= getNumberOfPages(count, rowsPerPage) - 1}
				aria-label="next page"
			>
				<KeyboardArrowRight />
			</IconButton>
			<IconButton
				onClick={handleLastPageButtonClick}
				disabled={page >= getNumberOfPages(count, rowsPerPage) - 1}
				aria-label="last page"
			>
				<LastPageIcon />
			</IconButton>
		</>
	);
}

const CustomMaterialPagination = ({ rowsPerPage, rowCount, onChangePage, onChangeRowsPerPage, currentPage }) => (
	<TablePagination
		component="nav"
		count={rowCount}
		rowsPerPage={rowsPerPage}
		page={currentPage - 1}
		onChangePage={onChangePage}
		onChangeRowsPerPage={({ target }) => onChangeRowsPerPage(Number(target.value))}
		ActionsComponent={TablePaginationActions}
	/>
);

CustomMaterialPagination.propTypes = {
	rowsPerPage: PropTypes.number.isRequired, // calculated rows per page state from DataTable
	rowCount: PropTypes.number.isRequired, // calculated row count from DataTable
	onChangePage: PropTypes.func.isRequired, // you want to "callback" the updated page number to DataTable so it can update its state
	onChangeRowsPerPage: PropTypes.func.isRequired, // you want to "callback" the updated rows per (newRowsPerPage, currentPage) to DataTable so it can update its state
	currentPage: PropTypes.number.isRequired, // the current page state from DataTable
};

const CustomPaginationTable = () => (
	<DataTable
		title="Movie List"
		columns={columns}
		data={data}
		pagination
		paginationComponent={CustomMaterialPagination}
	/>
);
```

Hope that helps!

**Comment by smammadov1994** [comment]
@jbetancur I am having an issue where the index of 0 is being passed in for the handlepreviousbuttonclick even if the button is disabled it is firing the function and causing too many rerenders. What is a good way to solve this, it seems to be the variable "page".

**Comment by jbetancur** [comment]
I'm not sure I follow. Are you saying the example above is doing that? Do you have some code or a working example of exactly what you are wanting to accomplish and that is causing "too many rerenders"?

**Comment by smammadov1994** [comment]
`import React from "react";
import Pagination from "react-bootstrap/Pagination";
import AddOrganizationButton from "./AddOrganizationButton";
import "../../CSS/CustomPaginationComponent.css";

const CustomPaginationComponent = ({
  count,
  page,
  rowsPerPage,
  onChangePage,
  currentPage,
}) => {
  console.log(page);

  const getNumberOfPages = (rowCount, rowsPerPage) =>
    Math.ceil(rowCount / rowsPerPage);

  const handleFirstPageButtonClick = () => {
    onChangePage(1);
  };

  // RDT uses page index starting at 1, MUI starts at 0
  // i.e. page prop will be off by one here

  const handleBackButtonClick = () => {
    page === 0 ? onChangePage(1) : onChangePage(page);
  };

  const handleNextButtonClick = () => {
    onChangePage(page + 2);
  };

  const handleLastPageButtonClick = () => {
    onChangePage(getNumberOfPages(count, rowsPerPage));
  };

  return (
    <>
      <Pagination className="pagination__wrapper">
        <section>
          <AddOrganizationButton />
        </section>
        <Pagination.Item
          onClick={handleFirstPageButtonClick}
          aria-disabled={page === 0}
          disabled={page === 0}
          aria-label="first page"
        >
          <i className="far fa-angle-double-left"></i>
        </Pagination.Item>
        <Pagination.Item
          onClick={handleBackButtonClick}
          aria-disabled={page === 0}
          disabled={page === 0}
          aria-label="previous page"
        >
          {currentPage}
        </Pagination.Item>
        <Pagination.Item
          onClick={handleNextButtonClick}
          disabled={page >= getNumberOfPages(count, rowsPerPage) - 1}
          aria-label="next page"
        >
          {currentPage + 1}
        </Pagination.Item>
        <Pagination.Item
          onClick={handleLastPageButtonClick}
          disabled={page >= getNumberOfPages(count, rowsPerPage) - 1}
        >
          <i className="far fa-angle-double-right"></i>
        </Pagination.Item>
      </Pagination>
    </>
  );
};

const CustomPag = ({
  rowsPerPage,
  rowCount,
  onChangePage,
  onChangeRowsPerPage,
  currentPage,
}) => (
  <CustomPaginationComponent
    component="nav"
    currentPage={currentPage}
    count={rowCount}
    rowsPerPage={rowsPerPage}
    page={currentPage - 1}
    onChangePage={onChangePage}
    onChangeRowsPerPage={({ target }) =>
      onChangeRowsPerPage(Number(target.value))
    }
    ActionsComponent={CustomPaginationComponent}
  />
);

export default CustomPag;
`

**Comment by smammadov1994** [comment]
Sorry wasn't sure how to format to look colorful. The thing is that I had to add extra logic because 0 would be passed into "handleBackButtonClick" and it would crash. 1) Is there a more proper way to handle this? 2) Can I avoid all of this and just give custom components to the back and forward buttons WHILE showing the current page or is there no way to access that variable from just giving a custom button component to be used? 3) Also how do I bring back the items per page from this?

**Comment by jbetancur** [comment]
I wired it up in codesandbox for you but everything seems to be working. I checked 2 pagination elements to First and Last respectively

https://codesandbox.io/s/custom-pagination-bootstrap-pbf1j?file=/src/index.js

See if you can duplicate the issue here.
