### ISSUE TITLE
[Documentation Error]

### ISSUE THREAD

**Issue by wilsonwg** [jbetancur/react-data-table-component#877]
In Section 11, Expandable Rows

const ExpandableComponent = ({ data }) => <img src={data.image} />;

class MyComponent extends Component {
  render() {
    return (
      <DataTable
        title="Arnold Movies"
        columns={columns}
        data={data}
        selectableRows
        selectableRowsComponent={Checkbox}
        selectableRowsComponentProps={{ inkDisabled: true }}
        sortIcon={<FontIcon>arrow_downward</FontIcon>}
        onSelectedRowsChange={handleChange}
        expandableRows
        expandableRowsComponent={ExpandableComponent}
      />
    )
  }
};

I think it's better to be written as:
expandableRowsComponent={<ExpandableComponent />}

Otherwise it may lead to confusion and result errors.

**Comment by jbetancur** [comment]
Please see https://github.com/jbetancur/react-data-table-component/issues/888 for the correct syntax for version 6 and 7. Also notable documentation changes are being made prior to the imminent release of version 7
