### ISSUE TITLE
Pagination/onChangePage does not prompt update of Datatable data prop

### ISSUE THREAD

**Issue by JugglerX** [jbetancur/react-data-table-component#88]
I am using the pagination, I would like to call my API on each page change and get the paginated data.

I am able to call the the API and I can confirm I have the updated data from the API in my state after the page change. 

But the DataTable component does not seem to update with the new data.

If I create a button and just fetch new data from the API outside of the handleChangePage function the component will update with the new state.

I think there might be a bug specific to the pagination/handleChangePage? At the moment I have had to build my own pagination component, but the one that comes with your library looks really slick so i'd prefer to use that!

```
  handleChangePage(state) {
    log.debug('handleChangePage: ', state); // Page 2
    axios.get('/users?limit=10&skip=10').then(res => {
       this.setState({data: res.data})
    })
  }
  render() {
    return (
      <DataTable
        data={this.state.data}
        onChangePage={this.handleChangePage}
```

**Comment by jbetancur** [comment]
Can you paste your component code or provide a code sandbox link? 

As an example, I created my code sandbox and was able to dupe (at least I think so).
https://codesandbox.io/embed/confident-gagarin-0sqwu

Additionally, this may also be a related issue that I just discovered when changing the page sizes
https://github.com/jbetancur/react-data-table-component/issues/89

**Comment by jbetancur** [comment]
The issue is that I am slicing the data set on server based pagination. This is why you are not seeing the records. Working on a fix.
```
    const lastIndex = currentPage * rowsPerPage;
    const firstIndex = lastIndex - rowsPerPage;
    const sortedRows = this.sortedRows(data, sortColumn, sortDirection);
    const currentRows = pagination
      ? sortedRows.slice(firstIndex, lastIndex)  // server side paging should not slice since we are already slicing the data set!
      : sortedRows;
```

**Comment by jbetancur** [comment]
Ok, this is fixed! I'm creating a PR for it shortly. For server-side paging you just need to provide the following properties:

* `paginationServer`
* `paginationTotalRows` - whatever API you are using should return the **total count** of records either in the response or the header. Check your API documentation for this but you must know the total record count for pagination to work. The following is a good example of this:
```
{  
   "page":1,
   "per_page":10,
   "total":12, // the total count of records in the api database
   "total_pages":2,
   "data":[  ...  ]
}
```

 I also updated the documentation and added a new storybook for server-side paging. Here is an example:

```
class AdvancedPaginationTable extends Component {
  state = {
    data: [],
    loading: false,
    totalRows: 0,
    perPage: 10,
  };

  async componentDidMount() {
    this.setState({ loading: true });
    const response = await axios.get(
      'https://reqres.in/api/users?page=1&per_page=10',
    );

    this.setState({
      data: response.data.data,
      totalRows: response.data.total,
      loading: false,
    });
  }

  handlePageChange = async page => {
    const { perPage } = this.state;

    this.setState({ loading: true });

    const response = await axios.get(
      `https://reqres.in/api/users?page=${page}&per_page=${perPage}`,
    );

    this.setState({
      loading: false,
      data: response.data.data,
    });
  }

  render() {
    const { loading, data, totalRows } = this.state;

    return (
      <DataTable
        title="Some Names"
        columns={columns}
        data={data}
        progressPending={loading}
        pagination
        paginationServer
        paginationTotalRows={totalRows}
        onChangeRowsPerPage={this.handlePerRowsChange}
      />
    );
  }
}
```

Note #89 is still an issue when updating the rows per page drop down, but I will fix this in a subsequent PR

**Comment by JugglerX** [comment]
Wonderful mate! I just updated to the latest version and can confirm `paginationServer` worked as expected.

Roughly my code ended up being:

```
export default class List extends Component {
    constructor(props) {
        super(props);
        this.state = {
            data: [],
            activePage: 1,
            total: 0,
            limit: 20
        };
    }

    componentDidMount() {
      fetchUsers(1, this.state.limit)
            .then(res => {
                this.setState({ data: res.result, total: res.total });
            })
    }

    handlePageChange = page => {
        fetchUsers(page, this.state.limit).then(res => {
            this.setState({ data: res.result, activePage: page });
        });
    };

    handleChangeRowsPerPage = (currentRowsPerPage, currentPage) => {
        this.setState({ limit: currentRowsPerPage }, () => {
            this.handlePageChange(currentPage);
        });
    };

    render() {
        return (
            <DataTable
                        ...
                        data={this.state.data}
                        pagination
                        paginationServer
                        paginationTotalRows={this.state.total}
                        paginationPerPage={this.state.limit}
                        onChangePage={this.handlePageChange}
                        onChangeRowsPerPage={this.handleChangeRowsPerPage}
                    />
        );
     }
}
```
