### ISSUE TITLE
Expandab;e rows not working

### ISSUE THREAD

**Issue by samueldervis** [jbetancur/react-data-table-component#888]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
When you click the row expander, the expandable row component does not appear

## To Reproduce

Follow tuts for expandable component

## Expected behavior
View expandable row component

## Code Sandbox, Screenshots, or Relevant Code
https://codesandbox.io/embed/mutable-snowflake-z1uec?fontsize=14&hidenavigation=1&theme=dark

## Versions (please complete the following information)
 - React  17.0+
 - Styled Components 5.3.1
 - OS: Windows
 - Browser [e.g. chrome, safari, firefox]: Chrome

**Comment by jbetancur** [comment]
Sorr, I am in the middle of transitioning the documentation and about to release version 7. For version 6 you needed to pass in a jsx component, so expandableComponent={<Expandable />}

Version 7 uses just takes the function Expandable. You can either fix this or try updating to rdt 7 - npm install --save react-data-tabla-component@next
