### ISSUE TITLE
How to overwrite CSS of the subheader component with styled-components?

### ISSUE THREAD

**Issue by smammadov1994** [jbetancur/react-data-table-component#889]
I would like to overwrite the css to the subheader component using styled-components. Essentially to make the width to take up as much as the table. Just trying to understand best practice here.

**Comment by jbetancur** [comment]
You can pass in your own `subHeaderComponent` and do whatever you need within it.

https://react-data-table-component.netlify.app/?path=/docs/api-props--page#headers
