### ISSUE TITLE
Localization of the table component

### ISSUE THREAD

**Issue by lcl45** [jbetancur/react-data-table-component#891]
Don't sure if this is a bug, a feature or only me not finding anything related to this so I'll leave it here.

## Describe the bug
When no data is passed to the DataTable, the label "There are no records to display" is shown. Since I'm building my app as a list of form inputs and under them the table, until the user has filled some fields this label will be shown. The problem is that I need to localize the entire application and I need to change also this string. Do you know if it is currently possible to do something about it?

## To Reproduce
If you need it there is this codesandbox https://codesandbox.io/s/vibrant-feistel-zples?file=/src/App.js . Since no data is passed then the label is shown.

## Expected behavior
Maybe to add the possibility to set a custom label or localize it in some way

Thanks for your time!!

**Comment by jbetancur** [comment]
Yes, you are looking for https://react-data-table-component.netlify.app/?path=/docs/api-props--page#general-properties

`noDataComponent`

You will want to pass your own component JSX:

const noData = <div style={{ padding: '24px' }}>No hay registros para mostrar</div>;

```js

noDataComponent={noData}
```

Updated sandbox
https://codesandbox.io/s/dank-smoke-nkjct?file=/src/App.js

**Comment by jbetancur** [comment]
If this answers your question please close the issue 😉

**Comment by lcl45** [comment]
Oh yes, that's perfect! Sorry, I didn't see it in the docs. Thank you very much
