### ISSUE TITLE
[Help- V7.0.0] generic type with default component

### ISSUE THREAD

**Issue by VictorHAS** [jbetancur/react-data-table-component#900]
I'm a little new with typescript and I'm using RDT v7, and I want to make a generic DataTable. In order not to keep doing the same import over and over, I decided to create a component, but I'm having trouble passing the type to Data and Columns, how can I do it? 

![image](https://user-images.githubusercontent.com/32372238/132538219-6bf43c57-e99c-42a6-a5b0-e93cf56af549.png)
![image](https://user-images.githubusercontent.com/32372238/132538300-961c4998-95dc-44cd-bd0d-fbd82acc0594.png)
![image](https://user-images.githubusercontent.com/32372238/132538505-491b38e9-801b-42f7-b473-38295ed39857.png)

**Comment by jbetancur** [comment]
Looking into this I think there might be some issues with generic types_

**Comment by jbetancur** [comment]
I believe T on Props needs to be your data type. Can you try leaving it off. T should infer.

`Props extends TableProps`

Internally RDT defaults to `RowRecord` which is basically `Record<string, unknown>

**Comment by jbetancur** [comment]
I'm sort of not 100% clear on your use case. If you are trying to cut down on repetition of props you can do something like this and avoid typing:

```js
const DataTableBase: React.FC<TableProps> => props -> {
  return <DataTable sortIcon={sortIcon} theme={theme.palette.type} dense {....props} />
}

export default DataTableBase;
```
Then, instead of importing `DataTable` you instead import `DataTableBase` which already has `theme`, `dense` and `sortIcon` configured once for all your instances of `DataTableBase`

**Comment by VictorHAS** [comment]
I went back to v6.11 because I was struggling with these types and to finalize a feature. I will be testing v7 again later, thanks a lot for the help!

**Comment by VictorHAS** [comment]
Now working in v7.3.1!! Ty! 🚀 🚀
