### ISSUE TITLE
Allow conditionalRowStyles to apply classNames to row in addition to styles

### ISSUE THREAD

**Issue by crawforde** [jbetancur/react-data-table-component#901]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe
We use stylesheets and Bootstrap for consistent website styling. All of our React components are styled with classnames, and we avoid inline styles completely because they cause confusion and CSS priority issues as our codebases grow. Currently, the only option this package provides for styling table rows is through inline styles.

## Describe the solution you'd like

It would be very helpful if the conditional styles object included a `classNames` key that could be set to an array of strings, which would all be applied to the row if the condition is met, in addition to any styles specified:

```javascript
const conditionalRowStyles = [{
  when: row => row.foo === "bar",
  classNames: ["text-uppercase", "bg-danger"]
}];
```

## Describe alternatives you've considered

Inline styles are the only option right now, and this is not ideal for the reasons that I mentioned in the problem description. They cause styling consistency and maintainability issues across our website.

## Additional context

I'm submitting this feature request to reopen the following issue, which was closed by a bot:
https://github.com/jbetancur/react-data-table-component/issues/393

**Comment by jbetancur** [comment]
so you just want to add some `classNames` in this case to `TableRow`?

**Comment by jbetancur** [comment]
I think this would be possible without much work (hopefully 😉 ). I'll flag it as a feature for a 7.1

**Comment by jbetancur** [comment]
This features is now available in 7.1.0

**Comment by crawforde** [comment]
Thanks for the quick turnaround!

**Comment by crawforde** [comment]
❤️
![Screen Shot 2021-09-14 at 1 43 17 PM](https://user-images.githubusercontent.com/27984319/133331120-2538ca9e-1e9c-4370-b530-205f822ea407.png)

**Comment by orosznyet** [comment]
So I've tried to use this with `*.module.css` references, I can see the class name appears on the DOM element but the data table style overrides mine (due to [specificity index](https://www.w3schools.com/css/css_specificity.asp)).

On one hand you could add `!important` to your style attributes, but I'd generally advise against that.
But on the other hand, you can also increase your selector specificity by adding div prefix to you class (`div.yourClassName`).

**Comment by SteffenKeller** [comment]
Is it also possible to add a custom class to the header only?
