### ISSUE TITLE
Fixed header + navigation: option to scroll to top of table body after sort/page change

### ISSUE THREAD

**Issue by androdel** [jbetancur/react-data-table-component#902]
When you scroll down to the bottom and you go to the next page, the scroll position stays the same. For UX, I think it would be better if the table body scrolls back to the top, or at least have the option to. Would then also trigger on sort change.

If filtering would be part of this component, then it could apply on filter change as well.

If this functionality sounds like a good idea, I'm happy to add it myself and create a PR for it.

**Comment by emanuallan** [comment]
Using [patch-package](https://www.npmjs.com/package/patch-package), I went into the `DataTable.tsx` file and made these changes so it would scroll to top on page change or sort:
<img width="542" alt="Screen Shot 2021-12-27 at 5 05 27 PM" src="https://user-images.githubusercontent.com/22531461/147512634-a6e86475-5aa7-45dc-827d-0fddea84907a.png">
<img width="829" alt="Screen Shot 2021-12-27 at 5 05 09 PM" src="https://user-images.githubusercontent.com/22531461/147512625-1082f433-7235-4fd5-b26f-85740f3fee49.png">
<img width="951" alt="Screen Shot 2021-12-27 at 5 05 58 PM" src="https://user-images.githubusercontent.com/22531461/147512652-794c41bf-2042-4f83-8032-38a81a0233aa.png">

**Comment by emanuallan** [comment]
or Implement the following in your onChangePage/onSort

       ```
      var tableElement = document.getElementsByClassName(
                  'rdt_Table',
                )[0];
                tableElement.scrollIntoView({ behavior: 'smooth' });
```
