### ISSUE TITLE
HOW TO CHECK/UNCHECK THE CHECKBOXES WITH OTHER METHOD INSTEAD onSelectedRowsChange

### ISSUE THREAD

**Issue by VelaJafet** [jbetancur/react-data-table-component#903]
## Describe the bug
I insert the elements with the same "Estado" into the selectedRows attribute because I use it in onSelectedRowsChange but visually it doesn't show selected.

## Expected behavior
I would like to select all the elements with the same "Estado" when I press the "Seleccionar iguales" option, this will save time to my users (**photo 1**).

I use the next function assigned to "Seleccionar iguales" option to try to make it work (**photo 2**), It inserts into my attribute selectedRows the elements with the same "Estado" but visually it doesn't show (**photo 3 & 4**).

## Code Sandbox, Screenshots, or Relevant Code

![imagen](https://user-images.githubusercontent.com/43042942/132923100-48b097a7-678b-49a4-9ae4-b96257395f91.png)
**photo 1.**

![imagen](https://user-images.githubusercontent.com/43042942/132923535-4edf7b3f-0e27-4757-ac91-a5844dabbbce.png)
**photo 2**

![imagen](https://user-images.githubusercontent.com/43042942/132923629-0d6ead0e-65a7-4ff2-8240-def2d9dcea7b.png)
**photo 3**

![imagen](https://user-images.githubusercontent.com/43042942/132923661-f4331d46-1300-4ab1-a206-134314f1d2b7.png)
**photo 4**

**How can I do it?**

## Additional context
I tried it with the RDT atributte "selectableRowSelected" but the documentation about it's poorly.

**Comment by jbetancur** [comment]
https://react-data-table-component.netlify.app/?path=/docs/selectable-pre-selected--pre-selected feel free to submit a PR if you  can improve.

`selectableRowSelected` works by allow you to select a check box depending on a condition in your data. For example:

```js
const iguales= row => row.estado  === 'Dispondible';

function MyComponent() {
  return (
    <DataTable
      columns={columns}
      data={data}
      selectableRows
      selectableRowSelected={iguales}
    />
  );
}
```

But since you want to do this programmatically with Seleccionar Iguales, you could in theory use state to pass the function in on that option:

```js
....
this.state = { igualesFunction: () => {} }; // noop basicaly

// then on your handler of  Seleccionar Iguales:
this.setState(igualesFunction: row => row.estado  === 'Dispondible';)

    <DataTable
      columns={columns}
      data={data}
      selectableRows
      selectableRowSelected={this.state.igualesFunction}
    />
```

Not 100% sure that works, but if it does it would be a great addition to the docs

**Comment by VelaJafet** [comment]
Maybe I did not explain well lol

I use the `handleSelectSame `function in the "Seleccionar iguales" option, this add all the elements with the same "FK_Estado" to the array `selectedRows`, this same array I use in the `onSelectedRowsChange` when I check/uncheck the elements in the Datatable.

The reason why I made the function `handleSelectSame `"works" but visually speaking (in the Datatable) it doesn't check the checkboxes added to `selectedRows `with the function.

**Comment by VelaJafet** [comment]
?

**Comment by keshavsharma07** [comment]
pagination clears selected checkbox values
