### ISSUE TITLE
Could not find a declaration file for module 'react-data-table-component'. Recent release [7.0.1]

### ISSUE THREAD

**Issue by blackgospel** [jbetancur/react-data-table-component#906]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
Not sure if any changes to bundle in most release [7.0.1] or whether it's affect users before but when installing that version I get error mentioned above, when trying to import the component. Could not find a declaration file for module 'react-data-table-component'. After looking at node_modules/dist folder for react-data-table-component, seems as though files path in package.json is looking for type declaration file in root rather than src folder where it lives. After changing files path from 'dist/index.d.ts' to 'dist/src/index.d.ts' it was able to compile.

## To Reproduce
1. Run yarn add react-data-table-component
2. Add import, `import DataTable from 'react-data-table-component'`
3. Run project and you'll get a bundle error or warning: TS7016: Could not find a declaration file for module 'react-data-table-component'.

## Expected behavior
Expected to import DataTable from react-data-table-component without compliation errors regarding a types declaration file.

**Comment by jbetancur** [comment]
Thank you for raising this. I did upgrade Typescript in 7.0.1 which might be the culprit. I'll get a fix out for this ASAP.

**Comment by jbetancur** [comment]
Thanks for pointing out the package.json which fixes this for now. I'll need to look into what changed because the types files used to be generated into the dist root. IN any case this is fixed for now - Release 7.0.2 shortly...
