### ISSUE TITLE
how I leave columns fixed to the (X) axis

### ISSUE THREAD

**Issue by Williams25** [jbetancur/react-data-table-component#908]
how I leave columns fixed to the (X) axis?

version 
react-data-table-component:  7.0.0-rc2

**Comment by epicmau5time** [comment]
Any luck on this?

**Comment by Williams25** [comment]
no

**Comment by irehmanullah** [comment]
Found any solution for this?

**Comment by Williams25** [comment]
no, in my case I removed some columns that would not be relevant and put this additional information in a modal

**Comment by irehmanullah** [comment]
Great

**Comment by diegosiao** [comment]
Same problem here.. nothing on this?

**Comment by Williams25** [comment]
in my case I created a modal to display this information

**Comment by diegosiao** [comment]
Nice @Williams25, but wouldn't be great if could just add a value to the columns declaration, like:

```
const columns = [
  {
    name: "Order",
    selector: "orderId",
    maxWidth: "10%",
    center: true,
    sortable: true,
    **sticky: true,**
  }
];
```
