### ISSUE TITLE
Netlify custom js page not working

### ISSUE THREAD

**Issue by AndrewPopa96** [jbetancur/react-data-table-component#912]
Greetings!
I am trying to add some custom js styles to the expander Row. I tried to open the styles.js on the bottom of this page but it takes me to a 404 page: https://react-data-table-component.netlify.app/?path=/docs/api-custom-styles--page

**Comment by jbetancur** [comment]
This has been fixed as of a few minutes ago.  The link should be https://github.com/jbetancur/react-data-table-component/blob/master/src/DataTable/styles.ts
