### ISSUE TITLE
How do I customize DataTable styles in typescript using styled-components?

### ISSUE THREAD

**Issue by gcleiton** [jbetancur/react-data-table-component#914]
First of all, thank you for making the library available, I'm starting to work with the tool in a project.

## Describe the bug
The problem is that the styled component is not able to preserve the DataTable's generic properties. This gives me an error in the columns property of my styled component.

## Code Sandbox, Screenshots, or Relevant Code
![Screenshot_22](https://user-images.githubusercontent.com/48367947/133889969-f73f30c5-acc3-4844-a0c8-80c1b9cd6deb.png)
![Screenshot_20](https://user-images.githubusercontent.com/48367947/133889974-2b85ee13-67e3-4d48-8f29-a8d86e00850e.png)
![Screenshot_19](https://user-images.githubusercontent.com/48367947/133889981-a94c16e8-567b-4a42-95b3-a8aedde55923.png)
![Screenshot_21](https://user-images.githubusercontent.com/48367947/133889984-59ab95c4-f54f-46af-9f96-7be1e78e530b.png)

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+): 17.0.2
 - Styled Components: 5.3.1
 - OS: [e.g. iOS] Windows 10

**Comment by jbetancur** [comment]
This is a bug in RDT that has to do with the way generics are being passed that I have been struggling with. In the next few days I can cut a 7.1.1 with this resolved. I would ignore the error for now.

**Comment by gcleiton** [comment]
Okay. For now, I've made a wrapper and styled it by calling the classes.

**Comment by jbetancur** [comment]
@gcleiton type inference should now be resolved in v7.2.0, however, you will need to cast to `DataTable` for this to work with styled-components. For example:

```ts
const Table = styled(DataTable)`` as typeof DataTable;
```

For reference: 
https://github.com/styled-components/styled-components/issues/1803
