### ISSUE TITLE
Context menu invisible even when rows are selected

### ISSUE THREAD

**Issue by pwojtowicz838** [jbetancur/react-data-table-component#922]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
After upgrading to v7 I've noticed that context menu does not show up when selecting rows. Also in storybook the menu also is invisible. I didn't find any api changes documented so I assume it's a regression.

## To Reproduce
1. Go to https://react-data-table-component.netlify.app/?path=/docs/getting-started-kitchen-sink--kitchen-sink
2. Select "Selectable rows"
3. Select a row
4. See that context menu is still invisible

**Comment by henchicky** [comment]
This is happening to me as well when upgrading to 7.3.0 from 7.0.0-rc2

**Comment by jbetancur** [comment]
Definitely something busted. I’ll look into this

**Comment by jbetancur** [comment]
fixed in 7.3.1
