### ISSUE TITLE
Updatable table state dynamically  : updating cell contents with new values

### ISSUE THREAD

**Issue by TinoOnline** [jbetancur/react-data-table-component#923]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

The problem I am experiencing might be a result of the intentional architecture of React Data Table component and as a result if this isn't meant to be a feature I am ultimately looking to get some assistance in being able to "implement" the feature locally.  

The problem that I have is that I have created custom rows thus cells that house textInputs/areaInputs, these allow me to update the content in the cells. The issue that I have is that it seems that the table has its own state that's different from page's state (outside the table). 
It appears as if the state of the table is cached with the data that is first loaded/populated. As a result of this, when I update the table (not the textInput cells) with new content (row entires/rows) then try to edit the textInputs, the new content clears and then reverts back to whatever data it was initially loaded with.  Without completely reloading the page the new entries will disappear and you can only edit the content that as initially loaded (please see video below). 

## Describe the solution you'd like

I am hoping that the state of the table can be somehow linked to the state of the actual page as it seems to have its own state. The table should be able to work with the most recent dataset when updated as opposed to falling back to the initial dataset once you start interacting with the contents of the cells, please see video below.

## Describe alternatives you've considered

I have tried to use react-redux to manage the state. 
I have attempted to use conditional rendering. 
I have tried to force update on the component.
I have tried using timeouts. 

## Additional context

I have uploaded a video showing the issue that I have, the table seems to to have a separate state of its own.
https://user-images.githubusercontent.com/64155956/134743754-f3bec480-8f66-43f2-bfa9-5612a90a323f.mov

I have also provided the js code that can be run **as is** to reproduce the behaviour it has the unnecessary code removed. The above video example was done with a live database and the delete function was only interacting with the database. The code below is only interacting with the local database and as a result the delete function acts weird too.  There are a lot of comments in the file to help guide understanding.
[impactAssessmnt.txt](https://github.com/jbetancur/react-data-table-component/files/7229243/impactAssessmnt.txt)

Thank you very much for your time in advance any assistance will be very much appreciated.

**Comment by jbetancur** [comment]
Thank for the detailed explanation to your issue.

You're correct that `data` is going to be behind the state of your parent components `data`, but the pattern I would use is to update you parent `data` when your editable `cell` changes.

1. Store your `data`  in state on your parent component
2. Foreach `cell`'s editable input implement an handler that returns when data changes (probably when they exit focus or something) then update your parent state. The data change will flow down into `DataTables` `data`

I took a stab at this using `contentEditable` which I may turn into documentation for others. I may look to adding this as a native feature when I have more time.

https://codesandbox.io/s/react-data-table-editable-nqc6x?file=/src/index.js

```js
function findById(array, id) {
  return array.findIndex((d) => d.id === id);
}

function App() {
  const [data, setData] = React.useState(movies);

  const columns = React.useMemo(() => {
    const handleTitleEditable = (field) => (row) => (e) => {
      const newRow = { ...row };
      newRow[field] = e.target.innerText;

      const newData = data.slice(0);

      newData[findById(data, row.id)] = newRow;
      // update your data model here in state, POST or whatever
      setData(newData);
    };

    return [
      {
        id: 1,
        name: "Title",
        selector: (row) => row.title,
        sortable: true,
        reorder: true,
        cell: (row) => (
          <div
            contentEditable
            suppressContentEditableWarning={true}
            onBlur={handleTitleEditable("title")(row)}
          >
            {row.title}
          </div>
        )
      },
      {
        id: 2,
        name: "Director",
        selector: (row) => row.director,
        sortable: true,
        reorder: true,
        cell: (row) => (
          <div
            contentEditable
            suppressContentEditableWarning={true}
            onBlur={handleTitleEditable("director")(row)}
          >
            {row.director}
          </div>
        )
      },
      {
        id: 3,
        name: "Runtime (m)",
        selector: (row) => row.runtime,
        sortable: true,
        right: true,
        reorder: true,
        cell: (row) => (
          <div
            contentEditable
            suppressContentEditableWarning={true}
            onBlur={handleTitleEditable("runtime")(row)}
          >
            {row.runtime}
          </div>
        )
      }
    ];
  }, [data]);

  return (
    <div className="App">
      <Card>
        <DataTable
          title="Movies"
          columns={columns}
          data={data}
          defaultSortFieldId={1}
          sortIcon={<SortIcon />}
          pagination
          selectableRows
        />
      </Card>
    </div>
  );
}
```

**Comment by TinoOnline** [comment]
Perfection @jbetancur, that resolved the issue and everything is now in sync. Thank you very much for the help and the quick response. 🚀
