### ISSUE TITLE
Dropdown Hiding inside the table

### ISSUE THREAD

**Issue by Gundetiakki** [jbetancur/react-data-table-component#926]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
I have a drowdown in my table it works fine when there are lots of data but when i search for a row/value inside table then my dropdown hides inside the table PS attaching the screen shot below 
so can you help me on this please

![image](https://user-images.githubusercontent.com/30874150/134859793-c6b73f4e-c95b-4009-8867-e5c0931d93c7.png)

## Expected behavior
I want to show the dropdown outside so that it will be visible to view the data inside

## Versions (please complete the following information)
 - React: 16.14
 - Styled Components
 - OS: window
 - Browser: chrome

**Comment by Wael-Dghim** [comment]
I'm bringing this issue back after almost 3 years because it still occurs even with Next.js

My issue is exactly the same, I have a drop down of actions in a DataTable and the menu is hidden inside the table itself.

**Versions straight from package.json**
"next": "13.4.4",
"react-data-table-component": "^7.5.3",
"react-data-table-component-extensions": "^1.6.0",

**Comment by MajidAliKhanQuaid** [comment]
I'm also facing the same issue, the dropdown is hiding inside the table. 

https://app.screencast.com/vt3cLxPKMtaWU

**Comment by prasannakulal16** [comment]
Hii, All

Lets add the `overflow:auto`  to the cell or remove overflow property from cell. After adding this dropdown is not hiding inside the table for me. lets try that once.
```
cells: {
      style: {
        paddingLeft: '16px',
        paddingRight: '16px',
        overflow: 'auto',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        fontSize: '14px',
        fontWeight: 500,
        lineHeight: '20px',
        color: '#222331'
      }
    },
```

**Comment by lukzfern** [comment]
This problem still occurs , how this issue can be closed?

**Comment by 10Poojayaadav** [comment]
Here is the solution of this problem :-

<DataTable
          columns={columns(
            handleActionClick,
            activeRow,
            handleEdit,
            handleView,
            handleDelete
          )}
          data={filteredData}
          pagination
          highlightOnHover
          striped
          noDataComponent="No records found"
         **className="!overflow-x-clip !overflow-y-visible"**
        />
        
        
  the Bold section will help you to show the dropdown above the datatable 
  Technology :- React Js

**Comment by Swathi-eGov** [comment]
Facing the same issue 
Dropdown is hiding inside the table cell using version  : "react-data-table-component": "7.6.2"
