### ISSUE TITLE
Github links on documentation page (for custom themes) are outdated due to migration to typescript

### ISSUE THREAD

**Issue by y4nrui** [jbetancur/react-data-table-component#927]
Affected documentation links that I've found:
- https://react-data-table-component.netlify.app/?path=/docs/api-custom-themes--page
- https://www.npmjs.com/package/react-data-table-component-with-filter#defining-your-own-theme-using-createtheme

If you click on the "themes.js" in "Refer to themes.js for properties you can use to create your own color theme."...
![image](https://user-images.githubusercontent.com/54534120/134892948-0dfb8fe7-4a21-4997-be94-3af316f4711d.png)

It will show a "404 missing GitHub page" error ->
![image](https://user-images.githubusercontent.com/54534120/134892450-72322355-be40-4d65-9e32-c1e00a326e1f.png)

The updated link should be this instead: https://github.com/jbetancur/react-data-table-component/blob/master/src/DataTable/themes.ts

**Comment by jbetancur** [comment]
Fixed in #933
