### ISSUE TITLE
Data format for data table

### ISSUE THREAD

**Issue by dannygooze** [jbetancur/react-data-table-component#93]
I have been trying to get my table to load in data from my database but have not been able to get any data structure to pass through properly. I currently have it as an array of object literals as shown in your read.me. It seems that as soon as I pass in the data prop it breaks. 

I have even tried using the basic table example and it breaks as soon as the data prop is passed also. Everything seems to be working until I pass in data to the data prop. 

Any guidance would be helpful, thanks in advance.

**Comment by jbetancur** [comment]
Can you paste the code and sample data? The exact errors if any would be helpful.  Even better use something like codesanbox and see if you can dupe the issue there.

**Comment by dannygooze** [comment]
`import React from 'react'
import DataTable from 'react-data-table-component'

let data = [{ id: 1, title: 'Conan the Barbarian', year: 1982 },
  { id: 2, title: 'Men in Black', year: 1999 }]

const columns = [
  {
    name: 'Title',
    selector: 'title',
    sortable: true
  },
  {
    name: 'Year',
    selector: 'year',
    sortable: true,
    right: true
  }
]

export const PeopleTables = (props) => {
  return (
    <div className='p-3'>
      <h2>Course Members:</h2>
      <p>x / x members in y page(s).</p>
      <div className='text-right'>
        <a className='btn btn-success btn-sm'>
          <div className='icon icon_user_plus2 icon_color_white' />
            &nbsp;&nbsp;Add People
        </a>
      </div>
      <DataTable
        title='People'
        columns={columns}
        data={data}
      />
    </div>
  )
}`


Here are the errors that appear in my console when I add the data prop:

Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. 

Let me know if you see anything wrong from my end. 
Thanks for the fast response!

**Comment by jbetancur** [comment]
Thank you. So, I just quickly loaded it in codesandbox and seems to be working. Perhaps the error is with how you are calling PeopleTables?

https://codesandbox.io/embed/dazzling-breeze-k2eht

**Comment by dannygooze** [comment]
I figured it out, it seems that I needed to have React and React-dom 16.6, I was using 16.4.

Do you know if this is the case? If so, it may be a good idea to update your docs. 

Thanks again for the fast response, and great job on this project!

**Comment by jbetancur** [comment]
Thank you!

Good catch and you are correct. It seems I am using `React.memo`  that was added in 16.6. I'll go ahead and update the docs
