### ISSUE TITLE
[FEATURE]: Dynamic Column Widths

### ISSUE THREAD

**Issue by yuvachang** [jbetancur/react-data-table-component#932]
## Is your feature request related to a problem? 
Difficult to implement column widths to fit dynamic data and columns. 
Flex grow does not fully solution varying data lengths and still results in overflowing text in row cells on pages, while setting hard (min/max) widths for columns is hard to respond to largely varying cell data (some short text, some extremely long text).

## Describe the solution you'd like
Would be great to have column widths somehow respond to the longest cell on the page, instead of the current 
`maxWidth || '100%' / minWidth || '100px'` / flex-grow solution.

Or, perhaps the `wrap` column setting can toggle to full width of content instead of `white-space: no-wrap; overflow: hidden; text-overflow: ellipsis;` 

## Describe alternatives you've considered
Really struggling, but I'm far from expert. 

## Additional context
Use case: dynamic columns make hardcoding/setting of widths/grow values difficult. Some pages may have only rows with very short data, but then some pages may have rows with extremely long data. Current width/grow settings result in pages with short data having extra/unnecessary col width and/or pages with long data having cutoff/overflown text in columns. 

Wondering if this is a possible feature or if more advanced customization of column widths is something considered, or if there are better ways around the varying column widths.
Thanks in advance!

**Comment by virik** [comment]
We have the same issue with our tables. We've set the content to nowrap, and the default min-width is as you know 100px. This causes the content to overflow the column. As we don't know the content of these cells, it's not possible to set a fixed width. What we're looking for is a similar functionality to the traditional <table>. The min-width of the cell being the longest content of any cell in that column. Screenshot: https://d.pr/i/b3xlp3

**Comment by afazrai** [comment]
@virik Have you checked out #234 ?
https://github.com/jbetancur/react-data-table-component/issues/234? 
I had the same issue and solved it

**Comment by virik** [comment]
Yes. I've read that post, but it doesn't provide us with a good answer. Neither of these options make our table behave like a normal table, adjusting the width based on the content.
