### ISSUE TITLE
selectableRowsComponentProps always missing one random prop

### ISSUE THREAD

**Issue by Firfi** [jbetancur/react-data-table-component#936]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You are using React 16.8.0+
- [x] You installed `styled-components`
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug

When setting `selectableRowsComponentProps`, *one random field* from the props object becomes undefined when passed to `selectableRowsComponent`.

## To Reproduce

declare component C and print its props in render

set selectableRowsComponent: C

set selectableRowsComponentProps: `{prop1: () => {}, props2: () => {}}`

## Expected behavior

`{prop1: () => {}, props2: () => {}}` is passed to C

instead `{prop1: undefined, props2: () => {}}` is passed to C; it's not relevant what are the prop names and how many of them are there; *always* one prop is missing.

## Code Sandbox, Screenshots, or Relevant Code

https://github.com/Firfi/react-data-table-component-selectable-props-bug

it's clean CRA project otherwise; 

`yarn start`, check console — you'll see 3 tables being rendered, each having a custom checkbox component that print its props

first has 1 extra prop and it comes undefined; second has 2 extra props and one of them comes undefined; third had 3 extra props and one of them comes undefined

## Versions (please complete the following information)
 - React^17.0.2
 - Styled Components^5.3.1
 - OS: iOS
 - Browser chrome

**Comment by jbetancur** [comment]
It does you just have to scroll as I don't have have the anchor link set the the selectablerows section

**Comment by Firfi** [comment]
https://user-images.githubusercontent.com/947595/136381545-9f511367-3c1c-48a1-b2d3-82bc846ce2f3.mov

I mean
