### ISSUE TITLE
selectableRowsSingle doesn't work with selectableRowSelected

### ISSUE THREAD

**Issue by dwalid7** [jbetancur/react-data-table-component#945]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [x] You installed `styled-components`
- [x] You are using React 16.8.0+
- [x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
I want to use selectableRowsSingle with selectableRowSelected.
When the component is rendered the first time, it doesnt show the selected Row when selectableRowsSingle is enabled.

selectableRowSelected={rowSelectCritera}
const rowSelectCritera = (row) => row.isSelected == true;

i made an example on codesandbox

## To Reproduce
1. Go to https://codesandbox.io/s/react-data-table-forked-c2biq?file=/src/index.tsx

## Expected behavior
Show selected

## Code Sandbox, Screenshots, or Relevant Code

https://codesandbox.io/s/react-data-table-forked-c2biq?file=/src/index.tsx

Otherwise, add screenshots and/or complete sample code to help explain your problem.

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+)
 - Styled Components
 - Browser [e.g. chrome, safari, firefox]

**Comment by aniket-solulab** [comment]
@dwalid7  issue still remains same are you able to find any different way.
