### ISSUE TITLE
Better documentation on expandableRowsComponentProps

### ISSUE THREAD

**Issue by izaacdb** [jbetancur/react-data-table-component#950]
I am upgrading from 7 beta to 7.4.4, all great so far but I am confused with the documentation on `expandableRowsComponentProps`. I am nesting data tables and have a expandable row component set like this:

    <DataTable
      expandableRows
      expandableRowsComponent={ComponentsTable}
      expandableRowsComponentProps={{stages}}
      etc />

And I have an expandable row component (nested table) of 

    interface Props {
      data: Product
      stages: Stage[]
    }
    
    export const ComponentsTable: FC<ExpanderComponentProps<Product>> = ({
      data
      stages,
    }: Props) => {
      return (
        <DataTable
          columns={generateColumns(data, stages)}
          data={data.components}
        />
      )
    }

This gives me a problem:

````
TS2322: Type '({ data, stages }: Props) => JSX.Element' is not assignable to type 'FC<ExpanderComponentProps<Product>>'.
  Types of parameters '__0' and 'props' are incompatible.
    Property 'stages' is missing in type 'PropsWithChildren<ExpanderComponentProps<Product>>' but required in type 'Props'.
````

I'm not sure what to do. I've tried `& Stages[]` in the type but this gives me another error in the parent data table.

**Comment by AlexanderFarkas** [comment]
Why props should be optional? Is there any case where they will not be passed? I believe, TS is powerful enough to correctly type it.
