### ISSUE TITLE
Mistyping in Docs: Selectable/Pre Disabled Rows

### ISSUE THREAD

**Issue by afazrai** [jbetancur/react-data-table-component#954]
File: react-data-table-component/stories/DataTable/selectableRows/preDisabled.mdx

Mistyping for <DataTable/> attribute:

Previously: 
`selectableRowSelected={rowDisabledCriteria}`
Correct one:
`selectableRowDisabled={rowDisabledCriteria}`

Some copy-pasting programmers might wonder why it won't pre disable the checkbox 👀

**Comment by jbetancur** [comment]
Thanks for raising this. A PR is also welcome 😉

**Comment by jbetancur** [comment]
Thank you! https://github.com/jbetancur/react-data-table-component/pull/960
