### ISSUE TITLE
[FATAL BUG] Infinite loop caused by selectableRowSelected + onSelectedRowsChange

### ISSUE THREAD

**Issue by akanoce** [jbetancur/react-data-table-component#955]
## Describe the bug
I'm experiencing a strange and fatal behavior when using `selectableRowSelected` in combination with `onSelectedRowsChange`:
The two props works great on their own, but broke everything when used together: (in order to pre-select and then select new rows), i run into an infinite loop (re-render) as soon as the table loads.

Based on my debugging, the fault occurs when i update the independent state which is keeping the rows selected.
The strange things, is that the state is never used in the application (neither i have a `useEffect` hook), but the behavior of the table changes based on how i update the state.;
- If i update the state with the `selectedRows` provided by  `onSelectedRowsChange`-> Infinte loop (Max update depth excedeed)
- If i update the state with an empty array (via `onSelectedRowsChange` trigger) -> Infinte loop (Max update depth excedeed);
- If i update the state with any string (via `onSelectedRowsChange` trigger) -> No errors and the selection work as expected (but i am unable to get the selected rows);
- If i update the state by strinigify the `selectedRows` provided by  `onSelectedRowsChange` -> No infinite loop, but i am unable to select new rows, the state keep only the stringified selected rows defined by `selectableRowSelected`;
 

## To Reproduce
```
import DataTable, { TableProps } from 'react-data-table-component';

export default Function Index(){
    const columns = [
          {
              name: 'Name',
              selector: row => row.name,
              sortable: true,
          }
      ];
    
    const data = [
    {"name": "test1" },
    {"name": "test2" },
    {"name": "test3" },
    {"name": "test4" },
    {"name": "test5" },
    {"name": "test6" },
    ]
    
    const [selected, setSelected]=useState(undefined)
    const handleSelectedRows = state => {
    
            // infinite loop 
            setSelected([]) 
            setSelected(state.selectedRows) 
    
            // no infinte loop, and selection works regularly, unable to save the selected rows
            setSelected("noinfiniteloop") 
    
             // strange behavior: no infinte loop, preselected ok but unable to select new rows 
            setSelected(JSON.stringify(state.selectedRows)) 
        }
    
    const anyRowCondition = row => false  
    return(
          <DataTable
                columns={columns}
                data={data}
                selectableRows
                onSelectedRowsChange={handleSelectedRows}
                selectableRowSelected={anyRowCondition}
            /> 
    )
}
```

`columns` and `data` are provided correctly. Everything is typed via typescript but for more clarity i posted the code without types.
`columns` defined using `useMemo`, `handleSelectedRows` tried with and without `useCallback` with no differences. 

## Expected behavior
I would like to be able to preselect some rows, and then mantain the possibility to select new ones (updating the state according to the selection)

## Versions (please complete the following information)
 - React 17.0.1 (RDT requires 16.8.0+)
 - Browser: Any
 - OS : Dockerized Node:16 
 - RDT : 7.4.5 

Thanks in advance for the support and keep on the great work you guys are doing with this awesome package!

**Comment by jbetancur** [comment]
Please see  https://github.com/jbetancur/react-data-table-component/issues/958

**Comment by akanoce** [comment]
Thanks for the response. Moving out `anyRowCondition` it's not possible for me as it depends on an hook so it must be declared inside the component. Btw, `useMemo` may be the answer, but i also found that downgrade to RDT 7.4.2 solve the issue even without `useMemo`

**Comment by jbetancur** [comment]
yes useMemo should work here as well if that isyour use case

**Comment by jbetancur** [comment]
I'm looking into this as a possible regression.

**Comment by msiddique-zz** [comment]
Any update on this?

I'm experiencing this same issue

**Comment by maitzeth** [comment]
Any update? I'm having this problem too.

**Comment by akanoce** [comment]
maitzeth i don't see a anything related to this in the new release 7.4.6 changelog. For me, the use of `useMemo` and `useCallback` with the version `7.4.2` works good and do not present this problem

**Comment by selirah** [comment]
Can you post the code on how it was done?

**Comment by robhitt** [comment]
Same Issue here

**Comment by eduardomdantas** [comment]
+1 Same Issue here

**Comment by robhitt** [comment]
> 

On the Base DataTable (or where the DataTable is for that matter) see if you are using see if you're inadvertently using the below line of code.  I was using it as a result of going through the website examples. Removing the below solved my issue.

1. `const selectProps = { indeterminate: (isIndeterminate: boolean) => isIndeterminate };`
2. `selectableRowsComponentProps={selectProps}` from the DataTable itself.

**Comment by MohdAhmad0** [comment]
same issue,, my code
```js
 <DataTable

          columns={columns}
          data={data}
          pagination
          selectableRows
          onSelectedRowsChange={(data) => setSeletedData(data)}
          customStyles={customStyles}
          persistTableHead
          subHeaderComponent
          subHeader
          selectableRowSelected={(row) => row.id < 3}
        />
```

**Comment by GuYounes** [comment]
I have the same issue and it's very annoying ! In the meantime I found a workaround.

```
import DataTable, { TableProps } from 'react-data-table-component';

interface Props {
    rows: {name: string}[];
    selectedRows: string[];
    setSelectedRows: Dispatch<SetStateAction<string[]>>;
}

export default Function MyTableComponent(props: Props) {
    let isInitialized = false; 
    const columns = [
          {
              name: 'Name',
              selector: row => row.name,
              sortable: true,
          }
      ];
    
    const handleSelectedRows = state => {
            if (state.selectedRows.length === selectedRows.length) {
                isInitialized = true;
            }

            if (initialized === true && state.selectedRows.length !== selectedRows.length) {
                setSelectedRows(state.selectedRows.map(row => row.name))
            }
        }
    
    const anyRowCondition = (row) => selectedRows.includes(row.name);  
    return(
          <DataTable
                columns={columns}
                data={data}
                selectableRows
                onSelectedRowsChange={handleSelectedRows}
                selectableRowSelected={anyRowCondition}
            /> 
    )
}
```

**Comment by musharafshaikh16** [comment]
Is this issue resolved i'm facing similar issue?

**Comment by allan-vera** [comment]
This bug should probably be reopened given how many people have run into the issue

**Comment by huypl53** [comment]
Inside `handleSelectedRows`, I just update state `selected` if `selected.length !== state.selectedRows.length` and it works

**Comment by AbdDub** [comment]
Any Official Fix for this ? still facing this issue in v7.6.2

**Comment by budby** [comment]
I use the 7.7.0 ver and still have this issue

**Comment by DonSmog** [comment]
Memoizing both works for me

const handleSelectedRows = useCallback((selectableRows: Building[]) => {
    setRowSelection(selectableRows);
  }, []);

  const selectableRowSelected = useMemo(
    () => (row: Building) => selectedBuildingIds.includes(row.id),
    [selectedBuildingIds]
  );
