### ISSUE TITLE
Values captured by closure in columns don’t update

### ISSUE THREAD

**Issue by bggolding** [jbetancur/react-data-table-component#957]
## Issue Check list
- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README
- [X] You are using React 16.8.0+
- [X] You installed `styled-components`
- [X] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
When a reference captured by a closure in columns is changed, the change isn’t reflected in the updated table.

## To Reproduce
1. Load the sandbox, note that the table renders
2. There is a button at the bottom “Set genre"
3. When that’s clicked it updates a “genreId” field on all of the movies and also updates the ref_genres object on the moviesWithGenre so that the genreId can be looked up in that field
4. When the table now renders, it crashes because when it tries to look up the genreId in the ref_genres object. The “moviesWithGenre.ref_genres” value was captured in a closure from when the table was first created, and hence doesn’t have the updated list so the app crashes.

## Expected behaviour
I believe that when the columns object is updated, it should be reflected in the output or there should be a way to get the columns item to update, possibly using a dependency list like useMemo et alia.

## Code Sandbox, Screenshots, or Relevant Code

https://codesandbox.io/s/react-data-table-forked-y65uv?file=/src/index.js

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+) 17.0.2
 - Styled Components 5.3.1
 - OS: [e.g. iOS] macOS 12.0.1
 - Browser [e.g. chrome, safari, firefox] Chrome

## Additional context
In our app, we have chess tournaments with a list of players. The players can optionally be assigned to teams. Because the teams are the same for all players on that team, we just set the teamId on the player and then have an object called ref_teams with the active teams for the tournament which we index using player.teamId. When rendering the table, we look up the team in the columns object and get its name. This is failing because the columns object holds onto the original ref_teams object which doesn’t have the updated list of teams.

I’ve simplified this to work with the movies example. I’ve added an extra field to the movie, genreId, which is initially null. The object also has a list of genres, ref_genres, which starts empty and when a new genre is added, it is added there. When the button is clicked, the code sets the genreId on all the films and adds a genre object to the ref_genres so it can be looked up.
```
    {
      id: 4,
      name: "Genre",
      selector: (row) => (row.genreId) ? moviesWithGenre.ref_genre[row.genreId].name : ""
    }
```
The issue appears to be that in DataTable.js, the value for columns is stored internally using useColumns (which in turn uses useState) and isn’t updated on later renders. That means that the references into the columns object can reference outdated data that’s maintained by a closure as I’ve illustrated here.

I think this is a subtle problem but it has cost us a lot of time to discover.

There is probably a performance tradeoff in not having the saved copy of the columns object but there ought to be a way to force it to update or to turn that off.

Even if this is not addressed, it should be documented clearly and I can’t find any mention of this.

**Comment by jbetancur** [comment]
The following  seems to fix the crash and the genre updates

```js
   {
      id: 4,
      name: "Genre",
      selector: (row) => row.genreId ? moviesWithGenre?.ref_genre[row.genreId]?.name : "",
      sortable: true,
      right: true,
      reorder: true
    }
```

Specifically, checking for undefined:

`selector: (row) => row.genreId ? moviesWithGenre?.ref_genre[row.genreId]?.name : ""`  or checking if this object is undefined before returning on the selector.

I believe you need to handle this case where ref_genre[row.genreId].name is undefined because if the genre ref object is undefined and you try to return that to `selector` it will crash.

https://codesandbox.io/s/react-data-table-forked-jk6e6?file=/src/index.js

**Comment by bggolding** [comment]
While that will stop the crash, it won’t display the correct value. I would expect the genre to be display correctly, ie “SciFi”, not to display an empty string.

**Comment by anmcn** [comment]
Essentially, the closure is capturing the state of the associated data (ref_genre) at the time creation of the columns. In our application, this is not correct - the associated data needs to be of the same age as the table row data (the movie example is contrived - it's more complex in the real application). It's not just a matter of suppressing the exception - we need it to use the ref_genre that corresponds to the current row data.

**Comment by anmcn** [comment]
This is still an issue for us, and we have no acceptable workaround.
