### ISSUE TITLE
Infinite render loop when using both selectableRowSelected and onSelectedRowsChange with rowSelectCritera function defined inside component.

### ISSUE THREAD

**Issue by marcoangelo** [jbetancur/react-data-table-component#958]
## Issue Check list
- [ x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [ x] Read the README
- [ x] You are using React 16.8.0+
- [ x] You installed `styled-components`
- [ x] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
component renders infinitely, causing the Maximum update depth exceeded React error.

## To Reproduce
1. Go to Codesandbox link
2. Uncomment line 47 & save
3. See error

## Expected behavior
I expect render loop to not occur.

## Code Sandbox, Screenshots, or Relevant Code
https://codesandbox.io/s/smoosh-wildflower-f69sf?file=/src/App.js

Otherwise, add screenshots and/or complete sample code to help explain your problem.

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+) 17.0.2
 - Styled Components 5.3.3
 - OS: Ios 11.6
 - Browser chrome 94.0.4606.81

## Additional context
The issue no longer occurs if the rowSelectCritera is defined OUTSIDE the component. This is not a viable option though, as I need to pass data from the table component into the rowSelectCritera comparison function.

**Comment by marcoangelo** [comment]
Found a workaround for this by wrapping the rowSelectCritera function in useMemo. See fix here - https://codesandbox.io/s/wandering-frog-gq1ts?file=/src/App.js

**Comment by jbetancur** [comment]
You just need to move the following outside of the react component

```js
const rowSelectCritera = (row) => {
  return row.device_id === "itnx";
};

export default function App() {
......
```

I am not sure if this is a bug or not, possibly, but what is happening is `rowSelectCritera ` is being recreated every time you render. Internally RDT will detects that change and tries to update the items that are selected. That is why `useMemo` works and also why simply moving it out of the react component works as well.
