### ISSUE TITLE
Fixed Table Header

### ISSUE THREAD

**Issue by webdev522** [jbetancur/react-data-table-component#96]
This library looks great.
Just wondering if this table has fixed header feature...

Regards.

**Comment by jbetancur** [comment]
Thank you! 

Yes, there is a `fixedHeader` property.

https://github.com/jbetancur/react-data-table-component#datatable-properties
and
https://jbetancur.github.io/react-data-table-component/?selectedKind=Basic&selectedStory=Fixed%20Header&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

I actually just made some fixes to this feature in version `1.5.3`, so make sure you update to that version.

**Comment by jbetancur** [comment]
Closing this as hopefully answered :)
