### ISSUE TITLE
Unable to style Title/Header font-weight

### ISSUE THREAD

**Issue by FiveOFive** [jbetancur/react-data-table-component#963]
## Issue Check list
- [X] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [X] Read the README
- [X] You are using React 16.8.0+
- [X] You installed `styled-components`
- [X] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
Currently styled components are configured to style Title/Header font-size and color, but not font-weight.

## To Reproduce

Create a react-data-table-component with customStyles for the header fontWeight. The fontWeight will not be changed. (fontSize and color can currently be styled).

`
customStyles = {
  header: {
    style: {
      fontWeight: 'bold'
    }
  }
}
`

## Expected behavior
Using customStyles for header font-weight should change the title/header font-weight.

## Code Sandbox, Screenshots, or Relevant Code

**Code Sandbox Reproduction** - https://codesandbox.io/s/react-data-table-forked-x0fm1

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+) - 17.0.2
 - Styled Components - 5.3.1
 - OS: [e.g. iOS] - iOS
 - Browser [e.g. chrome, safari, firefox] - firefox

## Additional context

I've created a pull request to fix this issue. It adds support for font-weight styling of the title/header - https://github.com/jbetancur/react-data-table-component/pull/962

**Comment by oalejandroelias** [comment]
Use css. Example:

  .rdt_TableCol {
    color: black;
    font-weight: bolder;
    font-size: 14px;
  }
