### ISSUE TITLE
[FEATURE]: Page size based on available height for table

### ISSUE THREAD

**Issue by tlindener** [jbetancur/react-data-table-component#968]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

Currently, we have to identify the best possible page size manually - this usually only works for a limited set of display heights or completely fails when a user resizes the window.

## Describe the solution you'd like

Add an optional approach to identify the max possible page size when using pagination. 
Additionally it should be possible to fix the position of the pagination controls, so that they stay at a static position which improves usability (e.g. user wants to change multiple pages in quick succession)

## Describe alternatives you've considered

Measuring the size of the parent and managing a list of "breakpoints" with respective page sizes

## Additional context
The images highlights the issue with lots of wasted space because the current default page size does not fit to the window height.
![image](https://user-images.githubusercontent.com/651357/142177406-2543f9e9-c8c6-4bb7-b231-8356b0b71cec.png)

**Comment by jbetancur** [comment]
So is the table container fixed height and you want pagination to dynamically calculate the rows per page based on the height of the parent container?

**Comment by tlindener** [comment]
Yes exactly, this would be amazing.

**Comment by PLJNS** [comment]
I've had some success doing this, but I'm not sure my solution is broadly applicable. It's not perfect, but it will size the table based on available height and display the maximum number of cells. Scroll bars make it a little annoying, as does rounding down.

```
import useScrollbarSize from "react-scrollbar-size";

const SomeComponent = () => {
  const { height } = useScrollbarSize();
  const [numberOfCellsForUsableHeight, setNumberOfCellsForUsableHeight] =
    useState<number | undefined>(undefined);

  function handleResize() {
    const usableHeight = (window.innerHeight ?? 0) - 72 - 56;
    const cellHeight = 48;
    const numberOfCellsForUsableHeight =
      Math.round(usableHeight / cellHeight) - 2;
    setNumberOfCellsForUsableHeight(numberOfCellsForUsableHeight);
  }

  useEffect(() => {
    if (typeof window !== "undefined") {
      window.addEventListener("resize", handleResize);
      handleResize();
      return () => window.removeEventListener("resize", handleResize);
    }
  }, []);

  return (
      <DataTable
        customStyles={{
          table: {
            style: {
              height: `calc(100vh - 72px - 56px - ${height}px)`, // NOTE: change for your view
            },
          },
        paginationComponentOptions={{
          noRowsPerPage: true,
        }}
        paginationRowsPerPageOptions={[numberOfCellsForUsableHeight ?? 1]}
        }}
    />
)}
  ```
