### ISSUE TITLE
Responsive-Datatables-with-automatic-column-hiding (Displaying the hidden columns in expandable row )

### ISSUE THREAD

**Issue by webpipl** [jbetancur/react-data-table-component#969]
which ever the columns hidden while responsive behavior by breakpoints  if we can get that hidden columns list then we can put and display them in extra row instead of making them non-visible  ,just like jquery datatable responsive auto column responsive feature

![image](https://user-images.githubusercontent.com/51621445/142886235-60822c9f-205d-45ee-975e-8afbd03ae7fc.png)

**Comment by jbetancur** [comment]
TBH I am not sure I follow. Could you provide more details please. Also note the the `hide` is based on media queries

**Comment by webpipl** [comment]
how i can get the media query hidden columns list   , and i want to show them in collapsible row

**Comment by webpipl** [comment]
how we can get hidden columns list
