### ISSUE TITLE
Fixed Header should allow you to set the TableBody Scroll Height

### ISSUE THREAD

**Issue by jbetancur** [jbetancur/react-data-table-component#97]
Ideally, I would want this to be dynamic to the container height. For now, the api should have a `fixedHeaderScrollHeight`

**Comment by surinderdeveloper** [comment]
Sorry, If I am repeating the question. I want to set the height 100% as per the container. How can achieve it? Thanks

**Comment by surinderdeveloper** [comment]
I achieved this with this answer: https://stackoverflow.com/a/58116121/2034774
