### ISSUE TITLE
[FEATURE]: fixed columns

### ISSUE THREAD

**Issue by locdangle2552** [jbetancur/react-data-table-component#971]
+ Issuses:
I have tried to set styles ` position: sticky; left: 0` to a **column data** but the header of that column is not sticky (only body is sticky).
+ Expectation:
 I want the column that is set those styles is sticky

Thank you for your support!

**Comment by amirfaisalz** [comment]
hi @locdangle2552 how do you solve this?

**Comment by iiian** [comment]
+1

**Comment by amastaneh** [comment]
+1
