### ISSUE TITLE
responsive = {true} not making my table horizontally scrollable/

### ISSUE THREAD

**Issue by 7dobi** [jbetancur/react-data-table-component#972]
## Describe the bug
responsive = "true" not making my table horizontally scrollable/

![image](https://user-images.githubusercontent.com/87612196/143542710-3eb5f402-e8cc-4cb8-b935-f6d04b61fbf2.png)

**Comment by jbetancur** [comment]
responsive true is the default so no need to set it. The horizontal bar will only appear when the fields have been compressed as much as possible. Are you sure that is the case? I can't tell from your screenshot.
