### ISSUE TITLE
createTheme with customName does not work

### ISSUE THREAD

**Issue by olgunkaya** [jbetancur/react-data-table-component#975]
## Describe the bug
Creating a new theme with name solarized (as in the storybook example) is not enough to assign it to theme property. 

## To Reproduce
1. createTheme named "solarized" -> https://react-data-table-component.netlify.app/?path=/docs/api-custom-themes--page
2. set prop theme to created theme "solarized"
3. Typescript will not allow this to work. 
4. solarized is not assignable to type Themes. 

## Expected behavior
there should not be a TS error with given storybook example. 

## Code Sandbox, Screenshots, or Relevant Code
```
createTheme('solarized', {
  highlightOnHover: {
    default: 'rgba(111, 172, 38, 0.1)',
  },
  striped: {
    default: 'rgba(203, 214, 226, 0.180179)',
  },
});
```

Error in terminal during the npm  start.
```
TS2322: Type '"solarized"' is not assignable to type 'Themes'.
    323 |                       highlightOnHover
    324 |                       pointerOnHover
  > 325 |                       theme="solarized"
        |                       ^^^^^
    326 |                       conditionalRowStyles={conditionalRowStyles}
    327 |                       customStyles={customStyles}
    328 |                     />
```

## Versions (please complete the following information)
"react-data-table-component": "^7.0.0-rc2",
 - React (RDT requires 16.8.0+) : "react": "17.0.1",
 - Styled Components : "styled-components": "^5.3.0",
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari, firefox] : chrome

## Additional context
the problem is that the theme property defined as 

`    theme?: Themes;`
Where type Themes is defined as 
```
export declare type Themes = 'default' | 'light' | 'dark';
```

**Comment by jbetancur** [comment]
Thanks for raising this - will look to having a fix soon.
