### ISSUE TITLE
TypeError: Ot.slice is not a function when enabling pagination

### ISSUE THREAD

**Issue by DaddyImPregnant** [jbetancur/react-data-table-component#977]
## Issue Check list
- [X] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [X] Read the README
- [X] You are using React 16.8.0+
- [X] You installed `styled-components`
- [X] Include relevant code or preferably a [code sandbox](https://codesandbox.io/embed/react-data-table-sandbox-ccyuu
)

## Describe the bug
When enabling pagination, I get the error TypeError: Ot.slice is not a function

## To Reproduce
1. Get data from Json
2. Put data from Json into a table
3. Enable pagination

## Expected behavior
Pagination to be enabled

## Code Sandbox, Screenshots, or Relevant Code
Please include a codesandbox to help **expedite** troubleshooting.

`
function Licenses() {
    const [data, setData] = useState({});

    useEffect(() => {
        axios.get('https://api.apiserver.com/api/licenses', {
            crossDomain: true,
            headers: {
                'Access-Control-Allow-Origin': '*',
                'Content-Type' : 'application/json'
            }
        }).then(response => setData(response.data))
    }, []);

    return(
        <Box >
            <DataTable
                columns={columns}
                data={data}
                pagination
            />
        </Box>
    );
}`

But I end up getting the error TypeError: Ot.slice is not a function.

https://cdn.daddyimpregnant.com/yoMU6/zEPEYeXU45.png

Otherwise, add screenshots and/or complete sample code to help explain your problem.

## Versions (please complete the following information)
 - React (RDT requires 16.8.0+): React 17.0.2
 - Styled Components 5.3.3
 - OS: [e.g. iOS] Linux
 - Browser [e.g. chrome, safari, firefox] Chrome

**Comment by jbetancur** [comment]
Are you sure your data is an Array? e.g. `[]`. The data must be an Array....

**Comment by DaddyImPregnant** [comment]
> 

Ah, that was it. Thank you!
