### ISSUE TITLE
[FEATURE]: Prop to "select all" on current page only

### ISSUE THREAD

**Issue by tlindener** [jbetancur/react-data-table-component#979]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

When using pagination it sometimes is preferable to only select the rows on the current page

## Describe the solution you'd like

Provide a prop similar to "selectableRowsNoSelectAll" to switch between select all across pages and select all on current page

## Describe alternatives you've considered

Afaik it's not possible to hook into the selection process otherwise

**Comment by jbetancur** [comment]
That feature already exists in the docs `selectableRowsVisibleOnly`. See https://react-data-table-component.netlify.app/?path=/docs/api-props--page Row Selection

**Comment by tlindener** [comment]
Perfect, thank you!
