### ISSUE TITLE
[FEATURE]: Sort arrows customization

### ISSUE THREAD

**Issue by stesvis** [jbetancur/react-data-table-component#980]
Would it be possible, or is it already, to customize the sort arrows to make the look like the bootstrap 5 icons?

Example from this:
![image](https://user-images.githubusercontent.com/6062684/146104555-9a61d0e7-9b83-4b61-b755-af2e56f8d968.png)

to this:
![image](https://user-images.githubusercontent.com/6062684/146104493-2da289ca-0a65-404c-93ac-3b64e5aafb44.png)

And of course the same for the `asc` sorting.

**Comment by jbetancur** [comment]
Yes please check the docs. Short answer is you can look into the sortIcon prop.

https://react-data-table-component.netlify.app/?path=/docs/getting-started-library-integration--page

**Comment by stesvis** [comment]
> Yes please check the docs. Short answer is you can look into the sortIcon prop.
> 
> https://react-data-table-component.netlify.app/?path=/docs/getting-started-library-integration--page

Awesome! Thank you!
