### ISSUE TITLE
expanderCell expanderButton changed to first column

### ISSUE THREAD

**Issue by 00270435** [jbetancur/react-data-table-component#989]
I haven't changed my code but the column that holds the expander button has moved to the left side as its position is now the first column of the table. I want it to be at the end in the last column, as it was before. how can I establish in which side the column with the expander goes?

**Comment by t4davidoneill** [comment]
It would be great if there was a prop to determine if the expand column is first or last 

Is this something you can implement and if not is there a work around ? 

Thanks
