### ISSUE TITLE
Issue with setting Page number

### ISSUE THREAD

**Issue by rakeshmanjunatha** [jbetancur/react-data-table-component#99]
In a table by default page number will be 1 but i want to set it to any number dynamically.
Any idea?

Thanks

**Comment by jbetancur** [comment]
I agree that this should be a feature. I’ll see if I can get this feature done this week

**Comment by rakeshmanjunatha** [comment]
Thanks for the update, but i'm trying to update this package in my system, its not happening getting older one only.

**Comment by jbetancur** [comment]
Hi,

That’s because I didn’t update anything yet ;)

**Comment by rakeshmanjunatha** [comment]
okay fine, it will be helpful if you push the latest one.

**Comment by jbetancur** [comment]
Fixed in https://github.com/jbetancur/react-data-table-component/pull/102

I'll cut a release this weekend once I get your other issue #101 resolved

**Comment by rakeshmanjunatha** [comment]
Hi,

Still its not working, when i'm trying to set the page number dynamically. but its working fine with initial default page number.

Actually i'm storing the page number in URL on onChangePage event.

Scenario: On page load if the URL has "page" number parameter, i'm trying to assigning value to **paginationDefaultPage**  using setState but its not working.
