### ISSUE TITLE
[FEATURE]: Add onRowClicked to the row element as well as cells

### ISSUE THREAD

**Issue by JayBox325** [jbetancur/react-data-table-component#991]
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

At the moment, when you use `onRowClicked` the component adds `data-tag='allowRowEvents'` to each cell within the row, but not the row itself. Making hover styling tricker than it needed to be.

## Describe the solution you'd like

Add a prop, whether it's a class or data attribute to the row element to indicate that this row is clickable.

## Describe alternatives you've considered

Currently been styling all rows with hover states regardless of whether they're clickable or not.

**Comment by jbetancur** [comment]
Not sure I follow - could you provide an example or sandbox? `data-tag="allowRowEvents" ` must be manually added to a custom column `cell` elements to allow event propagation, otherwise the onRowClicked event will trigger. This should not have anything to do with hover and is not dynamically applied.

**Comment by JayBox325** [comment]
https://user-images.githubusercontent.com/13233809/148136550-f0833906-58ce-4100-bb41-7c8c5e924bc9.mov

The issue I'm encountering is that you can see that each cell has the data attribute, but the cells aren't filling all available space even with some flex styling to force children to grow to the height of their parent. For me, if I add a row click event, it would be added to the row element, not the cells within. But that's my understanding of how it's been labelled.
