### ISSUE TITLE
[FEATURE]: [Filter Functionality for Columns]

### ISSUE THREAD

**Issue by yog121** [jbetancur/react-data-table-component#994]
## Feature Check list

- [ ] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [ ] Read the README to ensure the feature is not already present
- [ ] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [ ] Considered the value versus complexity for all users of the library as well as library maintenance
- [ ] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

Filter Functionality is very basic stuff in any Table , consider it like if you have 1000+ rows and you want relevant data to you , how you will figure out as currently there is now way , It will add significant increase in the usage of this package

## Describe the solution you'd like

Filter Functionality based for Columns

**Comment by juninhodeluca** [comment]
Hello! I don't know if I've been rightly understand your propose. I've made a search filter panel (with an advanced button to open other filters including non-visible) by myself using the subHeaderComponent and the result was almost perfect, but I agree it should be a very nice feature for future versions.

Is your idea similar to search panes of Datatables.net?
![](https://i.stack.imgur.com/pjyaf.png)

Or something like that below? 
![image](https://user-images.githubusercontent.com/2762856/148535311-7318d94a-4de4-4566-b653-80a2bf4ff94f.png)

**Comment by yog121** [comment]
Hi @juninhodeluca 
Thank you for responding.
Actually I checked filter functionality here (https://react-data-table-component.netlify.app/?path=/story/getting-started-intro--page )

So can you please share any document link for the same ?

**Comment by manentai** [comment]
Hi @juninhodeluca I am trying to implement something similar but with no success, do you happen to have a repo out there I can try? Thanks

**Comment by IanMayo** [comment]
+1 for the filter-by-column feature.

In the below screenshot it would allow the user to filter by staff in the `London` or `Edinburgh` offices.  A context menu would be available from the column header. Opening it would show a check-list of unique values in that column. The user would click on `London` and `Edinburgh` and then `Apply`. 

In some ways this is much more capable than the free-text search.

**Comment by ADTC** [comment]
Can you reopen? I want the same. Seems like a basic functionality to have...
